Move off of NuGet APIs and switch to HTTP client requests
PowerShell/PSResourceGet pull request #1023
Opened 2023-03-17 15:59 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-03-17 17:19 UTC, adityapatwardhan commented on src/code/GetHelper.cs
> +                }
```suggestion
                if (pkg.AdditionalMetadata.TryGetValue("NormalizedVersion", out string normalizedVersion))
                {
                  if (!NuGetVersion.TryParse(
                          value: normalizedVersion,
                          version: out NuGetVersion nugetVersion))
                  {
                      _cmdletPassedIn.WriteVerbose(String.Format("Package's normalized version '{0}' cannot be parsed into NuGetVersion.", normalizedVersion));
                      yield break;
                  }
                 }
                 else 
                 {
                     // some error handling
                 }

```

2023-03-20 19:06 UTC, adityapatwardhan requested changes

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/InstallPkgParams.cs
>  }
Add end of line
```suggestion
}

```

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/PSGetException.cs
> +    public class OperationNotSupportedException : Exception
Can we use InvalidOperationException instead?

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/IServerAPICalls.cs
> +    HttpContent InstallName(string packageName, bool includePrerelease, out ExceptionDispatchInfo edi);
If this is an abstraction over all types of server calls, would the file system endpoint also implement this interface? If so, then return type of HttpContent seems incorrect.

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/IServerAPICalls.cs
> +    HttpContent InstallVersion(string packageName, string version, out ExceptionDispatchInfo edi);
Same as above.

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/PSRepositoryInfo.cs
> +            Unknown,
```suggestion
            unknown,
```

Lowercase for consistency

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +                    versionType = VersionType.NoVersion;
The whole block from 760 - 789 can re-written like this, I believe it would be much simpler to understand.

```csharp
VersionType versionType = VersionType.NoVersion;
NuGetVersion nugetVersion = null;

if (depVersion.Trim().Equals("*"))
{
    versionRange = VersionRange.All;
    versionType = VersionType.VersionRange;
}

bool isNugetVersion = NuGetVersion.TryParse(depVersion, out nugetVersion);
bool isVersionRange = VersionRange.TryParse(depVersion, out versionRange);

if (!isNugetVersion && !isVersionRange)
{
    ThrowTerminatingError(new ErrorRecord(
                            new ArgumentException("Argument for -Version parameter is not in the proper format"),
                            "IncorrectVersionFormat",
                            ErrorCategory.InvalidArgument,
                            this));
                    }
}

if (isNugetVersion)
{
    versionType = Version.SpecificVersion;
}

if (isVersionRange)
{
    versionType = VersionType.VersionRange;
}
```

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +                if (depVersion != null)
This is guaranteed to be to not null.

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/ResponseUtil.cs
> +}
```suggestion
}

```

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/ResponseUtilFactory.cs
> +}
```suggestion
}

```

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/ServerApiCall.cs
> +}
```suggestion
}

```

2023-03-20 19:06 UTC, adityapatwardhan commented on src/code/ServerFactory.cs
> +}
```suggestion
}

```

2023-03-22 19:50 UTC, anamnavi commented on src/code/IServerAPICalls.cs
> +    HttpContent InstallName(string packageName, bool includePrerelease, out ExceptionDispatchInfo edi);
return Stream instead

2023-03-23 18:14 UTC, anamnavi commented on src/code/GetHelper.cs
> +                }
It's not exactly an error if NormalizedVersion cannot be found...only an error when neither NormalizedVersion nor Version could be found. I did clean up this code though to reflect this more clearly.

2023-03-23 21:26 UTC, adityapatwardhan commented on build.ps1
> +
extra line

2023-03-23 21:27 UTC, adityapatwardhan commented on src/code/InstallPSResource.cs
> +        // VersionRange _versionRange;
Remove this

2023-03-23 21:35 UTC, adityapatwardhan commented on src/code/RepositorySettings.cs
> +            if (repoUri.AbsoluteUri.EndsWith("api/v2"))
use the overload with StringComparison.OrdinalIgnoreCase

2023-03-23 21:37 UTC, adityapatwardhan commented on src/code/RepositorySettings.cs
> +            else if (repoUri.Scheme == Uri.UriSchemeFile)
```suggestion
            else if (repoUri.Scheme.Equals(Uri.UriSchemeFile, StringComparison.OrdinalIgnoreCase))
```

2023-03-23 21:37 UTC, adityapatwardhan commented on src/code/RepositorySettings.cs
> +            else if (repoUri.AbsoluteUri.EndsWith("v3/index.json"))
Same as above

2023-03-23 21:39 UTC, adityapatwardhan commented on src/code/SavePSResource.cs
> +        // VersionRange _versionRange;
Remove this

2023-03-23 21:52 UTC, adityapatwardhan commented on src/code/ServerApiCall.cs
> +        public abstract string FindVersionWithTag(string packageName, string version, string[] tags, ResourceType type, out ExceptionDispatchInfo edi);
API documentation missing

2023-03-23 22:25 UTC, adityapatwardhan commented on src/code/Utils.cs
> +            if (version == null || String.IsNullOrEmpty(version))
```suggestion
            if (String.IsNullOrEmpty(version))
```

2023-03-23 22:27 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                string pkgNameVersion = CreateHashSetKey(installedPkg.Name, installedPkg.Version.ToString());
```suggestion
                string pkgNameVersion = string.Format("{0}{1}", installedPkg.Name, installedPkg.Version.ToString());
```

Dont need a function for it I think.

2023-03-23 22:28 UTC, adityapatwardhan commented on src/code/Utils.cs
> +            /*
Remove dead code

2023-03-23 22:46 UTC, PaulHigin requested changes
Just starting the review.  Refactor comments do not necessarily have to be addressed for this PR, but something to keep in mind for next round of work.

2023-03-23 22:46 UTC, PaulHigin commented on doBuild.ps1
>                  'NuGet.Repositories'
At some point soon we will be able to remove these `NuGet` dependencies, correct?

2023-03-23 22:46 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                        _networkCredential = new NetworkCredential(username, password);
Declaring variables above is not necessary.

```suggestion
                        _networkCredential = new NetworkCredential(
                            repoCredential.UserName,
                            repoCredential.Password);
```

2023-03-23 22:46 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                    if (_networkCredential == null && currentRepository.CredentialInfo != null)
This code is duplicated three times, so we can have a utility method that performs this function (convert from PSCredential to NetworkCredential.

2023-03-23 22:46 UTC, PaulHigin commented on src/code/FindHelper.cs
> +        public IEnumerable<PSCommandResourceInfo> FindCommandOrDscResource(
It is better to have one method to find/return commands and one to find/return DSCResources.  A single method should not do both.  You can have a low level method that returns all.  Since it is streaming you can have a higher method perform the filter.

2023-03-23 22:46 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                            if ((isSearchingForCommands && package.Includes.Command.Contains(cmdOrDsc, StringComparer.OrdinalIgnoreCase)) ||
This `IsSearchingForCommands` filter can be done at a higher level after the `yield return` here.

2023-03-23 22:48 UTC, adityapatwardhan commented on src/code/V2ResponseUtil.cs
> +}
```suggestion
}

```

2023-03-23 22:48 UTC, adityapatwardhan commented on src/code/V2ResponseUtil.cs
> +            for (int i=0; i<elemList.Count; i++)
```suggestion
            for (int i=0; i < elemList.Count; i++) 
```

2023-03-23 22:49 UTC, adityapatwardhan commented on src/code/V3ResponseUtil.cs
> +}
```suggestion
}

```

2023-03-23 22:54 UTC, adityapatwardhan commented on test/SavePSResourceTests/SavePSResourceAATests.ps1
> +<# WIP
Remove these? or mark as pending

2023-03-23 22:56 UTC, adityapatwardhan commented on src/code/FindHelper.cs
>              SwitchParameter includeDependencies)
Why is this a SwitchParameter and not a bool?

2023-03-23 22:57 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                if (repository != null && repositoriesToSearch.Count == 0)
```suggestion
                if (repositoriesToSearch != null && repositoriesToSearch.Count == 0)
```

2023-03-23 23:01 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                if (repository != null && repositoriesToSearch.Count == 0)
```suggestion
                if (repositoriesToSearch != null && repositoriesToSearch.Count == 0)
```

2023-03-24 17:37 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +        private IEnumerable<PSResourceInfo> SearchByNames(ServerApiCall currentServer, ResponseUtil currentResponseUtil, PSRepositoryInfo repository)
Consider refactoring this method. It is pretty big and has many branches. Breaking it up into multiple smaller functions would make it easier to test and maintain. Maybe some code can be shared as well.

2023-03-27 04:47 UTC, anamnavi commented on test/SavePSResourceTests/SavePSResourceAATests.ps1
> +<# WIP
removed

2023-03-27 15:49 UTC, anamnavi commented on src/code/Utils.cs
> +            /*
done (not sure why we left it here)

2023-03-27 15:53 UTC, anamnavi commented on doBuild.ps1
>                  'NuGet.Repositories'
Yes, when we move off the NuGet APIs for local repositories (goal for beta21). I'll make a note to remove them then

2023-03-29 16:55 UTC, anamnavi commented on src/code/FindHelper.cs
> +        public IEnumerable<PSCommandResourceInfo> FindCommandOrDscResource(
This is only happening for local repositories (still using NuGet APIs). For remote repositories, when we get to FindHelper().FindCommandOrDSCResource() it calls one lower level API that handles both. The logic within FindHelper for Command or DSCResource is the same (for remote repositories) except that the underlying value of the tag is different. I could create a new method but the logic would be exactly same, and we would anyways pass a boolean like `isSearchingForCommands` to the lower level API so having this one method in findHelper seems reasonable.

2023-03-29 16:55 UTC, anamnavi commented on src/code/FindHelper.cs
> +                            if ((isSearchingForCommands && package.Includes.Command.Contains(cmdOrDsc, StringComparer.OrdinalIgnoreCase)) ||
This filtering is only happening for local repositories (still using NuGet APIs). We will address this in the next releas when we move off of NuGet APIs for local repos.

2023-03-29 18:00 UTC, PaulHigin approved these changes

2023-03-29 18:00 UTC, PaulHigin commented on src/code/FindHelper.cs
> +        public IEnumerable<PSResourceInfo> FindTag(
```suggestion
        public IEnumerable<PSResourceInfo> FindByTag(
```

2023-03-29 18:03 UTC, PaulHigin approved these changes

2023-03-29 19:27 UTC, adityapatwardhan approved these changes

2023-03-29 19:28 UTC, anamnavi commented on src/code/FindHelper.cs
> +        private IEnumerable<PSResourceInfo> SearchByNames(ServerApiCall currentServer, ResponseUtil currentResponseUtil, PSRepositoryInfo repository)
I will do this in the next release.

2023-03-29 19:36 UTC, merged