Add tests for CompatPowerShellGet
PowerShell/PSResourceGet pull request #1055
Opened 2023-04-07 05:50 UTC by alerickson

# PR Summary

Adding tests for integration with CompatPowerShellGet.

- Find-PSResource (tests Find-Command, Find-DscResource, Find-Module, and Find-Script)
    + Find-Command, Find-DscResource tests broken; version parameter tests broken
- Install-PSResource  (tests Install-Module, and Install-Script)
    + Version tests are broken, input object tests broken
- Save-PSResource  (tests Save-Module, and Save-Script)
    + Version tests are broken, input object tests broken
- Update-PSResource (tests Update-Module, and Update-Script)
    + All of update is broken because of Type parameter [parameter binding exception] -- issue with CompatPSGet
- Get-PSResource (tests Get-InstalledModule, and Get-InstalledScript)
    + Version parameter tests broken
- Uninstall-PSResource (tests Uninstall-Module, and Uninstall-Script)
    + Version parameter tests broken
- Publish-PSResource (tests Publish-Module and Publish-Script)
    + A few bugs with Publish-Module tests
- Get-PSResourceRepository (tests Get-PSRepository)
    + No broken tests
- Register-PSResourceRepository (tests Register-PSRepository)
    + 1 broken test
- Set-PSResourceRepository (tests Set-PSRepository)
    +	1 broken test
- Unregister-PSResourceRepository (tests Unregister-PSRepository)
    + 1 broken test

**These tests are needed for later:
(These are not a part of CompatPowerShellGet yet):**

- Test-PSScriptFileInfo
- New-PSScriptFileInfo
- Update-PSScriptFIleInfo
- Update-ModuleManifest

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-04-07 15:47 UTC, anamnavi commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +Import-Module "$((Get-Item $psscriptroot).parent)\PSGetTestUtils.psm1" -Force
We use this in the other nested test files to avoid some errors on windowspowershell.

```suggestion
$modPath = "$psscriptroot/../PSGetTestUtils.psm1"
Import-Module $modPath -Force -Verbose
```

2023-04-07 15:57 UTC, anamnavi commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +
```suggestion
    
    
```

2023-04-24 22:18 UTC, adityapatwardhan requested changes

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $psgetItemInfo.Count -ge 1 | Should -Be $true
```suggestion
        $psgetItemInfo.Count | Should -BeGreaterOrEqual 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -eq 2 | Should -Be $true
```suggestion
        $res | Should -HaveCount 2
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res | ForEach-Object { $_.Version -eq [Version]"3.0" | Should -Be $true }
I think this might work. It will give better errors when the test fails.

```suggestion
        $res | ForEach-Object { $_.Version | Should -Be [Version]"3.0" }
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -eq 0 | Should -Be $true
```suggestion
        $res | Should -HaveCount 0
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -eq 2 | Should -Be $true
```suggestion
        $res | Should -HaveCount 2
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res | ForEach-Object { $_.Version -ge [Version]"0.5" | Should -Be $true }
```suggestion
        $res | ForEach-Object { $_.Version | Should -BeGreaterOrEqual [Version]"0.5" }
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -eq 3 | Should -Be $true
```suggestion
        $res | Should -HaveCount 3
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -gt 1 | Should -Be $true
```suggestion
        $res.Count | Should -BeGreaterThan 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count -ge 2 | Should -Be $true
```suggestion
        $res.Count | Should -BeGreaterOrEqual 2
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count | Should -Be 1
```suggestion
        $res | Should -HaveCount 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +
fix new line at the end of file

2023-04-24 22:18 UTC, adityapatwardhan commented on test/GetPSResourceTests/CompatGetPSResource.Tests.ps1
> +        $res.Count -ge 1 | Should -Be $true
```suggestion
        $res.Count | Should -BeGreaterOrEqual 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/GetPSResourceTests/CompatGetPSResource.Tests.ps1
> +}
add end of line

2023-04-24 22:18 UTC, adityapatwardhan commented on test/SavePSResourceTests/CompatSavePSResource.Tests.ps1
> +        $pkgDirs.Count | Should -Be 1
```suggestion
        $pkgDirs | Should -HaveCount 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/SavePSResourceTests/CompatSavePSResource.Tests.ps1
> +        $pkgDirs.Count | Should -Be 1
```suggestion
        $pkgDirs | Should -HaveCount 1
```

2023-04-24 22:18 UTC, adityapatwardhan commented on test/SavePSResourceTests/CompatSavePSResource.Tests.ps1
> +        $pkgDirs.Count -ge 6 | Should -Be $true
All of such should be replaced with -HaveCount

2023-04-24 22:18 UTC, adityapatwardhan commented on test/SavePSResourceTests/SavePSResourceV2.Tests.ps1
> +### TODO:  this is broken because the "Prerelease" parameter is a boolean, but the type from
File an issue if this needs to be fixed to track this

2023-04-24 22:18 UTC, adityapatwardhan commented on test/SavePSResourceTests/SavePSResourceV3.Tests.ps1
> +### TODO:  this is broken because the "Prerelease" parameter is a boolean, but the type from
Same as above

2023-04-24 22:18 UTC, adityapatwardhan commented on test/UninstallPSResourceTests/UninstallPSResource.Tests.ps1
> +<#
Remove commented code?

2023-04-24 22:18 UTC, adityapatwardhan commented on test/UpdatePSResourceTests/UpdatePSResourceV2.Tests.ps1
> +<#
Delete commented out code

2023-04-24 22:29 UTC, alerickson commented on test/UpdatePSResourceTests/UpdatePSResourceV2.Tests.ps1
> +<#
These few files are commented out just to test against the CI system... ultimately we want to run everything that's commented out here.

2023-04-24 22:30 UTC, alerickson commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $psgetItemInfo.Count -ge 1 | Should -Be $true
I'll update all instances where this and the suggestions below occur

2023-04-26 03:25 UTC, adityapatwardhan commented on src/CompatPowerShellGet.psm1
> +
extra line

2023-04-26 03:26 UTC, adityapatwardhan commented on src/CompatPowerShellGet.psm1
> +    Write-Warning -Message "The cmdlet 'New-ScriptFileInfo' is deprecated, please use 'New-PSScriptFileInfo'."
Remove this

2023-04-26 03:26 UTC, adityapatwardhan commented on src/CompatPowerShellGet.psm1
> +
extra line

2023-04-26 03:26 UTC, adityapatwardhan commented on src/CompatPowerShellGet.psm1
> +
extra line

2023-04-26 03:27 UTC, adityapatwardhan commented on src/CompatPowerShellGet.psm1
> +    "Test-ScriptFileInfo",
Add New-ScriptFileInfo

2023-04-26 03:28 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count | Should -BeExactly 2
```suggestion
        $res | Should -HaveCount 2
```

2023-04-26 03:28 UTC, adityapatwardhan commented on test/FindPSResourceTests/CompatFindPSResource.Tests.ps1
> +        $res.Count | Should -BeExactly 2
BeExactly is a string comparison, case sensitive. We are testing for count so should use HaveCount

2023-04-28 20:56 UTC, adityapatwardhan commented on .github/ISSUE_TEMPLATE/Release_Checklist.yml
> +name: Release Checklist 🚀
This file should not be in this PR

2023-04-28 21:14 UTC, alerickson commented on .github/ISSUE_TEMPLATE/Release_Checklist.yml
> +name: Release Checklist 🚀
having some issues with pulling in massive changes, but working on fixing this

2023-05-01 19:34 UTC, PaulHigin requested changes

2023-05-01 19:34 UTC, PaulHigin commented on test/ScriptFileInfoTests/TestPSScriptFile.Tests.ps1
> +$testDir = (get-item $psscriptroot).parent.FullName
I would also add a `Get-Module` here (and everywhere we explicitly import PSGetV3 for testing), so that the CI output includes what modules are currently loaded into the session.  Maybe even check to see if PSGetV2 is imported, because if both v2 and v3 are imported into the session, I am not sure if the tests are still valid (i.e., actually testing v3 compat cmdlets instead of v2 cmdlets).

2023-05-01 19:38 UTC, adityapatwardhan commented on test/InstallPSResourceTests/InstallPSResourceV3Server.Tests.ps1
> +        $pkg.Name | Should -Be "TestModule"
This describe is commented out. Should be re-enable or delete it?

2023-05-01 19:38 UTC, adityapatwardhan commented on test/InstallPSResourceTests/InstallPSResourceV3Server.Tests.ps1
> +#>
```suggestion
#>

```

2023-05-01 19:39 UTC, adityapatwardhan commented on test/RepositoryTests/RegisterPSResourceRepository.Tests.ps1
> +<#
Add a comment on why this is commented out. Or delete / re-enable.

2023-05-01 19:40 UTC, adityapatwardhan commented on test/RepositoryTests/SetPSResourceRepository.Tests.ps1
> +    <#
Same here

2023-05-01 20:37 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceV3Server.Tests.ps1
> +        $pkg.Name | Should -Be "TestModule"
Those are tests which all require manual validation.  What's the best way mark it as something that should not be run in CI and only manually validated?  They're essentially just tests for ensuring prompting is actually prompting correctly.

2023-05-02 20:44 UTC, anamnavi commented on src/PowerShellGet.psd1
> +        'New -ScriptFileInfo'
remove space in cmdlet name
```suggestion
        'New-ScriptFileInfo'

```

2023-05-02 20:59 UTC, anamnavi approved these changes
LGTM, left some nitpicks to remove the Write-Host from test files (unless we need it). Also in the .psd1 file fixing the cmdlet name

2023-05-02 20:59 UTC, anamnavi commented on test/RepositoryTests/CompatGetPSResourceRepository.Tests.ps1
> +Write-Host "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
can we remove this Write-Host now?

2023-05-02 20:59 UTC, anamnavi commented on test/RepositoryTests/CompatRegisterPSResourceRepository.Tests.ps1
> +Write-Host "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
same as above, can we remove?

2023-05-02 20:59 UTC, anamnavi commented on test/RepositoryTests/CompatSetPSResourceRepository.Tests.ps1
> +Write-Host "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
same as above

2023-05-02 20:59 UTC, anamnavi commented on test/UninstallPSResourceTests/CompatUninstallPSResource.Tests.ps1
> +}
add newline
```suggestion
}

```

2023-05-02 21:02 UTC, alerickson commented on test/RepositoryTests/CompatGetPSResourceRepository.Tests.ps1
> +Write-Host "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
This is intentionally there as a kind of verbose output to help validate that the correct version of psget is being used

2023-05-02 22:19 UTC, PaulHigin commented on test/RepositoryTests/CompatGetPSResourceRepository.Tests.ps1
> +Write-Host "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
I would use `Write-Verbose -Verbose -Message` rather than Write-Host.

2023-05-03 04:44 UTC, ThomasNieto commented on src/PowerShellGet.psd1
> +    FunctionsToExport = @(
Please for all that is good in the world don't add the v2 and v3 cmdlets in the same module. It will be so confusing for users when they search for commands for this module.

Just have PowerShellGet have a required dependency on the compat layer. It solves the problem with v2 cmdlets being available while leaving v3 clean.

2023-05-03 16:27 UTC, alerickson commented on src/PowerShellGet.psd1
> +    FunctionsToExport = @(
Thanks for the input @ThomasNieto, we've gone back and forth on a few different ways to treat the compat layer, but I can definitely see how that could cause a lot of confusion.   
Agreed that when seeing that `Find-Module`, for example, is coming from PowerShellGet, we don't actually know if we're getting the compat version of `Find-Module` or the PSGet v2 version.

cc: @SteveL-MSFT @mgreenegit @adityapatwardhan @PaulHigin @anamnavi

2023-05-03 19:36 UTC, adityapatwardhan requested changes

2023-05-03 19:36 UTC, adityapatwardhan commented on src/PowerShellGet.psd1
> +
Remove this

2023-05-03 19:36 UTC, adityapatwardhan commented on test/ScriptFileInfoTests/TestPSScriptFile.Tests.ps1
> +Get-Module PowerShellGet
```suggestion
Write-Verbose -Verbose -Message "PowerShellGet version currently loaded: $($(Get-Module powershellget).Version)"
```

2023-05-03 19:58 UTC, PaulHigin commented on src/PowerShellGet.psd1
> +    FunctionsToExport = @(
I understand the concern.  The thinking here is to make PSGetV3 more desirable by making it compatible with V2.  Having the compat module be a nested module of PSGetV3 is a temporary solution.  Before RC we want to bring the V2 cmdlets into PSGetV3 as first class.

2023-05-03 19:58 UTC, PaulHigin approved these changes
LGTM

2023-05-03 20:00 UTC, adityapatwardhan approved these changes

2023-05-03 21:22 UTC, ThomasNieto commented on src/PowerShellGet.psd1
> +    FunctionsToExport = @(
What do you gain by having the logic directly in PSGet (or nested module) vs just having a required dependency? Both accomplish the same goal of having the compat layer present while on v3.

Then there is your comment about making them first class. Why? This wasn't in the RFC. What is the point of having two separate cmdlets do the same thing?

The nested module does not solve my concern with user confusion on when to use one cmdlet over another as the nested module cmdlets show up as the parent module. And making them "first class" doesn't either. You'll get questions from users when do I use Install-Module vs Install-PSResource. Their question is valid is bad user experience having both present in the single module. By having it separate there is some distinction and indicates what it's there for.

This also begs the question why not just use the old cmdlet names instead of making new ones since you're shipping the compat module for v2 processes. Just make the the compat layer a legacy parameter set. I know the reason behind using new names was to let users import v2 or v3 side by side without issue but now shipping the compat layer that has change fundamentally.

2023-05-03 22:11 UTC, SydneyhSmith commented on src/PowerShellGet.psd1
> +    FunctionsToExport = @(
@ThomasNieto we appreciate the feedback and are going to hold off on merging the PR, I am going to move these comments into the issue for the Compat integration so they can be more visible for community discussion

2023-05-04 23:59 UTC, alerickson commented
Closing this PR until a decision is made regarding integrating Compat or keeping as separate modules.

2023-05-04 23:59 UTC, closed without merging