add local API code and tests
PowerShell/PSResourceGet pull request #1065
Opened 2023-04-20 04:28 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-04-24 21:03 UTC, adityapatwardhan requested changes

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                // }
Remove this

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                // }
Remove this

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                //{
Remove this

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                foreach (PSResourceResult currentResult in currentResponseUtil.ConvertToPSResourceResult(responseResults: responses))
named parameters are usually only used when passing values likes 1,3 or boolean values. Passing an object is self explanatory

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                        FindResults responses = new FindResults();
is this needed? `FindNameGlobbing` and `FindNameGlobbingWithTag` return that object.

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
>                      if (pkgName.Trim().Equals("*"))
The method SearchByNames is very long, over 200 lines and has many if/else conditions and loops. I would like a code cleanup bug to refactor this in the future.

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                            _cmdletPassedIn.WriteError(new ErrorRecord(new InvalidOrEmptyResponse($"Dependency package with Name {dep.Name} and VersionRange {dep.VersionRange} could not be found in t
Please file an issue for having all error string in a resx file, to help localization.

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                                //continue;
Remove this

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/FindResults.cs
> +
Extra line, please remove

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/InstallHelper.cs
> +                if (repo.ApiVersion == PSRepositoryInfo.APIVersion.v2 || repo.ApiVersion == PSRepositoryInfo.APIVersion.v3 || repo.ApiVersion == PSRepositoryInfo.APIVersion.local)
Should this be flipped to `repo.ApiVersion != PSRepositoryInfo.APIVersion.unknown`

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/InstallHelper.cs
> +                if (repo.ApiVersion == PSRepositoryInfo.APIVersion.v2 || repo.ApiVersion == PSRepositoryInfo.APIVersion.v3 || repo.ApiVersion == PSRepositoryInfo.APIVersion.local)
Or even this:

```csharp
if (repo.ApiVersion == PSRepositoryInfo.APIVersion.unknown) {
 throw new InvalidOperation("Unexpected API version");
}
```

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/InstallHelper.cs
> +            FindResults responses = new FindResults();
is this required?

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +            }
This part looks very similar to previous method. Refactor?

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +            foreach (string path in Directory.GetFiles(repository.Uri.AbsolutePath))
Can this be used: https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-8.0#system-io-directory-getfiles(system-string-system-string)

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +                // TODO: catch more specific ones
TODO for this PR or for later?

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +                                // todo error handle?
Handle errors

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +                                // TODO error handle?
Same here

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +                                // TODO error handle?
Same here

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +
extra line

2023-04-24 21:03 UTC, adityapatwardhan commented on src/code/V2ServerAPICalls.cs
> +            //var requestUrlV2 = $"{repository.Uri}/Search()?{prereleaseFilter}&searchTerm='tag:{tagFilter}{tag}'{prereleaseFilter}{paginationParam}&{select}";
remove this

2023-04-25 23:02 UTC, PaulHigin requested changes

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +        public override PSRepositoryInfo repository { get; set; }
Class properties generally begin with uppercase (Pascal casing) , e.g., `Repository`.  (Non-blocking comment).

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +            foreach (Hashtable response in responses)
```suggestion
            foreach (Hashtable response in responseResults.HashtableResponse)
```

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +            Hashtable[] responses = responseResults.HashtableResponse;
Is it possible for HastableResponse property to be null?

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +                if (!response.ContainsKey(fileTypeKey) || fileTypeKey.Equals(Utils.MetadataFileType.None))
Should these be case insensitive string compares?

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +                Utils.MetadataFileType fileType = (Utils.MetadataFileType) response[fileTypeKey];
Can this cast fail?  Maybe use this pattern if Utils.MetadataFileType is an enum:

```csharp
Utils.MetadataFileType fileType;
if (! Utils.MetadataFileType.TryParse(fileTypeKey, out fileType)) { throw ... }

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalResponseUtil.cs
> +                        ))
Closing parentheses should not be on separate line.

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalServerApiCalls.cs
> +        public override PSRepositoryInfo repository { get; set; }
Do all of these need to be public access?  Please make private if not needed outside class.  Also properties should use Pascal naming convention and class fields should use camelCasing (with underscore prefix).

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalServerApiCalls.cs
> +                    if (!nugetVersion.IsPrerelease || includePrerelease)
Can combine these two if statements in to one.

2023-04-25 23:02 UTC, PaulHigin commented on src/code/LocalServerApiCalls.cs
> +                    if (!nugetVersion.IsPrerelease || includePrerelease)
Please combine these two if statements.

2023-04-28 20:09 UTC, anamnavi commented on src/code/LocalServerApiCalls.cs
> +                // TODO: catch more specific ones
For later, when we change how errors are captured in the next release.

2023-04-28 21:17 UTC, anamnavi commented on src/code/LocalServerApiCalls.cs
> +                                // TODO error handle?
this will actually be verbose handling, as this error shouldn't disqualify the package from being returned via Find. I'll create an issue to track this.

2023-05-01 17:34 UTC, anamnavi commented on src/code/LocalServerApiCalls.cs
> +            foreach (string path in Directory.GetFiles(repository.Uri.AbsolutePath))
For net462 the `GetFiles(string path, string searchPattern)` method's search has platform dependent case sensitivity, so this does not work. There's a parameter `EnumerationOptions` which can set case insensitivity but it's not present in net462 (is present in .Net 7)

From the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=netframework-4.6.2) under Remarks section:
The case-sensitivity of the path parameter corresponds to that of the file system on which the code is running. For example, it's case-insensitive on NTFS (the default Windows file system) and case-sensitive on Linux file systems.

2023-05-02 20:13 UTC, anamnavi commented on src/code/FindHelper.cs
>                      if (pkgName.Trim().Equals("*"))
https://github.com/PowerShell/PowerShellGet/issues/1087

2023-05-02 20:19 UTC, anamnavi commented on src/code/FindHelper.cs
> +                            _cmdletPassedIn.WriteError(new ErrorRecord(new InvalidOrEmptyResponse($"Dependency package with Name {dep.Name} and VersionRange {dep.VersionRange} could not be found in t
https://github.com/PowerShell/PowerShellGet/issues/1088

2023-05-02 20:21 UTC, anamnavi commented on src/code/LocalResponseUtil.cs
> +            Hashtable[] responses = responseResults.HashtableResponse;
I added checks to ensure this cannot be null.

2023-05-02 20:25 UTC, anamnavi commented on src/code/LocalResponseUtil.cs
> +                if (!response.ContainsKey(fileTypeKey) || fileTypeKey.Equals(Utils.MetadataFileType.None))
Since we add this key to the hastable with the same value (stored in a readonly string) as the value of they key it is parsed out of the hashtable with, this should never differ in case sensitivity.

`Hashtable.ContainsKey()` does not take a StringComparer parameter. Also the 2nd condition is comparing enum values, so it does not need to be case sensitive I believe.

2023-05-02 22:18 UTC, PaulHigin approved these changes

2023-05-03 01:22 UTC, alerickson approved these changes
LGTM!

2023-05-03 17:42 UTC, adityapatwardhan approved these changes

2023-05-03 17:47 UTC, merged