Add bugfix for parsing nuspec tags for local repos
PowerShell/PSResourceGet pull request #1119
Opened 2023-05-16 14:53 UTC by anamnavi

# PR Summary

The tags property is a string, not string[] in the .nuspec file. For non-powershell resources when we default to parsing the .nuspec we should parse tags out as string. Otherwise it fails with an error.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-05-16 17:52 UTC, alerickson approved these changes

2023-05-16 17:52 UTC, alerickson approved these changes

2023-05-16 19:31 UTC, adityapatwardhan requested changes

2023-05-16 19:31 UTC, adityapatwardhan commented on src/code/LocalServerApiCalls.cs
> +                    string nuspecTags = pkgMetadata["tags"] as string;
Need to add a test for this.

2023-06-06 22:22 UTC, adityapatwardhan approved these changes

2023-06-06 23:07 UTC, merged