Ado feed support
PowerShell/PSResourceGet pull request #1144
Opened 2023-05-19 15:09 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-05-19 17:26 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +        /// <summary>
remove

2023-05-19 17:27 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                if (repoUri.AbsoluteUri.Contains("pkgs.dev.azure.com"))
ask Johnathon so we are fully sure.

2023-05-27 01:42 UTC, alerickson requested changes
I added some suggestions for minor changes, but overall looks really good

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +using System.Security.Cryptography;
I would just move these directives under the copyright header

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +        /// Not supported for ADO repository.
```suggestion
        /// Not supported for v3 repositories.
```

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +        /// Not supported for ADO repository.
```suggestion
        /// Not supported for v3 repositories.
```

2023-05-27 01:42 UTC, alerickson commented on test/FindPSResourceTests/FindPSResourceADOServer.Tests.ps1
> +Write-Verbose -Verbose "Current module search paths: $psmodulePaths"
I think we can get rid of lines 7 and 8 now

2023-05-27 01:42 UTC, alerickson commented on test/FindPSResourceTests/FindPSResourceADOServer.Tests.ps1
> +        foreach ($item in $res) {
just add a line after line 64 and before line 65 that checks if $res is empty

2023-05-27 01:42 UTC, alerickson commented on test/FindPSResourceTests/FindPSResourceADOServer.Tests.ps1
> +        $res | ForEach-Object {
check of $res is empty before looping through

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +Write-Verbose -Verbose "Current module search paths: $psmodulePaths"
Remove lines 8 & 9 if not needed anymore

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +        $err[0].FullyQualifiedErrorId | Should -BeExactly "$ErrorId,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource"
I would also add a check here to see if it was installed (ie Get-InstalledPSResource $Name  should be empty)

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +    It "Install resource under specified in PSModulePath" {
We don't need this test anymore since we're no longer using PSModulePath

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +}
```suggestion
}

```

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +    # It "Restore resource after reinstall fails" {
If this test is in the v3 server test class I think we should just remove this entire unit test.

2023-05-27 01:42 UTC, alerickson commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +    # It "Install resource that requires accept license with -AcceptLicense flag" {
Does this test not work or is there an issue with finding a package to test against?

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +        private Dictionary<string, string> GetResourcesFromServiceIndex(out ExceptionDispatchInfo edi)
Add an example or url to an example here because it's a little confusing

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +            Dictionary<string, string> resources = GetResourcesFromServiceIndex(out edi);
There's a few methods that use `GetResourcesFromServiceIndex`, `FindRegistrationsBaseUrlForAllV3` and `GetVersionedResponses` all back to back.  Consider moving this out to a helper method that then calls all three methods.

2023-05-27 01:42 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +        public override Stream InstallName(string packageName, bool includePrerelease, out ExceptionDispatchInfo edi)
`InstallName` and `InstallVersion` essentially do the exact same thing except that `InstallVersion` is looping through `versionedResponses` and `InstallName` just chooses the first element in the array.  I think the implementation for `InstallVersion` can be moved out into a helper method and both `InstallName` and `InstallVersion` can call into it.  So if no version was passed in we just choose the first element in the array, but if a particular version was passed in we loop through searching for that one.

2023-05-30 20:02 UTC, anamnavi commented on test/InstallPSResourceTests/InstallPSResourceADOServer.Tests.ps1
> +    # It "Install resource that requires accept license with -AcceptLicense flag" {
need to create a package to test against.

2023-05-30 20:08 UTC, alerickson commented
I think this PR should resolve #1057

2023-05-30 22:24 UTC, anamnavi commented
> I think this PR should resolve #1057

It partially fixes it. PSGallery is searching scripts and modules endpoints, but only finds it from the modules endpoint and writes an error for the scripts endpoint, but also returns modules found. I'll fix this in a separate PR

2023-05-31 02:37 UTC, alerickson approved these changes
I tried adding these changes to your branch directly but despite my pushing it's not showing up here.  Everything looks good, but the tests are failing because some of the error messages are still referencing 'PowerShellGet' when they should reference 'PSResourceGet'.  Once the tests are passing should be good to go!

2023-05-31 20:02 UTC, closed without merging