Update V3Server support to account for non-NuGet.org repositories
PowerShell/PSResourceGet pull request #1167
Opened 2023-05-31 16:21 UTC by anamnavi

# PR Summary

Our existing V3 server support was supporting NuGet.org but not working for ADO server repositories. This PR changes the V3 server support to be more generalized to how all V3 servers should act (including ADO)

## PR Context

Resolves #1054 #1000 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-05-31 17:01 UTC, alerickson approved these changes

2023-05-31 21:22 UTC, alerickson commented
Okay, unfortunately I tested this against Artifactory and it's not yet working with those repositories just yet, but we may be small changes we need to make.  No need to worry about that for this PR, I just wanted to see if this would handle Artifactory scenarios.

2023-06-01 01:05 UTC, adityapatwardhan requested changes

2023-06-01 01:05 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +                        List<string> tags = new List<string>();
```suggestion
                        var arrayLength = tagsElement.GetArrayLength();
                        List<string> tags = new List<string>(arrayLength);
```

2023-06-01 01:05 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +                    string[] pkgTags = Utils.EmptyStrArray;
This can be removed and line 670 be:

string[] pkgTags = tags.ToArray();

2023-06-01 01:05 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +                        pkgTags = tagStr.Split(new char[]{' '}, StringSplitOptions.RemoveEmptyEntries);
Can this new char[]{' '} be added to Utils class as a constant. This will save on allocations.

2023-06-01 01:05 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +                // TODO vNext, a little complicated
Should there be a bug for this?

2023-06-01 14:06 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +                    string[] pkgTags = Utils.EmptyStrArray;
That line is in the `if` condition, I also set `pkgTags` in the `else` condition and use it outside the if/else, so I can't remove that line. Then `metadata["Tags"] is set to `pkgTags` (so that if Tags were neither array or string or an empty array, it's still set to an empty string array.

2023-06-01 19:16 UTC, adityapatwardhan approved these changes

2023-06-01 20:05 UTC, merged