WIP: Improve performance for Uninstall-PSResource by caching
PowerShell/PSResourceGet pull request #1175
Opened 2023-06-02 06:01 UTC by adityapatwardhan

# PR Summary

Cache the output of Get-Module -ListAvailable for every invocation of the cmdlet.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-06-02 20:58 UTC, alerickson requested changes

2023-06-02 20:58 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            // Structure of LINQ call:
``
```suggestion
```

2023-06-02 20:58 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            // Results is a collection of PSModuleInfo objects that contain a property listing module dependencies, "RequiredModules".
```suggestion
            // _dependentModules is a collection of PSModuleInfo objects that contain a property listing module dependencies, "RequiredModules".

```

2023-06-02 20:58 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +
```suggestion

```

2023-06-02 20:58 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            _dependentModules?.Clear();
what's the benefit to clearing _dependentModules here?  If there's pipeline input doesn't ProcessRecord() potentially occur multiple times before EndProcessing() is hit?

2023-06-06 18:53 UTC, adityapatwardhan commented on src/code/UninstallPSResource.cs
> +            _dependentModules?.Clear();
```suggestion
```

2023-06-06 19:16 UTC, alerickson approved these changes

2023-06-06 19:29 UTC, merged