WIP: Update changelog and psd1
PowerShell/PSResourceGet pull request #1177
Opened 2023-06-02 19:52 UTC by alerickson

# PR Summary
Update changelog and .psd1 for next release.  

The .csproj still needs to be updated.

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-06-06 20:22 UTC, SydneyhSmith commented
@sdwheeler do we need to update the help uri?

2023-06-06 20:57 UTC, sdwheeler commented
> @sdwheeler do we need to update the help uri?

Yes, you need two new FWLinks, one for each module, PSResourceGet and the compat module.

The target of both links needs to be "https://pshelpprod.blob.core.windows.net/cabinets/powershellget-3.x/".

Do you want me to create them?

2023-06-06 20:58 UTC, SydneyhSmith commented
> > @sdwheeler do we need to update the help uri?
> 
> Yes, you need two new FWLinks, one for each module, PSResourceGet and the compat module.
> 
> The target of both links needs to be "https://pshelpprod.blob.core.windows.net/cabinets/powershellget-3.x/".
> 
> Do you want me to create them?

@sdwheeler that would be great!

2023-06-06 21:09 UTC, sdwheeler commented
PSResourceGet - https://go.microsoft.com/fwlink/?linkid=2238183
PowerShellGet (compat) - https://go.microsoft.com/fwlink/?linkid=2238451

2023-06-06 21:19 UTC, sdwheeler commented
Here is another copy of the same video - https://www.youtube.com/watch?v=BXmUE5qWmyQ

2023-06-07 16:20 UTC, anamnavi requested changes
Tiny changes, but overall looks great!

2023-06-07 16:20 UTC, anamnavi commented on CHANGELOG.md
> +- Change the type of -InputObject from PSResource to PSResource[] for Install-PSResource, Save-PSResource, and Uninstall-PSResource (#1124)
```suggestion
- Change the type of -InputObject from PSResourceInfo to PSResourceInfo[] for Install-PSResource, Save-PSResource, and Uninstall-PSResource (#1124)

```

2023-06-07 16:20 UTC, anamnavi commented on CHANGELOG.md
> +- Support for Azure Artifacts, GitHub Packages, and Artifactory (#1167, #1180)
```suggestion
- Support for Azure Artifacts, GitHub Packages, and Artifactory (#1167, #1180, #1183)

```

2023-06-07 16:20 UTC, anamnavi commented on CHANGELOG.md
> +- Bug fix for parsing package tags from local repository (#1119)
```suggestion
- Bug fix for parsing package tags for packages that only have .nuspec from local repository (#1119) 

```

2023-06-07 18:37 UTC, anamnavi approved these changes

2023-06-07 19:10 UTC, merged