Add support for FindNameGlobbing scenarios for MyGet server repository (V3)
PowerShell/PSResourceGet pull request #1202
Opened 2023-06-20 19:07 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-06-22 17:06 UTC, alerickson requested changes

2023-06-22 17:06 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +        private readonly int myGetTotalHitsBuffer = 10000;
should this be 1,000 or is the numbe returned 10,000 + the actual number?

2023-07-08 01:25 UTC, anamnavi commented on src/code/V3ServerAPICalls.cs
> +        private readonly int myGetTotalHitsBuffer = 10000;
this should be 10,000 in the comment. Thanks for catching that. I've updated the comment and added the reasoning their engineer gave me so we know

2023-07-10 17:00 UTC, adityapatwardhan approved these changes

2023-07-10 23:41 UTC, alerickson approved these changes

2023-07-11 17:04 UTC, merged