Bug fix for searching through local repositories with -Type parameter
PowerShell/PSResourceGet pull request #1252
Opened 2023-07-11 19:04 UTC by alerickson

# PR Summary
Bug fix for searching through local repositories with -Type parameter.  This PR allows for filtering on type.

## PR Context
Resolves #1219 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-07-12 22:14 UTC, adityapatwardhan requested changes

2023-07-12 22:14 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +
Is this related to the PR? seems like a fix for a different issue

2023-07-13 19:34 UTC, alerickson commented on src/code/PSResourceInfo.cs
> +
Yup, I can add this is a different PR to it separate.

2023-07-13 21:38 UTC, alerickson commented on src/code/PSResourceInfo.cs
> +
Oh actually it is needed for the -Type issue, I tried removing it and it does impact -Type functionality.

2023-07-13 21:57 UTC, adityapatwardhan approved these changes

2023-07-13 23:20 UTC, merged