Fix error message for Publish-PSResource for MyGet.org feeds
PowerShell/PSResourceGet pull request #1256
Opened 2023-07-12 03:39 UTC by anamnavi

# PR Summary

Improve error messages presented when running Publish-PSResource for MyGet.org repository. When publishing to this type of repository errors can be written out when the -ApiKey value is missing or incorrect. The server side error message is not clear enough on its own so add to it.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-07-12 22:14 UTC, alerickson requested changes
Just a question and some quotation suggestions

2023-07-12 22:14 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': Please try running again with the -ApiKey parameter and specific API key for the repository specified. Exception: {1}", repoName
```suggestion
                        var message = String.Format("Repository '{0}': Please try running again with the -ApiKey parameter and specific API key for the repository specified. Exception: '{1}'", repoName, e.Message);

```

2023-07-12 22:14 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': The Credential provided was incorrect. Exception: {1}", repoName, e.Message);
```suggestion
                        var message = String.Format("Repository '{0}': The Credential provided was incorrect. Exception: '{1}'", repoName, e.Message);

```

2023-07-12 22:14 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': The ApiKey provided is incorrect or missing. Please try running again with the -ApiKey parameter and correct API key value for t
```suggestion
                        var message = String.Format("Repository '{0}': The ApiKey provided is incorrect or missing. Please try running again with the -ApiKey parameter and correct API key value for the repository. Exception: '{1}'", repoName, e.Message);

```

2023-07-12 22:14 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                    var message = String.Format ("Repository '{0}': The Credential provided was incorrect. Exception {1}", repoName, e.InnerException.Message);
```suggestion
                    var message = String.Format ("Repository '{0}': The Credential provided was incorrect. Exception '{1};", repoName, e.InnerException.Message);

```

2023-07-12 22:14 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        // For myGet.org repository feeds when the ApiKey is missing or incorrect.
Is MyGet the only one that has this error when the ApiKey is missing/incorrect?

2023-07-14 15:59 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                        // For myGet.org repository feeds when the ApiKey is missing or incorrect.
Yes, only MyGet throws a 403 when ApiKey is missing, the other repositories we have documented throw a 400 or 401.

2023-07-17 19:58 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                        // For myGet.org repository feeds when the ApiKey is missing or incorrect.
JFrog will throw 403 if ApiKey is specified (correct or incorrect)

2023-07-18 17:49 UTC, alerickson approved these changes
Just some formatting and wording suggestions.

2023-07-18 17:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': Please try running again with the -ApiKey parameter and specific API key for the repository specified. Exception: '{1}'", repoNa
```suggestion
                        var message = $"Could not publish to repository '{repoName}'. Please try running again with the -ApiKey parameter and the API key for the repository specified. Exception: '{e.Message}'";

```

2023-07-18 17:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': The Credential provided was incorrect. Exception: '{1}'", repoName, e.Message);
```suggestion
                        var message =$"Could not publish to repository '{repoName}'. The Credential provided was incorrect. Exception: '{e.Message}'";

```

2023-07-18 17:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': The ApiKey provided is incorrect or missing. Please try running again with the -ApiKey parameter and correct API key value for t
```suggestion
                        var message = $"Could not publish to repository '{repoName}'. The ApiKey provided is incorrect or missing. Please try running again with the -ApiKey parameter and correct API key value for the repository. Exception: '{e.Message}'";

```

2023-07-18 17:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                    var message = String.Format ("Repository '{0}': The Credential provided was incorrect. Exception '{1};", repoName, e.InnerException.Message);
```suggestion
                    var message = $"Could not publish to repository '{repoName}'. The Credential provided was incorrect. Exception '{e.InnerException.Message}'";

```

2023-07-18 17:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        var message = String.Format("Repository '{0}': The ApiKey provided is not needed for JFrog Artifactory. Please try running again without the -ApiKey parameter but ensure that
```suggestion
                        var message = $"Could not publish to repository '{repoName}'. The ApiKey provided is not needed for JFrog Artifactory. Please try running again without the -ApiKey parameter but ensure that -Credential is provided with ApiKey as password. Exception: '{e.Message}'";

```

2023-07-18 18:32 UTC, merged