Add aliases for Install-PSResource, Find-PSResource, Update-PSResource, Publish-PSResource
PowerShell/PSResourceGet pull request #1264
Opened 2023-07-13 02:30 UTC by alerickson

# PR Summary
Add 'inps', 'fips', 'upps' and 'pups' aliases for Install-PSResource, Find-PSResource, Update-PSResource, Publish-PSResource respectively.

## PR Context
Resolves #1152 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-07-13 02:53 UTC, ThomasNieto commented
I don't think `ps` is not the best alias noun as `ps` is short for PowerShell not resources. It might be confusing for users. Have you thought of using something like `rs` or `res`?

2023-07-13 02:55 UTC, ThomasNieto requested changes
You'll also need to add the aliases to the module manifest.

2023-07-13 03:02 UTC, ThomasNieto commented
The alias prefix also doesn't match the [verb alias recommendations](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.3).

> Each approved verb has a corresponding alias prefix defined. We use this alias prefix in aliases for commands using that verb. For example, the alias prefix for Import is ip and, accordingly, the alias for Import-Module is ipmo. This is a recommendation but not a rule; in particular, it need not be respected for command aliases mimicking well known commands from other environments.

```powershell
Get-Verb Install, Find, Update, Publish | select Verb, AliasPrefix

Verb    AliasPrefix
----    -----------
Find    fd
Publish pb
Update  ud
Install is
```

2023-07-14 16:00 UTC, anamnavi approved these changes

2023-07-14 16:05 UTC, anamnavi requested changes

2023-07-14 16:05 UTC, anamnavi commented on src/code/FindPSResource.cs
> +    [Alias("fips")]
```suggestion
    [Alias("fdps")]
```

2023-07-14 16:05 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +    [Alias("inps")]
```suggestion
    [Alias("isps")]
```

2023-07-14 16:05 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +    [Alias("pups")]
```suggestion
    [Alias("pbps")]

```

2023-07-14 16:05 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +    [Alias("upps")]
```suggestion
    [Alias("udps")]

```

2023-07-14 16:05 UTC, anamnavi commented on test/FindPSResourceTests/FindPSResourceLocal.Tests.ps1
> +        (Get-Alias fips).Definition | Should -BeExactly 'Find-PSResource'
```suggestion
    It "Get definition for alias 'fdps'" {
        (Get-Alias fdps).Definition | Should -BeExactly 'Find-PSResource'
```

2023-07-14 16:05 UTC, anamnavi commented on test/InstallPSResourceTests/InstallPSResourceLocal.Tests.ps1
> +        (Get-Alias inps).Definition | Should -BeExactly 'Install-PSResource'
```suggestion
    It "Get definition for alias 'isps'" {
        (Get-Alias isps).Definition | Should -BeExactly 'Install-PSResource'
```

2023-07-14 16:05 UTC, anamnavi commented on test/PublishPSResourceTests/PublishPSResource.Tests.ps1
> +        (Get-Alias pups).Definition | Should -BeExactly 'Publish-PSResource'
```suggestion
    It "Get definition for alias 'pbps'" {
        (Get-Alias pbps).Definition | Should -BeExactly 'Publish-PSResource'
```

2023-07-14 16:05 UTC, anamnavi commented on test/UpdatePSResourceTests/UpdatePSResourceLocalTests.ps1
> +        (Get-Alias upps).Definition | Should -BeExactly 'Update-PSResource'
```suggestion
    It "Get definition for alias 'udps'" {
        (Get-Alias udps).Definition | Should -BeExactly 'Update-PSResource'
```

2023-07-14 16:08 UTC, anamnavi commented
Thanks for the feedback @ThomasNieto . I've suggested changes to update the aliases to match the PowerShell recommended verbs aliases.

I also like the idea of not having "ps" denote "PSResource"...I agree it's not what my mind goes to first, I think of "powershell". Maybe "res"?

2023-07-14 16:40 UTC, alerickson commented
@ThomasNieto we'll chat about it with @SydneyhSmith, I was just copying the format of first two letters of the verb + first two letters of the noun,  but given that doc if we're changing the first part we may as well make the second half a bit more intuitive too

2023-07-14 20:10 UTC, alerickson commented on src/code/FindPSResource.cs
> +    [Alias("fips")]
added in a new commit

2023-07-17 18:23 UTC, ThomasNieto requested changes
The aliases look good to me, the last thing needed is to update the module manifest with the new aliases.

https://github.com/PowerShell/PSResourceGet/blob/5c783542f6d414b7146a405dcb867e98caac27ea/src/Microsoft.PowerShell.PSResourceGet.psd1#L39

2023-07-18 22:10 UTC, anamnavi commented
@alerickson can we add the aliases here too: https://github.com/alerickson/PSResourceGet/blob/addAliases/src/Microsoft.PowerShell.PSResourceGet.psd1#L40

2023-07-24 18:27 UTC, anamnavi approved these changes
LGTM

2023-07-24 18:31 UTC, adityapatwardhan approved these changes

2023-07-24 19:03 UTC, merged