add error handling for local repo searching
PowerShell/PSResourceGet pull request #1316
Opened 2023-07-28 19:18 UTC by anamnavi

# PR Summary
Find against a local repo where the name contains wildcard, is "*", or is a tag search will search through all file names in the repository. If the package name isn't a match it need not throw an error but it should gracefully recognize and continue past that package onto the next. Currently it was not and was throwing array out of bounds exceptions.

Resolves #1299 #1297
## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-07-31 21:17 UTC, alerickson requested changes

2023-07-31 21:17 UTC, alerickson commented on test/FindPSResourceTests/FindPSResourceLocal.Tests.ps1
> +        $res = Find-PSResource -Tag "nonexistenttag" -Repository $localRepo -ErrorVariable err -ErrorAction SilentlyContinue
Why should this not write an error?  The name is theoretically "*" since we need to search through all packages to find this tag, but there's no explicit wildcard search here.  Shouldn't we still write an error if the user is asking for a package with a specific tag and we can't find that tag?

2023-08-04 00:52 UTC, alerickson approved these changes

2023-08-04 00:52 UTC, alerickson commented on src/code/LocalServerApiCalls.cs
> +                errRecord = new ErrorRecord(new LocalResourceNotFoundException($"Package(s) with Tags '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."), "FindTagsPac
```suggestion
                errRecord = new ErrorRecord(new ResourceNotFoundException($"Package(s) with Tags '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."), "FindTagsPackageNotFound", ErrorCategory.ParserError, this);
```

2023-08-04 17:45 UTC, adityapatwardhan approved these changes

2023-08-04 21:13 UTC, anamnavi commented
PR #1339 must be merged in first

2023-08-11 17:22 UTC, merged