Bug fix for parsing required modules when publishing
PowerShell/PSResourceGet pull request #1326
Opened 2023-08-01 21:16 UTC by alerickson

# PR Summary
RequiredModules were not being parsed correctly from a module manifest during publish time, thus when, for example, RequiredModules contained both a Hashtable and a string, the hashtable would be parsed as a string and incorrectly assume the module name was "System.Collections.Hashtable".  This PR loops through every element of RequiredModules and tries to parse each object individually instead of assuming that all types within RequiredModules are the same and attempting to parse the object as a whole. 

## PR Context
Resolves #1305 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-08-02 19:10 UTC, adityapatwardhan requested changes

2023-08-02 19:10 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
>              foreach (var dependency in dependencies.Keys)
Never enumerate keys of a Hashtable. That causes rehashing and is bad for performance. Use should iterate like here: https://learn.microsoft.com/en-us/dotnet/api/system.collections.dictionaryentry?view=net-7.0

2023-08-02 19:10 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +                        dependenciesHash.Add(moduleHash["ModuleName"], moduleHash["ModuleVersion"]);
`moduleHash["ModuleName"]` is looked up multiple times. Better to store it in local variable and re-use the value

2023-08-03 19:22 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        dependenciesHash.Add(moduleHash["ModuleName"], moduleHash["ModuleVersion"]);
Actually it's only looked up once since it's an if/elseif/else condition. If it's guaranteed to only look up once per iteration I wasn't sure if it's better to have a variable or the look up.

2023-08-03 19:23 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +                        dependenciesHash.Add(moduleHash["ModuleName"], moduleHash["ModuleVersion"]);
Yes, i see

2023-08-03 19:23 UTC, adityapatwardhan approved these changes

2023-08-03 23:44 UTC, merged