WIP: Bug fix for searching through multiple repositories, some of which do not contain pkg to find
PowerShell/PSResourceGet pull request #1328
Opened 2023-08-02 19:09 UTC by alerickson

# PR Summary
When `Find-PSResource` searches through multiple repositories, it was previously writing errors for each repository it could not find the given package in along side the package information from the repository where it could find it.

This PR does not write errors from the repositories where the package does not exist and instead writes verbose messages.  

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-08-03 19:26 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                    pkgFound = currentPkg != null;
It seems that currentPkg can be null here. Should we be yield returning a null then?
Should be continue instead when it is null?

2023-08-03 19:27 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                            new ResourceNotFoundException($"Package(s) '{string.Join(", ", _pkgsLeftToFind)}' cound not be found in any registered repositories."),
```suggestion
                            new ResourceNotFoundException($"Package(s) '{string.Join(", ", _pkgsLeftToFind)}' could not be found in any registered repositories."),
```

2023-08-03 19:28 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                               _cmdletPassedIn.WriteVerbose($"Package '{pkgName}' could not be found");
consider having repository name in the message here.

2023-08-03 19:29 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                                            new ResourceNotFoundException($"Package '{pkgName}' with version '{_version}' could not be found", currentResult.exception),
same as above

2023-08-03 19:32 UTC, adityapatwardhan requested changes
Couple of suggestions above

2023-08-03 21:03 UTC, alerickson commented on src/code/FindHelper.cs
> +                                            new ResourceNotFoundException($"Package '{pkgName}' with version '{_version}' could not be found", currentResult.exception),
Anam made these changes in a PR that got merged, so I'll just pull in those changes.

2023-08-04 00:53 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +
```suggestion

                    pkgFound = true;
```

2023-08-04 00:54 UTC, adityapatwardhan approved these changes

2023-08-04 00:54 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                                _cmdletPassedIn.WriteVerbose($"Package '{pkgName}' could not be found in repository '{repository.Name}");
```suggestion
                               _cmdletPassedIn.WriteVerbose($"Package '{pkgName}' could not be found in repository '{repository.Name}");
```

2023-08-04 03:24 UTC, merged