Error handle for V2 Find
PowerShell/PSResourceGet pull request #1329
Opened 2023-08-02 19:46 UTC by anamnavi

# PR Summary

Improve error handling for V2 repositories. For FindTags() we currently write duplicated errors so this PR fixes that. It also error handles package not found type errors in ServerApiCall level instead of in ResponseUtil level.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-08-02 20:35 UTC, alerickson commented
Just added those suggested changes since 'ResourceNotFoundException' will be the one that gets later down the road in PR #1328

2023-08-02 20:35 UTC, alerickson approved these changes

2023-08-02 20:35 UTC, alerickson commented on src/code/V2ServerAPICalls.cs
> +                    new PackageNotFoundException($"Package with Tags '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."),
```suggestion
                    new ResourceNotFoundException($"Package with Tags '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."), 
```

2023-08-02 20:35 UTC, alerickson commented on src/code/V2ServerAPICalls.cs
> +                    new PackageNotFoundException($"Package with {parameterForErrorMsg} '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."),
```suggestion
                    new ResourceNotFoundException($"Package with {parameterForErrorMsg} '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."), 
```

2023-08-04 17:51 UTC, adityapatwardhan requested changes

2023-08-04 17:51 UTC, adityapatwardhan commented on src/code/V2ServerAPICalls.cs
>                  int initalScriptCount = GetCountFromResponse(initialScriptResponse, out errRecord);
```suggestion
                int initialScriptCount = GetCountFromResponse(initialScriptResponse, out errRecord);
```

typo in variable name

2023-08-04 17:51 UTC, adityapatwardhan commented on src/code/V2ServerAPICalls.cs
> +                if (initalScriptCount != 0)
```suggestion
                if (initialScriptCount != 0)
```

2023-08-04 17:51 UTC, adityapatwardhan commented on src/code/V2ServerAPICalls.cs
> +                    int count = initalScriptCount / 100;
```suggestion
                    int count = initialScriptCount / 100;
```

2023-08-04 17:51 UTC, adityapatwardhan commented on src/code/V2ServerAPICalls.cs
> +                    new ResourceNotFoundException($"Package with {parameterForErrorMsg} '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."),
should the message have tags here or should it be Command / DSC resource?

2023-08-04 18:55 UTC, anamnavi commented on src/code/V2ServerAPICalls.cs
> +                    new ResourceNotFoundException($"Package with {parameterForErrorMsg} '{String.Join(", ", tags)}' could not be found in repository '{Repository.Name}'."),
the parameter is called tags, but its value is Command names or DSCResource names passed in. Since it's a type of tag we just kept that parameter name

2023-08-04 21:05 UTC, adityapatwardhan approved these changes

2023-08-04 21:10 UTC, merged