Add verbose statements and clean up code
PowerShell/PSResourceGet pull request #1370
Opened 2023-08-18 04:26 UTC by alerickson

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-08-21 21:26 UTC, anamnavi requested changes
Looks great so far, marked this as "Request Changes" because the solution file got merged in and because I'm wondering if `_cmdletPassedIn` should be named `CmdletPassedIn` since its public?

2023-08-21 21:26 UTC, anamnavi commented on src/code/GetInstalledPSResource.cs
> +                        new PSArgumentException("Error: Could not resolve provided Path argument into a single path."),
Perhaps we write out what Path's value is.
```suggestion
                        new PSArgumentException($"Error: Could not resolve provided Path argument '{Path}' into a single path."),

```

2023-08-21 21:26 UTC, anamnavi commented on src/code/GetPSScriptFileInfo.cs
>              foreach (string msg in verboseMsgs)
should we rename the variable `verboseMsgs` now that we write it as a debug statement?

2023-08-21 21:26 UTC, anamnavi commented on src/code/Microsoft.PowerShell.PSResourceGet.sln
was this added accidentally?

2023-08-21 21:26 UTC, anamnavi commented on src/code/NuGetServerAPICalls.cs
> +        public PSCmdlet _cmdletPassedIn { get; set; }
if this is a public property instead of a private field do we need the underscore or should it be `CmdletPassedIn`?

2023-08-21 21:26 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +
Can we add a verbose or a debug on L843 where we set the registered repository's ApiVersion to unknown saying we couldn't recognize this as a known supported repository?

2023-08-21 21:26 UTC, anamnavi commented on src/code/V3ServerAPICalls.cs
> +                    _cmdletPassedIn.WriteDebug($"Id found '{id}'");
```suggestion
                    _cmdletPassedIn.WriteDebug($"Id for package that could be candidate for FindNameGlobbing found '{id}'");
```

2023-08-22 06:48 UTC, alerickson commented on src/code/NuGetServerAPICalls.cs
> +        public PSCmdlet _cmdletPassedIn { get; set; }
I just changed it to be a private field

2023-08-22 06:58 UTC, alerickson commented on src/code/RepositorySettings.cs
> +
I don't think we can add debug/verbose statements to the Read method in RepositorySettings because the ArgumentCompleter class calls it and it's not related to any particular cmdlet (https://github.com/PowerShell/PSResourceGet/blob/662c436a4ff277d6744965ce94cb65a6e0a988ed/src/code/ArgumentCompleter.cs#L19)

2023-08-22 07:17 UTC, alerickson commented
> Looks great so far, marked this as "Request Changes" because the solution file got merged in and because I'm wondering if `_cmdletPassedIn` should be named `CmdletPassedIn` since its public?

Just updated this to make it a private readonly variable like the other classes

2023-08-22 18:14 UTC, anamnavi approved these changes
LGTM

2023-08-22 18:26 UTC, merged