switch to using PowerShell session when calling cmdlets
PowerShell/PSResourceGet pull request #1385
Opened 2023-08-29 20:19 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-08-30 17:28 UTC, alerickson approved these changes

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                                message: $"Microsoft.PowerShell.SecretManagement module could not be imported for PSResourceRepository ({repositoryName}) authentication."),
```suggestion
                                message: $"Microsoft.PowerShell.SecretManagement module could not be imported for PSResourceRepository '{repositoryName}' authentication."),
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                                message: $"Microsoft.PowerShell.SecretManagement\\Get-Secret encountered an error while reading secret \"{repositoryCredentialInfo.SecretName}\" from vault \"{reposito
```suggestion
                                message: $"Microsoft.PowerShell.SecretManagement\\Get-Secret encountered an error while reading secret '{repositoryCredentialInfo.SecretName}' from vault '{repositoryCredentialInfo.VaultName}' for PSResourceRepository '{repositoryName}' authentication."),
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                        new PSNotSupportedException($"Secret \"{repositoryCredentialInfo.SecretName}\" from vault \"{repositoryCredentialInfo.VaultName}\" has an invalid type. The only supported type
```suggestion
                        new PSNotSupportedException($"Secret '{repositoryCredentialInfo.SecretName}' from vault '{repositoryCredentialInfo.VaultName}' has an invalid type. The only supported type is PSCredential."),
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
>                              message: $"Microsoft.PowerShell.SecretManagement\\Get-Secret encountered an error while reading secret \"{repositoryCredentialInfo.SecretName}\" from vault \"{repositoryCr
```suggestion
                            message: $"Microsoft.PowerShell.SecretManagement\\Get-Secret encountered an error while reading secret '{repositoryCredentialInfo.SecretName}' from vault '{repositoryCredentialInfo.VaultName}' for PSResourceRepository '{repositoryName}' authentication.",
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                                message: $"Microsoft.PowerShell.SecretManagement module could not be imported for PSResourceRepository ({repositoryName}) authentication."),
```suggestion
                                message: $"Microsoft.PowerShell.SecretManagement module could not be imported for PSResourceRepository '{repositoryName}' authentication."),
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
>                              message: $"Microsoft.PowerShell.SecretManagement\\Test-SecretVault encountered an error while validating the vault \"{repositoryCredentialInfo.VaultName}\" for PSResourceR
```suggestion
                            message: $"Microsoft.PowerShell.SecretManagement\\Test-SecretVault encountered an error while validating the vault '{repositoryCredentialInfo.VaultName}' for PSResourceRepository '{repositoryName}' authentication.",
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                bool result = (results.Count > 0) ? results[0] : false;
```suggestion
```

2023-08-30 17:28 UTC, alerickson commented on src/code/Utils.cs
> +                return result;
```suggestion
                return (results.Count > 0) ? results[0] : false;
```

2023-08-30 17:48 UTC, adityapatwardhan requested changes

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                    var results = pwsh.AddCommand("Microsoft.PowerShell.Core\\New-ModuleManifest").AddArgument(new object[] { parsedMetadata }).Invoke<Object>();
should check for pwsh.HadErrors or add ErrorAction Stop make sure an error causes an exception to be thrown.

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                var module = pwsh.AddCommand("Microsoft.PowerShell.Core\\Import-Module").AddParameters(
same as above

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                var secretValue = (results.Count == 1) ? results[0] : null;
results can be null in case of a failure in Get-Secret

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                var secretValue = (results.Count == 1) ? results[0] : null;
```suggestion
                var secretValue = (results?.Count == 1) ? results[0] : null;
```

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                var module = pwsh.AddCommand("Microsoft.PowerShell.Core\\Import-Module").AddParameters(
check of HadErrors

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                        { "ErrorAction", "Ignore"}
Dont think this is needed

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create();
use using around PowerShell.Create to ensure dispose

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create();
use using around PowerShell.Create

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create();
same as above

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                var results = pwsh.AddCommand("Microsoft.PowerShell.SecretManagement\\Test-SecretVault").AddParameters(
For all instances where ps is reused, remember to do a ps.Commands.Clear() otherwise the previous command is executed again.

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                bool result = (results.Count > 0) ? results[0] : false;
result can be null

2023-08-30 17:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                        { "ErrorAction", "Ignore"}
Actually the whole get-module to see if it is loaded is unnecessary.

2023-09-05 16:19 UTC, alerickson commented on src/code/Utils.cs
>                              message: $"Microsoft.PowerShell.SecretManagement\\Set-Secret encountered an error while adding secret \"{repositoryCredentialInfo.SecretName}\" to vault \"{repositoryCrede
```suggestion
                            message: $"Microsoft.PowerShell.SecretManagement\\Set-Secret encountered an error while adding secret '{repositoryCredentialInfo.SecretName}' to vault '{repositoryCredentialInfo.VaultName}' for PSResourceRepository '{repositoryName}' authentication.",
```

2023-09-05 16:20 UTC, alerickson commented on src/code/Utils.cs
>                              message: $"Cannot validate Microsoft.PowerShell.SecretManagement module setup for PSResourceRepository ({repositoryName}) authentication.",
```suggestion
                            message: $"Cannot validate Microsoft.PowerShell.SecretManagement module setup for PSResourceRepository '{repositoryName}' authentication.",
```

2023-09-07 19:00 UTC, adityapatwardhan approved these changes

2023-09-07 19:05 UTC, merged