Update release yaml to include manual validation jobs
PowerShell/PSResourceGet pull request #1400
Opened 2023-09-11 22:53 UTC by alerickson

# PR Summary
Add manual validation before publishing to PowerShell internal feed and before publishing to PowerShell Gallery.

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-09-11 23:03 UTC, adityapatwardhan requested changes

2023-09-11 23:03 UTC, adityapatwardhan commented on .ci/release.yml
> +        onTimeout: reject
```suggestion
- job: ${{ parameter.validationJob1 }}
  displayName: ${{ parameters.displayValidationJob1 }}
  pool: server
  timeoutInMinutes: 4320 # job times out in 3 days
  steps:
  - task: ManualValidation@0
    displayName: ${{ parameters.displayValidationJob1 }}
    timeoutInMinutes: 2880 # 2 days
    inputs:
      instructions: ${{ parameters.instructionsValidationJob1 }}
      onTimeout: reject
```

2023-09-11 23:03 UTC, adityapatwardhan commented on .ci/release.yml
> +- job: ${{ parameter.validationJob2 }}
this is missing the depends on ${{ parameters.jobName1 }}

2023-09-11 23:03 UTC, adityapatwardhan commented on .ci/release.yml
> +
```suggestion
- job: ${{ parameter.validationJob2 }}
  displayName: ${{ parameters.displayValidationJob2 }}
  pool: server
  timeoutInMinutes: 4320 # job times out in 3 days
  steps:
  - task: ManualValidation@0
    displayName: ${{ parameters.displayValidationJob2 }}
    timeoutInMinutes: 2880 # 2 days
    inputs:
      instructions: ${{ parameters.instructionsValidationJob2 }}
      onTimeout: reject

```

2023-09-11 23:03 UTC, adityapatwardhan commented on CHANGELOG.md
> -## 0.9.0-rc1
unrelated changes?

2023-09-11 23:03 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.PSResourceGet.psd1
> +            Prerelease   = 'rc'
unrelated changes?

2023-09-12 00:15 UTC, alerickson commented on .ci/ci_release.yml
> +          PackageVersion: '0.9.0-rc'
```suggestion
          PackageVersion: '0.9.0-rc1'
```

2023-09-12 00:16 UTC, alerickson commented on CHANGELOG.md
> +## 0.9.0-rc
```suggestion
## 0.9.0-rc1
```

2023-09-12 00:16 UTC, alerickson commented on src/Microsoft.PowerShell.PSResourceGet.psd1
> +            Prerelease   = 'rc'
```suggestion
            Prerelease   = 'rc1'
```

2023-09-12 00:17 UTC, alerickson commented on src/Microsoft.PowerShell.PSResourceGet.psd1
> +## 0.9.0-rc
```suggestion
## 0.9.0-rc1
```

2023-09-12 00:17 UTC, alerickson commented on .ci/release.yml
> +  displayName: ${{ parameters.displayValidationJob2 }}
```suggestion
  dependsOn: ${{ parameters.jobName1 }}
  displayName: ${{ parameters.displayValidationJob2 }}
```

2023-09-12 01:21 UTC, adityapatwardhan approved these changes

2023-09-12 01:52 UTC, merged