Provide more intuitive error message when JFrog feed is inactive
PowerShell/PSResourceGet pull request #1427
Opened 2023-09-29 19:52 UTC by anamnavi

# PR Summary

## PR Context
Resolves #1424

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-10-02 16:30 UTC, alerickson requested changes

2023-10-02 16:30 UTC, alerickson commented on src/code/V3ServerAPICalls.cs
> +                if (e.Message.Contains("'<' is an invalid start of a value"))
Is there anyway we can check the response so that if it can catch malformed responses more generically?  Like using JsonDocument.TryParse() and throwing recording an error if that fails?

2023-10-02 17:07 UTC, adityapatwardhan commented on src/code/V3ServerAPICalls.cs
> +                if (e.Message.Contains("'<' is an invalid start of a value"))
Also can we check what the type of the exception is. That might be helpful too.

2023-10-04 16:47 UTC, alerickson approved these changes

2023-10-04 17:08 UTC, adityapatwardhan approved these changes

2023-10-04 21:41 UTC, merged