Fix JFrog's NuGet Artifactory (v2 endpoint) bug
PowerShell/PSResourceGet pull request #1428
Opened 2023-09-30 05:09 UTC by alerickson

# PR Summary
Fixes a few bugs related to the v2 endpoint for JFrog's NuGet Artifactory repositories:

*  `Find` was not able to find a package in a repo.  It previously errored out saying package could not be found.  This was due to the request query being created adding the filter "Id eq '<packageName>'" (eg: https://test.jfrog.io/artifactory/api/nuget/nuget/FindPackagesById()?id='<packageName>'&$filter=IsLatestVersion and Id eq '<packageName>'), however the server have information for an 'Id' property.  What other repositories call 'Id' Jfrog calls 'Title', however filtering on title returns a 405, so I've removed the filter altogether for JFrog repos.  The filter cannot be removed for other v2 repos such as the PSGallery because "FindPackagesById()?id='<packageName>'" fuzzy matches, so it needs to be further filtered for exact matching.

* Because JFrog has no 'Id' property, when the package is returned PSResourceGet could not find the name of the package and returned whitespace instead of the proper package name.  When parsing the response xml, PSResourceGet now looks for 'Title' as well as 'Id' for the package name.

* Exceptions thrown from `SendV2RequestForContentAsync` were not properly getting caught and would cause null pointer exceptions to later get thrown. These request call exceptions (specifically related to v2 installation) are now properly caught and thrown.

*  `string.IsNullOrEmpty(content.ToString()))` was not validating that content was not null before using .ToString() method.  Simple null check was added here.

* Previously requests to install a package from JFrog looked like: `https://test.jfrog.io/artifactory/api/nuget/nuget/package/<packageName>`. However, the proper request should look like: `https://test.jfrog.io/artifactory/api/nuget/nuget/Download/<packageName>/<packageVersion>`.  JFrog needs the package version to install a package, it won't just install the latest.  `InstallName` now takes a `packageVersion` parameter so that it can form the proper query. 

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-10-03 15:04 UTC, anamnavi requested changes
PR looks great and thanks for the thorough explanation of findings! Left a thought about overall design wrt to the server APIs.

2023-10-03 15:04 UTC, anamnavi commented on src/code/IServerAPICalls.cs
> -    Stream InstallName(string packageName, bool includePrerelease, out ErrorRecord errRecord);
While I understand the reasoning you provided in the issue description for why you're letting `InstallName()` take a `packageVersion` parameter, and how JFrog can't do InstallName(), I think what may be better for the sake of the interface server APIs is if we don't turn `InstallName()` into `InstallVersion()`. That's effectively 2 methods doing the same install behavior and may seem like confusing or redundant behavior to future API implementers.. Perhaps instead in the FindHelper level we can determine from the current server instance that it is a JFrog V2 repository and then call `InstallVersion()`.

Arguably, since we currently call FindHelper before InstallHelper we will always know the package version and therefore always call InstallName..but we had left it as separate APIs so that if in the future we implement doing Install without Find we already have separate code.

2023-10-03 15:18 UTC, anamnavi commented on src/code/IServerAPICalls.cs
> -    Stream InstallName(string packageName, bool includePrerelease, out ErrorRecord errRecord);
or since we effectively do InstallVersion() instead of InstallName() for ADO V2 feed as well, perhaps in the `ServerApiCall` class we have an overridden method called `InstallPackage(pkgName, pkgVersion, other params)` that determines the situation and calls `InstallName()` or InstallVersion()` that would now only be private methods.

2023-10-03 18:08 UTC, alerickson commented on src/code/IServerAPICalls.cs
> -    Stream InstallName(string packageName, bool includePrerelease, out ErrorRecord errRecord);
> or since we effectively do InstallVersion() instead of InstallName() for ADO V2 feed as well, perhaps in the ServerApiCall class we have an overridden method called InstallPackage(pkgName, pkgVersion, other params) that determines the situation and calls InstallName() or InstallVersion()` that would now only be private methods.

I like this idea a lot.  Let me refactor and add this

2023-10-04 14:42 UTC, anamnavi approved these changes
LGTM, thanks for making this change!

2023-10-04 14:42 UTC, anamnavi commented on src/code/V3ServerAPICalls.cs
> +            Stream results = new MemoryStream();
Perhaps we can add a debug statement for this method, not blocking.
```suggestion
            Stream results = new MemoryStream();
            _cmdletPassedIn.WriteDebug("In V3ServerAPICalls::InstallPackage()");
```

2023-10-04 17:14 UTC, merged