Add method to extract nupkg to directory
PowerShell/PSResourceGet pull request #1456
Opened 2023-10-23 19:40 UTC by alerickson

# PR Summary
Some repositories (namely GitHub Packages) add an extra `_rels\rels` file to the .nupkgs. `System.IO.Compression.ZipFile.ExtractToDirectory` does not have an `overwrite` parameter for net472, so this method was throwing an exception every time it came across the second `_rels\rels`.    

This PR opens the .nupkg and runs `ExtractToFile` (which does have an `overwrite` parameter) on each item so that no exception gets thrown.  Note that anything under `_rels` by default gets thrown out by PSResourceGet, so overwriting this file is not an issue.  There should be no other duplicate files.  

## PR Context
Resolves #1433

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-10-23 20:15 UTC, anamnavi approved these changes
LGTM

2023-10-23 20:30 UTC, adityapatwardhan requested changes
Look at the CodeQL error.

2023-10-25 20:55 UTC, adityapatwardhan approved these changes

2023-10-25 20:59 UTC, merged

2023-10-26 09:33 UTC, jtomkiew-mng commented
Slight correction to the description: GitHub Packages repository does not modify the nupkg files on it's own, but [a certain popular tool](https://github.com/jcansdale/gpr) does (wich results in a duplicated `_rels/rels`).

If you publish a valid nupkg to GitHub Packages directly, e.g. using `dotnet nuget push`, it will stay valid (i.e. no duplicated `rels`).