Update README.md
PowerShell/PSResourceGet pull request #1458
Opened 2023-10-24 18:37 UTC by alerickson

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-10-24 19:08 UTC, anamnavi approved these changes

2023-10-24 19:09 UTC, anamnavi requested changes, later dismissed

2023-10-24 19:09 UTC, anamnavi commented on README.md
> +The repository for the PowerShellGet v3 is available at [PowerShell/PowerShellGetv2](https://github.com/PowerShell/PowerShellGet).
isn't this the PSResourceGEt repo?

2023-10-24 19:11 UTC, anamnavi commented on README.md
> +The repository for the PowerShellGet v3 is available at [PowerShell/PowerShellGetv2](https://github.com/PowerShell/PowerShellGet).
oh no that's fine, I think we mean that the repository for PowerShellGet, which will act as Compat so something like this perhaps:
```suggestion
The repository for the PowerShellGet, which will act as the Compat layer, is available at [PowerShell/PowerShellGet](https://github.com/PowerShell/PowerShellGet).
```

2023-10-24 20:30 UTC, alerickson commented on README.md
> +The repository for the PowerShellGet, which will act as the Compat layer, is available at [PowerShell/PowerShellGet](https://github.com/PowerShell/PowerShellGet).
```suggestion
The repository for the PowerShellGet v3, the compatibility layer between PowerShellGet v2 and PSResourceGet, is available at [PowerShell/PowerShellGet](https://github.com/PowerShell/PowerShellGet).
```

2023-10-27 19:15 UTC, adityapatwardhan approved these changes

2023-10-27 19:24 UTC, merged