ACR Integration:  Add JSON metadata to package manifest in ACR registries
PowerShell/PSResourceGet pull request #1522
Opened 2024-01-17 06:02 UTC by alerickson

# PR Summary
Add metadata JSON string to package manifest in ACR registries. 

![image](https://github.com/PowerShell/PSResourceGet/assets/25858831/28a6d964-81f3-4fcd-bf7e-4c0a93787492)
## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-01-18 00:31 UTC, adityapatwardhan requested changes

2024-01-18 00:31 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +            string fileContent = CreateJsonContent(nupkgDigest, configDigest, configDigest, fileSize, fileName, jsonString);
is the value of configDigest and metadataDigest the same? Earlier there was emptydigest

2024-01-22 18:11 UTC, alerickson commented on src/code/ACRServerAPICalls.cs
> +            string fileContent = CreateJsonContent(nupkgDigest, configDigest, configDigest, fileSize, fileName, jsonString);
metadataDigest is no longer used, nor is emptyDigest.  I removed the metadataDigest parameter because that should no longer be there.

2024-01-23 18:03 UTC, adityapatwardhan approved these changes

2024-01-23 19:04 UTC, merged