Enable Update-ModuleManifest and Get-PSScriptFileInfo tests that aren…
PowerShell/PSResourceGet pull request #1538
Opened 2024-01-23 20:51 UTC by anamnavi

…t being run

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-01-24 21:15 UTC, adityapatwardhan approved these changes

2024-01-24 21:36 UTC, alerickson commented on test/PSScriptFileInfoTests/GetPSScriptFileInfo.Tests.ps1
> +$buildModule = "$psscriptroot/../../out/Microsoft.PowerShell.PSResourceGet"
Did this end up still being needed then?

2024-01-24 21:36 UTC, alerickson commented on test/UpdateModuleManifest/UpdateModuleManifest.Tests.ps1
> +    It "Update module manifest given Prerelease parameter" -Skip:$IsWindowsPowerShell {
Why is this not working on Windows PS?

2024-01-24 21:36 UTC, alerickson commented on src/code/UpdateModuleManifest.cs
> +            if (RequireLicenseAcceptance != null && RequireLicenseAcceptance.IsPresent)
Just out of curiosity, how is `RequireLicenseAcceptance.IsPresent` different from `RequireLicenseAcceptance == null`?

2024-01-24 21:46 UTC, anamnavi commented on test/UpdateModuleManifest/UpdateModuleManifest.Tests.ps1
> +    It "Update module manifest given Prerelease parameter" -Skip:$IsWindowsPowerShell {
the `-Prerelease` parameter was not included for New-ModuleManifest cmdlet in WindowsPowerShell [per the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-5.1)

`ExternalModuleDependencies` and `RequireLicenseAcceptance` are the other paramaters also not included

2024-01-24 21:52 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            if (RequireLicenseAcceptance != null && RequireLicenseAcceptance.IsPresent)
oh yea I initially wondered this too!

Since `RequireLicenseAcceptance` is a parameter of type `SwitchParameter` when the cmdlet is called from the command line it'll have a default value of False, not null. The `SwitchParameter.IsPresent` property returns a bool that's only true if a value was provided for the parameter from the command line. So this helped me determine if the user actually provided the paramater with a value of False or it was just getting set as False by default. I suppose we could remove the null check, but I'm not sure if there are other ways in which the cmdlet could be provided parameters (like parameter splatting in a script?) and then the null check actually be needed. So I left it be.

2024-01-24 21:53 UTC, anamnavi commented on test/PSScriptFileInfoTests/GetPSScriptFileInfo.Tests.ps1
> +$buildModule = "$psscriptroot/../../out/Microsoft.PowerShell.PSResourceGet"
checking this now.

2024-01-25 00:09 UTC, alerickson commented on test/UpdateModuleManifest/UpdateModuleManifest.Tests.ps1
> +    It "Update module manifest given Prerelease parameter" -Skip:$IsWindowsPowerShell {
Okay, considering we have to be backwards compatible with Windows PS 5.1 we should add error handling if someone on Windows PowerShell tries to use those parameters and specify that it's a feature only available on later versions of PS.

2024-01-25 00:12 UTC, alerickson commented on src/code/UpdateModuleManifest.cs
> +            if (RequireLicenseAcceptance != null && RequireLicenseAcceptance.IsPresent)
Yeah, let's leave that as is since the value could be null

2024-01-25 16:14 UTC, anamnavi commented on test/PSScriptFileInfoTests/GetPSScriptFileInfo.Tests.ps1
> +$buildModule = "$psscriptroot/../../out/Microsoft.PowerShell.PSResourceGet"
this is good without the build.

2024-01-31 18:20 UTC, adityapatwardhan requested changes

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            }
```suggestion
            Utils.GetIsWindowsPowerShell(this) ? CreateModuleManifestForWinPSHelper(parsedMetadata, resolvedManifestPath) : CreateModuleManifestHelper(parsedMetadata, resolvedManifestPath);

```

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            Hashtable privateData = new Hashtable();
```suggestion

            Hashtable privateData = new Hashtable();

```

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            // This is due to the issue of New-ModuleManifest when the PrivateData entry is a nested hashtable.
Add a link to the issue.

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                parsedMetadata["LicenseUri"] = licenseUri;
similarly for all other assignments.

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                parsedMetadata["LicenseUri"] = licenseUri;
```suggestion
                parsedMetadata["LicenseUri"] = LicenseUri;

```

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                Directory.CreateDirectory(tmpParentPath);
Directory is not deleted in cleanup

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            string endingPrivateDataString = "\n" + "} # End of PSData hashtable" + "\n" + "} # End of PrivateData hashtable";
```suggestion
            string endingPrivateDataString = System.Environment.NewLine + "} # End of PSData hashtable" + System.Environment.NewLine + "} # End of PrivateData hashtable";

```

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            CreateNewPsd1WithUpdatedPrivateData(privateDataString, tmpModuleManifestPath, newTmpModuleManifestPath, out ErrorRecord errRecord);
errorRecord is not checked.

2024-01-31 18:20 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                    this);
should this return here?

2024-01-31 19:45 UTC, alerickson reviewed
Just added one comment, but looks good otherwise

2024-01-31 19:45 UTC, alerickson commented on src/code/Utils.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
Do you need to know if the `OSPlatform` is Windows?  Wondering if you can just check the `psCmdlet.Host.Version` to simplify?

2024-01-31 19:55 UTC, anamnavi commented on src/code/Utils.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
yea I don't think it's needed. I just added it in case. I'll remove and let the tests run.

2024-02-01 21:07 UTC, adityapatwardhan requested changes

2024-02-01 21:07 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +                WriteError(errorRecord);
should we return from here?  Or we can continue even with the error?

2024-02-01 21:07 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            bool successfulManifestCreation = Utils.GetIsWindowsPowerShell(this) ? TryCreateModuleManifestForWinPSHelper(parsedMetadata, resolvedManifestPath, out errorRecord) : TryCreateModuleManife
Both the Try.. method return bool. It is never checked. Maybe they dont need a return type.

2024-02-02 04:10 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +                WriteError(errorRecord);
I changed it to `ThrowTerminatingError()` now. There's no code after this so it would have anyways exited, but better to be more explicit about that.

2024-02-02 04:11 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            bool successfulManifestCreation = Utils.GetIsWindowsPowerShell(this) ? TryCreateModuleManifestForWinPSHelper(parsedMetadata, resolvedManifestPath, out errorRecord) : TryCreateModuleManife
Good point, I changed the return type to void. Only thing then is I can't use a ternary operator to call the methods as previously suggested (as there's no return type and that gives an error). So I changed that to an `if/else`

2024-02-02 21:52 UTC, adityapatwardhan approved these changes

2024-02-05 17:42 UTC, alerickson approved these changes

2024-02-05 18:17 UTC, merged