ACR Integration: Populate metadata into PSResourceInfo object
PowerShell/PSResourceGet pull request #1548
Opened 2024-01-30 02:31 UTC by alerickson

# PR Summary
This PR takes the metadata json string stored in 'annotations' and populates it into PSResourceInfo object.
eg:
![image](https://github.com/PowerShell/PSResourceGet/assets/25858831/533f98c7-86f1-4f20-8dbe-e59a6cbec2f5)

A small change was made to `Publish-PSResource` as well-- it now pushes "packageName" to 'annotations'. 

![image](https://github.com/PowerShell/PSResourceGet/assets/25858831/6166aebc-37c9-4586-aa90-58a289bdbf91)

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-02-01 23:32 UTC, adityapatwardhan requested changes

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                            latestVersionResponse.Add(GetACRMetadata(registry, packageName, pkgVersion, acrAccessToken, out errRecord));
Should check errorRecord

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                            latestVersionResponse.Add(GetACRMetadata(registry, packageName, pkgVersion, acrAccessToken, out errRecord));
should check errRecord

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                GetACRMetadata(registry, packageName, requiredVersion, acrAccessToken, out errRecord)
should check errRecord

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                GetACRMetadata(registry, packageName, requiredVersion, acrAccessToken, out errRecord)
After checking you can use AddRange

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +            }
this code is repetitive. see if a method can be made to handle it.

2024-02-01 23:32 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +
extra line

2024-02-06 21:37 UTC, anamnavi approved these changes
LGTM

2024-02-06 23:10 UTC, adityapatwardhan approved these changes

2024-02-06 23:14 UTC, merged