update changelog for 1.0.1 and 1.0.2 releases
PowerShell/PSResourceGet pull request #1554
Opened 2024-02-07 18:07 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-02-07 18:11 UTC, SydneyhSmith approved these changes

2024-02-07 19:29 UTC, adityapatwardhan commented on CHANGELOG.md
> +## 1.0.2
Add release date

2024-02-07 19:29 UTC, adityapatwardhan commented on CHANGELOG.md
> +## 1.0.2
Like - 7.4.1 - 2024-01-11

2024-02-07 19:52 UTC, alerickson approved these changes

2024-02-07 19:59 UTC, adityapatwardhan approved these changes

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +# CHANGELOG
remove this

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +
remove section if no contents

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +
extra line

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +- Move off of NuGet client APIs for local repositories (#1065)
always empty line after heading

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +
extra line

2024-02-07 19:59 UTC, adityapatwardhan commented on CHANGELOG/1.0.md
> +## [1.0.2] - 2024-02-06
is the intention to add the compare link? Then you need the definition of [1.0.2] example:

`[7.4.1]: https://github.com/PowerShell/PowerShell/compare/v7.4.0...v7.4.1`

2024-02-07 20:00 UTC, adityapatwardhan requested changes
Bunch of md linter issue and missing links

2024-02-07 20:54 UTC, anamnavi commented on CHANGELOG/1.0.md
> +## [1.0.2] - 2024-02-06
I was trying to copy how we have it for PowerShell/PowerShell. I add the compare links for 1.0.1 and 1.0.2. Since we didn't have tags prior to 1.0.0, I couldn't add a compare tag for that version.

2024-02-08 19:53 UTC, adityapatwardhan approved these changes

2024-02-08 19:53 UTC, merged