Ensure that exception is not swallowed by finally block
PowerShell/PSResourceGet pull request #1569
Opened 2024-02-16 02:51 UTC by adityapatwardhan

# PR Summary

Some cases the exception was not caught but swallowed by finally block.
Ensure we rethrow the exception after writing error.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-02-16 17:50 UTC, alerickson approved these changes

2024-02-16 18:07 UTC, anamnavi requested changes

2024-02-16 18:07 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                catch (Exception e)
this method is not called anymore. we can delete it.

2024-02-16 18:07 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                WriteError(new ErrorRecord(
perhaps make this a ThrowTerminatingError()

2024-02-16 18:07 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            catch (Exception e)
the method above is not catching this thrown error. Should we add a try/catch above?

2024-02-16 18:07 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            catch (Exception e)
the method above is not catching this thrown error. Should we add a try/catch above?

2024-02-20 23:28 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +                WriteError(new ErrorRecord(
Fixed

2024-02-20 23:32 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            catch (Exception e)
Removing the rethrow. The above layer checks for ErrorRecord and throws terminating error.

2024-02-20 23:33 UTC, adityapatwardhan commented on src/code/InstallHelper.cs
> +                catch (Exception e)
This method seems to be used. I will not remove it for now.

2024-02-20 23:34 UTC, adityapatwardhan commented on src/code/UpdateModuleManifest.cs
> +            catch (Exception e)
sane as above, removed the rethrow

2024-02-21 04:08 UTC, anamnavi approved these changes
LGTM

2024-02-21 04:08 UTC, merged