Add support for ACR when publishing scripts
PowerShell/PSResourceGet pull request #1573
Opened 2024-02-23 20:14 UTC by anamnavi

# PR Summary

Add support for scripts for ACR, for publish and install.
Add tests for scripts for publish.
Fix bug where ACR expects lowercase name but user provided input doesn't match it.

Still to do: 
fix bug where there's a mismatch between actual version (that ends with 0) and user provided version that may have more or less versions. 
Also versions cannot be expected to be in any order, they are only in order of when they were published. Fix this bug too.
PSResourceInfo.Type property will still reflect none when Find-PSResource or Get-InstalledPSResource is called for ACR resources. This will be fixed after cleanup refactor.

## PR Context
Resolves #1578 #1568

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-02-26 18:26 UTC, alerickson requested changes
Looks good, just add a test or add a validation in an existing test.

2024-02-29 19:18 UTC, alerickson commented on test/PublishPSResourceTests/PublishPSResourceACRServer.Tests.ps1
> +    <#
Does this test not work because of the digit bug?  can you add a comment here?

2024-02-29 19:18 UTC, alerickson commented on src/code/PublishPSResource.cs
> +
Theres a few comments related to `parsedMetadata`, one on line 264 and one on line 344, that I believe they're both outdated now.  Can you remove if not applicable?

2024-02-29 19:18 UTC, alerickson commented on src/code/PSResourceInfo.cs
> +                        // TODO: why don't we return here?
Let's just adding erroring out here, or we can try testing with local module that has incorrect version information.  I think this is a case of what do we do if a module version is malformed, do we return what info we have to the user or just say this is an invalid module.

2024-02-29 19:18 UTC, alerickson commented on src/code/ACRServerAPICalls.cs
>              // A script will already have the metadata parsed into the parsedMetadatahash,
I believe this information is outdated now too, right?

2024-02-29 19:18 UTC, alerickson commented on src/code/ACRServerAPICalls.cs
> +                parsedMetadata["Version"] = pkgNuGetVersion.ToNormalizedString(); // or ToString();
We should figure out if we need .NormalizedString() or regular .ToString().  I think we want a regular .ToString() because normalizing may alter the specific version syntax the user specified (was just looking at what exactly normalizing does here: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#normalized-version-numbers)

2024-02-29 19:34 UTC, alerickson commented
resolves #1578

2024-02-29 20:31 UTC, adityapatwardhan requested changes

2024-02-29 20:31 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                        // Versions are always in descending order i.e 5.0.0, 3.0.0, 1.0.0 so grabbing the first match suffices
Is this still accurate?

2024-02-29 20:31 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                if (pkgVersion == requiredVersion)
Is there an API is NugetVersioning to compare two versions? That might account for 7.0.0 and 7.0.0.0 right?

2024-02-29 20:31 UTC, adityapatwardhan commented on test/FindPSResourceTests/FindPSResourceACRServer.Tests.ps1
> +        # $res.Type | Should -Be "Script"
Remove?

2024-02-29 20:31 UTC, adityapatwardhan commented on test/FindPSResourceTests/FindPSResourceACRServer.Tests.ps1
> +        $res.Name | Should -Be $testScript
```suggestion
        $res.Name | Should -BeExactly $testScript
```

2024-02-29 20:31 UTC, adityapatwardhan commented on test/InstallPSResourceTests/InstallPSResourceACRServer.Tests.ps1
> +        # $pkg.Type | Should -Be "Script"
Remove?

2024-02-29 20:31 UTC, adityapatwardhan commented on test/InstallPSResourceTests/InstallPSResourceACRServer.Tests.ps1
> +        # $pkg.Type | Should -Be "Script"
Remove?

2024-02-29 20:31 UTC, adityapatwardhan commented on test/PublishPSResourceTests/PublishPSResourceACRServer.Tests.ps1
> +    <#
Ideally file an issue and link it here

2024-02-29 22:38 UTC, anamnavi commented on src/code/ACRServerAPICalls.cs
> +                if (pkgVersion == requiredVersion)
I'll fix this in the version bugfix for when the last digit is 0 and comparison is off, as our comparison logic needs to change

2024-02-29 22:39 UTC, anamnavi commented on src/code/ACRServerAPICalls.cs
>              // A script will already have the metadata parsed into the parsedMetadatahash,
yep, good call.

2024-02-29 22:41 UTC, anamnavi commented on src/code/ACRServerAPICalls.cs
> +                parsedMetadata["Version"] = pkgNuGetVersion.ToNormalizedString(); // or ToString();
good point and thanks this doc is helpful!

2024-02-29 22:48 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +                        // TODO: why don't we return here?
I'll add error handling. If the version could not be parsed as System.Version or NuGet.Version we will now tell the user that the version in the metadata couldn't be parsed and fail to find it.

2024-02-29 22:49 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +
good catch, thanks!

2024-03-01 00:11 UTC, alerickson approved these changes

2024-03-04 18:20 UTC, adityapatwardhan approved these changes

2024-03-04 18:32 UTC, merged