WIP: Acr dependencies
PowerShell/PSResourceGet pull request #1577
Opened 2024-02-29 00:31 UTC by alerickson

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-03-04 21:35 UTC, adityapatwardhan requested changes

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                    // TODO: error out
Add the error out

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +                // TODO: throw
Terminating error?

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +            // TODO: add err handling
Add error handling

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +
```suggestion
```

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +
```suggestion
```

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +            Console.WriteLine($"digest: {digest}");
Remove?

2024-03-04 21:35 UTC, adityapatwardhan commented on src/code/PSGetException.cs
> +    public class ProcessDependencyException : Exception
unsed class?

2024-03-04 21:36 UTC, adityapatwardhan commented
@alerickson - also need to add tests for this

2024-03-04 23:27 UTC, alerickson commented on src/code/PSGetException.cs
> +    public class ProcessDependencyException : Exception
Updated where this should have gone.

2024-03-05 16:26 UTC, anamnavi requested changes

2024-03-05 16:26 UTC, anamnavi commented on src/code/ACRServerAPICalls.cs
> +            File.Create(configFilePath).Dispose();
What happens if the file can't be created? The FileStream may be null then and `.Dispose()` would be called on that. I think the file should be created in a try catch and then if the FileStream isn't null then dispose.

2024-03-05 18:44 UTC, alerickson commented on src/code/ACRServerAPICalls.cs
> +            File.Create(configFilePath).Dispose();
Good catch, just added some exception handling in a new method

2024-03-05 20:29 UTC, anamnavi approved these changes
LGTM

2024-03-05 20:43 UTC, adityapatwardhan approved these changes

2024-03-05 20:48 UTC, merged