Add support for Find/Install ACR packages with dependencies
PowerShell/PSResourceGet pull request #1587
Opened 2024-03-06 05:48 UTC by alerickson

# PR Summary
This PR adds support specifically for Find and Install to retrieve dependency information for a package. 

It also removes some functionality added in PR #1577, namely it removes attaching dependency.json files to a package.  Instead dependency information is now retrieved from the `RequiredModules` property in the package's metadata.

## PR Context
Resolves #1585 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-03-06 20:07 UTC, adityapatwardhan requested changes

2024-03-06 20:07 UTC, adityapatwardhan commented on src/code/ACRServerAPICalls.cs
> +            TryCreateAndUploadManifest(fullNupkgFile, nupkgDigest, configDigest, pkgName, resourceType, metadataJson, configFilePath,
This method returns a bool which is never used. Should the return of current method be like:

```csharp
return TryCreateAndUploadManifest(fullNupkgFile, nupkgDigest, configDigest, pkgName, resourceType, metadataJson, configFilePath, pkgNameLower, pkgVersion, acrAccessToken);
```

2024-03-06 20:07 UTC, adityapatwardhan commented on src/code/PSResourceInfo.cs
> +        public static List<Dependency> ParseACRDependencies(JsonElement requiredModulesElement, out string errorMsg)
should this be internal instead?

2024-03-07 17:30 UTC, anamnavi approved these changes
LGTM

2024-03-08 22:59 UTC, adityapatwardhan approved these changes
Lgtm

2024-03-08 23:13 UTC, merged