Create OneBranch build and release pipeline
PowerShell/PSResourceGet pull request #1605
Opened 2024-03-20 18:51 UTC by alerickson

# PR Summary
Move build and release pipelines to OneBranch in Azure DevOps.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-03-21 15:53 UTC, anamnavi requested changes
Just wondering why there's 2 tsaoptions.json files, rest looks great!

2024-03-21 15:53 UTC, anamnavi commented on .config/tsaoptions.json
> +}
add newline; nitpick 
```suggestion
}

```

2024-03-21 15:53 UTC, anamnavi commented on .pipelines/PSResourceGet-Official.yml
> +       # - pwsh: |
do we need this commented out part? I believe SBOM gets done by OneBranch now

2024-03-21 15:53 UTC, anamnavi commented on .pipelines/tsaoptions.json
> +}
why is there a 2nd tsaoptions.json file here?

2024-03-21 15:53 UTC, anamnavi commented on global.json
> +}
```suggestion
}

```

2024-03-21 15:53 UTC, anamnavi commented on src/Microsoft.PowerShell.PSResourceGet.psd1
> +    ModuleVersion          = '1.0.0112'
why does this change?

2024-03-21 16:23 UTC, adityapatwardhan requested changes

2024-03-21 16:23 UTC, adityapatwardhan commented on .config/tsaoptions.json
> +}
There is another area path that should be used:

![image](https://github.com/PowerShell/PSResourceGet/assets/12820925/38be7fcd-a30c-4f92-9c9d-d1eeb75f830f)

2024-03-21 16:23 UTC, adityapatwardhan commented on .pipelines/PSResourceGet-Official.yml
> +        forStages: [Build]
```suggestion
        forStages: [stagebuild]
```

2024-03-21 16:23 UTC, adityapatwardhan commented on .pipelines/PSResourceGet-Official.yml
> +            search_root: $(signSrcPath)
Before doing third party signing we should check which files are unsigned. Only those need to be third party signed. Bunch of the files under dependencies folder will be from .NET and hence will be already signed.

2024-03-21 16:23 UTC, adityapatwardhan commented on .pipelines/PSResourceGet-Official.yml
> +       # - pwsh: |
Remove commented code

2024-03-21 16:23 UTC, adityapatwardhan commented on .pipelines/tsaoptions.json
> +}
This should be removed.

2024-03-21 16:26 UTC, adityapatwardhan commented
Did you verify the built module actually works? The files are signed etc?

2024-03-21 16:29 UTC, alerickson commented
@adityapatwardhan yup, verified files are signed and published module works

2024-03-22 01:02 UTC, adityapatwardhan approved these changes

2024-03-22 01:06 UTC, anamnavi approved these changes

2024-03-22 16:17 UTC, merged