Attempt fix save script without -includexml (#1609)
PowerShell/PSResourceGet pull request #1614
Opened 2024-03-31 12:17 UTC by o-l-a-v

# PR Summary

Attempt fix to save script without -includexml, #1609.

Test added in PR #1613.

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-04-05 17:59 UTC, SydneyhSmith commented
Thanks so much @o-l-a-v  could you please add the tests to this PR so they can all be tested together before merge...thanks!

2024-04-06 09:36 UTC, o-l-a-v commented
@SydneyhSmith Done. :)

2024-04-10 16:56 UTC, anamnavi approved these changes
LGTM, thanks for putting this fix in @o-l-a-v  we appreciate it :)

2024-04-10 17:26 UTC, anamnavi requested changes

2024-04-10 17:26 UTC, anamnavi commented on test/SavePSResourceTests/SavePSResourceV2Tests.ps1
> +        $SavedScriptFile = [System.IO.Path]::Combine($SaveDir,('{0}.ps1' -f $testScriptName))
```suggestion
$SavedScriptFile = Join-Path -Path $SaveDir -ChildPath "$testScriptName.ps1"
```

2024-04-10 17:26 UTC, anamnavi commented on test/SavePSResourceTests/SavePSResourceV2Tests.ps1
> +        [System.IO.File]::Exists($SavedScriptFile) | Should -BeTrue
```suggestion
Test-Path -Path $SavedScriptFile | Should -BeTrue
```

2024-04-10 17:35 UTC, o-l-a-v commented
I made the requested changes @anamnavi.

2024-04-10 17:37 UTC, anamnavi approved these changes

2024-04-10 17:38 UTC, anamnavi commented
Had to approve the workflow to start tests running, once they pass I'll merge it in :)

2024-04-12 18:33 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-04-12 19:45 UTC, merged