Publish-PSResource: Pack and Push eature
PowerShell/PSResourceGet pull request #1682
Opened 2024-07-31 19:33 UTC by jshigetomi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2024-08-06 02:28 UTC, alerickson requested changes
Looks really good, just made some small suggestions here and there.

2024-08-06 02:28 UTC, alerickson commented on test/PublishPSResourceTests/PublishPSResource.Tests.ps1
> +        Wait-Debugger
Can remove this line

2024-08-06 02:28 UTC, alerickson commented on test/PublishPSResourceTests/CompressPSResource.Tests.ps1
> +}
```suggestion
}

```

2024-08-06 02:28 UTC, alerickson commented on src/code/CompressPSResource.cs
> +}
```suggestion
}

```

2024-08-06 02:28 UTC, alerickson commented on src/code/CompressPSResource.cs
> +    [Alias("cmpres")]
I think we should actually change "cmpres" to "cmres" (even thought imo the former is more obvious in what's an alias for).  
 
If you run `Get-Verb compress` you can see what PowerShell thinks the appropriate alias prefix should be (`cm`).

2024-08-06 02:28 UTC, alerickson commented on src/code/CompressPSResource.cs
> +            _psResourceHelper = new PSResourceHelper(
This should be called something more descriptive, like `CompressHelper`

2024-08-06 02:28 UTC, alerickson commented on src/code/CompressPSResource.cs
> +            _psResourceHelper = new PSResourceHelper(
After looking at the other files, I think it should be called `PublishHelper` since `publish` uses all of these methods but `compress` only uses the Pack related methods.

2024-08-06 02:28 UTC, alerickson commented on src/code/CompressPSResource.cs
> +using System;
Looks like all the `System` directives are no longer needed here

2024-08-06 02:28 UTC, alerickson commented on src/code/PublishPSResource.cs
>  using NuGet.Versioning;
`NuGet.Versioning` is no longer needed as well

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +            if (!_cmdlet.ShouldProcess(string.Format("{0} '{1}' from the machine", _callerCmdlet, resolvedPath)))
I think this wording is a bit off, it looks something like:
`What if: Performing the operation "Compress-PSResource" on target "CompressPSResource 'C:\code\testPSResourceGet' from the machine".` right now

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +        #region Public Methods
```suggestion
        #region Internal Methods
```

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +                if (_callerCmdlet == CallerCmdlet.CompressPSResource)
This is an open question: do we want to skip validating the module manifest if we're just packing the module?

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +                    outputNupkgDir = System.IO.Path.Combine(outputDir, "nupkg");
Instead of having lines 293 to 300, consider adding a parameter to `PackResource()` that has the value for `outputNupkgDir`

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +                if(_callerCmdlet == CallerCmdlet.CompressPSResource)
I think we always want to delete `outputDir` when we're done with it

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +                        outputNupkgDir = pathToNupkgToPublish;
Also consider having `ouputNupkgDir` as a parameter that's passed in to PushResource()

2024-08-06 02:28 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +            _cmdlet.WriteDebug("In PublishPSResource::PackNupkg()");
Update `PublishPSResource` to the name of this class.  This happens in a few other places as well

2024-08-06 14:56 UTC, jshigetomi commented on src/code/PSResourceHelper.cs
> +                if(_callerCmdlet == CallerCmdlet.CompressPSResource)
The CompressPSResource path deletes it here. But the PublishPSResource path still needs it for push to preserve the previous functionality. The PushResource method finally block handles that.

2024-08-06 16:11 UTC, jshigetomi commented on src/code/CompressPSResource.cs
> +    [Alias("cmpres")]
I didn't know you could do that! I will use for any aliases I have to come up with in the future.

2024-08-06 17:17 UTC, jshigetomi commented on src/code/CompressPSResource.cs
> +            _psResourceHelper = new PSResourceHelper(
Confirm
*Are you sure you want to perform this action?
Performing the operation "Compress-PSResource" on target "CompressPSResource 'C:\Program
Files\PowerShell\7\Modules\PowerShellGet' from the machine".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

more like this maybe?

2024-08-06 17:19 UTC, jshigetomi commented on src/code/PSResourceHelper.cs
> +            if (!_cmdlet.ShouldProcess(string.Format("{0} '{1}' from the machine", _callerCmdlet, resolvedPath)))
Confirm
**Are you sure you want to perform this action?
Performing the operation "Compress-PSResource" on target "CompressPSResource 'C:\Program
Files\PowerShell\7\Modules\PowerShellGet' from the machine".**
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

more like this maybe?

2024-08-06 17:51 UTC, jshigetomi commented on src/code/PSResourceHelper.cs
> +                if (_callerCmdlet == CallerCmdlet.CompressPSResource)
I will remove this check because it is redundant. Compress-PSResource has no way of changing SkipModuleManifestValidate parameter because did not add it as a parameter.

I think adding an option to check for manifest could be useful to users who want a manifest file. Publish provides the option as well. It would be annoying if the user could only check with publish after they had already packed it.

2024-08-06 18:10 UTC, alerickson commented on src/code/PSResourceHelper.cs
> +                if (_callerCmdlet == CallerCmdlet.CompressPSResource)
I guess there's a couple things here-- first whether validating the module manifest should happen or not.  I think it should by default always occur, but we can add a parameter to `Compress-PSResource` to skip validation, similar to `Publish-PSResource` (https://github.com/PowerShell/PSResourceGet/blob/d0e71b2cf558822c040143f76803d6c5efb65584/src/code/PublishPSResource.cs#L82).  

Second, if we by default always validate the module manifest then the default value for `SkipModuleManifestValidate` should be false so the module manifest is always checked unless otherwise specified not to (https://github.com/PowerShell/PSResourceGet/blob/5b64c5eb1ccd13074d42d0aaea48c2fa5f6d0f69/src/code/PSResourceHelper.cs#L59)

2024-08-06 19:57 UTC, jshigetomi commented on src/code/PSResourceHelper.cs
> +                    outputNupkgDir = System.IO.Path.Combine(outputDir, "nupkg");
I've added it to their unique constructors for the PublishHelper class.

outputDir is created in PSResource helper so I would have to create it Publish and Compress, then pass it to PackResource(). Then in the Publish path I would have to assign it as a member because pack and push both use it.

2024-08-06 21:59 UTC, jshigetomi commented on src/code/PSResourceHelper.cs
> +                        outputNupkgDir = pathToNupkgToPublish;
passing outputNupkgDir makes it difficult to maintain old PublishResource Behavior. All the outputNupkgDir logic needs to be done in Publish and not in helper and that means in Compress as well.

2024-08-06 23:07 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-13 17:23 UTC, adityapatwardhan commented
Closing and re-opening to re-trigger CI

2024-08-13 17:24 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-08-20 16:59 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-20 18:56 UTC, jshigetomi commented
Fixed a test that was strangely passing on local machine but failing on git.

The problem was with 
>Get-ChildItem $script:repositoryPath2 | Should -Be $expectedPath
changed to 
>(Get-ChildItem $script:repositoryPath2).FullName | Should -Be $expectedPath

2024-08-20 20:20 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-20 20:24 UTC, alerickson commented on test/PublishPSResourceTests/PublishPSResource.Tests.ps1
> +        Remove-Item -Path $scriptPath
This should probably be moved into the "After All" or "After Each" (whichever is appropriate), just to isolate the test functionality itself and have clean up done outside of test

2024-08-20 20:56 UTC, alerickson commented on src/code/PublishHelper.cs
> +            _cmdlet.WriteDebug($"In {_callerCmdlet}::PackNupkg()");
These debug messages should specify "PublishHelper" instead of "_callerCmdlet" to stay consistent with how we're using the debug/verbose messages elsewhere in the repo

2024-08-21 01:39 UTC, jshigetomi commented on test/PublishPSResourceTests/PublishPSResource.Tests.ps1
> +        Remove-Item -Path $scriptPath
This test doesn't delete the test.ps1 file it creates. It only happen for this test.
Maybe it can be like the first test where it removes it in the test?
```pwsh
    It "Publish module with required module not installed on the local machine using -SkipModuleManifestValidate" {
        # Skip the module manifest validation test, which fails from the missing manifest required module.
        $testModulePath = Join-Path -Path $TestDrive -ChildPath ModuleWithMissingRequiredModule
        Publish-PSResource -Path $testModulePath -Repository $testRepository2 -Confirm:$false -SkipDependenciesCheck -SkipModuleManifestValidate

        $expectedPath = Join-Path -Path $script:repositoryPath2  -ChildPath 'ModuleWithMissingRequiredModule.1.0.0.nupkg'
        $publishedModuleFound = Test-Path -Path $expectedPath
        $publishedModuleFound | Should -BeTrue

        if ($publishedModuleFound) {
            Remove-Item $expectedPath -Force -ErrorAction SilentlyContinue
        }
    }
```

2024-08-21 01:40 UTC, jshigetomi commented on src/code/PublishHelper.cs
> +            _cmdlet.WriteDebug($"In {_callerCmdlet}::PackNupkg()");
done. Should I also change the errors as well like...

```csharp
                    _cmdlet.WriteError(new ErrorRecord(
                        new ArgumentException($"The resource repository '{Repository}' is not a registered. Please run 'Register-PSResourceRepository' in order to publish to this repository."),
                        "RepositoryNotFound",
                        ErrorCategory.ObjectNotFound,
                        this._cmdlet));

                    return;
```

2024-08-21 16:52 UTC, alerickson commented on test/PublishPSResourceTests/PublishPSResource.Tests.ps1
> +        Remove-Item -Path $scriptPath
Oh, sorry I was just looking at the line kind of out of context.  Really the entire line should be removed because `$scriptPath` will be deleted during clean up in the "After Each" block already: https://github.com/PowerShell/PSResourceGet/blob/0b4d77fa43f905284acee01db56f12eea3d3e795/test/PublishPSResourceTests/PublishPSResource.Tests.ps1#L108

2024-08-21 16:59 UTC, alerickson commented on src/code/PublishHelper.cs
> +            _cmdlet.WriteDebug($"In {_callerCmdlet}::PackNupkg()");
You can just leave it as `this` without the `.cmdlet` (eg: https://github.com/PowerShell/PSResourceGet/blob/e79f6a242f2e90545457b04336b937a47cfcce42/src/code/FindHelper.cs#L110).  And looking at that example, could you change `_cmdlet` to `_cmdletPassedIn`?  Staying consistent with the naming convention just helps us in the future if there's changes we need to make to the entire code base.  It's easier to search and replace one term instead of looking up the different permutations

2024-08-21 17:17 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-21 19:13 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-21 20:09 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-21 20:11 UTC, alerickson approved these changes

2024-08-21 20:52 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-21 20:59 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-08-21 21:28 UTC, alerickson commented on src/code/.vs/Microsoft.PowerShell.PSResourceGet/v17/.suo
Can you add this file back just to keep this PR clean with changes related to Publish/Compress?

2024-08-21 21:35 UTC, alerickson commented on test/testFiles/testScripts/test.ps1
We actually don't need the script as a separate file, the cmdlet `New-PSScriptFileInfo` can create a new script.  The testScripts directory just contains invalid or complicated to create scripts (scenarios that would fail if trying to use `New-PSScriptFileInfo`)

2024-08-21 21:36 UTC, alerickson commented on test/testFiles/testScripts/test.ps1
The docs for the cmdlet are here: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/new-psscriptfileinfo?view=powershellget-3.x

2024-08-21 21:37 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-21 21:49 UTC, jshigetomi commented on test/testFiles/testScripts/test.ps1
This is the test script that is created in that one test where I put remove-item. It was added here on accident when rebasing the PR. I will remove it.

2024-08-21 21:57 UTC, jshigetomi commented on src/code/.vs/Microsoft.PowerShell.PSResourceGet/v17/.suo
Add the file back.

2024-08-22 15:52 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-08-22 16:12 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-08-22 19:31 UTC, adityapatwardhan commented
/azp run PowerShell.PSResourceGet

2024-08-23 18:43 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2024-08-23 21:35 UTC, merged

2025-11-15 03:58 UTC, aluty commented
@adityapatwardhan Checking back after a while.  I see "preview" has an official release now.

- [PowerShell Gallery | Microsoft.PowerShell.PSResourceGet 1.1.0](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet/1.1.0) (2025-01-09)

Tested and documented somewhere?