Add support for publishing .nupkg file to ACR
PowerShell/PSResourceGet pull request #1763
Opened 2024-12-19 20:01 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2025-01-07 19:21 UTC, adityapatwardhan requested changes

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/ContainerRegistryServerAPICalls.cs
> +
```suggestion

```

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/ContainerRegistryServerAPICalls.cs
> +                        // script metadata will have "Version" property, but nupk only based .nuspec will have lowercase "version" property and JsonElement.TryGetProperty() is case sensitive
```suggestion
                        // script metadata will have "Version" property, but nupkg only based .nuspec will have lowercase "version" property and JsonElement.TryGetProperty() is case sensitive
```

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/ContainerRegistryServerAPICalls.cs
> +            string fullNupkgFile = !isNupkgPathSpecified ? System.IO.Path.Combine(outputNupkgDir, packageName + "." + packageVersion.ToNormalizedString() + ".nupkg") : originalNupkgPath;
Maybe flip the condition, might make it easier to understand

```suggestion
            string fullNupkgFile = isNupkgPathSpecified ? originalNupkgPath :           System.IO.Path.Combine(outputNupkgDir, packageName + "." + packageVersion.ToNormalizedString() + ".nupkg");
```

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/PublishHelper.cs
> +
```suggestion
```

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/PublishHelper.cs
> +                _cmdletPassedIn.WriteError(new ErrorRecord(
errRecord is not set here

2025-01-07 19:21 UTC, adityapatwardhan commented on src/code/PublishHelper.cs
> +                        string copiedNupkgFilePath = CopyNupkgFileToTempPath(nupkgFilePath: Path, errRecord: out ErrorRecord copyErrRecord);
The copied file is not cleaned up

2025-01-07 19:27 UTC, alerickson commented on src/code/PublishHelper.cs
> +            {
Does errRecord need to be set here if `TryParse` fails?

2025-01-07 20:45 UTC, anamnavi commented on src/code/PublishHelper.cs
> +                _cmdletPassedIn.WriteError(new ErrorRecord(
captured errRecord now and caller method will call WriteError() with the errRecord.

2025-01-07 20:45 UTC, anamnavi commented on src/code/PublishHelper.cs
> +            {
good catch!

2025-01-08 18:32 UTC, adityapatwardhan approved these changes

2025-01-08 18:55 UTC, merged