Integrate AzArtifacts Credential Provider
PowerShell/PSResourceGet pull request #1765
Opened 2024-12-19 23:33 UTC by alerickson

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2025-01-03 00:50 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-06-28 20:22 UTC, MatejKafka-MSFT commented
Just wondering, what is the state of this PR? Is it abandoned, or can I expect PSResourceGet to get support for AzDO auth in the near future? :)

2025-07-08 22:37 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-08 22:40 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 00:47 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 18:02 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 19:22 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 20:12 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 21:56 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 22:25 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 22:44 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 23:01 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 23:21 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-09 23:51 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 01:28 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 01:57 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 03:52 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 18:26 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 18:29 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 20:21 UTC, adityapatwardhan commented
/azp run

2025-07-10 20:31 UTC, adityapatwardhan commented
/azp run

2025-07-10 20:40 UTC, adityapatwardhan commented
/azp run

2025-07-10 21:23 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 22:13 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 23:20 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-10 23:39 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-11 01:01 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-11 21:19 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-11 21:56 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-11 23:05 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-14 17:38 UTC, adityapatwardhan requested changes

2025-07-14 17:38 UTC, adityapatwardhan commented on src/code/FindHelper.cs
> +                }
Can this be put in a utility method, seems to be repeated.

2025-07-14 17:38 UTC, adityapatwardhan commented on src/code/RegisterPSResourceRepository.cs
> +                Uri.EndsWith(".azurecr.io") || Uri.EndsWith(".azurecr.io/") || Uri.Contains("mcr.microsoft.com"))
need to for GovCloudMCR as well?

2025-07-14 17:38 UTC, adityapatwardhan commented on src/code/SetPSResourceRepository.cs
> +                repository.Uri.AbsoluteUri.EndsWith(".azurecr.io") || repository.Uri.AbsoluteUri.EndsWith(".azurecr.io/") || repository.Uri.AbsoluteUri.Contains("mcr.microsoft.com")))
same as above

2025-07-14 17:38 UTC, adityapatwardhan commented on src/code/Utils.cs
> +        internal static string GetCaseInsensitiveFilePath(string directory, string fileName)
I prefer either throwing expectation, having a TryGetCaseInsensitiveFilePath which returns a null, rather than returning null. If you want to return null, then make the return type `string?` so it is explicit to the caller.

2025-07-14 17:38 UTC, adityapatwardhan commented on test/CredentialProvider.Tests.ps1
> +
```suggestion
```

2025-07-15 00:55 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-15 01:15 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-15 17:49 UTC, adityapatwardhan requested changes

2025-07-15 17:49 UTC, adityapatwardhan commented on src/code/Utils.cs
> +        public static bool IsContainerRegistry(string uri)
I think this would be better if it is part of the PSRespositoryInfo.cs. Seems like cleaner design since the method is specifically operating on the registry. The isMARRepository method is also there which can be reused in this methods implementation.

Also realized that we might have to add support for GitHub container registry. But that should be a separate PR.

2025-07-15 17:49 UTC, adityapatwardhan commented on src/code/Utils.cs
> +        public static NetworkCredential SetNetworkCredentials(PSRepositoryInfo repository, NetworkCredential networkCredential, PSCmdlet cmdletPassedIn)
Another slight refactoring suggestion to consider for cleaner design. If the credential is tied to a repository, consider have that as a property on the PSRespositoryInfo object. So that you dont have to carry around the credential and the repository object in all calls to various methods.

2025-07-15 17:49 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                    return true;
Add a break here to stop the loop after finding the file.

2025-07-15 18:41 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-15 19:17 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-15 19:36 UTC, alerickson commented on src/code/Utils.cs
> +                    return true;
Returning here should break the loop when it exists the method, right?

2025-07-15 20:48 UTC, adityapatwardhan commented on src/code/Utils.cs
> +                    return true;
Yes, you are correct.

2025-07-16 18:22 UTC, adityapatwardhan approved these changes

2025-07-16 18:22 UTC, adityapatwardhan commented on src/code/PSRepositoryInfo.cs
> +            if (uri.EndsWith(".azurecr.io") || uri.EndsWith(".azurecr.io/") || uri.Contains("mcr.microsoft.com") || uri.StartsWith("mcr.microsoft"))
nitpick.. can re-use the IsMARRepository function here.

2025-07-16 18:23 UTC, adityapatwardhan commented on src/code/PSRepositoryInfo.cs
> +            if (uri.EndsWith(".azurecr.io") || uri.EndsWith(".azurecr.io/") || uri.Contains("mcr.microsoft.com") || uri.StartsWith("mcr.microsoft"))
Also should check is the ApiVersion == APIVersion.ContainerRegistry

2025-07-16 18:24 UTC, alerickson commented on src/code/PSRepositoryInfo.cs
> +            if (uri.EndsWith(".azurecr.io") || uri.EndsWith(".azurecr.io/") || uri.Contains("mcr.microsoft.com") || uri.StartsWith("mcr.microsoft"))
Good point, let me add that

2025-07-16 18:27 UTC, alerickson commented on src/code/PSRepositoryInfo.cs
> +            if (uri.EndsWith(".azurecr.io") || uri.EndsWith(".azurecr.io/") || uri.Contains("mcr.microsoft.com") || uri.StartsWith("mcr.microsoft"))
Oh I just realized I can't use IsMARRepository() because IsContainerRegistry needs to be a static class since it gets called when creating dynamic parameters.  However, I am adding the ApiVersion check to IsContainerRegistry()

2025-07-16 19:38 UTC, alerickson commented
/azp run PowerShell.PSResourceGet

2025-07-16 20:29 UTC, adityapatwardhan approved these changes

2025-07-16 20:29 UTC, merged

2026-04-22 20:17 UTC, deadlydog commented
Unfortunately, this still does not work and always returns 401 unauthorized errors. I provided evidence in #1601.