Fixed bug with ModuleName param for Find-PSResource, added tests for it
PowerShell/PSResourceGet pull request #233
Opened 2020-09-02 19:18 UTC by anamnavi

Bug would arise when using the Find-PSResource cmdlet with ModuleName parameter (and Version parameter along with it) for an incorrect resource type (i.e script resource). It would still return a resource. Resolved this bug and added error message in this current change.

2020-09-02 22:10 UTC, alerickson requested changes

2020-09-02 22:10 UTC, alerickson commented on src/FindPSResource.cs
> +                Console.WriteLine("builds predicate for ModuleNAme"); //Anam
Can you change this to a comment, or a debug statement?

2020-09-02 22:10 UTC, alerickson commented on src/FindPSResource.cs
> +                // predicate = predicate.And(pkg => pkg.Field<string>("Type").Equals("Module")); //Anam
Can you remove this comment as well, unless you think this change will be needed in the future for caching

2020-09-02 22:10 UTC, alerickson commented on src/FindPSResource.cs
> +                var nameVal = name == null ? _moduleName : name;
Will this throw any errors/cause any issues if both name and _moduleName are null?

2020-09-03 14:53 UTC, anamnavi commented on src/FindPSResource.cs
> +                var nameVal = name == null ? _moduleName : name;
Good question! I wasn't sure if we could have a case where Name and ModuleName parameters are not specified as but a Version parameter is specified, and if that would be allowable behavior. I assumed it could be, so in the code I checked for cases where name and _moduleName aren't null, i.e later lines L1009, L1022. 1050 and just added implementation for those cases. So adding code for that first case would be easy if it ends up being allowable behavior.


I realize that behavior of name and _moduleName being null but version isn't null probably isn't meaningful (as it could create a large search and return list), so I've changed the code to not account for this case. And I'll just have one overarching check for if nameVal is null.

2020-09-03 16:57 UTC, alerickson approved these changes

2020-09-03 17:03 UTC, anamnavi commented
Fixed ModuleName bug

2020-09-03 17:03 UTC, merged