Remaining find tests
PowerShell/PSResourceGet pull request #250
Opened 2020-09-10 21:45 UTC by anamnavi

added find tests that mirror v2 tests for Find-Command, Find-DSCResource, Find-RoleCapability, Find-Script

2020-09-11 18:22 UTC, SteveL-MSFT requested changes

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +# Copyright (c) Microsoft Corporation, 2020
Use standard copyright header:

```csharp
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
```

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +Import-Module "C:\code\PowerShellGet\src\bin\Debug\netstandard2.0\publish\PowerShellGet.dll" -force
This path is hardcoded to your computer and will fail on other systems.  Importing the newly built module should be part of `PSGetTestUtils` module.  Also the import should be on the psd1 and not the dll directly.

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +$PSGalleryLocation = 'https://www.powershellgallery.com/api/v2'
These should also be defined in the test module as I expect many tests to use this info

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +$tmpdir = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath $TestLocalDirectory
Pester has a `$TestDrive` you should use instead of directly using the temp folder as it gets cleaned up after test is finished

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +        # Register-PSResourceRepository $PoshTestGalleryName -URL $PostTestGalleryLocation -Trusted
Remove commented out code that is not used

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +        $repo.Name | should be $PoshTestGalleryName
Use consistent casing and switch format making the code easier to read:

$repo.Name | Should -Be ...

Applies everywhere in this PR

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +        $repo.Trusted | should be true
Booleans should be `$true` or `$false`, applies everywhere.  But when using Pester, it should be: `Should -BeTrue` or `Should -BeFalse`

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +    It "find Command resource with exact version, given Version parameter -> [4.3.0.0]" {
Many of these test cases are very similar, you should use `-TestCases`.  See https://github.com/PowerShell/PowerShell/blob/master/test/powershell/engine/Basic/Attributes.Tests.ps1 for an example

2020-09-11 18:22 UTC, SteveL-MSFT commented on test/Pester.CommandFindResourceTests.ps1
> +        $res.Version | Should -Be "1.9.3.0"
Won't this version change if new version of Az.Accounts get published?

2020-09-11 18:56 UTC, alerickson commented on test/Pester.CommandFindResourceTests.ps1
> +        $res.Version | Should -Be "1.9.3.0"
@anamnavi we can use test modules to have a stable module that checks for specific scenarios.  I have a handful already up, but it's easy to publish your own too, we can discuss offline

2020-09-11 18:59 UTC, alerickson commented on test/Pester.CommandFindResourceTests.ps1
> +    It 'find the Default Registered PSGallery' {
I think this test should go under 'Repository' tests instead of find

2020-09-11 19:01 UTC, alerickson commented on test/Pester.CommandFindResourceTests.ps1
> +        $res = Find-PSResource -Name Az.Compute
In general we should be using test modules instead of production modules just for more control and stability

2020-09-16 21:44 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +$baseP = $PSScriptRoot -split "\\" #PSScriptRoot should be : C:\Users\annavied\Documents\PowerShellGet\test
Be careful when using specific delimiters because this will change depending on the system... you can use something like `[io.path]::DirectorySeparatorChar` instead

2020-09-16 21:46 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +$basePWithoutTest = $basePWithoutTest -Join "\"
Do you need the -Join "\" if you're running Join-Path below?

2020-09-16 21:47 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +$script:fullPath = Join-Path $basePWithoutTest -ChildPath "\src\bin\Debug\netstandard2.0\publish\PowerShellGet.dll"
Also be cautious of the directory separators here

2020-09-16 21:49 UTC, anamnavi commented on test/Pester.CommandFindResourceTests.ps1
> +    It 'find the Default Registered PSGallery' {
moved.

2020-09-16 21:49 UTC, anamnavi commented on test/Pester.CommandFindResourceTests.ps1
> +        $repo.Trusted | should be true
fixed this.

2020-09-16 21:49 UTC, anamnavi commented on test/Pester.CommandFindResourceTests.ps1
> +        $repo.Name | should be $PoshTestGalleryName
fixed this.

2020-09-16 21:50 UTC, anamnavi commented on test/Pester.CommandFindResourceTests.ps1
> +$tmpdir = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath $TestLocalDirectory
removed it as my tests don't actually rely on this

2020-09-17 05:14 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +$baseP = $PSScriptRoot -split "\\" #PSScriptRoot should be : C:\Users\annavied\Documents\PowerShellGet\test
thanks for pointing this out! I used Join-Path now which uses appropriate directory separator chars

2020-09-17 05:14 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +$basePWithoutTest = $basePWithoutTest -Join "\"
good point thanks!

2020-09-17 19:54 UTC, anamnavi commented on test/Pester.CommandFindResourceTests.ps1
> +        $res.Version | Should -Be "1.9.3.0"
will submit this change in a separate PR for better readability

2020-09-18 16:29 UTC, SteveL-MSFT requested changes

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +Import-Module "$psscriptroot\PSGetTestUtils.psm1" -WarningAction SilentlyContinue -Force
I don't think there's a reason to have `-WarningAction` here?

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Name Az.Compute
I thought we would use a test module rather than a real module for the tests?  In this case, Az.Compute is likely to be there, but could also be unlisted if they rename or refactor it.

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Name Az.Compute
Or at least use a module that our team owns

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        @{Version="[4.3.0.0]";          ExpectedVersion="4.3.0.0"; Reason="validate version, exact match"},
For completeness, we should have a test case for each of the examples here: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given Name to validate version wilcard match " {
Does the wildcard also work with partial versions like 4.2.* or 4.2.*.0 or 4.*.*.0?

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $res.Version | Should -Be "2.0.1.0"
This is unreliable as a future version of preview Az.Accounts would have different version number

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource when given ModuleName to <Reason>" -TestCases @(
How is this different from the tests in line 34 above?

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given ModuleName to validate version wildcard match " {
this test also seems like a duplicate?

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $tagValue = "Azure"
Seems better to use test modules particularly when we know exactly how many modules should be returned

2020-09-18 16:29 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Tags $tagValue1,$tagValue2,$tagValue3 -Repository (Get-PoshTestGalleryName) | Where-Object { $_.Name -eq "Az.Accounts" }
Unnecessary to have tags defined as variables that are only used once, you can just inline them and quotes not needed if there isn't whitespace

```powershell
$res = Find-PSResource -Tags Azure,Authentication,ARM -Repository (Get-PoshTestGalleryName) | Where-Object { $_.Name -eq "Az.Accounts" }
```

2020-09-18 16:41 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource when given ModuleName to <Reason>" -TestCases @(
the tests in line 34 use the `Name` parameter. I added similar tests for the `ModuleName` parameter, because the logic in FindPSResource.cs on this [line ](https://github.com/PowerShell/PowerShellGet/blob/development/src/FindPSResource.cs#L1077) where it detects if a package has a specific version and adds it to the list of packages returned is handled with different logic if a `Name` or `ModuleName` was given. (For `ModuleName` it can only add the package if the package returned was of type module and not script). So I wanted to test both.

2020-09-18 16:42 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource when given ModuleName to <Reason>" -TestCases @(
the comment above was incorrect, so I fixed that. (It'll be removed in the next PR though)

2020-09-18 16:51 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +Import-Module "$psscriptroot\PSGetTestUtils.psm1" -WarningAction SilentlyContinue -Force
Good question. That was in the other v3 tests that I copied the format from, the reason is that without `-WarningAction SilentlyContinue` when you run the Pester tests the warning `WARNING: The names of some imported commands from the module 'PSGetTestUtils' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.` arises. It's about the naming of method I think Amber created for use in another test file, but I can go ahead and modify that.

2020-09-18 17:02 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Name Az.Compute
Yes, the plan is to use a test module (or module that our team owns) instead of a production one. I was going to change that in the next PR I create today. Should I create those modules and change it now instead?

2020-09-21 16:48 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +Import-Module "$psscriptroot\PSGetTestUtils.psm1" -WarningAction SilentlyContinue -Force
You should remove the warning action from this file.  After this PR is merged, I can submit a new PR to fix the verb used so that the warning message doesn't come up.

2020-09-21 16:50 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Name Az.Compute
Ok, make all those changes in a different PR

2020-09-21 19:52 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        @{Version="[4.3.0.0]";          ExpectedVersion="4.3.0.0"; Reason="validate version, exact match"},
I've covered all the cases for Version from this now. For the case of `Minimum version, inclusive`, their syntax is different than the one we use in V3. For version x such that x >= 1.0, They would use `-Version "1.0"` but the V3 syntax to do this would be `-Version "[1.0,)"`.  Doing it their way would give an exact version match in V3. Should I submit a PR to their documentation? Or maybe we make a note about the difference in V3 somewhere in our documentation?

2020-09-21 20:12 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given Name to validate version wilcard match " {
Wildcard implementation for version parameter isn't as expected. The version parsing relies on `NuGetVersion.TryParse()` so I need to look into that and/or add further wildcard implementation.

2020-09-21 20:13 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given Name to validate version wilcard match " {
Further explanation of current behavior when using wildcard version: someone adding `-Version 4.2.*` to their Find-PSResource command would expect it to find an exact version or list of exact versions that match this. Instead, it seems to get parsed as a range and the latest version is returned (so if there's a version later than 4.2.* it would return that. For the other 2 cases you listed it successfully prints an error message about those not being valid strings and doesn't return anything.

2020-09-21 20:15 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        $res.Version | Should -Be "2.0.1.0"
Agreed. This will be resolved by using our test modules versus production modules in the next PR

2020-09-21 20:21 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given ModuleName to validate version wildcard match " {
while similar to the tests on line 56, this tests the `-ModuleName` parameter and the similar one tests the `-Name` parameter. The logic and implementation for these two parameters are kind of separated in the code so I tried to test both.

2020-09-21 20:21 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        $tagValue = "Azure"
Agreed. Will resolve this in next PR.

2020-09-21 20:45 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        $res = Find-PSResource -Tags $tagValue1,$tagValue2,$tagValue3 -Repository (Get-PoshTestGalleryName) | Where-Object { $_.Name -eq "Az.Accounts" }
that makes sense 👍 I incorporated this change.

2020-09-21 20:46 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +Import-Module "$psscriptroot\PSGetTestUtils.psm1" -WarningAction SilentlyContinue -Force
okay done.

2020-09-21 20:54 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        @{Version="[4.3.0.0]";          ExpectedVersion="4.3.0.0"; Reason="validate version, exact match"},
If that is a change in nuget v3, then please open a doc bug against them

2020-09-21 20:55 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +    It "find Command resource given Name to validate version wilcard match " {
4.2.* should definitely be equivalent to maxversion < 4.3.  If this is not currently the case, please open a new issue.

2020-09-21 21:07 UTC, SteveL-MSFT requested changes
Getting better, almost there :)

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/CommandFindResource.Tests.ps1
> +        @{Version="[4.3.0.0]";          ExpectedVersion="4.3.0.0"; Reason="validate version, exact match"},
Would "4.3.0.0" now be an exact match instead of minimum match or something else?  Seems like that case should be covered even if it is an error case.  Seems like there should be a separate test case for validating incorrectly formatted version string syntax with many test variants.

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name "ContosoServer" -Version $Version -Repository (Get-PoshTestGalleryName)
It seems that with PowerShellGet v2, it has a difference in behavior when `-Repository` is explicitly used.  The only difference should be an optimization where PowerShellGet doesn't look through all repositories.  It seems we should have an explicit test for that.

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name ContosoServer -Version "*" -Repository (Get-PoshTestGalleryName)
Instead of calling `Get-PoshTestGalleryName` within each test, it would be better to have a `BeforeAll{}` block call that helper function and store result in $testGalleryName variable that is used by each test that needs it

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name "PSGTEST-PublishPrereleaseModule-3139"
Does the `3139` mean something?  Seems like we should use a namespace to avoid collisions and make the test module names descriptive without any "magic numbers".  Like `Microsoft.PowerShell.Test.PrereleaseModule`

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
You don't have to clean the whole file, but we should not have extra whitespace where it's not needed.  Just delete the ones near code you added/modified.

2020-09-21 21:07 UTC, SteveL-MSFT commented on test/RoleCapabilityFindResource.Tests.ps1
> +Describe 'Test Find-PSResource for Role Capability' {
Would be better to have a file name convention like: `FindPSResource.RoleCapability.Tests.ps1` that way if someone wanted to find all the `Find-PSResource` tests they can just do `ls FindPSResource.*` or if they do a listing they would be grouped together if sorted.

2020-09-22 15:05 UTC, anamnavi commented on test/CommandFindResource.Tests.ps1
> +        @{Version="[4.3.0.0]";          ExpectedVersion="4.3.0.0"; Reason="validate version, exact match"},
yes that would be an exact match. I added tests for invalid versions

2020-09-22 15:06 UTC, anamnavi commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name ContosoServer -Version "*" -Repository (Get-PoshTestGalleryName)
good point, I added this change

2020-09-22 15:10 UTC, anamnavi commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name "PSGTEST-PublishPrereleaseModule-3139"
The `3139` doesn't mean anything, I just hadn't thought about removing magic numbers from names but I can see why using a namespace is better practice here. I swapped out this module for a test one for other reasons, but I've made note of using namespaces to make the module name more descriptive and free of random numbers.

2020-09-22 15:12 UTC, anamnavi commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name "ContosoServer" -Version $Version -Repository (Get-PoshTestGalleryName)
I've added a performance test for this now

2020-09-22 15:12 UTC, anamnavi commented on test/RoleCapabilityFindResource.Tests.ps1
> +Describe 'Test Find-PSResource for Role Capability' {
good point, I hadn't considered file discovery from a user point of view. I made this change.

2020-09-28 21:51 UTC, anamnavi commented on test/ModuleFindResource.Tests.ps1
> +        $res = Find-PSResource -Name "ContosoServer" -Version $Version -Repository (Get-PoshTestGalleryName)
performance tests with timing and with Verbose messages will be added in next PR. Currently there is a [test ](https://github.com/anamnavi/PowerShellGet/blob/remaining-find-tests/test/FindResource.Command.Tests.ps1#L202) to check that the repository with higher priority is checked first for a resource. I set the repositories' configurations (including priorities in the BeforeAll section of the tests).

2020-09-28 23:53 UTC, SteveL-MSFT requested changes

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +
Extra newline

```suggestion
```

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +function RemoveTmpdir
This should not be needed as tests should be using $TestDrive which is auto-deleted

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/FindResource.Module.Tests.ps1
> +
Just do a search for all extra newlines and remove

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    $originalXmlFilePath = Join-Path -Path $env:LOCALAPPDATA -ChildPath "PowerShellGet" -AdditionalChildPath "PSResourceRepository.xml"
That env var doesn't exist on non-Windows.  If the intent of this is to overwrite the psrepository registration file, then it would be better to export the current psrepositories on the system, register the test ones, then on cleanup remove all the repositories and put back the originals.

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    $repoURLAddress = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "testdir"
Use $TestDrive instead of creating own TempPath

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
```suggestion
    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module" -NestedModules "$PublishModuleName.psm1"

```

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
```suggestion
    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module" -NestedModules "$PublishModuleName.psm1" -DscResourcesToExport @('DefaultGatewayAddress', 'WINSSetting') -Tags @('PSDscResource_', 'DSC')

```

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
```suggestion
    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module" -NestedModules "$PublishModuleName.psm1" -CmdletsToExport @('Get-Test', 'Set-Test')

```

2020-09-28 23:53 UTC, SteveL-MSFT commented on test/testRepositories.xml
> +</configuration>
Best practice is to have a trailing newline in all text files

2020-09-29 15:44 UTC, anamnavi commented on test/FindResource.Command.Tests.ps1
> +
removed

2020-09-29 15:44 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +function RemoveTmpdir
switched to using $TestDrive and didn't need this so removed it.

2020-09-29 15:45 UTC, anamnavi commented on test/FindResource.Module.Tests.ps1
> +
removed extra newlines

2020-09-29 15:45 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    $repoURLAddress = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "testdir"
switched to using $TestDrive

2020-09-29 15:45 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
made this change

2020-09-29 15:45 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
made this change

2020-09-29 15:45 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    New-ModuleManifest -Path (Join-Path -Path $PublishModuleBase -ChildPath "$PublishModuleName.psd1") -ModuleVersion $version -Description "$PublishModuleName module"  -NestedModules "$PublishModule
made this change

2020-09-29 15:45 UTC, anamnavi commented on test/testRepositories.xml
> +</configuration>
added newline

2020-10-01 22:19 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    $originalXmlFilePath = Join-Path -Path $env:LOCALAPPDATA -ChildPath "PowerShellGet" -AdditionalChildPath "PSResourceRepository.xml"
Currently we don't have functionality to take an entire snapshot of the repository like this. (We would just be able to save it's name, Repository, Description and Version - but other info like packages published to it, etc can't be saved. Also command to return the repositories returns a PSObject that going to change in the future so I talked to Amber and she suggested that wouldn't be good to rely on.) Instead I used the .NET Environment method. I checked and this works cross platform on Linux/WSL

2020-10-01 23:13 UTC, SteveL-MSFT approved these changes

2020-10-02 18:03 UTC, merged