Fix Register-PSResourceRepository to accept a non-Windows filesystem path
PowerShell/PSResourceGet pull request #256
Opened 2020-09-14 21:07 UTC by SteveL-MSFT

Unix file paths don't start with a drive letter, so the Url API fails.  Fix is to use an appropriate URL scheme which is `file://` in this case denoting it as a filesystem path.  This will work on both Windows and Unix systems.

No added test for this as I'm fixing the Register-PSRepository tests in a separate PR which requires more extensive changes.

Also added a luanch.json file so that VSCode can attach the pwsh process to debug PowerShellGet.dll

2020-09-14 21:43 UTC, PaulHigin requested changes

2020-09-14 21:43 UTC, PaulHigin commented on src/RegisterPSResourceRepository.cs
>                  if (url == null)
It looks like this should be ?
```
if (!Uri.TryCreate(value, string.Empty, out url))
{
...
}

2020-09-14 21:43 UTC, PaulHigin commented on src/RegisterPSResourceRepository.cs
> +                    var resolvedPath = string.Format("file://{0}", SessionState.Path.GetResolvedPSPathFromPSPath(value.ToString()).FirstOrDefault().Path);
I believe string.Format should include (CultureInfo.InvariantCulture).

2020-09-14 21:43 UTC, PaulHigin commented on src/RegisterPSResourceRepository.cs
> +                    Uri.TryCreate(resolvedPath, UriKind.Absolute, out url);
if (!Uri.TryCreate()) ?

2020-09-14 21:43 UTC, PaulHigin commented on src/RegisterPSResourceRepository.cs
> +                        var message = String.Format("The URL provided is not valid: {0}", value);
string.Format should include Culture.InvariantCulture

2020-09-14 21:46 UTC, TylerLeonhardt commented on src/RegisterPSResourceRepository.cs
> +                    var resolvedPath = string.Format("file://{0}", SessionState.Path.GetResolvedPSPathFromPSPath(value.ToString()).FirstOrDefault().Path);
Also:

![image](https://user-images.githubusercontent.com/2644648/93141478-17538480-f699-11ea-909d-bfecf63665ef.png)

2020-09-14 21:47 UTC, TylerLeonhardt commented on src/RegisterPSResourceRepository.cs
> +                    var resolvedPath = string.Format("file://{0}", SessionState.Path.GetResolvedPSPathFromPSPath(value.ToString()).FirstOrDefault().Path);
and

![image](https://user-images.githubusercontent.com/2644648/93141509-2803fa80-f699-11ea-97a3-e1758ce361b3.png)

2020-09-14 21:56 UTC, PaulHigin approved these changes
LGTM

2020-09-14 21:58 UTC, alerickson approved these changes

2020-09-14 22:20 UTC, anamnavi approved these changes

2020-09-14 22:21 UTC, merged

2020-09-15 00:33 UTC, TylerLeonhardt commented on src/RegisterPSResourceRepository.cs
> +                    var resolvedPath = string.Format(CultureInfo.InvariantCulture, "{0}{1}{2}", Uri.UriSchemeFile, Uri.SchemeDelimiter, SessionState.Path.GetResolvedPSPathFromPSPath(value.ToString())
I'm concerned about UNC paths...