Refactor Save-PSResource
PowerShell/PSResourceGet pull request #257
Opened 2020-09-15 15:58 UTC by alerickson

Refactor Save-PSResource to call into the same class that Install and Update use.  This allows some added functionality and reduces redundancy.

2020-09-15 19:03 UTC, SteveL-MSFT commented on src/InstallHelper.cs
> +using NuGet.Packaging;
NIT: These should be in alphabetical order

2020-09-15 19:54 UTC, SteveL-MSFT commented on src/InstallHelper.cs
> +                    myDocumentsPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.MyDocuments), "PowerShell");
I would think these paths are used in many places in PowerShellGet.  If so, should probably have some helper class with a method to retrieve this info and have that helper differentiate Windows/non-Windows and probably a helper to determine if user is root/elevated.

2020-09-15 19:56 UTC, SteveL-MSFT commented on src/InstallHelper.cs
> +            if (!save)
It seems like the only difference between Install and Save is the destination.  If so, then perhaps it makes sense for the InstallHelper to always do a save, but when used via Install-PSResource it gets passed in the destination depending on the parameters used.

2020-09-15 20:02 UTC, SteveL-MSFT commented on src/InstallHelper.cs
> +                    if (isWindowsPS && consoleIsElevated)
I'm not sure if this is the desired behavior.  Might be better to require `-Scope AllUsers` to be explicit.

2020-09-15 20:03 UTC, SteveL-MSFT commented on src/InstallHelper.cs
> +                if (!Directory.Exists(psModulesPath))
Since this code is almost the same, you could just have a foreach loop here

2020-09-15 21:27 UTC, SteveL-MSFT requested changes
Will wait for initial feedback to be addressed before continuing review

2020-09-16 22:01 UTC, alerickson commented on src/InstallHelper.cs
> +                    myDocumentsPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.MyDocuments), "PowerShell");
That's fair. I'll pull out this section which is all related to particular paths, PS editions, and elevations permissions.  It'll also help make this file specifically about installation.

2020-09-16 22:08 UTC, alerickson commented on src/InstallHelper.cs
> +                    if (isWindowsPS && consoleIsElevated)
We can change this behavior, I just tried to stay consistent with v2, but it makes more sense for this to be consistent with what happens in PSCore since we have the opportunity to modify it

2020-09-16 22:09 UTC, alerickson commented on src/InstallHelper.cs
> +            if (!save)
Save also does not include the XML unless specified, and can be saved as a nupkg or unpacked.  I'll think about more at a high level and see which is easier

2020-09-17 16:19 UTC, PaulHigin requested changes
Just beginning review.  This is pretty complex code so I am glad to see it being refactored (good job!).
Overall I feel the readability can be improved by breaking functional pieces into separate helper methods.
Also please think about errors and how they can be presented to the user that makes sense.
It is not always clear to me when an error should be terminating or just emitted and allow processing to continue.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                if (!Directory.Exists(psModulesPath))
I feel a foreach loop is unnecessarily complex here.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                    cmdletPassedIn.WriteVerbose(string.Format("Newly created PowerShell modules path is: {0}", psModulesPath));
Verbose message should be: "Creating PowerShell modules path...", etc.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                    Directory.CreateDirectory(psModulesPath);
File operations can fail in a number of ways.  I wonder if it makes sense to wrap in try/catch here and provide a general error message: "Unable to create <name> with error: <exception error>", for a better user experience?

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                            localPkgMetadataResource = new LocalPackageMetadataResource(localResource);
It looks like localPkgMetadataResource can be obtained outside the foreach loop.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +            LocalPackageMetadataResource localPkgMetadataResource = null;
Is there a base class that encompasses both PackageMetadataResource and LocalPackageMetadataResource?  It would be nice to create one package resource object since they are both used in the same way.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                {
I think a single helper function can be created here that returns 'filteredFoundPkgs' from local or other repos and handles version range as needed.  It would make readability better and handle errors in a uniform way.

2020-09-17 16:19 UTC, PaulHigin commented on src/InstallHelper.cs
> +                            filteredFoundPkgs = (localPkgMetadataResource.GetMetadataAsync(pkgName, prerelease, false, context, NullLogger.Instance, cancellationToken).GetAwaiter().GetResult()
Please include comments when using nuget APIs.  How they work is not obvious (to me) and a short explanation would be helpful.

2020-09-17 17:37 UTC, anamnavi approved these changes

2020-09-17 17:37 UTC, anamnavi commented on src/InstallHelper.cs
> +                    localRepo = repo.Properties["Url"].Value.ToString().StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter) ? true : false;
just a small thing but is the ternary operator needed for this line? if `repo.Properties["Url"].Value.ToString().StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter)` returns `true` or `false` anyways and `localRepo` is of type bool, then I think `localRepo = repo.Properties["Url"].Value.ToString().StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter);` could suffice?

2020-09-17 17:37 UTC, anamnavi commented on src/InstallHelper.cs
> +                                    && !tag.Equals("PSModule") && !tag.Equals("PSScript"))
I'm guessing that because Find-PSResource wasn't working for filtering by the PSScript tag when you search for all packages without a name specified, some tests or cases of install might break here, but once I get the Type parameter figured out I can provide more insight on whether checking for PSScript tag may actually be an issue or not.

2020-09-27 06:00 UTC, alerickson commented on src/InstallHelper.cs
> +                            localPkgMetadataResource = new LocalPackageMetadataResource(localResource);
Those two variables are redundant so I'm just removing them

2020-09-28 16:01 UTC, alerickson commented
There's still more comments I need to address, but I pushed changes to address some of the major issues

2020-11-12 19:34 UTC, PaulHigin approved these changes

2020-11-15 00:41 UTC, merged