Refactor tests testmodules
PowerShell/PSResourceGet pull request #297
Opened 2020-10-26 15:51 UTC by anamnavi

Refactored the Find tests to use test modules instead of production modules. Since the team has control and ownership over these test modules, testing for an exact version or anything else that is dependent upon the package not being updated is less error prone than before. This makes the tests more reliable as a failing test would indicate an error with the code, not dependant packages having changed. Resolves #263

2020-11-02 18:21 UTC, SteveL-MSFT requested changes

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        $res = Find-PSResource -Name "test_command_module"
I think test modules should use the namespace: Microsoft.PowerShell.Test.*

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        @{Version='(2.5.0.0)';       Description="exlcusive version (4.2.1.0)"},
Description doesn't match test?  There's also a typo

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
>          try {
What is purpose of try/catch?  If you ever have a generic catch, it must have a comment indicating why.  I realize this is existing code, but we should fix this as it might be catching errors that should cause the test to fail.  Applies everywhere.

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        $res.Count | Should -Be 4
Should have a loop to validate each of the results is correct module, applies to all cases

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Module.Tests.ps1
>          $psGetItemInfo.Count | Should -BeGreaterThan 1
Does this actually query for all the modules in the gallery?  Seems like an unnecessary load on psgallery.  Perhaps the cmdlet should require some input before returning results?  Should open an issue to discuss, even requiring an explicit wildcard like `*` would indicate it was a deliberate action by the user rather than just trying `Find-PSResource` and incurring a load on psgallery.

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Module.Tests.ps1
> +        $res.Count | Should -Be 7
Instead of the magic number 7, should have somewhere (probably in the utils module) a hashtable that contains all the test module versions and then using a count to match

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.RoleCapability.Tests.ps1
>          $res.Count | Should -BeGreaterOrEqual 1
The count should be exact since we control the test modules

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/FindResource.Script.Tests.ps1
> +        $resPrerelease.Version | Should -Be "3.0.0.0"
There's trailing whitespace, you should have VSCode setup to automatically strip it

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/testRepositories.xml
> +
unnecessary whitespace?

2020-11-02 18:21 UTC, SteveL-MSFT commented on test/testRepositories.xml
> +  <Repository Name="psgettestlocal"  Url="file:///c:/code/testdir"                  Priority="40" Trusted="false" />
these file paths only work on Windows and only if that machine has C: drive which isn't guaranteed

2020-11-10 14:46 UTC, anamnavi commented on test/FindResource.Module.Tests.ps1
> +        $res.Count | Should -Be 7
added in

2020-11-10 14:49 UTC, anamnavi commented on test/FindResource.RoleCapability.Tests.ps1
>          $res.Count | Should -BeGreaterOrEqual 1
I forgot to change this test to be against the exact count. Updated it now to check count against that of the role capability test module hashtable stored in PSGetTestUtils

2020-11-10 20:23 UTC, anamnavi commented on test/FindResource.Module.Tests.ps1
>          $psGetItemInfo.Count | Should -BeGreaterThan 1
Created issue, will discuss in PSGet triage meeting on Thursday.
https://github.com/PowerShell/PowerShellGet/issues/302

2020-11-17 16:39 UTC, anamnavi commented on test/FindResource.Command.Tests.ps1
>          try {
This was catching a ArgumentException, I used Pester's Should -Throw to check more explicitly, it checks the error message.

2020-11-17 17:06 UTC, anamnavi commented on test/FindResource.Command.Tests.ps1
> +        $res = Find-PSResource -Name "test_command_module"
I discussed this with Amber and her view was that we may be better off changing this when we move to NuGet gallery or reach the situation when we need the names to have the Microsoft namespace to stand out and not conflict with generic test modules. The way to change the name from something like `test_module` to `Microsoft.PowerShell.Test.*` is to either create a new module with this name or to update it in the database/from the backend which Amber could do. It's not a simple update by publishing the module with an updated version (with the name change made in). So her suggestion was to update once when we know for sure what we want it to be like.

2020-11-17 17:09 UTC, anamnavi commented on test/testRepositories.xml
> +  <Repository Name="psgettestlocal"  Url="file:///c:/code/testdir"                  Priority="40" Trusted="false" />
Good point :) my thought was that this filepath gets changed before it's ever used, but I see that it's better to not have to rely on that alone. Better to not introduce something that could cause an issue later or if missused. Additionally, this really helped my understanding of how PSGet registers the default repos and which ones. I removed this and instead register the test repo and unregister it in the PSGetTestUtils file now, with Join-Path to create the path.

2020-11-17 17:57 UTC, SteveL-MSFT requested changes

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +       Get-RegisterLocalRepos
`Register` is a verb.  Also, nouns are expected to be singular, so perhaps `Get-LocalPSRepository`

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +       Get-UnregisterLocalRepos
Same as above

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        {Find-PSResource -Name "test_command_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore} | Should -Throw -ExceptionType ([ArgumentException])
```suggestion
        { Find-PSResource -Name "test_command_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore } | Should -Throw -ExceptionType ([ArgumentException])
```

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        $expectedModules = @()
Typically `expected` is what you validate against, so this is really `$actualModules`

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +            }
Is there a reason to filter out incorrect results that may be returned?  Seems like this test should validate that each returned module has the right name

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.DSCResource.Tests.ps1
> +        {Find-PSResource -Name "test_dsc_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore} | Should -Throw -ExceptionType ([ArgumentException])
```suggestion
        { Find-PSResource -Name "test_dsc_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore } | Should -Throw -ExceptionType ([ArgumentException])
```

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        {Find-PSResource -Name "test_command_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore} | Should -Throw -ExceptionType ([ArgumentException])
Why is `-ErrorAction Ignore` used here?

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Command.Tests.ps1
> +        $res = Find-PSResource -Name "test_command_module" -Version $Version -Repository $TestGalleryName -ErrorAction Ignore
I thought we were going to use namespaced test module names?

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/FindResource.Module.Tests.ps1
> +        Find-PSResource -ModuleName "test_module" -Version "*" -Repository $TestGalleryName | ForEach-Object {
This code is similar in several cases, you can use `-TestCases` with splatting to cover different parameter variations and use the same validation code.  Something like:

```powershell
It "... with parameter '<Parameter>'" -TestCases @(
  @{ Parameter = 'Name' }
  @{ Parameter = 'ModuleName' }
) {
  param($parameter)
  ...
  $parameters = @{
    $parameter = 'test_module'
    Version = '*'
    Repository = $TestGalleryName
  }

  Find-PSResource @parameters
```

2020-11-17 17:57 UTC, SteveL-MSFT commented on test/PSGetTestUtils.psm1
> +    @{Name="test_command_module"; Version="2.5.0.0"; Repository="PoshTestGallery"; Description="this a test command resource of type module"},
lots of repetition, so recommend storing repeated values in a variable in case they need to change in the future or reused

2020-11-17 23:01 UTC, JamesWTruher commented on test/FindResource.Command.Tests.ps1
> +       Get-RegisterLocalRepos
```suggestion
       Register-LocalRepos
```

2020-11-17 23:01 UTC, JamesWTruher commented on test/FindResource.Command.Tests.ps1
> +       Get-UnregisterLocalRepos
```suggestion
       Unregister-LocalRepos
```
`Register` and `Unregister` are approved verbs

2020-11-19 16:56 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +    @{Name="test_command_module"; Version="2.5.0.0"; Repository="PoshTestGallery"; Description="this a test command resource of type module"},
stored in variable.

2021-06-21 23:26 UTC, closed without merging