WIP: Catalog v3 implementation
PowerShell/PSResourceGet pull request #321
Opened 2020-12-10 19:39 UTC by anamnavi

created PR to get feedback on wildcard implementation

2021-01-22 19:49 UTC, anamnavi commented on src/code/FindPSResource.cs
> +                        // I'm not 100% confident in this code being thread-safe. variables currentPkg and trackedPercent are the ones
Please see the note I've left here

2021-01-22 20:47 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +        [Parameter(ValueFromPipeline = true, ValueFromPipelineByPropertyName = true)]
Is this temporary and only for initial testing?  Should use an enum instead of Int.  With PowerShell 7, you can mark this as experimental so that users understand that it may change (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_experimental_features?view=powershell-7.1)

2021-01-22 20:47 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +                if (repoName.Properties["Url"].Value.ToString().EndsWith("/v3/index.json") &&
Is case sensitively a concern for the URL?

2021-01-22 20:48 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +                            PSObject pkgAsObject = new PSObject();
We should probably declare a class for this rather than returning a PSObject with noteproperties

2021-01-22 20:49 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +                    // flattenedPkgs.ToList();
Commented out code should be removed

2021-01-22 20:50 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +        public Dictionary<CatalogEntry, string> ProcessCatalogWithDict(string repoName, string sourceUrl, CancellationToken cancellationToken){
STYLE: opening braces should always be on a newline

2021-01-22 20:52 UTC, SteveL-MSFT commented on src/code/FindPSResource.cs
> +                        Host.UI.WriteProgress(
Is there a reason you are calling Host.UI.WriteProgress() directly instead of using WriteProgress() that is part of Cmdlet class?

2021-01-22 20:53 UTC, SteveL-MSFT requested changes
Perhaps have tests written first before code to show how this feature would work with the expected results?

2021-01-22 22:49 UTC, PaulHigin requested changes
Overall looks good.  Let's chat about some of these comments.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +        public int Technique
Maybe 'Technique' should be an enum type with allow list.  But I assume this is just for testing so may not be worth changing.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                    (_name.Length != 0 || _name.Any(n => n.Contains("*"))))
Is '*' the only wildcard character supported by v3 protocol?  If so, we might want to see how we can support PowerShell wildcard characters with an extra layer.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                    var flattenedPkgs = returnedPkgsFound.Flatten();
Why do packages need to be flattened?  Shouldn't 'FindPackagesFromSource' return a simple list?  Do we ever want hierarchical lists?  If not then it seems helper functions should return data with desired format.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                            pkgAsPSObject.Members.Add(new PSNoteProperty("Name", pkg.Identity.Id));
I feel we should have a regular .NET type for returning data (like PSRepositoryItemInfo), and not create a PSCustomObject.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +        public Dictionary<CatalogEntry, string> ProcessCatalogWithDict(string repoName, string sourceUrl, CancellationToken cancellationToken){
Should this be a 'private' accessible method?

Actually, I think both these functions should be part of a utility or helper class.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +            Dictionary<string, CatalogEntry> uniquePkgs = new Dictionary<string, CatalogEntry>();
Nitpick.  You can use 'var' in these delcarations:
```csharp
var uniquePkgs = new Dictionary<string, CatalogEntry>();
```

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +            var feed = new Uri(sourceUrl);
Style: No need to declare this variable here, and can insert in 'new CatalogReader(feed)' below, since it seems to be used only there.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                IReadOnlyList<CatalogEntry> my_list = catalog.GetFlattenedEntriesAsync(cancellationToken).GetAwaiter().GetResult();
Style: `my_list` should benamed `cataloglist`?  To be more descriptive.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                        trackedPercent = currentPercent;
Can this progress logic be wrapped into a helper method?  It may be needed for other cmdlets or cases.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                    if(v3Pattern.IsMatch(pkg.Id) && (_prerelease || !pkg.Version.IsPrerelease) && ((!uniquePkgs.TryGetValue(pkg.Id, out CatalogEntry entry)) || (pkg.Version > entry.Version)))
We usually add a comment to help clarify the filter logic.  Something like:
```csharp
// Add unique package if
//    Pattern matches
//    Not prerelease version or prerelease versions allowed
//    Package version does not already exist in list
```

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                    {
The last filter condition `(pkg.Version > entry.Version)` doesn't seem right.  Presumably there can be multiple packages in `uniquePkgs` with different versions, and an new one should only be added if the version is different from any other package version (with same id).  This seems to rely on order, which Dictionary does not guarantee.

I wonder if the uniquePkgs dictionary should be keyed with a key generated from id and version.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                    pkgsWithDesc.Add(current, current.GetNuspecAsync().GetAwaiter().GetResult().GetDescription());
I assume this is done in a separate loop because this retrieve has performance implications?  A comment should be added to clarify.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
I agree that this is worrisome.  It is always hard to reason about multi-threaded code.  I am pretty sure `Host.UI.WriteProgress()` is not thread safe, plus it probably must only be called with monotonically increasing values.

I think the best solution is to have a worker thread that writes to `Host.UI.WriteProgress()`, and only writes when a volatile 'currentprecent' variable is incremented.

However, I am not sure it is worth the effort just for progress tracking.

2021-01-22 22:49 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +        public Dictionary<CatalogEntry, string> ProcessCatalogWithPLINQ(string repoName, string sourceUrl, CancellationToken cancellationToken)
It is not clear to me that the perf gain is worth the trouble of multi-threaded code here.  But if we find it is, I would rather use .Net Tasks rather than PLINQ.

2021-03-04 03:47 UTC, rjmholt commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
I know it's been a while, but I just want to chime in to say I suggested the code here on the basis that `Host.UI.WriteProgress()` is threadsafe ([this](https://github.com/PowerShell/PowerShell/blob/9aede0558a4c26a4f0769a51d8f0bb3e5fcfa744/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1322) suggests at least that ConsoleHost's UI is written with this intention).

Given that @anamnavi discovered that parallelising the catalog presented a significant speedup, I tried to come up with a relatively lightweight way to preserve that parallelisation while also informing the user of progress. So rather than juggling locks or event queues, this just increments an integer across threads and whichever thread pushes the percentage over a given interval updates the progress.

The downsides are:
- It's not terribly straightforward code, although I'm not sure another solution would be more obvious
- The `sourceId` parameter is cumbersome
- The thread-safety relies on a monotonicity condition within the logic itself, rather than a locking primitive, so changing it could break things

I'll see if I can come up with a consumer-thread solution for the sake of comparison

2021-03-04 18:31 UTC, rjmholt commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
Here's an alternative, event-queue-based implementation:

```csharp
protected override void EndProcessing()
{
    // We need to be able to cancel in case something happens in the tasks
    var tasksDone = new CancellationTokenSource();
    // We'll use this as an event queue to write progress
    var progressEvents = new BlockingCollection<bool>();
    // This is our global monotonically increasing count of task progress across threads
    int count = 0;
    Task countTask = Task.WhenAll(
        Enumerable.Range(0, 100000)
            .Select(async i => {
                try
                {
                    // Simulate some work here
                    await Task.Delay(1);
                    // There are 100,000 tasks, and every 1000th will send a progress update, for 100 total
                    if (Interlocked.Increment(ref count) % 1000 == 0)
                    {
                        progressEvents.Add(true);
                    }
                }
                catch
                {
                    // If anything happens, we cancel the awaiter
                    // but also rethrow so the task awaiter will pick up the exception
                    tasksDone.Cancel();
                    throw;
                }
            // We also want to signal when we're done so the awaiter knows to end
            // we can do this with the cancellation token
            // or just by sending a different message to the event queue
            })).ContinueWith(_ => progressEvents.Add(false));

    int progressPercent = 0;
    try
    {
        foreach (bool shouldContinue in progressEvents.GetConsumingEnumerable(tasksDone.Token))
        {
            // We will be sent false at the end, so that's when we break
            if (!shouldContinue)
            {
                break;
            }
            // For every event, we just update the percentage by 1 and write progress
            WriteProgress(
                new ProgressRecord(activityId: 1, "Counting", "Almost done!")
                {
                    PercentComplete = progressPercent++
                });
        }
    }
    // This is how cancellation will occur, so we just catch it to proceed
    catch (OperationCanceledException)
    {
    }

    // We await the task here so that any exceptions that occur are thrown properly on our thread
    countTask.GetAwaiter().GetResult();
}
 ```

2021-03-04 18:50 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
@rjmholt If you look at the remoting code, you will see that a lot of effort is expended ensuring all data streams (including progress) are marshaled onto a single thread on the client.  So I would be hesitant to trust WriteProgress.  Frankly, I feel the effort is probably not worth it, at least for the initial implementation.

2021-03-04 19:21 UTC, rjmholt commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
Example using a lock (really a better configuration of the original):

```csharp
protected override void EndProcessing()
{
    // Lock for incrementing percentage and writing progress
    var progressLock = new object();
    // This is our global monotonically increasing count of task progress across threads
    int count = 0;
    // How much progress we've made
    int percentage = 0;

    Enumerable.Range(0, 1000)
        .AsParallel()
        .ForAll(i => {
            // Simulate work
            Task.Delay(1).Wait();

            // Each thread can atomically increment the count and get a unique result
            // If this thread is one of the 100 that ticks over a 0, it writes progress
            if (Interlocked.Increment(ref count) % 10 == 0)
            {
                // Now we lock around both writing progress and incrementing percentage
                lock (progressLock)
                {
                    Host.UI.WriteProgress(
                        sourceId: 1,
                        new ProgressRecord(activityId: 1, "Counting", "Almost done!")
                        {
                            PercentComplete = percentage++
                        });
                }

                // If we decided that Host.UI.WriteProgress is threadsafe, we could do this equivalently and save needing to use a lock:
                // Host.UI.WriteProgress(
                //     sourceId: 1,
                //     new ProgressRecord(activityId: 1, "Counting", "Almost done!")
                //     {
                //         PercentComplete = Interlocked.Increment(ref percentage),
                //     });
            }
        });
}
```

2021-03-04 19:40 UTC, rjmholt commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
One thing I noticed doing this is that if you have any kind of async operation in your task body, you're much better off with a `Select(async _ => { })` rather than `.AsParallel().ForAll()` or similar, just because being able to `await` means you won't block the threadpool

2021-03-05 17:16 UTC, PaulHigin commented on src/code/FindPSResource.cs
> +                        // A possible solution could be to use the commented conditional code below that nests Interlocked operations
Again, I wonder if it is worth the effort/overhead to parallelize this.  The lock re-serializes the threads, making them less efficient.  Testing will show any benefit.  Also, the new x-plat, inline progress indicator may be more performant.

2021-06-21 23:25 UTC, closed without merging