Refactoring
PowerShell/PSResourceGet pull request #346
Opened 2021-03-02 21:40 UTC by anamnavi

Would appreciate feedback on the refactored Register-PSResourceRepository cmdlet code (in Register-PSResourceRepository.cs). I have added tests for this cmdlet too. Would also appreciate feedback on the RepositorySettings.cs Add() method and PSRepositoryItem.cs class (which will be the type of the object returned/used when `-PassThru` is specified.

Note: I've included the code for the Get-PSResourceRepository and Unregister-PSResourceRepository cmdlets because I use those cmdlets to help with testing of Register-PSResource but the review for them will take place later when they're fully finished and have their tests.

# PR Summary

- refactored Register-PSResourceRepository code in RegisterPSResourceRepository.cs
- created PSRespositoryItem class
- refactored Add() method in RepositorySettings.cs to be return PSRepositoryItem objects (to be used for PassThru)

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-03-02 22:20 UTC, alerickson reviewed
I left some comments on this but I just wanted to make a meta comment since this pops up a lot throughout the entire repo:  kind of a nit, but as we're going through all the files we should change any implicit types to be explicit

2021-03-02 22:20 UTC, alerickson commented on src/code/Get-PSResourceRepository.cs
> +            var r = new RepositorySettings();
Something Paul had previously suggested  (that I definitely think we should do) is to make RepositorySettings a static class

2021-03-02 22:20 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +        public Uri Proxy
We should also be sure to document which parameters are not yet working yet.. I believe the Proxy/Proxy Credential params should be included in this.

2021-03-02 22:20 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +        RepositorySettings repositorySettings = new RepositorySettings();
Same comment as earliery about using a static Repository Settings class here.

2021-03-02 22:20 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +            // string repoName = repo.Properties["Name"].Value.ToString();
I think we can get rid of this comment

2021-03-02 22:20 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +        string commandName,  // For cmdlets Get-PSResource, Set-PSResource, and Unregister-PSResource
We can either update the comment here or just remove the comment all together since it's not terribly helpful

2021-03-02 22:20 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +using Microsoft.PowerShell.PowerShellGet.PSRepositoryItem;
Is this assembly needed?  Just a general comment to any unnecessary assemblies (these all very well may be needed here, but just wanted to mention that since I know there's a handful of files that have extraneous assemblies).

2021-03-02 22:20 UTC, alerickson commented on src/code/Get-PSResourceRepository.cs
> +            foreach (var repo in items)
We should try to explicitly type variables that were previously implicitly types,  this 'var' for example

2021-03-02 22:20 UTC, alerickson commented on src/code/PSRepositoryItem.cs
> +        public PSRepositoryItem(string name, Uri url)
Are you using these constructors anywhere?  If not we can get rid of the constructors and just use the auto-implemented getters and setters, eg:  `public string Name { get; set; };`

2021-03-02 22:20 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +    using RepositorySettings = Microsoft.PowerShell.PowerShellGet.RepositorySettings.RepositorySettings;
You can just add this using statement with the other using statements at the top of the file and just include `Microsoft.PowerShell.PowerShellGet.RepositorySetting`

2021-03-02 22:20 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +                    throw new Exception("perhaps you used the wrong type for the parameter" + e.GetType());
We should also get @SydneyhSmith's input on language for all the error messages

2021-03-02 22:20 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +            WriteDebug("new cmdlet");
I would add something a little more specific for the debug messaging here, maybe something like "Entering Register-PSRepository"  or "Register-PSRepository::ProcessRecord"

2021-03-02 22:20 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +                foreach (var item in items)
Same comment as earlier about explicit typing here.

2021-03-02 22:20 UTC, alerickson commented on src/code/RepositorySettings.cs
> +                throw new ArgumentException("Was not able to successfully create xml");
With the exceptions, we should be consistent with how we're using them.  We can discuss with Paul (I know we had briefly discussed error handling in the past) to figure out what we want to set as our standard for error handling in the repo.

2021-03-02 23:03 UTC, PaulHigin requested changes

2021-03-02 23:03 UTC, PaulHigin commented on src/code/ArgumentCompleter.cs
> +                res.Add(new CompletionResult(repoName));
We don't need to use the `res` list, and instead can use the C# `yield` keyword here, since the return type is `IEnumerable`.  For an example see:
https://github.com/PowerShell/SecretManagement/blob/9de1193e327291b2ec1b0f94680a69b5011bcf3c/src/code/SecretManagement.cs#L106

2021-03-02 23:03 UTC, PaulHigin commented on src/code/ArgumentCompleter.cs
> +        return CompleteRepositoryName(wordToComplete);
Probably don't need to have a separate private method here, and just copy the method body here, with the `yield` keyword.

2021-03-02 23:03 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +        private string[] _name = new string[0];
We don't need a private field and can just use C# properties:
```csharp
public string[] Name { get; set; } = new string[0];
```

2021-03-02 23:03 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +        [Parameter(Position = 0, ValueFromPipeline = true,
Since there seems to be only one parameter set, you don't need the `ParameterSetName` field here.  But when you do, we usually set the name string as a constant field, so it can be referred to later:
```csharp
private const string NameParameterSet = "NameParameterSet";
```

For an example please see:
https://github.com/PowerShell/SecretManagement/blob/9de1193e327291b2ec1b0f94680a69b5011bcf3c/src/code/SecretManagement.cs#L1371

2021-03-02 23:03 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +        RemotingCapability = RemotingCapability.None)]
I don't think `RemotingCapability` is needed anymore, and you can remove it here.

2021-03-02 23:14 UTC, anamnavi commented on src/code/Get-PSResourceRepository.cs
> +            var r = new RepositorySettings();
agreed!

2021-03-02 23:17 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +        string commandName,  // For cmdlets Get-PSResource, Set-PSResource, and Unregister-PSResource
removed

2021-03-02 23:35 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +            WriteDebug("new cmdlet");
left this in here by accident; removed. If we do add Debug messages I think we can have a chat with @SydneyhSmith on language and where/how often it's used, etc.

2021-03-02 23:37 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +using Microsoft.PowerShell.PowerShellGet.PSRepositoryItem;
these ones are used, but I'll remove any unused assemblies from all files I touch while refactoring.

2021-03-03 00:27 UTC, anamnavi commented on src/code/PSRepositoryItem.cs
> +        public PSRepositoryItem(string name, Uri url)
using it in RepositorySettings [here](https://github.com/anamnavi/PowerShellGet/blob/refactoring/src/code/RepositorySettings.cs#L134) when I create a PSRepositoryItem instance that contains the Name, URL, Trusted, Priority fields filled in with the XML document attributes

2021-03-04 00:41 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +                res.Add(new CompletionResult(repoName));
Didn't know about this C# syntactic sugar, thanks for pointing it out and for the example!

2021-03-04 22:20 UTC, PaulHigin requested changes
These are a lot of comments.  Let's get together and talk about them and what design/style changes should be made.

Overall this is a great start!

2021-03-04 22:20 UTC, PaulHigin commented on src/code/PSRepositoryItem.cs
> +        private string _name;
Again, there is no need for private fields.  We can just use properties:
```csharp
public string Name { get; set; }
...
```

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        public string Name
Please remove private fields where not needed (I'll stop reminding and assume all classes will be so modified :)).

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                        var message = string.Format(CultureInfo.InvariantCulture, "The URL provided is not valid: {0}", value);
It would be nice to provide information about what URLs are valid:
```
The provided URL, {0}, is not valid.  A valid repository URL has the form ...
```

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        public Uri Proxy
We should also throw a `System.Management.Automation.PSNotImplementedException` error until it is implemented.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            List<PSRepositoryItem> items = new List<PSRepositoryItem>();
Instead of passing in `items` in each helper method, have each helper method return a repository list?

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            catch (Exception e)
Re-throwing `Exception` here doesn't seem useful.  But using `this.ThrowTerminatingError()` may be worthwhile as we can provide an errorId and augment the error message.  What errors doe RepositorySettings throw?  I assume it does not allow duplicate entries, but does it perform other validation?  In any case we should ensure the user error message is comprehensible and should have error tests.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    throw new Exception(e.Message);
Same comment for exception rethrow as above.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                if(repo.ContainsKey(PSGalleryRepoName))
I think that hashtable parameter validation can be done in a helper method, and maybe it returns required values, either user provided or default if parameter is not required.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    throw new System.ArgumentException(string.Format(CultureInfo.InvariantCulture, "Repository name cannot be null"));
We should not throw a terminating error here, because it ignores any hashtable entries afterwards.  Instead we should `WriteError` and continue the loop.  This can be done in a Hashtable validation helper method.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                NameParameterSetHelper(items);
This helper method throws a terminating exception that terminates the loop, which we don't want.  Maybe `NameParameterSetHelper` just write errors or returns a success boolean and error.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static readonly string DefaultRepositoryFileName = "PSResourceRepository.xml";
Do we ever allow the repository file name and location to ever change?  If not then maybe we should remove the 'default' from the variable names and update the comment.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static bool FindRepositoryXML()
`CheckRepository()`?  `XML` doesn't seem necessary in the method name.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            // Search in the designated location for the repository XML
```csharp
return File.Exists(DefaultFullRepositoryPath);
```

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static void CreateNewRepositoryXML()
`CreateRepository()`.  This only creates a new repository if one doesn't already exists.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            if (FindRepositoryXML())
I wonder if this should also do a content validation check.  What if a user (malicious or otherwise) modifies or overwrites the file with something that does not provide valid registry information.  Should we just create a new one (after emitting a warning)?

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            // create directory if needed
Comment here and on line 66 probably not needed.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            newRepoXML.Save(DefaultFullRepositoryPath);
What happens if path/file creation fails with access denied or out of memory?  Do we let the file/io exception propagate?  I think in this case it might be good to wrap this in a PSInvalidOperation exception, with a message that provides context:
```
"Repository store creation failed with error: {0}."
```

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        /// Add a repository to the XML
Add a repository to the store?

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +    static class RepositorySettings
This should probably have `internal` access.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                throw new ArgumentException("Was not able to successfully create xml");
I don't think it make sense to wrap in `ArgumentException`, and it is better to remove try/catch and let cmdlet provide a wrapper exception with a message that can provide more context.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                FindRepositoryXML();
I think there should be a single `CheckRepositoryStore()` method that creates the file based repository store if it doesn't exist, (or if the file is corrupted?).  It can throw an exception if creation fails (access, IO error).  If Get, Update, Remove fail because the repository does not exist in the store, then that is the error to be returned.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            if (string.IsNullOrEmpty(repoName))
I think we should do name,uri validation at a higher level instead of for each low level helper method.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            var node = doc.Descendants("Repository").Where(e => string.Equals(e.Attribute("Name").Value, repoName, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
We should have a 'Get()' method that returns repository information from a name look up.  It can be used for Update and Remove operations as well.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            var node = doc.Descendants("Repository").Where(e => string.Equals(e.Attribute("Name").Value, repoName, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
Using XmlDoc class for this simple repository information seems too heavy weight to me.  I wonder if we should use a simple json file format, which is consistent with other PowerShell modules.  Also, if two PowerShell instances modify the store file at the same time, information is lost.  We might want to think about synchronizing.  If so, we can look at SecretManagement for an example.  Let's discuss more offline.

2021-03-04 22:20 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static List<PSRepositoryItem> Read(string[] repoNames)
Oh, I see that there is this `Read` method (instead of `Get`).

2021-03-05 19:53 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                NameParameterSetHelper(items);
this is where non terminating error handling should happen. Also NameParameterSet helper should not throw terminating error bc rest of repositories will not be considered/evaluated

2021-03-05 19:54 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                _name = repo["Name"].ToString();
pass in values, instead of using fields (implicit values where you can't be sure 100% of their state persisting)

2021-03-05 20:00 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                        var message = string.Format(CultureInfo.InvariantCulture, "The URL provided is not valid: {0}", value);
problem, if possible what is wrong and how can be remedied (can be of this type, etc) -> general template

2021-03-05 20:43 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +            if(ParameterSetName.Equals(PSGalleryParameterSet)){
use switch statements instead

2021-03-05 20:46 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +    using RepositorySettings = Microsoft.PowerShell.PowerShellGet.RepositorySettings.RepositorySettings;
The `RepositorySettings` and `PSRepositoryItem` classes are now part of the `Microsoft.PowerShell.PowerShellGet.UtilClasses` namespace to avoid this workaround for using a namespace and class of same name.

2021-03-05 21:36 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            if (FindRepositoryXML())
do we want to make this file tamper proof? Possible side effects of this (based on how tests are currently done, etc). If we wish to look at .NET libraries being used to detect this in SecretManagement

2021-03-05 21:37 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            if (FindRepositoryXML())
also can change to a json format file for the repository store..

2021-03-08 16:50 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        public static bool FindRepositoryXML()
CheckRepositoryStore() and FindRepositoryStore() should be private

2021-03-08 16:52 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        public static void CreateNewRepositoryXML()
rename to show it's conditionally creating repo store. CheckAndCreateRepositoryStore()

2021-03-08 17:16 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            if (FindRepositoryXML())
at minimum reset state if corrupted, emit error and let user reset it.

2021-03-08 17:37 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            var node = doc.Descendants("Repository").Where(e => string.Equals(e.Attribute("Name").Value, repoName, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
discuss with @SydneyhSmith about intended change

2021-03-08 17:38 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        public static List<PSRepositoryItem> Read(string[] repoNames)
instead of get helper to parse through xml document, just use Read with that name.

2021-03-11 21:12 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        public static bool FindRepositoryXML()
CheckRepositoryStore() is public per our discussion

2021-03-16 17:43 UTC, PaulHigin requested changes
Added comments for the RepositorySettings class, but still need to review the other cmdlet implementations.

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        /// Also, the user level setting file at '%APPDATA%\NuGet' always uses this name
I am not sure what this comment means, but it appears we use `%LOCALAPPDATA%` instead of `%APPDATA%`.

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                try{
Style nitpick:  
We should be consistent on bracket placement (For csharp, usually on next line rather than same line).
Also spacing before '(' on 'if' statement:
```csharp
if (...)
```

instead of 
```csharp
if(...)
```

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        private static XElement FindExistingRepositoryHelper(XDocument doc, string name)
A better name, `FindRepositoryElement` ?

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            if(node != null)
Can just return here, but it would be good to indent to make this more readable.
```csharp
return doc.Descendants("Repository").Where(
    e => string.Equals(
        e.Attribute("Name").Value,
        name,
        StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
```

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            PSRepositoryItem repoItem = new PSRepositoryItem(repoName, repoURL, repoPriority, repoTrusted);
We don't really need the repoItem variable.

```csharp
return new RepositoryItem(repoName, ...)
```

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                if (repoURL != null)
It is Ok to have a null repository url?  It seems like the repository entry is useless without one.  Except maybe for PSGallery that has a fixed Url?  If that is the only case we should verify.

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        Uri thisUrl;
This declaration can be removed.  Also it seems like we should test the result of TryCreate and return appropriate error, or return a null Uri value?  Not sure what is expected.
```csharp
if (!Uri.TryCreate(repo.Attribute("Url").Value, UriKind.Absolute, out Uri thisUrl))
{
    ...
}
```

2021-03-16 17:43 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            catch (Exception e)
Since we are processing multiple repository names, I feel we shouldn't have a catch all - throw here and instead return whatever results we can.  There can be a separate try/catch around the XDocument.Load() since if it fails we cannot proceed.  But if an exception is thrown in a processing loop we should save the error and continue with other entries.

We should change the method signature to something like:
``` csharp
public static List<PSRepositoryItem> Read(string[] repoNames, out string[] errorMsgs)
```
where the calling cmdlet can provide individual error records as needed.

2021-03-17 16:49 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                if (repoURL != null)
discussed

2021-03-17 17:00 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                        Uri thisUrl;
1) changed declaration
2) I thought we could assume that repositories already registered will have to had correct URLs (that we tested can be created as URIs). I can add a check in case the user modifies the repository.xml and somehow adds a URL not of valid Uri type...if TryCreate fails I'll write an error and skip past that repository

Done..pass in cmdlet and write debug statements for each method

2021-03-17 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                        Uri thisUrl;
Instead: write debug at cmdlet level, and have them write the error I think.

2021-03-18 16:35 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            catch (Exception e)
Done.

2021-03-22 23:37 UTC, PaulHigin requested changes
Just a few more comments.  Will finish tomorrow.

2021-03-22 23:37 UTC, PaulHigin commented on src/code/ArgumentCompleter.cs
> +        catch(PSInvalidOperationException e)
Is there a reason to catch and rethrow this error?

2021-03-22 23:37 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +        SupportsShouldProcess = true,
We don't seem to be implementing `SupportsShouldProcess` so we should remove this attribute.  This cmdlet doesn't change any state so it doesn't seem necessary.

2021-03-22 23:37 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +            try
This only needs to be called once.  Since `Name` parameter takes pipeline input, this block will be called for each name passed in the pipeline.  I think this check should be added to the `BeginProcess` block and executed only once per cmdlet instance.

2021-03-22 23:37 UTC, PaulHigin commented on src/code/Get-PSResourceRepository.cs
> +                throw new Exception(string.Format("Unable to successfully read repository store. {0}", e.Message));
I am wondering if we should throw here (and stop the running pipeline).  Could other names in the pipeline succeed?  If not then this is correct as is.

2021-03-22 23:37 UTC, PaulHigin commented on src/code/PSRepositoryItem.cs
> +    public class PSRepositoryItem
public sealed?

```suggestion
    public sealed class PSRepositoryItem
```

2021-03-22 23:37 UTC, PaulHigin commented on src/code/PSRepositoryItem.cs
> +            get
Do we need the getters?  Is this object meant to be mutable?

2021-03-22 23:37 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        SupportsShouldProcess = true,
This attribute makes sense for a register operation, but I don't see the code implementation.

2021-03-22 23:37 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        [Parameter(ValueFromPipelineByPropertyName = true)]
Just curious why Proxy, ProxyCredential is passed in through a pipeline object?

2021-03-23 17:58 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +        catch(PSInvalidOperationException e)
There isn't. As per our discussion yesterday I removed it.

2021-03-23 18:50 UTC, anamnavi commented on src/code/Get-PSResourceRepository.cs
> +                throw new Exception(string.Format("Unable to successfully read repository store. {0}", e.Message));
No, if this error occurs other names in the pipeline would be run into the same error. I removed the try/catch per above comment and our discussion...so if this error occurs it'll be thrown from RepositorySettings, propagate up the stack and stop the running pipeline (which is fine since the other names in the pipeline couldn't have succeeded anyways).

2021-03-23 19:01 UTC, anamnavi commented on src/code/Get-PSResourceRepository.cs
> +        SupportsShouldProcess = true,
I agree

2021-03-23 19:34 UTC, PaulHigin requested changes

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    WriteDebug("Invalid parameter set");
I would use a `Debug.Assert()` here, since this should never happen.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (String.IsNullOrEmpty(repoName) || repoName.Contains(" ") || repoName.Contains("*"))
Can use `string.IsNullOrWhiteSpace()` here.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (repoName.Equals("PSGallery"))
This should be a case insensitive compare:
```csharp
if (repoName.Equals("PSGallery", StringComparison.OrdinalIgnoreCase))
```

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (!repo.ContainsKey("Name") || String.IsNullOrEmpty(repo["Name"].ToString()))
Can repo name contain white spaces?  If so, the argument completer above will need to insert single quotes.  Ping me for more info.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (repo["Name"].ToString().Equals("PSGallery"))
Case insensitive compare?

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            }
PowerShell style guidelines state there should always be a new line after a closing bracket.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                        new PSInvalidOperationException("Repository url cannot ne null"),
```suggestion
                        new PSInvalidOperationException("Repository url cannot be null"),
```

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                // false, setting to true
Can probably remove these comments?

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            List<string> temp = new List<string>();
Nitpick, var name: errorList?

2021-03-23 19:34 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        temp.Add(String.Format("Unable to find repository matching Name '{0}'.  Use Get-PSResourceRepository to see all available repositories.", repo));
We (PowerShell) don't emit an error if a wildcard search returns no results.  An error is emitted only if a specific name (no wildcard) is provided.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/Unregister-PSResourceRepository.cs
> +            foreach (string error in errorMsgs)
It looks like RepositorySettings class can return a null value for `errorMsgs`.  I think we should change it so that it never returns null, but an empty array for no errors.  That we you can use this code here to just iterate without first having to check for null value.  Otherwise you will need to add a check for null here.

2021-03-23 19:34 UTC, PaulHigin commented on src/code/Unregister-PSResourceRepository.cs
> +                if (!String.IsNullOrEmpty(error))
Since we control the internal class that reports these errors, I think you should just never return a null or empty error message, so the high level code here does not have to check each returned item.

2021-03-23 19:34 UTC, PaulHigin commented on test/GetPSResourceRepository.Tests.ps1
> +        $tmpDir1Path = Join-Path -Path (Get-TempPath) -ChildPath "tmpDir1"
You can use `$testdrive` built-in variable for creating test directories and files, which will be cleaned up automatically so you don't need to in an After block.

```powershell
$tmpDirPath = Join-Path -Path $testdrive -ChildPath "tmpDir1"
...
```

2021-03-23 19:34 UTC, PaulHigin commented on test/GetPSResourceRepository.Tests.ps1
> +        $errorMsg = "Unable to find repository matching Name '$nonRegisteredRepoName'.  Use Get-PSResourceRepository to see all available repositories."
We normally don't use error messages for testing because a) they are (sometimes) localized to different languages, and b) are subject to change.  Instead we use the ErrorRecord `FullyQualifiedErrorId` string as that should never change.
E.g.,

```powershell
It "Verifies Set-SecretInfo fails with expected unsupported error" {
            Set-SecretInfo -Name TestDefaultMeta -Metadata @{ Fail = $true } -ErrorVariable err 2>$null
            $err | Should -HaveCount 2
            $err[1].FullyQualifiedErrorId | Should -BeExactly 'SetSecretMetadataCommandNotSupported,Microsoft.PowerShell.SecretManagement.SetSecretInfoCommand'
        }
```

The `FullyQualifiedErrorId` is for the user to be able to uniquely specify an error for any language.
I don't know if/when we would localize error messages for this module so it is not as important here, but it might be good to follow PowerShell testing conventions.
```

2021-03-24 15:36 UTC, anamnavi commented on src/code/Get-PSResourceRepository.cs
> +            try
added a `BeginProcessing()` block for Get and Unregister which both support values from pipeline.

2021-03-24 17:48 UTC, anamnavi commented on src/code/Unregister-PSResourceRepository.cs
> +            foreach (string error in errorMsgs)
I actually don't need to set it to null or even an empty array at the start. (I think I added this here when I was debugging some other issue for it that was resolved.)

2021-03-26 17:30 UTC, anamnavi commented on test/GetPSResourceRepository.Tests.ps1
> +        $tmpDir1Path = Join-Path -Path (Get-TempPath) -ChildPath "tmpDir1"
I replaced the TempPath with $TestDrive, thanks for pointing this out! From Pester $TestDrive documentation: "When the Describe block is finished all contents of the TestDrive are discarded", so I still had to include the AfterAll block.

2021-03-26 19:04 UTC, anamnavi commented on src/code/PSRepositoryItem.cs
> +            get
remove setter, use Property in the constructor too.

2021-03-26 20:37 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +        [Parameter(ValueFromPipelineByPropertyName = true)]
it shouldn't be until we implement it. Removed ValueFromPipeline tag from these parameters

2021-03-26 22:22 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +        SupportsShouldProcess = true,
added, with target/action formatting. Also added `ShouldProcess` to Unregister-PSResourceRepository.

2021-03-30 20:54 UTC, PaulHigin requested changes
Just a handful of minor changes.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        [ValidateNotNullOrEmpty]
Unnecessary attribute for int type.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        [ValidateNotNullOrEmpty]
Missing `[parameter]` attribute

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +        public PSCredential ProxyCredential { get; set; }
Missing `[parameter]` attribute

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (Proxy != null || ProxyCredential != null)
Please move to `BeginProcessing()` block, since values are not passed in via pipeline.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +
Please remove space.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                RepositorySettings.CheckRepositoryStore();
Can also be moved to `BeginProcessing()` block.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (PassThru)
Please add space after bracket.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +
Please remove space

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +
Please remove space

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            return reposAddedFromHashTable;
Please add space after bracket.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +
Please remove white space.

2021-03-30 20:54 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static readonly string RepositoryFileName = "PSResourceRepository.xml";
I believe these can be `private` access as they are only used within the class.

2021-03-30 22:37 UTC, PaulHigin approved these changes
LGTM

2021-03-31 23:35 UTC, PaulHigin commented
@anamnavi  Can you look at the test failures?

2021-04-02 23:00 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +        List<PSRepositoryInfo> listOfRepositories = RepositorySettings.Read(null, out string[] _);
Is the out variable for error?  And does it get used anywhere here?

2021-04-02 23:53 UTC, alerickson commented on src/code/ArgumentCompleter.cs
> +        var wordToCompletePattern = WildcardPattern.Get(
I'm a little confused about the wildcard within the argument completer.
The scenario I typically think of for argument completer is:  get-psresourcerepository ps  <tab through>.  
It looks like this is trying to handle the wildcard scenario  get-psresourcerepository ps* <tab through>?
Is that correct?

2021-04-03 00:18 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +        List<PSRepositoryInfo> listOfRepositories = RepositorySettings.Read(null, out string[] _);
Yes, the out variable is a array of error strings. RepositorySettings.Read() takes a `out string[]` as a parameter so when we call Read() from ArgumentCompleter we need to pass it a variable that the called method must modify. But we don't have any errors that get returned to ArgumentCompleter, so we pass a `_` variable which means we wish to discard whatever results it gives us. However, the out variable gets returned errors in Get-PSResourceRepository or Unregister-PSResourceRepository when we call Read() so this is just a case where we  must provide Read() the out variable but it's results are never interesting.

2021-04-03 00:28 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +        var wordToCompletePattern = WildcardPattern.Get(
before the refactoring Argument Completer would check for any repositories that started with (via `StartsWith()` ) the (partial) repository name provided. So if I typed `Get-PSResourceRepository ps` it would find any repositories starting with ps . This basically does the same thing because it'll just search for repository whose names match ps* so it effectively does the StartsWith() check but without the StartsWith() call because now it uses a wildcard pattern matching.

I think the added benefit of this way is that if we have a Name that has a space in the middle (allowed use case) then when that becomes a wildcard pattern the space is included and handled.

2021-04-05 07:01 UTC, alerickson approved these changes
Everything looks good, just left a few nit comments and a couple of general questions

2021-04-05 07:01 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +                    Dbg.Assert(false, "Invalid parameter set");
I'm not sure if this is needed since we have a default parameter set, anything that's not part of the PSGalleryParameterSet or the RepositoriesParameterSet should be part of the default parameter set

2021-04-05 07:01 UTC, alerickson commented on src/code/RepositorySettings.cs
> +        private static readonly string RepositoryPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.LocalApplicationData), "PowerShellGet"); //"%APPDATA%/PowerShellGet";  // c:\code\temp\rep
We should delete the comment on this line

2021-04-05 07:01 UTC, alerickson commented on src/code/RepositorySettings.cs
> +            Dbg.Assert(!string.IsNullOrEmpty(repoName), "Repository name cannot be null or empty");
I'm curious about System.Diagnostics.Debug vs WriteDebug.  Is there a particular reason why the former is chosen?

2021-04-05 07:01 UTC, alerickson commented on src/code/RepositorySettings.cs
> +                            temp.Add(String.Format("Unable to read incorrectly formatted URL for repo {0}", node.Attribute("Name").Value));
This is a nit that I don't think is necessary to change but I personally feel like we should stay away from using variable names that are generic (ie temp).  I think it's appropriate here, just wanted to mention it as a high level comment.

2021-04-05 07:01 UTC, alerickson commented on src/code/UnregisterPSResourceRepository.cs
> +                    new PSNotImplementedException(e.Message),
I'm not sure if 'PSNotImplementedException' is the correct error to be throwing here.  I think something along the lines of does not exist or incorrect format would be more appropriate here.

2021-04-05 07:01 UTC, alerickson commented on src/code/Utils.cs
> +}
I'm not sure why it complains about there being no new line here, but do you need to add one here?

2021-04-05 07:01 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +using System.Globalization;
Another nit to have these in alphabetical order.

2021-04-05 15:14 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        private static readonly string RepositoryPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.LocalApplicationData), "PowerShellGet"); //"%APPDATA%/PowerShellGet";  // c:\code\temp\rep
agree. I also updated the location in the comment on L 26

2021-04-05 15:18 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            Dbg.Assert(!string.IsNullOrEmpty(repoName), "Repository name cannot be null or empty");
good question :) `WriteDebug()` is declared in the abstract Cmdlet class. Since `RepositorySettings` doesn't inherit from `PSCmdlet` (which in turn inherits from `Cmdlet`) like the cmdlet classes do, I can't use WriteDebug there like I do in my cmdlet classes (i.e Register-PSResourceRepository class).

2021-04-05 15:32 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +            Dbg.Assert(!string.IsNullOrEmpty(repoName), "Repository name cannot be null or empty");
This is a correct use of a debug assert.  This class/method is internal access and we control all code paths, and the contract is that arguments should never be null.  The assert is to ensure this, and I feel WriteDebug() is not necessary here.

2021-04-05 15:34 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    Dbg.Assert(false, "Invalid parameter set");
This is a correct use of debug assert as this is something that should never happen.  If down the line, someone adds a new parameter set but forgets to adds processing, this assert will show it immediately.

2021-04-05 15:38 UTC, PaulHigin commented on src/code/ArgumentCompleter.cs
> +        var wordToCompletePattern = WildcardPattern.Get(
Personally, I am fine with it either way.  The WildcardPattern is not crucial and the previous match code works just as well.

2021-04-05 15:38 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                            temp.Add(String.Format("Unable to read incorrectly formatted URL for repo {0}", node.Attribute("Name").Value));
modified this to be `tempErrorList`

2021-04-05 15:40 UTC, anamnavi commented on src/code/Utils.cs
> +}
added

2021-04-05 17:50 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +                    Dbg.Assert(false, "Invalid parameter set");
Oh I should have been more clear, I meant the entire 'default' case

2021-04-05 17:54 UTC, anamnavi commented on src/code/ArgumentCompleter.cs
> +        var wordToCompletePattern = WildcardPattern.Get(
I prefer the wildcard pattern way because it'll just be consistent with using the wildcard pattern in RepositorySettings Read() API (for Get-PSResourceRepository.cs) and any other future code we may refactor (i.e Find-PSResource.cs)

2021-04-06 18:12 UTC, anamnavi commented on src/code/UnregisterPSResourceRepository.cs
> +                    new PSNotImplementedException(e.Message),
just throw it.

2021-04-08 17:24 UTC, merged