WIP: Refactor Get-InstalledPSResource cmdlet
PowerShell/PSResourceGet pull request #351
Opened 2021-03-12 03:23 UTC by alerickson

# PR Summary
Still a few small updates that need to be made (see below).  This PR primarily addresses refactoring and completing functionality for 'Get-InstalledPSResource', which primarily touch GetInstalledPSResource.cs and GetHelper.cs.  A new class PSResourceInfo was created to output a concrete dotnet type in order to address formatting returned output. 

TODOs:
- [ ] Ensure proper folder structure (in re to srcOld and src directories)
- [ ] Ensure extensive testing in place
- [ ] Ensure help info is added

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-03-12 17:16 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +
add license info to file (at least I've done that so if we don't need to then I can remove for consistency sake)

2021-03-12 17:28 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +namespace Microsoft.PowerShell.PowerShellGet
I added my concrete dotnet type output class (PSRepositoryItem.cs) to the `Microsoft.PowerShell.PowerShellGet.UtilClasses` namespace. As I type this out I see I should rename mine to match your name style, but I think it'll be helpful to have them both be in the same namespace

2021-03-12 19:59 UTC, anamnavi commented on srcOld/code/GetInstalledPSResource.cs
> +    [Cmdlet(VerbsCommon.Get, "InstalledPSResource", HelpUri = "<add>", RemotingCapability = RemotingCapability.None)]
@PaulHigin said we could remove RemotingCapability as it's not used.

2021-03-15 15:02 UTC, anamnavi commented on src/PSGet.Format.ps1xml
> +</Configuration>
add new line here.

2021-03-15 16:38 UTC, anamnavi requested changes
Overall looks good to me. I left a couple of comments but a couple of meta comments:
- I think we should change any implicit types to explicit
- most files needed a new line added at the end
- do we need to modify the srcOld files? If not I think we can just remove them entirely from the PR
- do we need error handling in Get-Helper GetProcessParams()?

2021-03-15 16:38 UTC, anamnavi commented on src/PowerShellGet.psd1
> +}
add new line here too

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +using Microsoft.PowerShell.PowerShellGet.RepositorySettings;
is this class being used? If so I can't see where in the file it is...but just a heads up that when my changes for RepositorySettings get merged in if you use it here you may need to update some of your code and update the using statement to be `using Microsoft.PowerShell.PowerShellGet.UtilClasses` and access the class from that namespace

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +    /// Find helper class
Do you mean `Get helper class`?

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +        public List<PSObject> ProcessGetParams(string[] name, string version, bool prerelease, string path)
could we return `List<PSResourceInfo>` instead?

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                foreach (var modulePath in modulePaths)
have the explicit type of modulePath instead of var if possible.

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +            foreach (var dir in dirsToSearch)
same as above, use explicit type instead of var

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                foreach (var pkgPath in dirsToSearch)
same comment about explicit type of pkgPath instead of var. I'm going to stop commenting on these now and assume it gets switched in all future instances.

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                            if (pkgPath.ToLower().Contains("Scripts"))
do you mean `pkgPath.ToLower().Contains("scripts")` since an uppercase S in scripts won't be present after ToLower()? Or maybe do IgnoreCase()?

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                            // TODO:  check if this xml file exists, if it doesn't check if it exists in a previous version
does this check still need to happen or it does and we can remove TODO comment

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        /* // testing adding prerelease parameter
will we be adding prerelease support...do we need to uncomment this?

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        pkgAsPSObject.Members.Add(new PSNoteProperty("Name", nameInfo.Any()? nameInfo.FirstOrDefault().Value : string.Empty));
Instead of PSObject this should be saved as an instance of PSResourceInfo object

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +                    catch { }
What's done in the catch? Should this throw a terminating error (`ThrowTerminatingError()`) or non-terminating error (`WriteError()`)?

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetHelper.cs
> +}
add newline

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetInstalledResource.cs
> +}
add new line

2021-03-15 16:38 UTC, anamnavi commented on src/code/GetInstalledResource.cs
> +            foreach (PSResourceInfo psObject in getHelper.ProcessGetParams(Name, Version, Path))
are there any errors that could come from ProcessGetParams that we need to handle here (via a try/catch)? @PaulHigin may have a better idea about the error handling needed in `ProcessGetParams()` as he helped me recognize that for Register-PSResourceRepository's helper functions/classes.

2021-03-15 16:38 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +}
new line needed, but rest of this LGTM

2021-03-15 16:38 UTC, anamnavi commented on srcOld/code/GetHelper.cs
> -﻿// Copyright (c) Microsoft Corporation. All rights reserved.
were there any changes made to this file? I thought our intention was to not modify any of the `srcOld` files..if we don't need to make any changes to it perhaps we can remove this file off this PR?

2021-03-15 16:38 UTC, anamnavi commented on srcOld/code/GetInstalledPSResource.cs
> +﻿// Copyright (c) Microsoft Corporation. All rights reserved.
I thought our intention was to not modify any of the srcOld files..if we don't need to make any changes to it perhaps we can remove this file off this PR?

2021-03-15 16:38 UTC, anamnavi commented on srcOld/code/PSResourceInfo.cs
> +
I thought our intention was to not modify any of the srcOld files (and not create any new ones there either)..if we don't need to make any changes to it perhaps we can remove this file off this PR since we already have a PSResourceInfo.cs class in `src`?

2021-03-15 16:38 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +# Copyright (c) Microsoft Corporation.
tests look good to me so far! One comment Steve had last time was that we don't need the `Purpose, Action, Expected comments before each test...the It "<test description>" is probably clear enough. I know the Find-PSResource tests follow the old comment style though, but I believe you could remove them here. Overall, good use of the Pester templating!

2021-03-15 16:39 UTC, anamnavi commented on srcOld/code/GetInstalledPSResource.cs
> +    [Cmdlet(VerbsCommon.Get, "InstalledPSResource", HelpUri = "<add>", RemotingCapability = RemotingCapability.None)]
deleting because this change shouldn't be made to srcOld file

2021-03-15 21:27 UTC, anamnavi commented on src/code/GetHelper.cs
> +using Microsoft.PowerShell.PowerShellGet.RepositorySettings;
remove directive

2021-03-15 21:27 UTC, anamnavi commented on srcOld/code/GetHelper.cs
> -using Microsoft.PowerShell.PowerShellGet.RepositorySettings;
remove this directive

2021-03-16 22:06 UTC, PaulHigin requested changes

2021-03-16 22:06 UTC, PaulHigin commented on src/PSGet.Format.ps1xml
> +      		    <TableColumnHeader><Label>Name</Label></TableColumnHeader>
Nitpick.  Fix indentation.

2021-03-16 22:06 UTC, PaulHigin commented on src/PSModule.psm1
> -    $script:FrameworkToRemove = 'net472'
Weren't we going to move to a single framework dependency?  PSReadline and SecretManagement both use 'net461' and I wonder if that is enough here.

I think our refactor should include this change if we can make it.

2021-03-16 22:06 UTC, PaulHigin commented on src/PowerShellGet.psd1
> -    Description       = 'PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, DSC Resources, Role Capabilities and Scripts.'
Are we still supporting 'Role Capabilities'?  I thought we were removing it for our first release.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                foreach (var modulePath in modulePaths)
I think var is correct here since there is no question about type.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +    class GetHelper : PSCmdlet
Since a PSCmdlet object is passed in to use, do we still need to derive this class from PSCmdlet class?  Also we should explicitly define the accessibility (probably 'internal').

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +#if NET472
Do we need this #ifdef?  I believe these APIs will work equally well on either framework.  If we just need to know what version of PowerShell is running, this can be a runtime check.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                cmdletPassedIn.WriteDebug(string.Format("Current user scope path: '{0}'", myDocumentsPath));
I think it is better to use 'WriteVerbose' instead of 'WriteDebug', as most users use the '-Verbose' switch to get more details on running operations.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +            foreach (var dir in dirsToSearch)
Instead of having a separate foreach to write search directories, you can just add the 'WriteVerbose' above where each directory is added.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                var psModulePath = Environment.GetEnvironmentVariable("PSModulePath");
These should be defined below, right next to where they are used.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +        public List<PSObject> ProcessGetParams(string[] name, string version, bool prerelease, string path)
Nitpick.  `name` should be `names`, then inside loops you can use a single `name` variable.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                Array.ForEach(name, n => nameLowerCased.Add(n.ToLower()));
Both nameLowerCased and scriptXMLnames lists can both be filled in one foreach loop, with two statements in the lambda block.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                dirsToSearch = dirsToSearch.FindAll(p => (nameLowerCased.Contains(new DirectoryInfo(p).Name.ToLower())
I am not clear what this does, but it appears to be filtering the directory search list to provided directory names.  This should be made clear in the comment above.  So the method `name` parameter should probably be `dirName` or `modName` or `resourceName` and the comment should make clear how it is used.

Also converting to lower case and allocation is not good practice in a loop.  If we want to do case insensitive matches, we should use .Net string comparer with `IgnoreCase`.  

You could use a `HashSet<string>` for unique lists such as dirsToSearch, and construct it with a case insensitive string comparer.  It will guarantee uniqueness and you don't need to use `dirsToSearch.Disctinct()`.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                cmdletPassedIn.WriteDebug(dirsToSearch.Any().ToString());
I agree WriteDebug is better than WriteVerbose in this case, since it prints dirs multiple times after filtering/processing.  WriteVerbose should inform on progression steps and WriteDebug provides more details on how state varies.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                NuGetVersion specificVersion;
Don't need to declare specificVersion variable above.
Does Version.TryParse() exist?  If so we should use it.

```csharp
// Try parsing as version
if (NuGetVersion.TryParse(version, out NuGetVersion specificVersion)
{
    ...
}
else if (Version.TryParse(...))
{

}
```

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                    versionRange = VersionRange.Parse(version);
Can this throw?  We should use TryParse if available.  Also what if version is non-null but doesn't parse to a valid version or version range?  Do we ignore, emit a warning, or terminate with error?

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                    dirsToSearch.AddRange(Directory.GetDirectories(modulePath).ToList());
I think we should check to see if the path exists before adding to dirsToSearch, since they are used as-is in later processing and may cause a 'not found' error.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                            if (pkgPath.ToLower().Contains("Scripts"))
I think this is just if the path leaf node is 'scripts', correct?  What if other parts of the path contains the word 'scripts'?  We may have to parse the path here (e.g., use GetFileName() again).  Otherwise instead of ToLower and Contains, you can use `pkgPath.IndexOf('scripts', StringComparison.OrdinalIgnoreCase) > -1` here.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                foreach (var pkgPath in dirsToSearch)
These are not really package paths yet are they?  They are directories in which packages (modules, scripts) may exist in their own sub directories, correct?  Or maybe I missed something above.  Variable names are important for complex code like this, and comments should make steps and expected (path) state clear.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                    dirsToSearch.AddRange(Directory.GetDirectories(modulePath).ToList());
I see now the `GetDirectories` is called so these are actually individual 'package' or 'resource' sub directories.  What if modulePath does not exist, or there is an access denied error?  How are the errors handled?

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +            foreach (string xmlFilePath in flattenedPkgs)
I feel each of these sections should go into their own private methods.  This helps define and clarify the individual processing steps that are performed.

1. Gather search directories
2. Gather individual package or resource directories
3. Filter package or resource directories based on user input
4. Create package object for each found resource directory

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                    ReadOnlyPSMemberInfoCollection<PSPropertyInfo> copyrightInfo;
Weren't we going to create a concrete class for this, instead of creating a PowerShell custom object?  It would make creating the package info object easier and easier to use down the line.

2021-03-16 22:06 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                        nameInfo = deserializedObj.Properties.Match("Name");
Will this throw if the match fails?  If not then we are good, but we don't want to terminate the loop processing for one bad package xml.  Same goes for the Deserialize() method, we may want to try/catch rather than let an obscure error surface.

2021-03-17 20:11 UTC, alerickson commented on src/PSModule.psm1
> -    $script:FrameworkToRemove = 'net472'
Note:  remove targetting net472 (or any .net framework target0

2021-03-17 20:12 UTC, alerickson commented on src/PowerShellGet.psd1
> -    Description       = 'PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, DSC Resources, Role Capabilities and Scripts.'
Remove Role Capabilities

2021-03-17 20:16 UTC, alerickson commented on src/code/GetHelper.cs
> +#if NET472
Yup, remove the #ifdefs

2021-03-17 20:18 UTC, alerickson commented on src/code/GetHelper.cs
> +                cmdletPassedIn.WriteDebug(string.Format("Current user scope path: '{0}'", myDocumentsPath));
We'll think about this and where to use debug vs verbose

2021-03-17 20:24 UTC, alerickson commented on src/code/GetHelper.cs
> +                foreach (var modulePath in modulePaths)
I'll add the type here

2021-03-17 20:27 UTC, alerickson commented on src/code/GetHelper.cs
> +                    dirsToSearch.AddRange(Directory.GetDirectories(modulePath).ToList());
I need to look into error handling here

2021-03-17 20:29 UTC, alerickson commented on src/code/GetHelper.cs
> +                foreach (var modulePath in modulePaths)
Make sure to check if the paths in modulePaths exist before adding it in

2021-03-17 20:34 UTC, alerickson commented on src/code/GetHelper.cs
> +                dirsToSearch = dirsToSearch.FindAll(p => (nameLowerCased.Contains(new DirectoryInfo(p).Name.ToLower())
Add a comment on the functionality here (filtering)

2021-03-17 20:40 UTC, alerickson commented on src/code/GetHelper.cs
> +                    versionRange = VersionRange.Parse(version);
> Also what if version is non-null but doesn't parse to a valid version or version range? Do we ignore, emit a warning, or terminate with error?

This needs to be addressed... I believe this should be throwing a non-terminating error

2021-03-17 20:45 UTC, alerickson commented on src/code/GetHelper.cs
> +                            if (pkgPath.ToLower().Contains("Scripts"))
Create a Util method to figure out if path "is a script" path

2021-03-17 20:49 UTC, alerickson commented on src/code/GetHelper.cs
> +                            // TODO:  check if this xml file exists, if it doesn't check if it exists in a previous version
This still needs to be implemented

2021-03-18 19:24 UTC, alerickson commented on srcOld/code/GetHelper.cs
> +// Copyright (c) Microsoft Corporation. All rights reserved.
Please ignore this file.  There are no changes here and functioning GetHelper code is in src/code/GetHelper.cs

2021-03-29 18:37 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +        Register-PSRepository $TestGalleryName -SourceLocation "https://www.poshtestgallery.com/api/v2"
There's a helper method in PSGetTestUtils.psm1 that returns the PoshTestGallery URL so if you add this to the BeforeAll: `$PoshTestGalleryURL = Get-PoshTestGalleryLocation` then you can use the `$PoshTestGalleryURL` variable for the `-SourceLocation` value.

2021-03-29 18:37 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +        param($Version, $ExpectedVersion)
should be `param($Name, $ExpectedName)` here

2021-03-29 18:37 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +    It "find resource when given Name to <Reason> <Version>" -TestCases @(
remove `<Version>` here as this variable doesn't exist in your hashtables

2021-03-29 18:37 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +        $pkgs.Name | Should -Be "PowerShellGet"
use `$ExpectedName` instead of `"PowerShellGet"` here.

2021-03-29 18:37 UTC, anamnavi commented on test/GetInstalledResource.Tests.ps1
> +}
add newline

2021-03-29 18:37 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        var tokenizedName = n.Split(wildcardDelimiter, StringSplitOptions.RemoveEmptyEntries);
I'll reach out about this offline, but might be better to use wildcardpattern.IsMatch() on names

2021-03-29 18:37 UTC, anamnavi commented on src/code/GetHelper.cs
> +                            if (versionRange != null && xmlFilePath.EndsWith("_InstalledScriptInfo.xml"))
based on L105 are the xml file paths that are used here been converted to lowercase? (Just wondering in case that means EndsWith() condition is never hit.

2021-03-29 18:37 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        {
I agree with WriteError() for not being able to be parse non-mandatory parameters which weren't provided (instead of throwing a terminating error). However, maybe we can have 1 try catch where you try to parse all these optional fields and in the catch it writes a general parsing error. Or have a helper where this deserialized object is being parsed. Just some ideas :)

2021-03-29 18:37 UTC, anamnavi commented on src/code/GetInstalledResource.cs
> +    [Cmdlet(VerbsCommon.Get, "InstalledPSResource", HelpUri = "<add>", RemotingCapability = RemotingCapability.None)]
can remove RemotingCapability

2021-04-06 20:25 UTC, alerickson commented on src/code/GetHelper.cs
> +                    versionRange = VersionRange.Parse(version);
> Can this throw? We should use TryParse if available. 

No, but I've updated this to use TryParse now.

> Also what if version is non-null but doesn't parse to a valid version or version range? Do we ignore, emit a warning, or terminate with error?

Currently it's ignored, but I've updated it to throw a non-terminating error

2021-04-09 16:01 UTC, anamnavi requested changes
Looks great! I think GetHelper.cs is looking more intuitive and easier to follow. I left some questions and comments. I also wanted to ask is there a reason ` srcOld/code/GetHelper.cs ` is included in the PR?

Requesting change because of the typo comment.

2021-04-09 16:01 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        cmdletPassedIn.WriteVerbose(string.Format("Error retrieving directories from '{0}': '{1)'", modulePath, e.Message));
typo in error string, it should be: `{1}`

2021-04-09 16:01 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        wildCardDirsToSearch.AddRange(dirsToSearch.FindAll(p => (new DirectoryInfo(p).Name.ToLower().Equals(n))));
let's try to use wildcardpattern to do <strike>this entire thing</strike> just the `if` condition code...the issue with tokenized names is that it doesn't account for all cases with more than 2 tokens: i.e `pow*rsh*llget`

2021-04-09 16:01 UTC, anamnavi commented on src/code/GetHelper.cs
> +                    versionRange = new VersionRange(specificVersion, true, specificVersion, true, null, null);
do you mean to pass in the same argument (`specificVersion`) to the constructor twice?

2021-04-09 16:01 UTC, anamnavi commented on src/code/GetHelper.cs
> +                            catch (Exception e2)
just to have a better understanding, why are you doing 2 parsings (in 2 try blocks) here?

2021-04-09 16:01 UTC, anamnavi commented on src/code/GetHelper.cs
> +                    if (isCorePS)
not necessary but just an idea: 

instead of the `if (isCorePS)` `else` you could do:
`string powershellType = isCorePS ? "PowerShell" : "WindowsPowerShell"`
and then have just one assignment of myDocumentsPath and programFilesPath here like so:
` myDocumentsPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.MyDocuments), powerShellType);`
` programFilesPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.ProgramFiles), powerShellType);`

instead of separate similar assignments in the if/else. If you feel like it's clearer to have the if/else feel free to keep it as it is :) just an idea.

2021-04-09 16:03 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        wildCardDirsToSearch.AddRange(dirsToSearch.FindAll(p => (new DirectoryInfo(p).Name.ToLower().Equals(n))));
let me write out the code for this suggestion one min

2021-04-09 16:36 UTC, anamnavi commented on src/code/GetHelper.cs
> +                    if (n.Contains("*"))
`WildcardPattern nameWildCardPattern = new WildcardPattern(n, WildcardOptions.IgnoreCase);`
`wildCardDirsToSearch.AddRange(dirsToSearch.FindAll(p => nameWildCardPattern.IsMatch(new DirectoryInfo(p).Name.ToLower())));`

` wildCardDirsToSearch.AddRange(dirsToSearch.FindAll(p => nameWildCardPattern.IsMatch(System.IO.Path.GetFileName(p))));`

2021-04-09 16:40 UTC, anamnavi commented on src/code/GetHelper.cs
> +                        wildCardDirsToSearch.AddRange(dirsToSearch.FindAll(p => (new DirectoryInfo(p).Name.ToLower().Equals(n))));
I put the code above for the `if (name contains *)` condition. so that same wildcard pattern code where I check if each name has a match may not work here in the `else` condition.

I'm not sure why you're calling `ToLower()` on the names...if it was for the tokenized names code and you can use the wildcard pattern code instead remove ToLower() as the wildcard pattern will ignore case if I specify it to. Then over here on L 193 you could remove the `Name.ToLower()` and just do `Name.Equals()`

2021-05-18 16:54 UTC, alerickson commented on src/code/GetHelper.cs
> +                    versionRange = new VersionRange(specificVersion, true, specificVersion, true, null, null);
I never replied to this comment, but this is where we create a version range from an exact version eg: [1.0.0,1.0.0]

2021-05-25 22:54 UTC, PaulHigin requested changes
LGTM, as per our offline review.

However, I see some test failures so please resolve them.
Please resolve any valid Codacy errors.
Also, please close all open conversations.

Then I think we can merge this PR.

2021-05-25 22:54 UTC, PaulHigin commented on src/PSModule.psm1
> +$script:Framework = 'netstandard2.0'
I think we want to standardize on 'net461' framework.  But we can discuss.

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +        private CancellationToken cancellationToken;
Since this is only assigned in the constructor, it can also be 'readonly'.
But this doesn't appear to be used anywhere in this class, but maybe will be?

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +    internal class GetHelper
Nitpick: Maybe named 'GetUtils'?

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +        public IEnumerable<PSResourceInfo> ProcessGetParams(string[] name, VersionRange versionRange, List<string>pathsToSearch)
Name: 'GetPackages'?

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +        public List<string> FilterPkgsByName(string[] names, List<string> dirsToSearch)
Should this be 'private' access or is it used outside the class?
Also maybe this should be called 'FilterPkgPathsByName' since it returns directory paths and not packages.

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                // ./Modules/Test-Module
Are these comments still applicable?  It seems like we are not making a distinction in path type yet...

2021-05-25 22:54 UTC, PaulHigin commented on src/code/GetHelper.cs
> +            List<string> installedPkgsToReturn = new List<string>();  // these are the xmls
// these are the package xml file paths
Name: GetResourceMetadataFilePaths ?

2021-06-08 19:55 UTC, closed without merging