WIP:  Refact Uninstall-PSResource
PowerShell/PSResourceGet pull request #353
Opened 2021-03-23 17:00 UTC by alerickson

# PR Summary
Refactoring the contents of Uninstall-PSResource

TODOs:
- [ ] help
- [ ] completing tests (after install-psresource is complete)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [x] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-03-25 14:19 UTC, anamnavi commented on src/code/UninstallPSResource.cs
>                  if (successfullyUninstalledPkg)
`if (UninstallPkgHelper(pkgName, cancellationToken)) {
  WriteVerbose("Successfully uninstalled " + pkgName);
}
else {
 ...
}`

2021-03-25 14:40 UTC, anamnavi commented on src/code/UninstallPSResource.cs
>              if (!foundResourceObj)
was trying to leave a comment for L186 above where you set foundResourceObj: `var foundResourceObj = foundInMyDocuments || foundInProgramFiles || File.Exists(scriptPathMyDocuments) || File.Exists(scriptPathProgramFiles) ? true : false;`
you could do:
`bool foundResourceObj = (the condition);`

2021-03-25 19:18 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +                if (nugetVersion == null && versionRange == null)
you could nest this under Line 69 above. So:
`if(nugetVersion == null)`
`{`
`     VersionRange.TryParse(Version, out versionRange);`
`     if(versionRange == null) {`
`          ThrowTerminatingError()`
`     }`      
`}`

2021-03-25 19:34 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +                WriteDebug("Could not find the resource: ");
WriteDebug("Could not find the resource: " + pkgName);

2021-03-25 19:49 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +                        throw new System.ArgumentException(string.Format(CultureInfo.InvariantCulture, "Cannot uninstall {0}, the following package(s) take a dependency on this package: {1}.  If you
is this exception wrapped and handled in the caller method? or is it supposed to terminate the cmdlet right here?

2021-03-25 19:57 UTC, anamnavi commented on src/code/UninstallPSResource.cs
left a similar comment above, but is this a wrapped exception handled by the caller or do we expect the cmdlet to terminate over here? Perhaps in `ProcessRecord() we add a try/catch around when this method or (`UninstallModuleHelper()`) gets called.

2021-03-25 20:01 UTC, anamnavi commented on test/UninstallPSResource.ps1
> +        $pkg = Uninstall-PSResource -Name Benchpress, bogreader
Fine to use production modules for now, but at some point we may need to use our own test modules that we get from the Gallery, install and then uninstall.

2021-03-25 20:02 UTC, anamnavi commented on test/UninstallPSResource.ps1
> +}
nitpick, add new line

2021-03-25 20:05 UTC, anamnavi reviewed
this PR just showed changes, so some of the pre-existing code was hard to comment on because Github just wouldn't let me add a comment there. So I'm going to make them here:
- add license info at start of file
- remove RemotingCapability tag on Cmdlet (Line 22)
- as for error handling, it appears that UninstallScriptHelper() and UninstallModuleHelper() throw errors so we could add try/catch around when they get called in ProcessRecord()

2021-03-30 16:36 UTC, PaulHigin requested changes

2021-03-30 16:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                NuGetVersion.TryParse(Version, out nugetVersion);
Just curious, does `NuGetVersion.TryParse` return false or do you always have to check the result to be null?  It seems like `TryParse` should return false if it is unable to parse the string as a NuGetVersion, and you can skip the null check.
Same question for `VersionRange.TryParse`.

Also I believe this is used in other cmdlets so there can be a static helper method in the Utils class to parse a version string.

2021-03-30 16:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var isXPlatformPS = this.Host.Version.Major.CompareTo("6") > 1 ? true : false;
Don't need ternary operation here, and I feel this is more readable:
```csharp
private static psVersion6 = new Version(6, 0);
var isWindowsPS = Host.Version < psVersion6;
```

Note that we normally leave off `this.`
```

2021-03-30 19:06 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +    /// Uninstall
Add summary

2021-03-30 19:06 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +using NuGet.Versioning;
move this below 'System' assemblies

2021-03-30 23:19 UTC, PaulHigin requested changes

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var isXPlatformPS = this.Host.Version.Major.CompareTo("6") > 1 ? true : false;
This can be simplified to

```csharp
private static PSVersion6 = new Version (6, 0);
var isCorePS = Host.Version >= PSVersion6;
```

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                using (System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create())
It is not clear what this does, and `results` does not appear to be used.  Can you add a comment or remove if not needed?
Also, since this is a cmdlet, you can use `InvokeCommand.InvokeScript` to run script in the cmdlet context, instead of creating a new PowerShell/Runspace.

E.g.,
https://github.com/PowerShell/SecretManagement/blob/b1fbbd0e7f4c0e035e7a2d495472f8a2790fe04d/src/code/SecretManagement.cs#L195

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +        private string programFilesPath;
Non static class fields naming convention is to have a preceding underscore character.
```csharp
private string _programfilesPath;
private string _myDocumentsPath;
...
```

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            foreach (var pkgName in Name)
This is really the only code you need in the `ProcessRecord()` block since the `Name` property values can come from the pipeline.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +        private bool UninstallPkgHelper(string pkgName, CancellationToken cancellationToken)
Since `cancellationToken` is a class field, it does not need to be passed into the method.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +        /// Just uninstall module, not dependencies
'Installs a single resource`

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            dirsToDelete = new List<string>();
`dirsToDelete` should not be a class field or instantiated here.  It is only used in the `UninstallModuleHelper` method and so should be scoped to there only.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var successfullyUninstalledPkg = false;
```csharp
var dirsToDelete = new List<string>();
```

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                    WriteVerbose("Did not successfully uninstall " + pkgName);
We should write a non-terminating error for each package that was not successfully uninstalled.  WriteVerbose should continue to list each packages that was successfully installed.

Also we should include the package path (if available) along with the package name that was uninstalled.  It would probably be better to write the error/verbose message closer to where the uninstall operation occurs, or pass back error/success messages with more information.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var versionDirsMyDocuments = (Directory.Exists(dirNameMyDocuments)) ? Directory.GetDirectories(dirNameMyDocuments) : null;
Existence of `dirNameMyDocuments` path should be checked only once.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var parentDirFilesMyDocuments = (Directory.Exists(dirNameMyDocuments)) ? Directory.GetFiles(dirNameMyDocuments) : null;
`parentDirFilesMyDocuments` path appears to be identical to `versionDirsMyDocuments` path.  Please add comment with examples to help clarify the difference between the two paths.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (Directory.Exists(psModulesPathMyDocuments))
We should check for directory existence just once and do all relevant processing at the same time (including the versionDirsProgramFiles, etc. from above).

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (Directory.Exists(psScriptPathMyDocuments))
Does order matter?  If a module appears in both directories, do we uninstall both?

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                WriteDebug("Could not find the resource: ");
We should write a 'not found' non-terminating error.  We should differentiate between package not found and package not successfully uninstalled.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var foundInMyDocuments = (Directory.Exists(dirNameMyDocuments) && (versionDirsMyDocuments.Any() || parentDirFilesMyDocuments.Any())) || File.Exists(scriptPathMyDocuments); // check for sc
Don't need to check for dir existence again, can just check `versionDirsMyDocuments` and `parentDirFilesMyDocuments` for null and empty.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                psScriptsPathAllFiles.AddRange(Directory.GetFiles(psModulesPathMyDocuments).ToList());
`psScriptsPathAllFiles` does not appear to be used anywhere.

2021-03-30 23:19 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var foundResourceObj = foundInMyDocuments || foundInProgramFiles || File.Exists(scriptPathMyDocuments)
Redundant `scriptPathMyDocuments` existence check.

2021-03-31 17:16 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +                using (System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create())
TODO:
- Create a method in util class.  
- Add comments
- Get rid of pwsh creation (consider using invoke script if use is necessary)

2021-03-31 17:17 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            foreach (var pkgName in Name)
Add previous code into BeginProcessing

2021-03-31 17:19 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +                    WriteVerbose("Did not successfully uninstall " + pkgName);
Consider adding pkg path to both success and failed paths.

2021-03-31 17:30 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            var parentDirFilesMyDocuments = (Directory.Exists(dirNameMyDocuments)) ? Directory.GetFiles(dirNameMyDocuments) : null;
Put in some examples to clarify, what you expect to see and what you expect it to look like

2021-04-01 16:15 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (Directory.Exists(psModulesPathMyDocuments))
Add comments, particularly for sections

2021-04-01 16:18 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (Directory.Exists(psScriptPathMyDocuments))
Check this and add comments for how ordering occurs.

2021-04-01 16:19 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +                psScriptsPathAllFiles.AddRange(Directory.GetFiles(psModulesPathMyDocuments).ToList());
Remove this section

2021-04-01 16:22 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            var successfullyUninstalledPkg = false;
This where dirsToDelete should be moved to

2021-04-08 23:13 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +                using (System.Management.Automation.PowerShell pwsh = System.Management.Automation.PowerShell.Create())
Results was being used to figure out if a user was running as a superuser, I'll remove this since it's a relic from when the code was checking for elevated privileges.

2021-04-09 05:48 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            var parentDirFilesMyDocuments = (Directory.Exists(dirNameMyDocuments)) ? Directory.GetFiles(dirNameMyDocuments) : null;
It looks like `parentDirFilesMyDocuments` is not used anywhere anymore so I'm completely removing it

2021-04-09 18:08 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +                if (isCorePS)
I left the same optional suggestion in Get-InstalledPSResource...

not necessary but just an idea:

instead of the if (isCorePS) else you could do:
string powershellType = isCorePS ? "PowerShell" : "WindowsPowerShell"
and then have just one assignment of myDocumentsPath and programFilesPath here like so:
myDocumentsPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.MyDocuments), powerShellType);
programFilesPath = Path.Combine(Environment.GetFolderPath(SpecialFolder.ProgramFiles), powerShellType);

instead of separate similar assignments in the if/else. If you feel like it's clearer to have the if/else feel free to keep it as it is :) just an idea.

2021-04-09 18:08 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +            var successfullyUninstalled = false;
could do `bool successfullyUninstalled;` for default initialization

2021-04-09 18:08 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +            if (String.IsNullOrWhiteSpace(pkgName))
I thought `Name` parameter could not be null or empty. If there's an array of names provided for `Name` parameter and one of the elements in that array is null or whitespace I think we should write an error with a specific "could not uninstall pkg - null name not allowed"?

For this, you do one of two things:
1) perhaps UninstallPkgHelper() could take a `out string[] errorMsgs` parameter and then in ProcessRecord() where you check if UninstallPkgHelper() returned false you could print any additional error messages.

2) before you return from UninstallPkgHelper() on L111 you could write the specific error message there "Name provided is null or whitespace". So overall there would be 2 error messages printing (one in UninstallPkgHelper() and one in ProcessRecord()).

2021-04-09 18:08 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +            bool foundInMyDocuments = false;
for these variables of type bool you can just use the default initialization. So `bool foundInMyDocuments;`

2021-04-22 22:07 UTC, PaulHigin requested changes

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +
Please remove unneeded whitespace and 'RemotingCapability'.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +        [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true, ParameterSetName = "NameParameterSet")]
Currently we only have one parameter set 'NameParameterSet', but eventually will have another that takes 'PSResource' objects in the pipeline, correct?  We should go ahead and add the other parameter set.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +
Please add `#region` sections for fields and PSCmdlet method overrides.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            Utils.TryParseVersionOrVersionRange(Version, out NuGetVersion _nugetVersion, out VersionRange _versionRange, this);
This utility method should not throw, since it returns a success boolean.  It is better to throw at this higher cmdlet level where it has more context to provide a good error message.  

```csharp
if (! Utils.TryParseVersionOrVersionRange(..., out string errorMsg))
{
    ThrowTerminatingError(new PSArgumentException('Unable to parse Version parameter with error: {0}, errorMsg));
}

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                    WriteVerbose("Did not successfully uninstall " + pkgName);
This is an error, since the user asked that a specific package be uninstalled, and that operation failed.  But it is not a command terminating error, so we just write the error and continue.  But the error message should also contain the reason that the operation failed (invalid filepath, access denied, corrupted package info, ...):
```csharp
if (!UninstallPackage(pkgName, out string errorMsg))
{
    WriteError(string.Format("Did not successfully uninstall package {0}, with error: {1}", pkgName, errorMsg);
}
```

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var successfullyUninstalled = false;
I think local variables have to be explicitly initialized (?)

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (String.IsNullOrWhiteSpace(pkgName))
Agreed. At this level `pkgname` should be assumed to be valid (not null or whitespace), since it is private access method that we control.  However, this is a good example where assert can be used to validate the implied contract.
```csharp
System.Diagnostics.Debug.Assert(!String.IsNullOrWhiteSpace(pgkName), "pkgName cannot be null or empty.");
```

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            var psModulesPathMyDocuments = Path.Combine(_myDocumentsPath, "Modules");
It looks like these paths never change and so they can be created just once in 'BeginProcessing()' block, and these variables can be class fields.  The `_myDocumentsPath`, etc don't need to be fields.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +
Please remove extra whitespace.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            // Program Files
Please add line here and make comments consistent.

2021-04-22 22:07 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                psModulesPathAllDirs.AddRange(Directory.GetDirectories(psModulesPathMyDocuments).ToList());
.ToList() is not needed here.

2021-04-23 17:52 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +        [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true, ParameterSetName = "NameParameterSet")]
Yes, that should be added as well.

2021-04-23 17:55 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +                    WriteVerbose("Did not successfully uninstall " + pkgName);
I think the intent early on was to fail quietly because to my understanding that's the philosophy PS generally takes.  V2 does not throw an error if uninstall was unsuccessful so I'm apprehensive about adding this.  I think this would be a good thing to discuss though.

2021-04-23 17:55 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            var successfullyUninstalled = false;
I believe so too, but I'll double check.

2021-04-23 18:36 UTC, PaulHigin requested changes

2021-04-23 18:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            bool foundResourceObj = foundInMyDocuments || foundInProgramFiles;
Variable not needed since it is just used below.

```csharp
if (!foundInMyDocuments && !foundInProgramFiles)
{
    WriteError ...
}
```

2021-04-23 18:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +
Please remove extra white space.

2021-04-23 18:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (!isScript)
Why is it important to know if the resource is script or not here?  Same as to whether the resource was found in 'MyDocuments' or 'ProgramFiles'.  I think this section can be simplified to just collecting a list of paths to uninstall that match the package Name match.  The helper function can then examine each resource path and figure out how to uninstall it (whether it includes version path or is script).

2021-04-23 18:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (_versionRange != null)
I wonder if we can move the version range check up to the calling function.  The calling function determines which resource directories match the name and version range and creates a list of them, and this helper function then just needs to figure out how to uninstall each resource path in the list.

2021-04-23 18:36 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            // if dirsToDelete is empty, meaning we didn't find any modules, it's possible it's a script
Please add comments that illustrate what kinds of resource paths are expected and how they look and all variations that need to be accommodated.  Something like:
```csharp
// Expected resource paths to uninstall:
//    c:\users\user\documents\modules\MyModule1\1.0.0
//    c:\users\user\documents\modules\MyModule1\1.1.0
//    c:\users\user\documents\modules\MyModule1\1.2.0
//    c:\Program Files\PowerShell\Modules\MyModule2\2.0.0
//    c:\Program Files\PowerShell\Scripts\MyScript1
```

2021-04-23 18:40 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (String.IsNullOrWhiteSpace(pkgName))
I also agree that this needs to be addressed some how.   I think addressing validation of the package name earlier on makes much more sense and that creating writing a debug statement would be a clear way of relaying that information while still continuing to uninstall the rest of the packages

2021-04-23 19:05 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (_versionRange != null)
That makes sense to me, I think that's feasible.

2021-04-23 19:16 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (!isScript)
Just took a look at that and I think it's possible to refactor and get rid of those variables.  The latter variables I believe are relics from when there was a check for elevated privileges.  I think what you're suggesting would work and certainly makes sense.

2021-04-23 21:39 UTC, alerickson commented on src/code/UninstallPSResource.cs
> +            if (_versionRange != null)
Consider moving to begin processing

2021-04-29 03:47 UTC, anamnavi commented on src/code/Utils.cs
> +            return successfullyParsed;
I think you need a closing bracket `}` after this line?

2021-05-25 22:48 UTC, PaulHigin approved these changes
LGTM

Please resolve all open conversations.

Also please look at Codacy issues (some may not apply):
https://app.codacy.com/gh/PowerShell/PowerShellGet/pullRequest?prid=7144195

After that I feel we can merge these changes.

2021-05-27 14:51 UTC, anamnavi approved these changes
LGTM. Just one question..

What's the difference between `test/UninstallPSResource.ps1 ` and `test/UninstallPSResource.Tests.ps1 `? (The latter follows our test file naming convention, should we remove the first from this PR?)

2021-06-04 21:08 UTC, merged