Refactor setpsresourcerepository
PowerShell/PSResourceGet pull request #359
Opened 2021-04-13 22:39 UTC by anamnavi

This PR includes refactoring for Set-PSResourceRepository cmdlet. This cmdlet updates repository info, so I also had to update code in the Update() method in RepositorySettings.cs. I also included a `-PassThru` parameter for this cmdlet, and the output is of type PSRepositoryInfo class (which was created in a previous PR).

# PR Summary
summary of changes included in this PR:
- refactored Set-PSResourceRepository.cs
- refactored Update() API in RepositorySettings.cs
- created tests in SetPSResourceRepository.Tests.ps1

still need to do:
- update help doc for Set
- I think I can get rid of the NameParameterSetHelper() method in Set-PSResourceRepository.cs as it just calls UpdateRepositoryStoreHelper() (I can't think of any NameParameterSet specific checks that need to happen)

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-04-13 22:40 UTC, anamnavi commented
I think I can get rid of the NameParameterSetHelper() method in Set-PSResourceRepository.cs as it just calls UpdateRepositoryStoreHelper() (I can't think of any NameParameterSet specific checks that need to happen)

2021-04-15 18:15 UTC, anamnavi commented
not sure how to implement the Credential parameter to be honest

2021-04-15 19:07 UTC, alerickson commented
@anamnavi I think the credential param should be completely removed.  If we need it later on with the integration of credential persistence we can add it back then, but there's currently no need for it.

2021-04-15 22:24 UTC, alerickson requested changes

2021-04-15 22:24 UTC, alerickson commented on help/Set-PSResourceRepository.md
> +Set-PSResourceRepository -Repositories <Hashtable[]> [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-Priority <Int32>] [-WhatIf] [-Confirm] [<CommonParameters>]
I don't believe -Proxy or -ProxyCredential are needed for this cmdlet

2021-04-15 22:24 UTC, alerickson commented on help/Set-PSResourceRepository.md
>  ### -Proxy
Again, I think we should remove -Proxy and -ProxyCredential

2021-04-15 22:24 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +using Dbg = System.Diagnostics.Debug;
nit to have the using directives in alphabetical order (with System first)

2021-04-15 22:24 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +        public PSCredential Credential { get; set; }
Again, I think we can remove this because we're not actually pinging an endpoint to make sure that access is available.

2021-04-15 22:24 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +            repoName = repoName.Trim(' ');
Just a nit, but you can simply use .Trim() if you're only trimming whitespace

2021-04-16 20:49 UTC, anamnavi commented
I copied the `ValueFromPipelineByPropertyName` tag in `[Parameter]` for all the parameters. I notice we allowed `Name`, `URL`, `Repositories`, `Priority` parameters to be passed in as pipeline input...but 

1) does it make sense for all these parameters? I'm honestly not sure how we decide which parameters we should allow to pass in via pipeline input 

2) if we allow `Priority` to be passed in shouldn't we also allow `Trusted` to be passed in via the pipeline?

2021-04-19 20:21 UTC, anamnavi commented
For Set: allow by pipeline just Name, and REpositories. For Register, ok as is.

2021-06-07 16:42 UTC, alerickson approved these changes

2021-06-07 16:45 UTC, PaulHigin approved these changes

2021-06-07 16:45 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +        public static PSRepositoryInfo Update(string repoName, Uri repoURL, int repoPriority, bool? repoTrusted)
Please update comment (// Returns: void)

2021-06-07 16:45 UTC, PaulHigin commented on src/code/RepositorySettings.cs
>                  // Get root of XDocument (XElement)
On line 129, error is not ArgumentException, the argument is valid.  Should be ItemNotFoundException error.

2021-06-07 16:46 UTC, merged