WIP: Refactor Find-PSResource cmdlet
PowerShell/PSResourceGet pull request #363
Opened 2021-04-24 02:55 UTC by anamnavi

This PR includes refactoring for the Find-PSResource cmdlet. This cmdlet searches for requested packages. **Note**: At the moment this PR just includes barebone functionality (package with specified Name can be searched for and the latest package version will be returned, but additional filtering by other parameters will be added soon in this PR).

# PR Summary

Summary for this PR:
- refactored Find-PSResource.cs
- will create tests in this PR
- will update help doc for this cmdlet in this PR.
## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-05-12 20:23 UTC, PaulHigin requested changes

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +            if (Version != null)
You could have an early out here, and there would be less indentation afterward (easier to read).
```csharp
if (Version == null) { return successfullyParsed; }
```

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +                    successfullyParsed = true;
Same here, could early out.

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +using NuGet.Versioning;
using statements should be ordered alphabetically.

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +        public static bool TryParseVersionOrVersionRange(string Version, out VersionRange versionRange, out bool allVersions, PSCmdlet cmdletPassedIn)
`string Version` parameter name should be lower case.  Also `cmdletPassedIn` is not used.

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +                        versionRange = new VersionRange(nugetVersion, true, nugetVersion, true, null, null);
For long complex function parameters, it is good to use named parameters for readability.

2021-05-12 20:23 UTC, PaulHigin commented on src/code/Utils.cs
> +
Please consider something of this form:
```csharp
        public static bool TryParseVersionRange(
            string version,
            out VersionRange versionRange,
            out bool allVersions)
        {
            versionRange = null;
            allVersions = false;

            if (version == null) { return false; }

            if (version.Trim().Equals("*"))
            {
                allVersions = true;
                return true;
            }

            // Try to parse as NuGetVersion
            if (NugetVersion.TryParse(version, out NuGetVersion nugetVersion))
            {
                versionRange = new VersionRange(
                    minVersion: nugetVersion,
                    includeMinVersion: true,
                    maxVersion: nugetVersion,
                    includeMaxVersion: true,
                    floatRange: null,
                    originalString: null);
                return true;
            }

            // Try to parse as a Version range
            return VersionRange.TryParse(version, out versionRange);
        }
```

2021-05-12 21:06 UTC, PaulHigin requested changes

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +        public static bool TryParse(
We normally don't use 'TryParse' here since metadata should always be readable, and 'ConvertFromMetadata' is probably better, or maybe 'TryConvert'.  We may even want a class constructor that takes a metadata argument.

I feel this method should simply convert metadata into a PSResourceInfo object.  If some properties are missing then they are just set to null or empty string.  We can let higher level layers decide if required information is missing or not.

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            if (metadataToParse == null)
In this case, we may want to consider throwing an exception here instead of returning a boolean.  We just want to convert from one form to another and we expect the operation to succeed except for null argument.

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +                NuspecReader pkgNuspec = objToParse.GetNuspecAsync().GetAwaiter().GetResult();
I guess I don't understand how the package metadata is structured.  Some properties are directly from the catalog entry, and others seem to require a second retrieval of a nuspec part.  Please include comments to illustrate and clarify.

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            if (pkg.Identity != null)
```csharp
return pkg.Identity?.Id ?? string.Empty;
```

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            char[] delimeter = new char[]{' ', ','};
This should be static, so an allocation isn't performed each method call.

2021-05-12 21:06 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +                if(String.Equals(tag, "PSScript", StringComparison.OrdinalIgnoreCase))
Maybe have an internal enum instead of string?

2021-06-16 16:13 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +        public static bool TryParse(
has changed since, but I renamed the TryParse method to TryConvert

2021-06-21 14:39 UTC, anamnavi commented on src/code/PSResourceInfo.cs
> +                NuspecReader pkgNuspec = objToParse.GetNuspecAsync().GetAwaiter().GetResult();
this is no longer happening, I was using this to get information on the package for a CatalogEntry object (which we are no longer using).

2021-06-21 22:41 UTC, PaulHigin approved these changes
LGTM

2021-06-21 23:09 UTC, alerickson approved these changes

2021-06-21 23:11 UTC, merged