Update cmdlet
PowerShell/PSResourceGet pull request #407
Opened 2021-07-08 15:53 UTC by anamnavi

# PR Summary

Refactor Update-PSResource cmdlet.

- [ ] refactored Update-PSResource code
- [ ] added tests
- [ ] updated design and help docs
- [ ] I have pulled in Install changes so far

## PR Context

Part of PSGet V3 refactoring prior to prerelease.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-07-20 18:57 UTC, PaulHigin requested changes

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +    /// The Save-PSResource cmdlet combines the Save-Module, Save-Script cmdlets from V2.
Please update for Update-PSResource.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        HelpUri = "<add>")]
Please remove HelpUri.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +    public sealed
This usually goes on one line.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +    [OutputType(typeof(PSResourceInfo))]
Remove output?

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        private const string InputObjectParameterSet = "InputObjectParameterSet";
Please remove as it is unused.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        private CancellationToken _cancellationToken;
Please remove as field, if not used.  Local variable?

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        protected override void StopProcessing()
After our discussion, let's remove stop processing as it would be too disruptive.
Also look at doing this for Install-PSResource.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +                cancellationToken: _cancellationToken,
Please look into removing this parameter from InstallHelper, since we will not be supporting interruption.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        [ValidateNotNullOrEmpty]
Don't need [ValidateNotNullOrEmpty] for enum types.
Also please remove 'None' Scope type, and make 'CurrentUser' default.  (Also for Install-PSResource).

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        public object[] InputObject { get; set; }
Remove InputObject (along with InputObjectParameterSet).

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            Name = Utils.FilterWildcards(Name, out string[] errorMsgs, out bool isContainWildcard);
Utils.ProcessNameWildcards ?

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            if (Name.Length == 0)
Please move check up one.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            if (Version !=null && !Utils.TryParseVersionOrVersionRange(Version, out versionRange))
Please check if Utils.TryParseVersionOrVersionRange behavior is same for all uses, and if so if version check (version == null -> versionRange.All), and if so do null check within the utils method.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            VersionRange versionRange = new VersionRange();
Don't need this declaration (can do within out variable during parse).

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            if (isContainWildcard)
'nameContainsWildcard'

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +                Name = getHelper.FilterPkgPaths(
Might consider putting this work into a private 'ProcessNames' method that returns usable name array.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            switch (ParameterSetName)
Please remove after removing unneeded InputObject parameter set.

2021-07-20 18:57 UTC, PaulHigin commented on src/code/Utils.cs
> +        }
Please add white space.

2021-07-20 18:57 UTC, PaulHigin commented on test/UpdatePSResource.Tests.ps1
> +    It "update resource under CurrentUser scope" {
Please use:
```powershell
It "update resource under CurrentUser scope" -skip:(!$IsWindows) {
```

2021-07-27 16:37 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Windows only
I added some Linux tests to install... maybe add similar tests here as well

2021-07-27 16:38 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # update script resource
- [ ] 
```suggestion

```

2021-07-27 16:38 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Name
```suggestion
```

2021-07-27 16:38 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Version
```suggestion
```

2021-07-27 16:39 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +}
```suggestion
}

```

2021-07-27 16:39 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +
```suggestion
```

2021-07-27 16:39 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # InputObject
```suggestion
```

2021-07-27 16:39 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Credential
```suggestion
```

2021-07-27 16:39 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Prerelease
```suggestion
```

2021-07-27 16:40 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # Scope
```suggestion
```

2021-07-27 16:40 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # AcceptLicense
```suggestion
```

2021-07-27 16:40 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # TrustRepository
```suggestion
```

2021-07-27 16:41 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +
```suggestion
```

2021-07-27 16:41 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +
```suggestion
```

2021-07-27 16:42 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # TODO: ask Amber if we can publish another version to TestModuleWithLicense
Is this still needed?  I can publish if so

2021-07-27 16:43 UTC, alerickson approved these changes
I'll put in a PR to get the cancellation token out of Install, but looks good to me

2021-07-28 21:39 UTC, anamnavi commented on test/UpdatePSResource.Tests.ps1
> +    # TODO: ask Amber if we can publish another version to TestModuleWithLicense
yes please, if you can publish another version that would be great, thanks!

2021-07-28 22:12 UTC, anamnavi commented on test/UpdatePSResource.Tests.ps1
> +    # Windows only
just added. The AllUsers scope one fails on Linux unless run with sudo

2021-07-29 00:43 UTC, alerickson commented on test/UpdatePSResource.Tests.ps1
> +    # TODO: ask Amber if we can publish another version to TestModuleWithLicense
Just published a new version (0.0.3)

2021-07-29 15:45 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +        private CancellationToken _cancellationToken;
removed

2021-07-29 15:45 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +                cancellationToken: _cancellationToken,
removed.

2021-07-29 15:46 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +            if (Version !=null && !Utils.TryParseVersionOrVersionRange(Version, out versionRange))
I will do this in a later PR so as to ensure all cmdlets relying on this don't have their tests break

2021-07-29 16:48 UTC, PaulHigin requested changes

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        [Parameter(Position = 0, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true, ParameterSetName = NameParameterSet)]
Do we ever plan on adding another parameter set?  If not then we don't need the 'NameParameterSet' and can just remove the 'ParameterSetName' attribute parameter.  But this is not a blocking issue.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +        private string[] ProcessNames(string[] namesToProcess, VersionRange versionRange)
Not blocking: We usually separate private methods and override methods into separate regions.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            {
This seems wrong.  This private method works on 'namesToProcess' parameter argument, not 'Name' property.  It is not clear why it would be affected by above wild card name processing.  It should not assume some connection between the two.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +                WriteVerbose("Name was detected to be (or contain an element equal to): '*', so all packages will be updated");
It seems strange to have a special condition just to write a verbose message here.  It seems like this verbose message should be emitted later (after line 176):

```csharp
Name = ProcessNames(Name);
if () { WriteVerbose() }
```

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +
Please remove white space.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +                WriteVerbose("ShouldProcess was set to false.");
This WriteVerbose statement seems unnecessary.  It is not something the user needs to be reminded of.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/UpdatePSResource.cs
> +            Name = ProcessNames(Name, versionRange);
Since the 'Name' field is not used elsewhere after this (like in another part of the cmdlet class), it is better to assign local variable here.

```csharp
var namesToUpdate = ProcessNames(Name, versionRange);
...
installHelper.InstallPackages(
names: namesToUpdate,
...
)
```

2021-07-29 16:48 UTC, PaulHigin commented on src/code/Utils.cs
> +                        errorMsgsList.Add(String.Format("-Name with wildcards '?' and '[' are not supported for Find-PSResource so Name entry: {0} will be discarded.", name));
This error message is specific to 'Find-PSResource', but I assume this is a general utility function?  So maybe say '... not supported for this cmdlet ...'.

2021-07-29 16:48 UTC, PaulHigin commented on src/code/Utils.cs
> +                        errorMsgsList.Add(String.Format("-Name with wildcards '?' and '[' are not supported for Find-PSResource so Name entry: {0} will be discarded.", name));
Also, please add 'continue;' after this message, and remove else:

```csharp
foreach ()
{
    ...
    if (WildcardPattern.Contains())
    {
        ...
        if (name.Contains("?") ...)
        {
            errorMsgList.Add();
            continue;
        }

        isContainWildCard = true;
    }

    namesWithSupportedWildcards.Add(name);
}
```

2021-07-29 16:48 UTC, PaulHigin commented on src/code/Utils.cs
> +        public static string[] ProcessNameWildcards(
Please add comment block, something like:
```csharp
/// <Summary>
/// This method checks all provided package names for wild card characters and removes any name containing invalid characters.
/// If any name contains a single '*' wildcard character then it is returned alone, indicating all packages should be processed.
/// </Summary>
```

2021-07-29 16:48 UTC, PaulHigin commented on src/code/Utils.cs
> +        public static string[] ProcessNameWildcards(
Also 'ProcessPackageNames' or 'ProcessPackageNameWildCards' might be more descriptive message name.

2021-07-29 17:08 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +            {
this was a typo from when I refactored it into a helper method, thanks for catching this

2021-07-29 18:05 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +                WriteVerbose("Name was detected to be (or contain an element equal to): '*', so all packages will be updated");
left as is

2021-07-29 18:06 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +                WriteVerbose("ShouldProcess was set to false.");
changed verbose statement

2021-07-29 18:33 UTC, PaulHigin approved these changes
LGTM

2021-07-29 19:17 UTC, merged