Install refactor
PowerShell/PSResourceGet pull request #408
Opened 2021-07-08 16:33 UTC by alerickson

# PR Summary
This is a refactor of the Install-PSResource cmdlet.  

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-07-08 23:30 UTC, PaulHigin requested changes

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +using Microsoft.PowerShell.PowerShellGet.UtilClasses;
Please add copyright info here.

2021-07-08 23:30 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +using System.Reflection;
Please ensure the copyright comment info is at the top of the file.

2021-07-08 23:30 UTC, PaulHigin commented on azure-pipelines-2.yml
> +# The name of the build that will be seen in mscodehub
Please remove this file from the PR.

2021-07-08 23:30 UTC, PaulHigin commented on azure-pipelines-1.yml
> +# The name of the build that will be seen in mscodehub
Please remove this file from the PR.

2021-07-08 23:30 UTC, PaulHigin commented on azure-pipelines.yml
> +# The name of the build that will be seen in mscodehub
Please remove this file from the PR.

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            this.cancellationToken = cancellationToken;
It looks like this field is not used and can be removed.

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            this.cmdletPassedIn = cmdletPassedIn;
Field names should begin with underscore character.

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private readonly bool update;
Recommend name: `_updatePackage`.
Also this field is not currently used, but I assume will be?

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private readonly bool save;
Recommend name: `_savePackage`.

2021-07-08 23:30 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        public void ProcessInstallParams(
Recommend name: `InstallPackages`

2021-07-09 17:20 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +                    else if (InputObject[0].GetType().Name.Equals("PSModuleInfo"))
how does this condition differ from that of the `if` statement above?

2021-07-09 17:23 UTC, PaulHigin requested changes

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            IEnumerable<PSResourceInfo> pkgsAlreadyInstalled = new List<PSResourceInfo>();
This unused variable can be removed.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                if (sourceTrusted || yesToAll)
Could to early out here:
```c#
if (!sourceTrusted && !yesToAll)
{
    Write-Verbose("Skipping untrusted repository 'A'");
    return;
}
```
```

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    var isLocalRepo = repo.Url.AbsoluteUri.StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter);
```suggestion
                    var isLocalRepo = repo.Url.AbsoluteUri.StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter, StringComparison.OrdinalIgnoreCase);

```

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    // Deduplicate any packages
I feel that `findHelper.FindByResourceName()` should never return duplicate packages.  Unless there is a scenario where we would want duplicate packages returned (?), in which case I think `FindByResourceName` should take a parameter argument to optionally return only unique results.

This also sorts in name/version order, but shouldn't we expect `FindByResourceName` to already do this?

Please add comments to indicate the expected form of the package list:
```c#
// PacakgeA Version 1.5
// PackageA Version 1.2
// PackageA Version 1.0
// PackageB Version 1.0
```

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    // Make sure only the latest version of a module gets installed
Comment should indicate expected order of returned packages (as shown in my comment above), and this comment should clarify that this code is selecting the first of each package name group, which is guaranteed to be the latest version.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    if (!pkgsFromRepoToInstall.Any()) continue;
Style guidelines, we should always use statement brackets.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        if (packagesToInstall.Contains(name))
We don't need this check to see if the list contains an item here.  `packagesToInstall.Remove()` just returns a boolean and doesn't throw if item to remove does not exist.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            _pathsToSearch = new List<string>();
`_pathsToSearch` should just be a local variable and not a field variable, since it is only used in this local scope.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            foreach (var path in _pathsToInstallPkg)
```c#
// _pathsToSearch will contain all resource package subdirectories within _pathsToInstallPkg path locations
// e.g.
// ./InstallPackagePath1/PackageA
// ./InstallPackagePath1/PackageB
// ./InstallPackagePath2/PackageC
// ./InstallPackagePath3/PackageD
```

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        cmdletPassedIn.WriteDebug("Error parsing version into a NuGetVersion");
I assume we cannot continue processing the package and need to go to the next in the list.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        else
Don't need else block here since if block uses continue.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        // Set up NuGet API resource for download
Please add comment here that makes it clear this section is for downloading from non-local repository.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            /*
Why is this commented out?  We should try to not check in any code with commented out sections.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    if (_includeXML) CreateMetadataXMLFile(tempDirNameVersion, installPath, repoName, p, isScript);
Style guidelines, we should always use statement blocks with brackets.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    if (save)
How is this save different from above _asnupkg save?  If it is just the form in which it is saved, then the save should always be done using this field (should be named `_save`) and `_asnupkg` is used to save in the correct form.  A separate helper function may be good for this.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        //TODO:  SavePackage
It would be great to include this functionality in this PR submission, for completeness.

2021-07-09 17:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +           // j = 1;
Please remove commented out code.  If progress bar support is not ready, we can just add a TODO: comment, and implement later.

2021-07-09 17:26 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +        // todo: add tab completion (look at get-psresourcerepository at the name parameter)
`[ArgumentCompleter(typeof(RepositoryNameCompleter))]` this would be the line of code to do so

2021-07-09 18:10 UTC, PaulHigin requested changes

2021-07-09 18:10 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +                // can be an array or hashtable
In what cases is the dependency info object an array?  Please clarify comment about what kind of array and when this occurs, and what form the information is organized.

2021-07-09 18:10 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            return pkg.Identity.Version.IsPrerelease;
```suggestion
            return pkg.Identity?.Version?.IsPrerelease ?? false;
```

2021-07-09 18:10 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            if (AdditionalMetadata != null)
In what cases is this null?  Please clarify.

2021-07-09 18:17 UTC, PaulHigin requested changes

2021-07-09 18:17 UTC, PaulHigin commented on src/code/PowerShellGet.csproj
> +    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
Why is this needed?

2021-07-09 18:17 UTC, PaulHigin commented on src/code/PowerShellGet.csproj
> +    <LangVersion>7.2</LangVersion>
Language == 8.0 ?

2021-07-09 18:17 UTC, PaulHigin commented on src/code/InstallPkgParams.cs
> +public class PkgParams
What is this for?  It doesn't seem to be used anywhere.

2021-07-09 18:20 UTC, anamnavi requested changes
looks good, just some nitpicks and questions :)

2021-07-09 18:20 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +        // todo: add tab completion (look at get-psresourcerepository at the name parameter)
[ArgumentCompleter(typeof(RepositoryNameCompleter))]

2021-07-09 18:20 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +                    else if (InputObject[0].GetType().Name.Equals("PSModuleInfo"))
how does this condition differ from that of the if statement above? The code in the if block and else if block look different so perhaps you meant to have a different condition for one?

2021-07-09 18:20 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +}
add newline (at end of all files). I'll just make the comment here though :)

2021-07-09 18:20 UTC, anamnavi commented on src/code/Utils.cs
> +                public static void WriteVerboseOnCmdlet(
nitpick, but the indentation got weird here..

2021-07-09 18:20 UTC, anamnavi commented on src/code/Utils.cs
> +        public static List<string> GetAllResourcePaths(PSCmdlet psCmdlet)
if you could add a comment here saying `this method returns paths to all installed resources, for example: 'c:\users\johndoe\Documents\PowerShell\Modules\TestModule'` that would be great :) That comment helped me understand the difference between this helper and GetInstallationPaths.

2021-07-09 18:20 UTC, anamnavi commented on src/code/Utils.cs
> +        // Find all potential installation paths given a scope
`only return the parent module/script path, for example 'c:\users\americks\Documents\PowerShell\Modules'` that was how you explained this helper method in one of our chats and that really helped if that can be added here.

2021-07-09 18:26 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                    // Deduplicate any packages
We could do this in FindHelper.FindResourceName() the only reason I hadn't was because we'd have to get all packages first, sort for unique and then yield from that list.

Currently it yields each package as it "finds" it. I thought collecting all packages and sorting would be better done as far up as possible to retain some of the efficiency we get by yielding

2021-07-09 21:59 UTC, alerickson commented on src/code/InstallPkgParams.cs
> +public class PkgParams
Yup, this is old and got added in.  Will remove this file as well.

2021-07-10 00:57 UTC, alerickson commented on src/code/PowerShellGet.csproj
> +    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
Don't believe it is anymore, I've removed it.

2021-07-10 00:59 UTC, alerickson commented on src/code/InstallHelper.cs
> +        private readonly bool update;
Yes that's correct, I'll remove this from this PR, it can get added back in with the update PR

2021-07-10 01:05 UTC, alerickson commented on src/code/InstallHelper.cs
> +            this.cancellationToken = cancellationToken;
I've updated the class so that where FindHelper was previously passing in a new cancellation token, it's now passing in the Install cancellation token.  This token is now also getting passed into the NuGet API calls (GetDownloadResourceResultAsync and PackageReader.CopyFiles).

2021-07-10 05:34 UTC, alerickson commented on src/code/InstallHelper.cs
> +                if (sourceTrusted || yesToAll)
I don't think the early out would actually do anything because if that condition is not satisfied it just moves onto the next iteration of the loop.

2021-07-12 18:08 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    // Deduplicate any packages
This sounds reasonable to me.  Let's keep the code as is then.

2021-07-12 18:10 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                if (sourceTrusted || yesToAll)
Oh yes, thanks.  We would need a `continue;` here.

2021-07-12 18:29 UTC, PaulHigin requested changes

2021-07-12 18:29 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +        //[Parameter(ParameterSetName = RequiredResourceFileParameterSet)]
I think we should not have commented out parameter sets.  We should either not include the code or include the code and throw a `PSNotImplementedExpection`.

2021-07-12 18:29 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +            if (ParameterSetName.Equals("NameParameterSet") && Version != null && !Utils.TryParseVersionOrVersionRange(Version, out _versionRange))
```suggestion
            if (ParameterSetName.Equals(NameParameterSet) && Version != null && !Utils.TryParseVersionOrVersionRange(Version, out _versionRange))

```

2021-07-12 18:29 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                    WriteDebug("Not yet implemented");
We should throw a `PSNotImplementedException`.

2021-07-13 19:40 UTC, alerickson commented on src/code/InstallPSResource.cs
> +        //[Parameter(ParameterSetName = RequiredResourceFileParameterSet)]
I'll take this out right now

2021-07-13 19:43 UTC, alerickson commented on src/code/InstallHelper.cs
> +                        //TODO:  SavePackage
Added now :)

2021-07-13 20:32 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                    else if (InputObject[0].GetType().Name.Equals("PSModuleInfo"))
Removing all of this code for now, and will add in later when we discuss whether we want to pursue "ValueFromPipelineByPropertyName" vs "InputObject"

2021-07-13 20:34 UTC, alerickson commented on src/code/InstallHelper.cs
> +                        cmdletPassedIn.WriteDebug("Error parsing version into a NuGetVersion");
Yes that's correct, I added a continue statement here

2021-07-13 20:39 UTC, alerickson commented on src/code/InstallHelper.cs
> +                    if (save)
I've removed this condition because it's not needed anymore

2021-07-14 21:40 UTC, PaulHigin commented on src/code/PSResourceInfo.cs
> +            if (AdditionalMetadata != null)
I see now.  Please disregard.

2021-07-15 15:21 UTC, merged