Ensure URI creation is cross platform compatible
PowerShell/PSResourceGet pull request #421
Opened 2021-07-27 16:40 UTC by anamnavi

# PR Summary

Fixed URI creation in Register-PSResource and Set-PSResource cmdlets. The user input for URL is now of type String instead of URL and in ProcessRecord we convert it to type URI while ensuring it's compatible cross platform and with absolute paths (and if it's detected to not be an absolute path, resolve it to the relative path)

## PR Context

Before, this was breaking tests in Linux.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-07-27 19:19 UTC, alerickson requested changes
We discussed with Paul offline, but the only change I'd recommend is pulling out the TryCreateURL method into the Utils class and just passing in the PSCmdlet as a param so that you can access the SessionState.

Everything else looks good to me

2021-07-27 22:36 UTC, PaulHigin approved these changes
Just some style comments.

2021-07-27 22:36 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    bool isUrlValid = Utils.TryCreateValidUrl(URL, this, out _url, out ErrorRecord errorRecord);
Nitpick: 
```csharp
Utils.TryCreateValidUrl(URL, cmdletPassedIn: this, out _url, out ErrorRecord errorRecord);
```

2021-07-27 22:36 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if (!isUrlValid)
Nitpick:
``` csharp
if (!Utils.TryCreateValidUrl(
    urlString:  repo["Url"].ToString(),
    cmdlet: this,
    out Uri repoURL,
    out ErrorRecord errorRecord))
{

}
```

2021-07-27 22:36 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +            if (!String.IsNullOrEmpty(URL))
Suggest:
```csharp
if (MyInvocation.BoundParameters.ContainsKey(nameof(URL)))
{

}
```

2021-07-27 22:36 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                if (!isUrlValid)
Same nitpick comment as above.

2021-07-27 22:36 UTC, PaulHigin commented on src/code/Utils.cs
> +                    string resolvedUrlString = cmdletPassedIn.SessionState.Path.GetResolvedPSPathFromPSPath(urlString)[0].Path;
Don't really need 'resolvedUrlString' variable since it is used only once.

2021-07-28 23:37 UTC, alerickson approved these changes

2021-07-28 23:39 UTC, PaulHigin approved these changes

2021-07-28 23:41 UTC, merged