Install should implement ShouldProcess
PowerShell/PSResourceGet pull request #425
Opened 2021-07-28 17:20 UTC by anamnavi

# PR Summary

Add implementation for ShouldProcess to InstallPSResource cmdlet. Resolves issue #279 #131 

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-07-28 17:35 UTC, alerickson approved these changes

2021-07-29 00:48 UTC, alerickson commented
Can you add this test to the Install tests as well:

    It "Install module using -WhatIf, should not install the module" {
        Install-PSResource -Name "TestModule" -WhatIf

        $res = Get-Module "TestModule" -ListAvailable
        $res | Should -BeNullOrEmpty
    }

2021-07-29 16:54 UTC, PaulHigin requested changes

2021-07-29 16:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                WriteVerbose("ShouldProcess was set to false.");
I don't think we need this verbose output ... or if so it should say: 'Install operation was aborted by user'.

2021-07-29 22:02 UTC, PaulHigin approved these changes

2021-07-29 22:06 UTC, merged