Support Azure Artifacts
PowerShell/PSResourceGet pull request #449
Opened 2021-08-06 20:45 UTC by anamnavi

# PR Summary

If Azure Artifacts (or other repository) contains packages that are not PowerShell packages they will not contain a `.psd1` file. Add error handling for this case.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-08-06 21:15 UTC, alerickson commented on src/code/Utils.cs
> +                    var message = String.Format("File {0} does not exist {0}. This is not a valid PowerShell package.", moduleFileInfo);
Everything looks good, just a comment to consider changing 'package' to 'resource'

2021-08-06 21:15 UTC, alerickson approved these changes

2021-08-09 16:13 UTC, PaulHigin requested changes

2021-08-09 16:13 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            continue;
Is this an error condition (invalid or non-existing module manifest?).  Should we emit an error message or at least a verbose message?

2021-08-09 16:13 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    if (!Directory.Exists(tempInstallPath))
Directory.Delete will throw an exception if it fails, so this check is not needed and you can add the verbose message after line 442.  But if this fails (access denied, File.IO exceptions), it will break the loop.  It seems like we want to catch a failure, emit a message, and continue processing packages.

I suggest creating a utility method 'TryDeleteDirectory'.  Also we should be using Utils.DeleteDirectory().

2021-08-09 16:17 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            continue;
If this is expected because we assume it is an artifact resource, please add a comment here to indicate that.  Is there any other way to determine an 'Az artifact' other than it does not have a manifest file?  Utils.ParseModuleManifest should have a way to indicate that no file exists, as opposed to the file exists but is empty (invalid manifest), or we should directly check for its existence here to make the code clear.

2021-08-09 17:54 UTC, alerickson commented on src/code/InstallHelper.cs
> +                            continue;
This is an error condition, but there is error handling that happens within ParseModuleManifest that specifies that the manifest is invalid, for example.  However, because that error isn't terminating the method would return and continue on with the rest of this method.  Anam added the check to see if the hashtable is empty so that we know the parsing failed (at this point an error has already been displayed), and can exit out of this iteration.  

Another thing we could do is change 'ParseModuleManifest' to 'TryParseModuleManifest'  that way if false gets returned we just continue on to the next loop iteration instead of checking if the hashtable's empty.

2021-08-09 18:14 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                    if (!Directory.Exists(tempInstallPath))
I moved this into a helper method named TryDeleteDirectory()

2021-08-09 18:14 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            continue;
So parsedMetadataHashtable.Count == 0 means that there is no manifest file?  If so, please add a comment to make that clear.

2021-08-09 18:16 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            continue;
And also that it means the resource is a Az artifact and not a powershell module...

2021-08-09 18:17 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                            continue;
I agree that the error handling (to check if the module manifest file exists- which would only be false if the resource was a NuGet resource, not a PowerShell resource wrapped in a NuGet resource) should be done earlier.

So I modified this code so that we check if the module manifest file exists in InstallHelper. Utils.ParseModuleManifest() should only be called if the module manifest file exists. I think it makes sense for the caller to handle this.

I do the `parsedMetadataHashtable.Count == 0)` because by default the returned hashtable there is set to a new empty one. And if it's not filled then it'll have a count of 0 and no keys and cause exceptions to be thrown later.

2021-08-09 18:20 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                            continue;
@PaulHigin no, now if parsedMetadataHashtable.Count == 0, it would mean that we had errors while parsing the .psd1 file (which we wrote errors for in Utils.ParseModuleManifest(). But before calling this method we verified that the module manifest file existed- thus it was a PowerShell resource, not a NuGet resource)

2021-08-09 18:35 UTC, alerickson commented on src/code/InstallHelper.cs
> +                            var message = String.Format("Module manifest file: {0} does not exist. This is not a valid PowerShell resource.", moduleManifest);
```suggestion
                            var message = String.Format("Module manifest file: {0} does not exist. This is not a valid PowerShell module.", moduleManifest);

```

2021-08-09 19:28 UTC, alerickson commented on src/code/InstallHelper.cs
> +                            if (parsedMetadataHashtable.Count == 0)
I think we should be able to get rid of this condition since the only time the hashtable will be empty is if the TryParse failed

2021-08-09 20:01 UTC, PaulHigin approved these changes
This looks good, after addressing @alerickson comment.

2021-08-09 20:31 UTC, merged