Tag type paramset
PowerShell/PSResourceGet pull request #478
Opened 2021-08-25 18:14 UTC by anamnavi

# PR Summary

- [x] Support `-Name "*"` for Find-PSResource. 
- [x] Support "*" cases for `-Repository` parameter.
- [x] Implement Tag parameter set (`Find-PSResource -Tag "Dell"`)
- [x] Implement Type parameter set (`Find-PSResource -Type Module`) 
- [x] Packages returned will be unique by Name,Version,Repository

## PR Context

Complete not yet implemented parameter sets for Find-PSResource. Towards resolving issue #466 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-08-25 19:42 UTC, PaulHigin approved these changes
Just some minor, non-blocking comments.

2021-08-25 19:42 UTC, PaulHigin commented on test/FindPSResource.Tests.ps1
> +        $res.Count | Should -BeGreaterThan 1
If we are using our own test repository, can we check for an exact count here to ensure all resources are returned?

2021-08-25 19:42 UTC, PaulHigin commented on test/FindPSResource.Tests.ps1
> +        $res.Count | Should -BeGreaterThan 1
If we are using our own test repository, can we check for an exact count here to ensure all resources are returned?

2021-08-30 18:33 UTC, anamnavi commented on test/FindPSResource.Tests.ps1
> +        $res.Count | Should -BeGreaterThan 1
yes, updated to check PoshTestGallery instead of PSGallery resources.

2021-08-30 20:05 UTC, PaulHigin requested changes

2021-08-30 20:05 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                _cmdletPassedIn.WriteVerbose("uri absolute uri: " + repositoriesToSearch[i].Url.AbsoluteUri);
This message is not very informative.   It should include the repository name and should make clear it is emitting a repository uri for searching.

2021-08-30 20:05 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                else if (String.Equals(repositoriesToSearch[i].Url.AbsoluteUri, _poshTestGalleryURL, StringComparison.InvariantCultureIgnoreCase))
We should not be special casing galleries, other than PowerShellGallery.  We should not include test code in our cmdlet implementations.

2021-08-30 20:05 UTC, PaulHigin commented on test/FindPSResource.Tests.ps1
> +        $res.Count | Should -BeGreaterOrEqual 2004
If we are unsure of the number of items in our test repository, we should probably not have this test.  I was assuming that we controlled the test repository and therefore knew exactly how many items should be returned.  Instead perhaps we should check for an expected resource item.

2021-08-30 20:09 UTC, anamnavi commented on src/code/FindHelper.cs
> +                _cmdletPassedIn.WriteVerbose("uri absolute uri: " + repositoriesToSearch[i].Url.AbsoluteUri);
oops I meant to remove this Verbose message

2021-09-22 15:57 UTC, anamnavi commented on src/code/FindHelper.cs
> +                else if (String.Equals(repositoriesToSearch[i].Url.AbsoluteUri, _poshTestGalleryURL, StringComparison.InvariantCultureIgnoreCase))
per our code review discussion, we'll special case PoshTestGallery for now in addition to PSGallery.

2021-09-22 15:58 UTC, anamnavi commented on test/FindPSResource.Tests.ps1
> +        $res.Count | Should -BeGreaterOrEqual 2004
changed this to test for "testmodule" and "test_script" resources in all results returned, instead of a count which could change.

2021-09-28 22:32 UTC, PaulHigin approved these changes

2021-09-29 00:21 UTC, merged