Add support for credential persistence
PowerShell/PSResourceGet pull request #480
Opened 2021-08-30 22:23 UTC by cansuerdogan

# PR Summary

- [x] Add an `-Authentication` parameter to the `Register-PSResourceRepository`
- [x] Add an authentication dimension to the `PSRespositoryInfo` object
- [x] The `-Authentication` parameter will take a hashtable which specifies the vault and secret where the credential is stored
- [x] Detailed error messaging to indicate why authentication failed (SecretManagement wasn't installed, no vault was available, the vault couldn't be reached etc.)
- [x] Since not all repositories requires authentication (principally PSGallery) PowerShellGet will not take a dependency
on SecretManagement
- [x] When `<x>-PSResource` is called and the prioritized repository is determined, a check will also be made to the `Authentication` property

## PR Context

Add functionality for supporting credential persistence as discussed in issue #330.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
        - Cmdlets have been tested manually due to the private feed requirement
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-08-30 22:32 UTC, cansuerdogan commented on src/code/AuthenticationHelper.cs
> +    internal static class PowerShellInvoker
I grabbed this from the [SecretManagement repository](https://github.com/PowerShell/SecretManagement/blob/master/src/code/Utils.cs#L1456)

2021-08-30 22:42 UTC, cansuerdogan commented on src/code/PSRepositoryInfo.cs
> +        public Hashtable Authentication { get; }
Adding this here changes the layout of `Get-PSResourceRepository` results and I'm not sure if that's desired but I don't know how to leave `Authentication` out.

![psresourcerepository](https://user-images.githubusercontent.com/2630383/131415029-a5357c9f-ef0d-4a67-af0e-04234d524e40.PNG)

2021-09-01 19:37 UTC, alerickson commented on src/code/PSRepositoryInfo.cs
> +        public Hashtable Authentication { get; }
Don't worry about that, we actually have the ability to modify the properties displayed for the object by updating the format.xml file.  We can add this.

2021-09-01 19:40 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +        public Hashtable Authentication {get; set;}
```suggestion
        public Hashtable Authentication { get; set; }
```

2021-09-01 20:44 UTC, alerickson commented
Thanks @cansuerdogan for this PR!  It's very thorough and looks good so far, @anamnavi and I are reviewing and will update you shortly.  Just adding a couple of small nitpicks right now.

2021-09-01 22:08 UTC, alerickson commented on .gitignore
> +result.pester.xml
```suggestion
result.pester.xml

```

2021-09-01 22:10 UTC, alerickson commented on test/SetPSResourceRepository.Tests.ps1
> +}
```suggestion
}

```

2021-09-01 22:10 UTC, alerickson commented on test/testRepositoriesWithAuthentication.xml
> +</configuration>
```suggestion
</configuration>

```

2021-09-01 23:30 UTC, alerickson commented on src/code/AuthenticationHelper.cs
> +}
```suggestion
}

```

2021-09-02 16:44 UTC, cansuerdogan commented
Thank you @alerickson! Please let me know if you have any questions.

2021-09-02 16:47 UTC, cansuerdogan commented on src/code/PSRepositoryInfo.cs
> +        public Hashtable Authentication { get; }
Oh that's great! TIL

2021-09-09 23:24 UTC, PaulHigin requested changes
Just started reviewing the code, and have a few initial comments.

2021-09-09 23:24 UTC, PaulHigin commented on src/code/AuthenticationHelper.cs
> +    internal static class PowerShellInvoker
I don't think you need the PowerShellInvoker here, and can just use the _cmdletPassedIn.InvokeCommand.InvokeScript() API.  Here is an example:

https://github.com/PowerShell/SecretManagement/blob/f756708bc6a534bce43ccb7aab541fdb1d05fab9/src/code/SecretManagement.cs#L195

Also I think we need a check to see if the SecretManagement module is installed and available, and if not then to provide a good user error message.  This check may be needed both when repository is registered and when it is used and requires credential authentication.

2021-09-09 23:24 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                string password = authHelper.GetRepositoryAuthenticationPassword(
It may make more sense to store and retrieve the credential as a PSCredential type rather than a password string, since the PSCredential contains both username and password information.

2021-09-14 00:12 UTC, cansuerdogan commented on src/code/AuthenticationHelper.cs
> +    internal static class PowerShellInvoker
Registration currently doesn't depend on SecretManagement being available. If we will be adding an error message at repository registration time, do we also want to test vault connection?

2021-09-17 22:33 UTC, PaulHigin commented on src/code/AuthenticationHelper.cs
> +    internal static class PowerShellInvoker
Good point, maybe we would emit a warning in this case, or nothing until the repository is accessed.

2021-09-17 22:34 UTC, PaulHigin commented
I didn't get to this PR this week, but will make it a high priority to review early next week.  Sorry for the delay.

2021-09-21 17:25 UTC, PaulHigin requested changes
Overall I think this is a good start.  However, I feel a number of changes should be made and/or considered.

The cmdlet parameter should be `-AuthenticationInfo` instead of `-Authentication`.  The latter usually refers to authentication type, whereas the former indicates information used for authentication.

The `-AuthenticationInfo` parameter should take a concrete type (`AuthenticationInformation`) instead of a hashtable type.  This way we don't have to repeatedly check the hashtable for the required name/value pairs.  Basic validation can be done at binding (non-null, not-empty values).  Also, hashtable syntax can still be used to pass the authentication information, since PowerShell will automatically convert to the concrete type during parameter binding.

```powershell
# This still works, even though -AuthenticationInfo takes a 'AuthenticationInformation' class type.
Register-PSResourceRepository -Name MyRepo -URL https://MyRepo -AuthenticationInfo @{ VaultName='MyVault'; SecretName='MyRepoCreds' }
```
I think we should also consider a parameter set option that automatically persists credentials when they are provided.  Something like:
```powershell
Register-PSResourceRepository -Name MyRepo -URL https://MyRepo -ProxyCredential $credentials -PersistCredentials @{ VaultName='MyVault'; SecretName='MyRepoCreds' }
```
We should be consistent and persist `PSCredential` type in the SecretManagement vault (since we pass in `PSCredential` type for `-ProxyCredential` parameter.

We should use `PSCmdlet.InvokeCommand.InvokeScript()` API to invoke the SecretManagement `Get-Secret`, `Set-Secret` commands.  This will run the command in the current cmdlet context and allow the vault to prompt the user for a passkey if needed.  For example the SecretStore vault defaults to 'password required' configuration and user prompting for password when needed.

We should try to do `AuthenticationInfo` validation as early as possible.

We need to make sure reported errors are useful and not confusing, in cases where SecretManagement is not installed/configured correctly.

- SecretManagement not installed
- Vault not found
- Secret not found

Not sure, but we may want to catch errors and wrap them in our own to provide better context.

2021-09-22 19:34 UTC, cansuerdogan commented
Thank you @PaulHigin for the feedback! Sorry I was away for a few days but I will try to get your suggestions implemented and pushed hopefully by EOD tomorrow.

- I already verified `PSCmdlet.InvokeCommand.InvokeScript()` works last week but I still need to spend some time on error messages.
- I will rename the parameter and change the type it expects.
- Just to make sure I'm understanding the `-PersistCredential` proposal: 
  - Have a parameter set for the combination of `-ProxyCredential` and `-PersistCredential` 
  - If `-ProxyCredential` is provided by itself, proceed as it is now, i.e. don't save the credential anywhere
  - If both are provided, call SecretManagement\Set-Secret with the credential and authentication info passed in

Is this correct? If so, do we want to maybe take in only the VaultName and use the username from PSCredential as the secret name? Because when it's time to pass credential into the Nuget library call, we are assuming SecretName is the username.

2021-09-23 19:35 UTC, PaulHigin commented
@cansuerdogan 
I think we still need to talk through the proposals, and decide on how to proceed.  We hope to do this internally (early) next week, and then I think it would be good to have a live chat with you, if you are available.  In the mean time it may not be worthwhile to make too many code changes.  My aim is to soon have a list of action items that we all agree on.

2021-10-20 21:55 UTC, cansuerdogan commented
Hi @alerickson, @anamnavi and @PaulHigin,

It has been a while sorry! I can finally get back to working on this pull request. Do you still have the notes from our meeting by any chance?

Here is what I remember:
- Parameter name will be changed to CredentialInfo
- I will be adding a concrete type for CredentialInfo which will have the following:
  - String VaultName
  - String SecretName
  - PSCredential Credential
- Register-PSResourceRepository will at the very least take VaultName and SecretName as part of CredentialInfo, but optionally, users can also pass in a PSCredential to save the secret in the provided vault
  - If only VaultName and SecretName are passed in, PowerShellGet will NOT print out a warning regarding SecretManagement setup since this can come later
  - If additionally a Credential is passed in and SecretManagement setup is wrong or incomplete, PowerShellGet will throw a terminating error and will not register the repository
- We will keep the PowerShell Invoker implementation for importing and using SecretManagement as part of PowerShellGet but try to add more meaningful error messages where things may go wrong

Are these accurate? Please let me know if I'm missing anything or misremembering any part. 

Thank you!

2021-11-09 20:40 UTC, alerickson commented
Hi @cansuerdogan just wanted to check in.  We are targeting mid December for our next release, with all changes in by the end of the month so we can have a couple weeks to do manual testing and validations.  This PR certainly doesn't need to be in by then, but I just wanted to keep you updated.

2021-11-09 20:45 UTC, cansuerdogan commented
Hi @alerickson! I had some time off in between so I wasn't able to get back to this PR sorry. Can you please confirm if what I remembered from our discussion ([summarized in this comment](https://github.com/PowerShell/PowerShellGet/pull/480#issuecomment-948067600)) was correct? If so I'll get started on those changes and we can sync up after I have them implemented. Thank you!

2021-11-30 21:12 UTC, SydneyhSmith commented
Thanks @cansuerdogan your notes from the meeting all look correct, thanks for following up! It would be awesome to know when you may have a chance to return to this work--thanks so much!

2021-12-02 21:00 UTC, cansuerdogan commented
@SydneyhSmith Sorry for the delay on this! I will try to finish this up by end of next week.

2021-12-02 21:08 UTC, StevenBucher98 commented
Thanks for the update @cansuerdogan, we are planning for a new release on Wednesday (12/2, so it would need to be in this week) so we might not be able to fit it in that release but will shoot to include it in the next release earlier in the new year! Thanks so much!

2021-12-02 21:43 UTC, cansuerdogan commented
Thank you for the heads-up @StevenBucher98 ! Good luck with the new release!

2022-01-11 23:13 UTC, PaulHigin requested changes
Sorry for the delay in the review.  Thanks for doing this work!  Overall changes look good, most comments are just style changes.

2022-01-11 23:13 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                    PSRepositoryInfo psGalleryScripts = new PSRepositoryInfo(_psGalleryScriptsRepoName, psGalleryScriptsUrl, repositoriesToSearch[i].Priority, false, null);
```suggestion
                    PSRepositoryInfo psGalleryScripts = new PSRepositoryInfo(_psGalleryScriptsRepoName, psGalleryScriptsUrl, repositoriesToSearch[i].Priority, trusted: false, credentialInfo: null);
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                    PSRepositoryInfo poshTestGalleryScripts = new PSRepositoryInfo(_poshTestGalleryScriptsRepoName, poshTestGalleryScriptsUrl, repositoriesToSearch[i].Priority, false, null);
```suggestion
                    PSRepositoryInfo poshTestGalleryScripts = new PSRepositoryInfo(_poshTestGalleryScriptsRepoName, poshTestGalleryScriptsUrl, repositoriesToSearch[i].Priority, trusted: false, credentialInfo: null);
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +            private set
Please add white space here.

2022-01-11 23:13 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +            private set
Please add white space here.

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                    WriteWarning($"Microsoft.PowerShell.SecretManagement module cannot be imported. Make sure it is available before performing PSResource operations in order to successfully authenti
```suggestion
                    WriteWarning($"Microsoft.PowerShell.SecretManagement module cannot be found. Make sure it is installed before performing PSResource operations in order to successfully authenticate to PSResourceRepository \"{repoName}\" with its CredentialInfo.");
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            return AddToRepositoryStoreHelper(PSGalleryRepoName, psGalleryUri, repoPriority, repoTrusted, null);
```suggestion
            return AddToRepositoryStoreHelper(PSGalleryRepoName, psGalleryUri, repoPriority, repoTrusted, repoCredentialInfo: null);
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +            if(repo.ContainsKey("CredentialInfo")) {
```suggestion
            if (repo.ContainsKey("CredentialInfo"))
            {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RegisterPSResourceRepository.cs
> +                if (!Utils.TryCreateValidPSCredentialInfo(credentialInfoCandidate: (PSObject) repo["CredentialInfo"],
We can remove this extra `if` statement and just have:
```csharp
if (repo.ContainsKey("CredenialInfo") &&
    !Utils.TryCreateValidPSCredentialInfo(...))
{
    WriteError(errorRecord1);
    return null;
}
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                Add(PSGalleryRepoName, psGalleryUri, defaultPriority, defaultTrusted, null);
```suggestion
                Add(PSGalleryRepoName, psGalleryUri, defaultPriority, defaultTrusted, repoCredentialInfo: null);
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                // So only set VaultName and SecretName attributes if non-null value passed in for repoCredentialInfo
```suggestion
                // Set only VaultName and SecretName attributes if non-null value passed in for repoCredentialInfo
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                catch (Exception)
We should check for null attributes instead of using a catch all here.

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                if(node.Attribute("VaultName") != null & node.Attribute("SecretName") != null)
```suggestion
                if (node.Attribute("VaultName") != null & node.Attribute("SecretName") != null)
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        if (node.Attribute(PSCredentialInfo.VaultNameAttribute) != null && node.Attribute(PSCredentialInfo.SecretNameAttribute) != null) {
```suggestion
                        if (node.Attribute(PSCredentialInfo.VaultNameAttribute) != null && node.Attribute(PSCredentialInfo.SecretNameAttribute) != null)
                        {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    if (repo.Attribute(PSCredentialInfo.VaultNameAttribute) != null && repo.Attribute(PSCredentialInfo.SecretNameAttribute) != null) {
```suggestion
                    if (repo.Attribute(PSCredentialInfo.VaultNameAttribute) != null && repo.Attribute(PSCredentialInfo.SecretNameAttribute) != null)
                    {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    else if (repo.Attribute(PSCredentialInfo.VaultNameAttribute) == null && repo.Attribute(PSCredentialInfo.SecretNameAttribute) == null) {
```suggestion
                    else if (repo.Attribute(PSCredentialInfo.VaultNameAttribute) == null && repo.Attribute(PSCredentialInfo.SecretNameAttribute) == null)
                    {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        else if (node.Attribute(PSCredentialInfo.VaultNameAttribute) == null && node.Attribute(PSCredentialInfo.SecretNameAttribute) == null) {
```suggestion
                        else if (node.Attribute(PSCredentialInfo.VaultNameAttribute) == null && node.Attribute(PSCredentialInfo.SecretNameAttribute) == null)
                        {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        else {
```suggestion
                        else
                        {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                    if(!isSecretManagementModuleAvailable)
```suggestion
                    if (!isSecretManagementModuleAvailable)
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                            new PSInvalidOperationException($"Microsoft.PowerShell.SecretManagement module is required for saving PSResourceRepository {repoName}'s Credential in a vault."),
```suggestion
                            new PSInvalidOperationException($"Microsoft.PowerShell.SecretManagement module is not found, but is required for saving PSResourceRepository {repoName}'s Credential in a vault."),
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                if(!isSecretManagementModuleAvailable)
```suggestion
                if (!isSecretManagementModuleAvailable)
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                    WriteWarning($"Microsoft.PowerShell.SecretManagement module cannot be imported. Make sure it is available before performing PSResource operations in order to successfully authenti
```suggestion
                    WriteWarning($"Microsoft.PowerShell.SecretManagement module cannot be found. Make sure it is installed before performing PSResource operations in order to successfully authenticate to PSResourceRepository \"{repoName}\" with its CredentialInfo.");
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +            if(repo.ContainsKey("CredentialInfo")) {
```suggestion
            if (repo.ContainsKey("CredentialInfo"))
            {
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/SetPSResourceRepository.cs
> +                if (!Utils.TryCreateValidPSCredentialInfo(credentialInfoCandidate: (PSObject) repo["CredentialInfo"],
We can remove this extra `if` statement and include conditional in above `if`.

2022-01-11 23:13 UTC, PaulHigin commented on src/code/Utils.cs
> +                if(!string.IsNullOrEmpty((string) credentialInfoCandidate.Properties[PSCredentialInfo.VaultNameAttribute]?.Value)
```suggestion
                if (!string.IsNullOrEmpty((string) credentialInfoCandidate.Properties[PSCredentialInfo.VaultNameAttribute]?.Value)
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/Utils.cs
> +                    if(credentialInfoCandidate.Properties[PSCredentialInfo.CredentialAttribute] != null)
```suggestion
                    if (credentialInfoCandidate.Properties[PSCredentialInfo.CredentialAttribute] != null)
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/Utils.cs
> +            if(!IsSecretManagementVaultAccessible(repositoryName, repositoryCredentialInfo, cmdletPassedIn))
```suggestion
            if (!IsSecretManagementVaultAccessible(repositoryName, repositoryCredentialInfo, cmdletPassedIn))
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/Utils.cs
> +            if(secretValue is PSCredential)
Suggest:

```csharp
if (secretValue is PSCredential secretCredential)
{
    return secretCredential;
}
```

2022-01-11 23:13 UTC, PaulHigin commented on src/code/Utils.cs
> +            if(!IsSecretManagementVaultAccessible(repositoryName, repositoryCredentialInfo, cmdletPassedIn))
```suggestion
            if (!IsSecretManagementVaultAccessible(repositoryName, repositoryCredentialInfo, cmdletPassedIn))
```

2022-01-13 02:40 UTC, cansuerdogan commented on src/code/RepositorySettings.cs
> +                catch (Exception)
I've changed this to catch ArgumentException since the constructor throws that if the values are null or empty. But if you'd prefer, I can add the null checks here.

2022-01-13 17:18 UTC, PaulHigin requested changes

2022-01-13 17:18 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                catch (ArgumentException)
I don't think it makes sense to throw an exception just to capture and ignore it.  It is better to explicitly check for null values and ignore.

2022-01-13 20:34 UTC, PaulHigin requested changes

2022-01-13 20:34 UTC, PaulHigin commented on test/PSCredentialInfo.Tests.ps1
> +        { New-Object Microsoft.PowerShell.PowerShellGet.UtilClasses.PSCredentialInfo ("", "testsecret") } | Should -Throw "Invalid CredentialInfo, VaultName must be a non-empty string"
We should always test for `ErrorId` of the thrown error.  The error message can change for clarity or localization, but the ErrorId should never change.  Example:
```powershell
... | Should -Throw -ErrorId "ArgumentNullException"
```

2022-01-14 18:44 UTC, PaulHigin approved these changes
LGTM.  Again, thanks for your contribution!

2022-01-14 22:19 UTC, alerickson approved these changes

2022-01-14 22:32 UTC, anamnavi approved these changes
had 2 minor nitpicks, but LGTM

2022-01-14 22:32 UTC, anamnavi commented on .gitignore
> +result.pester.xml
is this necessary or were you creating this file locally to output the tests to and trying to ignore?

2022-01-14 22:32 UTC, anamnavi commented on test/PSCredentialInfo.Tests.ps1
> +}
please add a newline; nitpick

2022-01-14 22:36 UTC, cansuerdogan commented on .gitignore
> +result.pester.xml
I was running the tests locally to verify and did not want to commit this file that gets generated. I can remove it if you'd like.

2022-01-14 22:38 UTC, anamnavi commented on .gitignore
> +result.pester.xml
That makes perfect sense, if you can remove it that would be appreciated :)

2022-01-14 23:24 UTC, merged

2022-01-15 01:31 UTC, cansuerdogan commented
Thank you all for your guidance and collaboration!