Implement -DestinationPath parameter for Publish-PSResource
PowerShell/PSResourceGet pull request #506
Opened 2021-10-08 03:23 UTC by alerickson

# PR Summary
Implements the -DestinationPath parameter for Publish-PSResource.  This allows the user to save the generated .nupkg that gets pushed to a repository to to a specified path on the local file system as well.

## PR Context
Resolves #430 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-10-08 19:02 UTC, anamnavi approved these changes
LGTM, just some minor nitpicks. Also perhaps we can update the help doc for the `-DestinationPath` parameter that would be great. I can definitely also help with this if needed :)

2021-10-08 19:02 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                    WriteError(DestinationPathDoesNotExist);
so in this case, we'd just write the error and `_destinationPath` wouldn't be set to anything, i.e be an empty string?

2021-10-08 19:02 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                        var message = string.Format("Error moving .nupkg into destination path: '{0}'.", e.Message);
I read this expecting the `{0}` value to be the destinationPath, not the reason why the nupkg couldn't be moved to the destinationPath, so perhaps:

```suggestion
                        var message = string.Format("Error moving .nupkg into destination path '{0}' due to: '{1}'.", _destinationPath, e.Message);

```

2021-10-08 19:02 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                PushNupkg(outputNupkgDir, repositoryUrl);
do we need to handle the cases where we get unsuccessful response status codes?

2021-10-08 19:02 UTC, anamnavi commented on test/PublishPSResource.Tests.ps1
> +        $expectedPath = Join-Path -Path $script:repositoryPath2  -ChildPath "$script:PublishModuleName.$version.nupkg"
```suggestion
        $expectedPath = Join-Path -Path $script:repositoryPath2 -ChildPath "$script:PublishModuleName.$version.nupkg"

```

2021-10-08 20:01 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                PushNupkg(outputNupkgDir, repositoryUrl);
Ideally yes, but this method does not return anything and does not throw exceptions, it just writes to the console.  @PaulHigin do you have any suggestions on how to properly address this situation?

2021-10-08 20:03 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                    WriteError(DestinationPathDoesNotExist);
Yes, so essentially the -DestinationPath param would no longer be applicable.  Although now I'm wondering if we should throw a terminating error instead and ensure the user passes in a valid argument.

2021-10-08 20:51 UTC, PaulHigin requested changes

2021-10-08 20:51 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +        /// Specifies a path to one or more locations. Wildcards are permitted. The default location is the current directory (.).
I don't understand this comment description.  How can a single path string specify more than one location?  How can and why would a package be saved to multiple locations?  Is there a limit on the number of locations?  Why is there a default location, if this is an optional parameter ... a valid destination location is specified or it isn't.

2021-10-08 20:51 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                string resolvedPath = string.Empty;
It should be Ok to set the path to null or empty string as this just means the package is not published to a local file path.
This should be the first check and return immediately.  If the path doesn't exist we should either create it (-Force) or throw terminating error.

However, it feels strange to have this option in `Publish-PSResource`, since it is doing two different things.  One is to publish to a repository.  The other is to save the package to a file path.  At the very lease I feel this should be a separate parameter set, and maybe should be a separate cmdlet (`Publish-PSResourceToPath`).

2021-10-08 20:51 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                PushNupkg(outputNupkgDir, repositoryUrl);
Sounds like a poor API, we should try to get the owners to fix.  In the mean time, is there a way to verify the publishing?  Maybe add an optional switch parameter to do the verification.

2021-10-08 20:51 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        File.Move(System.IO.Path.Combine(outputNupkgDir, nupkgName), System.IO.Path.Combine(_destinationPath, nupkgName));
We should consistently use the Utils.FileMove method that works over different volumes.

2021-10-12 20:24 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                    WriteError(DestinationPathDoesNotExist);
Check that's a valid path and that the path actually exists.  Write a terminating error.

2021-10-12 20:30 UTC, alerickson commented
- Consider creating a new parameter set for -DestinationPath
     - Publish-PSResource -Path -DestinationPath
     - Publish-PSResource -LiteralPath -DestinationPath

- Consider getting rid of the -LiteralPath parameter

2021-11-05 07:01 UTC, merged