Add -NoClobber functionality to Install-PSResource
PowerShell/PSResourceGet pull request #509
Opened 2021-10-12 06:41 UTC by alerickson

# PR Summary

Add functionality to Install-PSResource for -NoClobber parameter

## PR Context

Resolves #203 
Resolves #204 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-10-12 22:27 UTC, PaulHigin requested changes

2021-10-12 22:27 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            IEnumerable<PSResourceInfo> pkgsAlreadyInstalled = getHelper.FilterPkgPaths(new string[] { "*" }, VersionRange.All, _pathsToSearch);
'FilterPkgPaths' method name is misleading.  It is not filtering package paths, but instead is getting PSResourceInfo information on every installed resource indicated by the directory path.
Should be 'GetPkgInfoFromPaths()' or something similar.

2021-10-12 22:27 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            foreach (var cmdlet in parsedMetadataHashtable["CmdletsToExport"] as object[])
```suggestion
            foreach (var cmdletName in parsedMetadataHashtable["CmdletsToExport"] as object[])
```

2021-10-12 22:27 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                listOfCmdlets.Add(cmdlet as string);
```suggestion
                listOfCmdlets.Add(cmdletName as string); 

```

2021-10-12 22:27 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            foreach (var cmdlet in parsedMetadataHashtable["CmdletsToExport"] as object[])
We also need to include module 'FunctionsToExport' in list.

2021-10-12 22:27 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    duplicateCmdlets = listOfCmdlets.Where(cmdlet => pkg.Includes.Cmdlet.Contains(cmdlet)).ToList();
We need to do case insensitive string compare.

2021-10-20 16:13 UTC, anamnavi approved these changes
LGTM

2021-11-05 04:44 UTC, merged