Add InputObject parameter sets for appropriate *-PSResource cmdlets, to provide pipeline support
PowerShell/PSResourceGet pull request #510
Opened 2021-10-13 00:24 UTC by anamnavi

# PR Summary

Add `InputObjectParameterSet` to Install-PSResource, Uninstall-PSResource, Save-PSResource.
Remove `ValueFromPipeline`/`ValueFromPipelineByPropertyName` for all but Name property for these cmdlets as well.

## PR Context

Add pipeline support, resolves #482 , #348 (partially).

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-10-13 20:35 UTC, alerickson approved these changes

2021-10-13 20:35 UTC, alerickson commented on src/code/InstallPSResource.cs
> +        [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true, ParameterSetName = InputObjectParameterSet)]
Is the ValueFromPipelineByPropertyName needed here?

2021-10-13 21:04 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +        [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true, ParameterSetName = InputObjectParameterSet)]
good question, I checked and don't need that attribute. I've removed `ValueFromPipelineByPropertyName` from Install, Uninstall and Save

2021-10-18 18:28 UTC, PaulHigin requested changes
Looks good.  Just some minor suggestions.

2021-10-18 18:28 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +        public PSResourceInfo[] InputObject { get; set; }
```suggestion
        public PSResourceInfo InputObject { get; set; }

```
It is not necessary to take the InputObject parameter as an array type.

2021-10-18 18:28 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                    // If no Version specified, install latest version for the package.
Please remove extra white space.

2021-10-18 18:28 UTC, PaulHigin commented on src/code/SavePSResource.cs
> +        public PSResourceInfo[] InputObject { get; set; }
Array type not needed.

2021-10-18 18:28 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +        [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ParameterSetName = InputObjectParameterSet)]
Array type not needed.

2021-10-18 19:57 UTC, PaulHigin approved these changes

2021-10-18 20:05 UTC, merged