Uninstall and Get-Installed prerelease support for Version parameter
PowerShell/PSResourceGet pull request #523
Opened 2021-10-26 17:58 UTC by anamnavi

# PR Summary

Add prerelease support for Uninstall-PSResource and Get-InstalledPSResource, so that a prerelease version module isn't obtained when the version part alone is provided, we look into the PSGetModuleInfo.xml file and verify that is the correct version with prerelease label specifically. 

## PR Context

Part of bug fixes for preview 12 release
resolves #365 , resolves #83, resolves #348
screenshot of #83 working:
![image](https://user-images.githubusercontent.com/30238344/140185452-0db22a8e-e4c2-41c2-bc56-1d693a8e6e5c.png)

screenshot of #348 working:
![image](https://user-images.githubusercontent.com/30238344/140186794-9e6df8dc-27f6-4540-8cc2-256f8201de01.png)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-11-01 16:08 UTC, PaulHigin requested changes

2021-11-01 16:08 UTC, PaulHigin commented on src/code/GetInstalledPSResource.cs
> +            else if (!Utils.TryParseVersionOrVersionRange(version: Utils.GetVersionWithoutPrerelease(Version, out _prereleaseLabels),
version: parameter should go on next line.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/GetInstalledPSResource.cs
> +            string[] versionRangeParts = _versionRange.ToString().Trim(new char []{'[', ']', '(', ')'}).Split(',');
Include comment demonstrating what expected version range looks like and what parts are returned.  It would be better to have a private method that parses the version range and returns a concrete type that contains expected version parts.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/GetInstalledPSResource.cs
> +                if ((_versionRange != VersionRange.All) && (!String.IsNullOrEmpty(versionRangeParts[0]) && pkg.Version.ToString().StartsWith(versionRangeParts[0]) && !String.Equals(pkg.PrereleaseLabe
This should be in a private method along with comments to demonstrate expected form.  Why are there multiple prerelease labels.  Will the array always contain two items?  Private method should guarantee version/prerelease contains all expected internal items.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (!CheckIfPrerelease(isModule: true, pkgName: pkgName, pkgPath: pkgPath))
We never uninstall prerelease packages?  Should have a comment.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            if (!PSResourceInfo.TryRead(PSGetModuleInfoFilePath, out PSResourceInfo psGetInfo, out string errorMsg))
Should error be reported?

2021-11-01 16:08 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +            string[] versionRangeParts = _versionRange.ToString().Trim(new char []{'[', ']', '(', ')'}).Split(',');
Duplicate code should go into a single private method.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                (psGetInfo.Version.ToString().StartsWith(versionRangeParts[0]) && !String.Equals(psGetInfo.PrereleaseLabel, _prereleaseLabels[0], StringComparison.InvariantCultureIgnoreCase)) ||
Again, it is not clear what this is doing.  Comment should clearly explain what is expected for prerelease versions.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/Utils.cs
> +        public static string GetVersionWithoutPrereleaseHelper(string versionString, out string prereleaseLabel)
We should stop using 'helper' in method names.  Should just be a description of what the method does.

2021-11-01 16:08 UTC, PaulHigin commented on src/code/Utils.cs
> +                string[] versionRangeParts = versionString.Trim(new char[]{'[', ']', '(', ')'}).Split(',');
Duplicate code.

2021-11-02 18:31 UTC, anamnavi commented on src/code/UninstallPSResource.cs
> +            if (!PSResourceInfo.TryRead(PSGetModuleInfoFilePath, out PSResourceInfo psGetInfo, out string errorMsg))
we write a verbose message with error now, and skip to next package

2021-11-02 19:44 UTC, PaulHigin requested changes

2021-11-02 19:44 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                        if(!Utils.GetVersionFromPSGetModuleInfoFile(installedPkgPath: versionPath,
Maybe name should be: `GetVersionForInstallPath`?

2021-11-02 19:44 UTC, PaulHigin commented on src/code/UninstallPSResource.cs
> +                    string inputObjectVersion = String.IsNullOrEmpty(inputObjectPrereleaseLabel) ? InputObject.Version.ToString() : Utils.GetNormalizedVersionString(versionString: InputObject.Version
Please add vertical space for readability.

2021-11-02 19:44 UTC, PaulHigin commented on src/code/Utils.cs
> +            string pkgName = String.Empty;
Could use the ternary operator here.

2021-11-02 19:44 UTC, PaulHigin commented on src/code/Utils.cs
> +            string PSGetModuleInfoFilePath = isModule ? Path.Combine(installedPkgPath, "PSGetModuleInfo.xml") : Path.Combine((new DirectoryInfo(installedPkgPath).Parent).FullName, "InstalledScriptInf
Variable name should be camel case, and should not include 'module' since the path can be for either module or script package.  Maybe `packageInfoFilePath`?

2021-11-02 19:44 UTC, PaulHigin commented on src/code/Utils.cs
> +                cmdletPassedIn.WriteVerbose(String.Format("The PSGetModuleInfo.xml file found at location: {0} cannot be parsed due to {1}", PSGetModuleInfoFilePath, errorMsg));
Message is not quite correct.  Could be PSGetModuleInfo.xml or _InstalledScriptInfo.xml file.

2021-11-02 19:44 UTC, PaulHigin commented on src/code/Utils.cs
> +                NuGetVersion.TryParse(installedPkgPath, out pkgNuGetVersion);
Is there any reason to return parsed version from path if `false` is returned?  Please comment to indicate what the returned boolean means.

2021-11-03 17:01 UTC, anamnavi commented on src/code/Utils.cs
> +            string PSGetModuleInfoFilePath = isModule ? Path.Combine(installedPkgPath, "PSGetModuleInfo.xml") : Path.Combine((new DirectoryInfo(installedPkgPath).Parent).FullName, "InstalledScriptInf
renamed to `packageInfoXMLFilePath`

2021-11-03 17:17 UTC, anamnavi commented on src/code/Utils.cs
> +                NuGetVersion.TryParse(installedPkgPath, out pkgNuGetVersion);
Good point, thanks! If false is returned that means the PSGetModuleInfo.xml or InstalledScriptInfo.xml file could not be parsed properly, or, that the version could not be parsed into a NuGetVersion. I've added a comment to explain this. In GetHelper the caller method skips the package if false is returned as expected. So I changed this called method to not parse a version if we're returning false; instead we'll set it to null.

2021-11-03 20:39 UTC, PaulHigin approved these changes
LGTM

2021-11-04 19:32 UTC, alerickson approved these changes

2021-11-04 19:32 UTC, alerickson commented on src/code/GetHelper.cs
> +                            out NuGetVersion dirAsNugetVersion))
Maybe the varianble name `dirAsNugetVersion` should be changed to `pkgNuGetVersion` or something like that?

2021-11-04 19:32 UTC, alerickson commented on src/code/GetHelper.cs
> +                        _cmdletPassedIn.WriteVerbose(string.Format("Directory parsed as NuGet version: '{0}'", dirAsNugetVersion));
And this could be changed to something like `Package version parsed as NuGet version: ` or something of that nature.

2021-11-04 22:48 UTC, merged