Bug fix for Publish-PSResource deleting a temp dir that contains a readonly file
PowerShell/PSResourceGet pull request #543
Opened 2021-11-10 19:46 UTC by alerickson

# PR Summary
Publish-PSResource moves a module it is going to publish into a temp directory and then after publishing attempts to delete the temp directory it created. Occasionally there are files that have permissions that do not allow PSGet to delete, thus it's not able to fully delete the temp directory it created.  This PR attempts to set the file permissions when a file throws an access denied error. 

## PR Context
Resolves #526 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-11-10 22:14 UTC, PaulHigin requested changes

2021-11-10 22:14 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                    string[] filesLeftToDelete = Directory.GetFiles(outputDir);
This won't get files from subdirectories.  But we should always be using the `Utils.DeleteDirectory()` anyway. 
https://github.com/PowerShell/PowerShellGet/blob/4632fa59f32110e743910a3ac05c5f8f669cbfee/src/code/Utils.cs#L568

I think we should add code there to ensure each file has the right attributes for deletion.  Instead of try/catch we should first check file attribute and ensure it is not ReadOnly.

2021-11-15 15:57 UTC, anamnavi approved these changes

2021-11-15 17:31 UTC, PaulHigin requested changes

2021-11-15 17:31 UTC, PaulHigin commented on src/code/Utils.cs
> +                FileAttributes attribute = File.GetAttributes(dirFilePath);
Since the `FileAttributes` enumeration is a bitfield we need to use bitwise operators.  Also I think we just need to check for the 'ReadOnly' flag:
```csharp
var attributes = File.GetAttributes(dirFilePath);
if (attributes.HasFlag(FileAttributes.ReadOnly))
{
    // Remove 'ReadOnly' attribute so the file can be deleted.
    attributes &= ~FileAttributes.ReadOnly;
    File.SetAttributes(dirFilePath, attributes);
}

File.Delete(dirFilePath);

```

2021-11-30 23:09 UTC, PaulHigin approved these changes
One small change, you could save the file attributes in a variable and avoid calling GetAttributes() twice.

2021-11-30 23:15 UTC, merged