WIP: Rename params: *url to *uri
PowerShell/PSResourceGet pull request #551
Opened 2021-11-20 16:41 UTC by fsackur

# PR Summary

- Changed `-URL` params to `-Uri` (including, e.g., `-LicenseUrl` => `-LicenseUri`)
    - Updated (almost) all identifiers in source code `url` => `uri`, for consistency
    - Updated docs
    - A few strings and comments left at `URL`, where they make sense in the context
- Added `test/result*` to `.gitignore`
- Amended `build.ps1` to try importing `PSPackageProject` before installing again

## PR Context

Ref https://github.com/PowerShell/PowerShellGet/issues/460

Broadly speaking, all installed-by-default modules use `uri` in parameter names instead of `url`. To provide consistency, I think PowerShellGet should also follow this convention.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-11-22 19:41 UTC, fsackur commented
Requesting feedback!

I hope it's not too contentious to change all the terminology in private code; it seemed to me that leaving inconsistencies would be a poor dev experience for future maintainers.

2021-11-23 02:49 UTC, alerickson requested changes
Thank you @fsackur for opening up this PR!  
Just a few things--
1)  There's a handful of changes in PublishPSResource that should actually not be changed, specifically 'licenseUrl', 'iconUrl', and 'projectUrl'.  Those names are specified in the module manifest, which is used to generate the nuspec, so it'll cause problems when publishing (see [nuspec reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec#general-form-and-schema) if interested)

2)  This is very minor but the last two tests (SetPSResourceRepository.Tests.ps1 and UnregisterPSResourceRepository.Tests.ps1) have Uri in all caps whereas the other tests have it in pascal case.  I would recommend changing the former tests to pascal case just to be consistent.  Of course this is just an aesthetic request!

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                <projectUri>https://github.com/PowerShell/PowerShell</projectUri>
Same comment here-- this should stay as 'projectUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        $expectedNuspecContents.Contains($projectUri) | Should Be $true
This should stay as 'projectUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        Publish-PSResource -Path $script:PublishModuleBase -ProjectUri $projectUri
Lines 214 and 215 should be 'projectUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +    It "Publish a module with -ProjectUri" {
Should be 'ProjectUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        $expectedNuspecContents.Contains($iconUri) | Should Be $true
Should be 'iconUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +    It "Publish a module with -IconUri" {
Should be 'iconUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        Publish-PSResource -Path $script:PublishModuleBase -IconUri $iconUri
Should be 'iconUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        $expectedNuspecContents.Contains($licenseUri) | Should Be $true
Should be 'licenseUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +        Publish-PSResource -Path $script:PublishModuleBase -LicenseUri $licenseUri
Should be 'licenseUrl'

2021-11-23 02:49 UTC, alerickson commented on test/PublishPSResource.Tests.ps1
> +    It "Publish a module with -LicenseUri" {
Should be 'licenseUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("licenseuri"))
This still needs to remain 'licenseUrl' because we can't change the module manifest metadata.

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("licenseUri", parsedMetadataHash["licenseuri"].ToString().Trim());
Again should be 'licenseUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("projecturi"))
For the same reason as above, should be 'projectUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("projectUri", parsedMetadataHash["projecturi"].ToString().Trim());
And again, 'projectUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("iconuri"))
Again, for the same reason as above should be 'iconUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("iconUri", parsedMetadataHash["iconuri"].ToString().Trim());
Should be 'iconUrl'

2021-11-23 02:49 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                <licenseUri>https://licenses.nuget.org/MIT</licenseUri>
Should be 'licenseUrl'

2021-11-29 18:15 UTC, anamnavi requested changes
Hi @fsackur! Thanks for creating this PR and for diligently going through all the files and making appropriate changes. I know it looks like a lot of comments but I had feedback in 3 main areas:

1) please remove the local `test/result*` file reference from the .gitignore. Thanks :)

2) it's a bit of a nitpick but it would be nice to match the casing of cmdlet's Uri parameter across all tests/code. I know in some of the original code we accidentally had it as "URL" so I understand changing it to "URI" however "Uri" where appropriate would be best. I left suggestions on where all this would happen.

3) I echoed @alerickson's feedback on reverting the *url to *uri change for LicenseUrl, IconUrl, ProjectUrl in a few documentation files just so that we don't miss it.

Thanks for making all these changes, it's looking great :D

2021-11-29 18:15 UTC, anamnavi commented on Docs/PublishPSResource.md
> +[[-APIKey] <string>] [-Repository <string>] [-DestinationPath <string>] [-Path] <string>] [-Credential <pscredential>] [-SkipDependenciesCheck] [-ReleaseNotes <string>] [-Tags <string[]>] [-LicenseUr
per @alerickson 's comment please revert this to *url for the LicenseUrl/ProjectUrl/IconUrl cases in this file. I'm just commenting so we don't miss anything, thanks for tackling changes to so many files :)

2021-11-29 18:15 UTC, anamnavi commented on Docs/RegisterPSResourceRepository.md
> +Tests able to register repositories with different allowed URI schemes.
```suggestion
Tests able to register repositories with different allowed URI schemes.
```
```suggestion
Tests able to register repositories with different allowed Uri schemes.
```

2021-11-29 18:15 UTC, anamnavi commented on Docs/RegisterPSResourceRepository.md
> +Tests able to register repositories with different allowed URI schemes.
sorry I shouldn't have made Uri upper case initially in the comment, if you can change it to lower case per the suggestion that would be great :)

2021-11-29 18:15 UTC, anamnavi commented on Docs/UnregisterPSResourceRepository.md
> +Tests able to unregister repositories with different allowed URI schemas.
```suggestion
Tests able to unregister repositories with different allowed URI schemas.
```
```suggestion
Tests able to unregister repositories with different allowed Uri schemas.
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/PSRepositoryInfo.cs
> +        /// the URI for the repository
```suggestion
        /// the URI for the repository
```
```suggestion
        /// the Uri for the repository
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/FindHelper.cs
> +            if (repositoryUri.Scheme == Uri.UriSchemeFile)
while not needed per se, this would make it consistent with how it's referenced in RegisterPSResourceRepository.cs

```suggestion
            if (repositoryUri.Scheme == Uri.UriSchemeFile)
```
```suggestion
            if (repositoryUri.Scheme == System.Uri.UriSchemeFile)
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +        /// Updates a repository name, URI, priority, or installation policy
```suggestion
        /// Updates a repository name, URI, priority, or installation policy
```
```suggestion
        /// Updates a repository name, Uri, priority, or installation policy
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                // A null URI value passed in signifies the URI was not attempted to be set.
```suggestion
                // A null URI value passed in signifies the URI was not attempted to be set.
```
```suggestion
                // A null Uri value passed in signifies the Uri was not attempted to be set.
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                // So only set URI attribute if non-null value passed in for repoUri
```suggestion
                // So only set URI attribute if non-null value passed in for repoUri
```
```suggestion
                // So only set Uri attribute if non-null value passed in for repoUri
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    throw new PSInvalidOperationException(String.Format("Unable to read incorrectly formatted URI for repo {0}", repoName));
suggesting this so we can match casing for cmdlet parameters (that you made in this PR):
```suggestion
                    throw new PSInvalidOperationException(String.Format("Unable to read incorrectly formatted URI for repo {0}", repoName));
```
```suggestion
                    throw new PSInvalidOperationException(String.Format("Unable to read incorrectly formatted Uri for repo {0}", repoName));
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                        tempErrorList.Add(String.Format("Unable to read incorrectly formatted URI for repo {0}", repo.Attribute("Name").Value));
```suggestion
                        tempErrorList.Add(String.Format("Unable to read incorrectly formatted URI for repo {0}", repo.Attribute("Name").Value));
```
```suggestion
                        tempErrorList.Add(String.Format("Unable to read incorrectly formatted Uri for repo {0}", repo.Attribute("Name").Value));
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                            tempErrorList.Add(String.Format("Unable to read incorrectly formatted URI for repo {0}", node.Attribute("Name").Value));
```suggestion
                            tempErrorList.Add(String.Format("Unable to read incorrectly formatted URI for repo {0}", node.Attribute("Name").Value));
```
```suggestion
                            tempErrorList.Add(String.Format("Unable to read incorrectly formatted Uri for repo {0}", node.Attribute("Name").Value));
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/SetPSResourceRepository.cs
> +            // determine if either 1 of 3 values are attempting to be set: URI, Priority, Trusted.
```suggestion
            // determine if either 1 of 3 values are attempting to be set: URI, Priority, Trusted.
```
```suggestion
            // determine if either 1 of 3 values are attempting to be set: Uri, Priority, Trusted.
```

2021-11-29 18:15 UTC, anamnavi commented on src/code/SetPSResourceRepository.cs
> +                throw new ArgumentException("Either URI, Priority or Trusted parameters must be requested to be set");
match cmdlet parameter casing:
```suggestion
                throw new ArgumentException("Either URI, Priority or Trusted parameters must be requested to be set");
```
```suggestion
                throw new ArgumentException("Either Uri, Priority or Trusted parameters must be requested to be set");
```

2021-11-29 18:15 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
> +    It "set repository given Name and URI parameters" {
while PowerShell is case insensitive, it would be nice to match casing of cmdlet parameters (per changes you made in this PR)
```suggestion
    It "set repository given Name and URI parameters" {
```
```suggestion
    It "set repository given Name and Uri parameters" {
```

2021-11-29 18:15 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
> +        Register-PSResourceRepository -Name "testRepository" -URI $tmpDir1Path
please make the following change (as well as for the instances of "URI" below. Sorry for making it uppercase in the original code, was by accident):
```suggestion
        Register-PSResourceRepository -Name "testRepository" -URI $tmpDir1Path
```
```suggestion
        Register-PSResourceRepository -Name "testRepository" -Uri $tmpDir1Path
```

2021-11-29 18:15 UTC, anamnavi commented on test/UnregisterPSResourceRepository.Tests.ps1
> +        Register-PSResourceRepository -Name "testRepository" -URI $tmpDir1Path
please make the following change also for lines 33, 34, 49 (sorry for unintentionally making them upper case in the original code but we should have them match the case of the cmdlet parameter Uri):
```suggestion
        Register-PSResourceRepository -Name "testRepository" -URI $tmpDir1Path
```
```suggestion
        Register-PSResourceRepository -Name "testRepository" -Uri $tmpDir1Path
```

2021-11-29 18:15 UTC, anamnavi commented on test/RegisterPSResourceRepository.Tests.ps1
> +    It "register repository given Name, URI (bare minimum for NameParameterSet)" {
we should match cmdlet parameter's casing (i.e Uri). Please also make this change for lines 36, 44, 143, 147, 151, 155, 164, and 224:
```suggestion
    It "register repository given Name, URI (bare minimum for NameParameterSet)" {
```
```suggestion
    It "register repository given Name, Uri (bare minimum for NameParameterSet)" {
```

2021-11-29 18:15 UTC, anamnavi commented on .gitignore
> +test/result*
please remove this change, I imagine it's to ignore local test result files created on your machine.

2021-11-29 20:45 UTC, fsackur commented
My thanks for the detail - this represents a lot of review work. I will not be able to look at it for 10 days at least - I aim to update the PR by 2021-12-16.

2022-01-24 10:56 UTC, fsackur commented
Aplogies for sitting on this so long, after anamnavi put so much time into review. I will update the PR this week

2022-01-24 12:11 UTC, kilasuit commented
@alerickson / @anamnavi  - It's worth remembering that whilst nuget uses `ProjectURL` & `LicenseURL`, PowerShell Module Manifests have always used `ProjectUri` & `LicenseUri` as their properties as can be seen in the [New-ModuleManifest doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-7.2#example-1---create-a-new-module-manifest)

Whilst I haven't looked deeply at this repositories code base (or this PR either) we need to be sure that the module manifest is correct as people who run the following would end up being broken if the resultant manifest uses `Url` not `Uri` in all the properties in the PSData hashtable under the PrivateData HashTable.

Just thought it worth mentioning

2022-01-30 19:57 UTC, fsackur commented on .gitignore
> +test/result*
My bad, removed

2022-01-30 19:59 UTC, fsackur commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("licenseuri"))
Done

2022-01-30 19:59 UTC, fsackur commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("licenseUri", parsedMetadataHash["licenseuri"].ToString().Trim());
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("projecturi"))
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("projectUri", parsedMetadataHash["projecturi"].ToString().Trim());
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +            if (parsedMetadataHash.ContainsKey("iconuri"))
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +                metadataElementsDictionary.Add("iconUri", parsedMetadataHash["iconuri"].ToString().Trim());
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +                <licenseUri>https://licenses.nuget.org/MIT</licenseUri>
Done

2022-01-30 20:00 UTC, fsackur commented on src/code/PublishPSResource.cs
> +                <projectUri>https://github.com/PowerShell/PowerShell</projectUri>
Done

2022-01-30 20:06 UTC, fsackur commented on test/PublishPSResource.Tests.ps1
> +        $expectedNuspecContents.Contains($projectUri) | Should Be $true
Done

2022-01-30 20:06 UTC, fsackur commented on test/PublishPSResource.Tests.ps1
> +        Publish-PSResource -Path $script:PublishModuleBase -ProjectUri $projectUri
Done

2022-01-30 20:06 UTC, fsackur commented on test/PublishPSResource.Tests.ps1
> +    It "Publish a module with -ProjectUri" {
Done

2022-01-30 20:06 UTC, fsackur commented on test/PublishPSResource.Tests.ps1
> +        $expectedNuspecContents.Contains($iconUri) | Should Be $true
Done

2022-01-30 20:07 UTC, fsackur commented on Docs/PublishPSResource.md
> +[[-APIKey] <string>] [-Repository <string>] [-DestinationPath <string>] [-Path] <string>] [-Credential <pscredential>] [-SkipDependenciesCheck] [-ReleaseNotes <string>] [-Tags <string[]>] [-LicenseUr
Docs deleted upstream

2022-01-30 20:08 UTC, fsackur commented on Docs/RegisterPSResourceRepository.md
> +Tests able to register repositories with different allowed URI schemes.
Docs deleted in HEAD

2022-01-30 20:08 UTC, fsackur commented on Docs/UnregisterPSResourceRepository.md
> +Tests able to unregister repositories with different allowed URI schemas.
Docs deleted in HEAD

2022-01-30 22:55 UTC, fsackur commented
Thanks for the feedback, I have addressed the points. Can I get a re-review?

@anamnavi you asked me to pascal-case some `URI`s in some strings and comments. I've changed a few. Mainly, I've used `Uri` where the comment refers to the parameter and `URI` when expressing an actual URI. That's the style I've seen the most. It seems more natural in a sentence. Want me to change?

2022-02-01 19:32 UTC, alerickson requested changes
Looks good, just a couple of spots that both @anamnavi and I added suggested changes to be consistent with the Pascal casing of 'Uri'.  Once those are in this should be good to go 😄

2022-02-01 19:32 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +            if (repoUri == null || !(repoUri.Scheme == System.Uri.UriSchemeHttp || repoUri.Scheme == System.Uri.UriSchemeHttps || repoUri.Scheme == System.Uri.UriSchemeFtp || repoUri.Scheme == System
Is the `System.`  needed here?

2022-02-01 19:32 UTC, alerickson commented on src/code/Utils.cs
> +                // This is needed for a relative path uri string. Does not throw error for an absolute path.
```suggestion
                // This is needed for a relative path URI string. Does not throw error for an absolute path.
```

2022-02-01 19:32 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +                throw new ArgumentException("The PSGallery repository has a pre-defined URI. Setting the -Uri parameter for this repository is not allowed, instead try running 'Register-PSResourceRep
```suggestion
                throw new ArgumentException("The PSGallery repository has a pre-defined Uri. Setting the -Uri parameter for this repository is not allowed, instead try running 'Register-PSResourceRepository -PSGallery'.");
```

2022-02-01 19:32 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +            // check PSGallery URI is not trying to be set
```suggestion
            // check PSGallery Uri is not trying to be set
```

2022-02-01 19:32 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +                throw new ArgumentException("Invalid URI, must be one of the following URI schemes: HTTPS, HTTP, FTP, File Based");
```suggestion
                throw new ArgumentException("Invalid Uri, must be one of the following Uri schemes: HTTPS, HTTP, FTP, File Based");
```

2022-02-01 19:32 UTC, alerickson commented on src/code/RepositorySettings.cs
> +        /// Updates a repository name, URI, priority, installation policy, or credential information
```suggestion
        /// Updates a repository name, Uri, priority, installation policy, or credential information
```

2022-02-01 19:32 UTC, alerickson commented on help/Register-PSResourceRepository.md
> +URI can be of the following URI schemas: HTTPS, HTTP, FTP, file share based.
```suggestion
Uri can be of the following Uri schemas: HTTPS, HTTP, FTP, file share based.
```

2022-02-01 19:32 UTC, alerickson commented on help/Register-PSResourceRepository.md
> +URI string input must be of one of the following URI schemes: HTTP, HTTPS, FTP, File
```suggestion
Uri string input must be of one of the following Uri schemes: HTTP, HTTPS, FTP, File
```

2022-02-01 20:31 UTC, fsackur commented on src/code/RegisterPSResourceRepository.cs
> +            if (repoUri == null || !(repoUri.Scheme == System.Uri.UriSchemeHttp || repoUri.Scheme == System.Uri.UriSchemeHttps || repoUri.Scheme == System.Uri.UriSchemeFtp || repoUri.Scheme == System
Yes, to disambiguate from the `Uri` param at L54

2022-02-01 20:38 UTC, fsackur commented on src/code/RegisterPSResourceRepository.cs
> +                throw new ArgumentException("Invalid URI, must be one of the following URI schemes: HTTPS, HTTP, FTP, File Based");
```suggestion
                throw new ArgumentException("Invalid Uri, must be one of the following Uri schemes: HTTPS, HTTP, FTP, File Based");
```

2022-02-01 20:39 UTC, fsackur commented on src/code/RegisterPSResourceRepository.cs
> +                        new PSInvalidOperationException("Repository URI cannot be null"),
```suggestion
                        new PSInvalidOperationException("Repository Uri cannot be null"),
```

2022-02-01 20:44 UTC, fsackur commented
I take that feedback to mean that `URI` should always be `Uri` in comments and strings, so I have changed all occurrences in https://github.com/PowerShell/PowerShellGet/pull/551/commits/6c92c80e16fcdec4b767b32a98b24f4cafe715be

2022-02-02 02:18 UTC, alerickson commented
Thanks for giving us a heads up on that @kilasuit!  I'm going to open up an issue so that we can test and make sure we have the 'projectUrl' or 'projectUri' and 'iconUrl' or 'iconUri' in the appropriate places.  I'll open up a new PR to fix any changes there and add you to review it (no pressure to if you'd rather not).

2022-02-02 02:40 UTC, alerickson approved these changes

2022-02-03 18:43 UTC, fsackur commented
I did publish a module to the gallery from this branch. I was then able to find it; it did have project and licese properties as set in my .psd1.

2022-02-03 18:58 UTC, fsackur commented
@anamnavi thanks for all the work you and @alerickson have put into this review. I have taken your review comments to mean that I should change `URI` => `Uri` in ALL comments and strings, so I've done that in ALL occurrences (there were a few that you hadn't highlighted). 

The only places where all-caps `URI` still appear:

```
Path                       LineNumber Line
----                       ---------- ----
.\CHANGELOG.md                     38 - Fix bug to register repositories with local file share paths, ensuring repositories with valid URIs can be registered.
.\test\PSGetModuleInfo.xml         34       <URI N="LicenseUri">https://github.com/PowerShell/SecretManagement/blob/master/LICENSE</URI>
.\test\PSGetModuleInfo.xml         35       <URI N="ProjectUri">https://github.com/powershell/secretmanagement</URI>
.\test\PSGetTestUtils.psm1        514 .LICENSEURI$(if ($LicenseUri) {" $LicenseUri"})
.\test\PSGetTestUtils.psm1        516 .PROJECTURI$(if ($ProjectUri) {" $ProjectUri"})
.\test\PSGetTestUtils.psm1        518 .ICONURI$(if ($IconUri) {" $IconUri"})
```

I can haz merge?

2022-02-03 21:01 UTC, anamnavi approved these changes

2022-02-03 21:01 UTC, anamnavi commented on src/code/FindHelper.cs
> +            if (repositoryUri.Scheme == Uri.UriSchemeFile)
fine as is

2022-02-03 21:14 UTC, anamnavi commented on src/PowerShellGet.psd1
> +    HelpInfoUri       = 'http://go.microsoft.com/fwlink/?linkid=855963'
@fsackur can you please revert this change specifically? Like just change it back to "HelpInfoURI".
This variable is uppercased "URI" (i.e HelpInfoURI) in the module manifest files for packages on PSGallery. Example: https://www.powershellgallery.com/packages/PowerShellGet/2.2.5/Content/PowerShellGet.psd1   L286).

2022-02-03 21:17 UTC, anamnavi commented
@fsackur thank you for the hard work and being so diligent with these changes and also sharing the rule of thumb you used when changing URI => Uri in all strings and comments, that's helpful for us to know! Sorry for the late response and review, I was a little out of it after my booster shot. This looks good to me, only one minor change request, per my comment right above this one (it's just a capitalization change for consistency sake with other .psd1 files, and is just a small nitpick if you don't mind addressing that). Thank you for your contribution! :D

2022-02-03 21:57 UTC, alerickson commented on src/PowerShellGet.psd1
> +    HelpInfoUri       = 'http://go.microsoft.com/fwlink/?linkid=855963'
Actually I just noticed 'ProjectUri' and 'LicenseUri' both have Uri in Pascal case, so I think we should leave this as is for now

2022-02-03 21:58 UTC, anamnavi commented on src/PowerShellGet.psd1
> +    HelpInfoUri       = 'http://go.microsoft.com/fwlink/?linkid=855963'
okay that makes sense. I'll merge the PR in then :)

2022-02-03 21:58 UTC, merged