Install progressbar
PowerShell/PSResourceGet pull request #552
Opened 2021-11-23 20:32 UTC by anamnavi

# PR Summary

Add Progress Bar for Install-Helper. This means that cmdlets which call into Install-Helper (i.e. Update/Save) will now also have a progress bar displayed while the install portion of the operation is occurring.

## PR Context

Part of missing cmdlet implementation, resolves #518 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-11-29 17:59 UTC, alerickson approved these changes
Looks good to me!

2021-11-29 18:55 UTC, PaulHigin requested changes

2021-11-29 18:55 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    pckgNamesToInstall,
Nitpick.  We should use consistent naming ... 'pkgNamesToInstall'.

2021-11-29 18:55 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            for (int i = 0; i < pkgsToInstall.Count(); i++)
It is inefficient to pass in an enumerator and then use it like an array type.  Here, I think we can use foreach, and create a new 'count' variable outside the loop to keep track of the install package number.

2021-11-29 18:55 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            int j = 1;
Please use descriptive variable names:
```csharp
int totalPkgCount = 0;
int dependentPkgCount = 1

foreach (var pkg in pkgsToInstall)
{
    totalPkgCount++;
    ...
}
```

2021-11-30 20:59 UTC, PaulHigin approved these changes
Also, please remove the unused 'repoName' parameter in the `private List<string> InstallPackage` method.

2021-11-30 20:59 UTC, PaulHigin commented on src/code/InstallHelper.cs
>              string repoName,
Also, I notice that 'repoName' argument is not used.  Please remove.

2021-11-30 20:59 UTC, PaulHigin commented on src/code/InstallHelper.cs
>              string repoName,
@anamnavi

2021-11-30 21:54 UTC, anamnavi commented on src/code/InstallHelper.cs
>              string repoName,
I removed this

2021-11-30 22:04 UTC, merged