Install should not silently fail
PowerShell/PSResourceGet pull request #554
Opened 2021-12-01 21:12 UTC by anamnavi

# PR Summary

Install-PSResource should not fail silently. Most of these cases were resolved by PR #525. However for the cases where a package name requested to be installed doesn't exist we want it to not fail silently. Instead the cmdlet should write out a Warning message indicating that the installation didn't happen successfully.

## PR Context

Resolves #154

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2021-12-01 21:21 UTC, anamnavi commented on src/code/InstallPSResource.cs
Given that we have a for loop for the `- PassThru` condition next, the runtime of this check for whether packages we expected to be installed were actually installed plus the -PassThru check ends up being O(n) + O(n) + O(n) = 3 O(n).

An alternative solution is listed below. With this the runtime would be O(n) + O(n) = 2 O(n). It also doesn't use LINQ. However I feel like the original solution is more clear and the different operations are separated out better for clarity. Also, `-PassThru` won't always be used so runtime may be 2 O(n) most of the time.
```suggestion
            List<string> actualPkgNames = new List<string>();
            foreach (PSResourceInfo pkg in installedPkgs)
            {
                actualPkgNames.Add(pkg.Name);
                if (PassThru)
                {
                    WriteObject(pkg);
                }
            }

            foreach (string expectedName in pkgNames)
            {
                if (!actualPkgNames.Contains(expectedName))
                {
                    WriteWarning(String.Format("Package '{0}' was not installed. Please run the cmdlet with -Verbose to see more information", expectedName));
                }
            }
```

2021-12-01 21:43 UTC, alerickson approved these changes

2021-12-01 21:43 UTC, alerickson commented on src/code/InstallPSResource.cs
I prefer the implementation that's currently in the code.  I think it's a little cleaner and easier to understand and to me the efficiency benefits vs the implementation above seems minimal.

2021-12-01 21:43 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                    WriteWarning(String.Format("Package '{0}' was not installed. Please run the cmdlet with -Verbose for more information", expectedPkgName));
If we get to this point, does that mean that the package simply wasn't found in any of the repositories?  Should we specify that and then suggest running -Verbose for more info if desired?

2021-12-01 21:54 UTC, PaulHigin requested changes

2021-12-01 21:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +            List<string> actualPkgNames = installedPkgs.Select(x => x.Name).ToList();
```suggestion
            List<string> installedPkgNames = installedPkgs.Select(x => x.Name).ToList();
```

2021-12-01 21:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
I think Linq is fine in this case.
However, we should emit an error if a requested resource package could not be installed.
It would be nice to include the reason the install failed (not found, file error, etc.), maybe InstallerHelper.InstallPackages() can return an array of error records?

2021-12-03 22:41 UTC, anamnavi commented on src/code/InstallPSResource.cs
I changed the logic altogether, please see edited description in the PR Summary.

2021-12-06 23:12 UTC, PaulHigin approved these changes
LGTM

2021-12-07 17:47 UTC, merged