Implement RequiredResourceFile and RequiredResource parameters
PowerShell/PSResourceGet pull request #592
Opened 2022-01-14 20:35 UTC by alerickson

# PR Summary
This is the implementation for the -RequiredResourceFile and -RequiredResource parameters as specified in the [RFC](https://github.com/PowerShell/PowerShell-RFC/blob/17ecbf7c091dca0c00bad7eb5054491d9d5a0639/2-Draft-Accepted/RFCxxxx-PowerShellGet-3.0.md#dependencies-and-version-management).

One note here:  the RFC specifies that -RequiredResourceFile take in a .psd1.  This is not implemented yet as the specs defining what exactly should be done here is not yet complete.  The idea behind accepting a .psd1 file is to mimic the behavior of [PSDepend](https://www.powershellgallery.com/packages/PSDepend/0.3.2).  Again, because there's still a lot of unknowns here, I've chosen to leave that out of this PR.   

## PR Context

This resolves issue https://github.com/PowerShell/PowerShellGet/issues/515.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-01-14 23:54 UTC, PaulHigin requested changes

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +            get {
```suggestion
            get
            {
```

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                    var exMessage = String.Format("The RequiredResourceFile does not exist.  Please try specifying a path to a valid .json or .psd1 file");
We don't currently support .psd1 files, correct?

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +            get { return _requiredResourceHash != null ? (Object)_requiredResourceHash : (Object)_requiredResourceJson; }
Cast to 'Object' should not be needed here.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (value.GetType().Name.Equals("String"))
Suggest:
```csharp
if (value is String jsonResource)
{
    _requiredResourceJson = jsonResource;
}
else if (value is Hashtable hashResource)
{
    _requiredResourceHash = hashResource;
}
else ...
```

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                            pkgsInJson = JsonConvert.DeserializeObject<Hashtable>(_requiredResourceJson, new JsonSerializerSettings { MaxDepth = 6 });
Rather than taking a dependency on `Newtonsoft.Json`, I feel we should just use PowerShell's `ConvertFrom-Json`.  This can be a Utility function, like: https://github.com/PowerShell/PowerShellGet/blob/1242151789400fc6cda38cb16e68f8a6451038f7/src/code/Utils.cs#L741

We should look at removing the `Newtonsoft.Json.dll` file from the binaries we ship if we don't need it.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                        pkgsInJsonFile = JsonConvert.DeserializeObject<Hashtable>(requiredResourceFileStream, new JsonSerializerSettings { MaxDepth = 6 });
Same comment to not use `JsonConvert.DeserializeObject`.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                            pkgsInJson = JsonConvert.DeserializeObject<Hashtable>(_requiredResourceJson, new JsonSerializerSettings { MaxDepth = 6 });
This converts json to Hashtable, right?  So variable name should be `pkgsHash` or something.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                    var pkgParamJTokens = pkgParamInfo as Newtonsoft.Json.Linq.JToken;
Not sure why this is needed.  But if some Hashtable values return json, please use `ConvertFrom-Json` utility to convert to hash table.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (pkgParamInfo is Hashtable)
```csharp
if (pkgParameInfo is Hashtable pkgInstallHash)
{
    ...
}
```

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPkgParams.cs
> +	public bool SkipDependencyCheck { get; set; }
```suggestion
public bool SkipDependencyCheck { get; set; }

```
This is using tab character for indent.  Please be sure to conform to tab == whitespace convention so our source file formats are consistent.

2022-01-14 23:54 UTC, PaulHigin commented on src/code/InstallPkgParams.cs
> +                break;
Please add `default:` case.  We may want to assert if an unknown name is unexpected.

2022-01-15 01:27 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                    var pkgParamJTokens = pkgParamInfo as Newtonsoft.Json.Linq.JToken;
I'll try that, this cast was needed to extract values out of the object.  But probably moot since this JSON conversion will be changed anyway.

2022-01-15 01:29 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                            pkgsInJson = JsonConvert.DeserializeObject<Hashtable>(_requiredResourceJson, new JsonSerializerSettings { MaxDepth = 6 });
Yup, that makes much more sense, I'll do that and try to completely remove Newtonsoft

2022-01-15 01:30 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                    var exMessage = String.Format("The RequiredResourceFile does not exist.  Please try specifying a path to a valid .json or .psd1 file");
Correct, I'll remove that section

2022-01-21 23:05 UTC, PaulHigin approved these changes
LGTM

2022-01-21 23:06 UTC, merged