Add support for Uninstall-PSResource
PowerShell/PSResourceGet pull request #593
Opened 2022-01-19 03:18 UTC by anamnavi

# PR Summary

Add support for Uninstall-PSResource -Prerelease parameter. It should support the following cases:
`Uninstall-PSResource -Name "MyPkg" -Version "*" ` --> should uninstall all versions (stable and prerelease versions)
`Uninstall-PSResource -Name "MyPkg" -Version "*" -Prerelease` --> should only uninstall prerelease versions

For Get-PSResource, prerelease versions support is present as of 3.0.12-beta. The following scenarios are confirmed. There are no changes for Get-PSResource (sorry couldn't rename the branch).

`Get-PSResource -Name "MyPkg"` --> returns all versions (stable and prerelease)
Given: MyPkg version 3.0.0-preview is installed on machine
`Get-PSResource -Name "MyPkg" -Version "3.0.0-preview"` --> will return MyPkg version 3.0.0-preview
`Get-PSResource -Name "MyPkg" -Version "3.0.0"` --> won't return MyPkg version 3.0.0-preview as full version (with prerelease label wasn't specified)
`Get-PSResource -Name "MyPkg" -Version "[3.0.0-preview, 5.0.0]" --> will return all versions (stable and prerelease which fall within this version range)

## PR Context

Resolves #467 #440 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-01-21 21:18 UTC, PaulHigin requested changes

2022-01-21 21:18 UTC, PaulHigin commented on src/code/GetHelper.cs
> +                            if (!selectPrereleaseOnly)
Suggest:
```csharp
if (!selectPrereleaseOnly || pkgNugetVersion.IsPrerelease)
{
    yield return versionPath;
}
```

2022-01-22 02:57 UTC, alerickson approved these changes
Looks good!  I agree with Paul's suggestion but everything else looks solid.  Thanks for the detailed comments, it's super helpful to quickly see why the param should be true or false for various calls.

2022-02-04 15:48 UTC, anamnavi commented on src/code/GetHelper.cs
> +                            if (!selectPrereleaseOnly)
good call, thanks. I pushed this change.

2022-02-04 16:36 UTC, PaulHigin approved these changes

2022-02-04 18:36 UTC, merged