WIP: Script file info cmdlets
PowerShell/PSResourceGet pull request #602
Opened 2022-01-31 17:16 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-06-09 20:22 UTC, PaulHigin requested changes

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        [Parameter]
We don't need the [Parameter] and [Validate...] attributes on these properties.

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        #region Constructor
Please add white space after #region and #endregion.

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        public string[] Role { get; set; } = new string[]{};
Would we want a `private set`, indicating that this object is readonly and immutable.

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        public static bool TryParseScriptFile(
Should this be internal access, or will users need to use it?

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            /* <#PSScriptInfo
At some point just create a document issue for documenting what a script file should contain.  Not a blocker.

2022-06-09 20:22 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            List<Token> commentTokens = tokens.Where(a => String.Equals(a.Kind.ToString(), "Comment", StringComparison.OrdinalIgnoreCase)).ToList();
regex pattern should match to beginning of line.

2022-06-14 21:01 UTC, anamnavi commented
still need to warn/alert user if update will violate signature

2022-06-22 04:09 UTC, alerickson reviewed
I added a lot of suggestions to remove things then later realized you're still modifying and incorporating comments from our previous group code reviews, so feel free to ignore anything that's irrelevant.  

Everything's looking good!  I just wanted to add if you'd like help with writing tests I'm more than happy to help out wherever you'd like

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +### -PassThru
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +When specified, displays the PSScriptFileInfo object representing the script metadata.
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +```yaml
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Type: SwitchParameter
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Parameter Sets: (All)
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Aliases:
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Required: False
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Position: Named
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Default value: None
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Accept pipeline input: False
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +Accept wildcard characters: False
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +```
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on help/Test-PSScriptFileInfo.md
> +
```suggestion
```
Test-PSScriptFileInfo .\testscript.ps1
```
```

2022-06-22 04:09 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> +
```suggestion
```
New-PSScriptFileInfo .\myscript.ps1
```
```

2022-06-22 04:09 UTC, alerickson commented on help/Update-PSScriptFileInfo.md
> +
```suggestion
```
Update-PSScriptFileInfo -FilePath .\myscript.ps1 -Version "2.0.0"
```
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +        /// <summary>
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +        /// If specified, the .ps1 file contents are additionally written out to the console
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +        /// </summary>
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +        [Parameter]
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +        public SwitchParameter PassThru { get; set; }
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +            if (PassThru)
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +            {
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +                WriteObject(psScriptFileContents);
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +            }
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +            using(FileStream fs = File.Create(FilePath))
I don't think this needs to be changed, but I just wanted to mention StreamWriter as an alternative here, especially as we're just writing text.

2022-06-22 04:09 UTC, alerickson commented on src/PowerShellGet.psd1
> +        'Test-VersionEquality',
Is this supposed to be a public/user facing cmdlet?

2022-06-22 04:09 UTC, alerickson commented on src/code/PSScriptFileInfo.cs
> +            string[] newlineDelimeters = new string[]{"\r\n", "\n"}; // TODO should I also have \n?
I'm assuming you decided we do also need \n?  
Feel free to reject my suggestion of course, but just going to get rid of the comment if it's no longer needed 😃 :

2022-06-22 04:09 UTC, alerickson commented on src/code/PSScriptFileInfo.cs
> +            string[] newlineDelimeters = new string[]{"\r\n", "\n"}; // TODO should I also have \n?
```suggestion
            string[] newlineDelimeters = new string[]{"\r\n", "\n"};
```

2022-06-22 04:09 UTC, alerickson commented on src/code/PSScriptFileInfo.cs
> +            // TODO: I think hashtable keys should be lower cased
You can also make the hashtable keys case insensitive if that's what you're concerned about.

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        /// <summary>
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        /// If specified, passes the contents of the created .ps1 file to the console
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        /// If -Path is not specified, then .ps1 contents will just be written out for the user
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        /// </summary>
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        [Parameter]
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +        public SwitchParameter PassThru { get; set; }
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +            // TODO: put this in a try catch
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +            // TODO: ceck with Sydney if we wnat to return PSScriptFileInfo obj?
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +            if (PassThru)
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +            {
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +                WriteObject(updatedPSScriptFileContents);
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +            }
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/Utils.cs
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/Utils.cs
> +
```suggestion
```

2022-06-22 04:09 UTC, alerickson commented on src/code/Utils.cs
> +                    Guid moduleSpecGuid = moduleSpec.ContainsKey("Guid") ? (Guid) moduleSpec["Guid"] : Guid.Empty; // TODO: ANAM this can be the default
```suggestion
                    Guid moduleSpecGuid = moduleSpec.ContainsKey("Guid") ? (Guid) moduleSpec["Guid"] : Guid.Empty;
```

2022-06-22 04:09 UTC, alerickson commented on test/NewPSScriptFileInfo.Tests.ps1
> +    # TODO: test with each param really....would be easier to test if we returned PSSriptFileInfoObject with PassThru
I can help with writing tests if you like

2022-06-22 04:09 UTC, alerickson commented on test/TestPSScriptFileInfo.Tests.ps1
> +        # TODO: how to test for warnings? (psScriptMissingAuthor)
Missing author should throw an error, right (same with version, description, and guid)?

2022-06-22 20:57 UTC, anamnavi commented on test/TestPSScriptFileInfo.Tests.ps1
> +        # TODO: how to test for warnings? (psScriptMissingAuthor)
Currently Test-PSScriptFileInfo writes a warning with the errors, instead of directly writing errors or throwing them. The cmdlet also returns false. This is because if this cmdlet were run in a pipeline we wouldn't want pipeline execution to stop and thus don't want to write or throw errors, just warnings. This is my understanding, but happy to change it. We can discuss with Paul & Sydney.

2022-06-22 20:58 UTC, anamnavi commented on src/PowerShellGet.psd1
> +        'Test-VersionEquality',
oh that got added by mistake, I've removed that.

2022-06-22 21:13 UTC, anamnavi commented on src/code/NewPSScriptFileInfo.cs
> +            using(FileStream fs = File.Create(FilePath))
resolved, doing File.WriteAllText() now

2022-06-22 21:13 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            string[] newlineDelimeters = new string[]{"\r\n", "\n"}; // TODO should I also have \n?
yea we also needed to delimeter by \n. Sorry I left a bunch of old comments in here

2022-06-22 21:19 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            // TODO: I think hashtable keys should be lower cased
made this change, thanks!

2022-07-06 14:34 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            /* <#PSScriptInfo
I'll work to create this.

2022-07-06 18:21 UTC, alerickson approved these changes

2022-07-06 18:21 UTC, alerickson commented on src/code/NewPSScriptFileInfo.cs
> +using Microsoft.PowerShell.PowerShellGet.UtilClasses;
nit: just to move this below with the other using statements and get rid of whitespace

2022-07-06 18:21 UTC, alerickson commented on src/code/UpdatePSScriptFileInfo.cs
> +using Microsoft.PowerShell.PowerShellGet.UtilClasses;
same nit here

2022-07-06 21:01 UTC, PaulHigin requested changes

2022-07-06 21:01 UTC, PaulHigin commented on src/code/NewPSScriptFileInfo.cs
> +    /// Creates a new .ps1 file with script information required for publishing a script
Nitpick.  Line comments should always end with '.'.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/NewPSScriptFileInfo.cs
> +                uriResult: out projectUri,
We can remove the Uri declaration at the top of each of these TryCreateValidUri.

```suggestion
                uriResult: out Uri projectUri,
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/NewPSScriptFileInfo.cs
> +        protected override void ProcessRecord()
Since we do not handle any pipeline input, this should be done in the `EndProcessing()` block.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/NewPSScriptFileInfo.cs
> +            PSScriptFileInfo currentScriptInfo = new PSScriptFileInfo(
```suggestion
            PSScriptFileInfo scriptInfo = new PSScriptFileInfo(
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        internal static bool TryParseScript(
```suggestion
        private static bool TryParseScriptFile(
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            if (ast == null)
Can this ever happen?  I assume Parser.ParseFile() will always return non-null Ast if no errors are returned.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            var contentAfterDescription = contentAfterAndIncludingDescription.SkipWhile(x => !x.Contains("#>")).Skip(1).ToList();
Why convert to list here and then immediately convert to array below?

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        internal static bool TryValidateScript(
```suggestion
        private static bool TryValidateScript(
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            if (errors.Length > 0)
```suggestion
            return (errors.Length == 0);
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        internal static bool TryParseScriptIntoPSScriptInfo(
```suggestion
        internal static bool TryParseScriptFile(
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                        verboseMsgsList.Add("LicenseUri property could not be created as a Uri");
I think this should at least be a warning.  If we are updating a script file, this ends up removing the previous license uri.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        )
Style: Closing parentheses never appear on separate line.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +
Remove extra white space.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        #region Private Methods
Always extra line after '#region'

2022-07-06 21:01 UTC, PaulHigin commented on src/code/TestPSScriptFileInfo.cs
> +using System.Net;
Should not be above copyright notice.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                if (EndOfFileContents.Contains(signatureStartString))
This test can be moved into 'RemoveSignatureString()', which will do nothing if there is no signature block.

2022-07-06 21:01 UTC, PaulHigin commented on src/code/UpdatePSScriptFileInfo.cs
> +                    var exMessage = "Cannot update script as the .ps1 contains a signature. Either use -RemoveSignature paramter or manaully remove signature block and re-run cmdlet.";
```suggestion
                    var exMessage = "Cannot update the script file because the file contains a signature block and updating will invalidate the signature. Use -RemoveSignature to remove the signature block, and then re-sign the file after it is updated.";
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/Utils.cs
> +                return new string[]{};
```suggestion
                return Utils.EmptyStrArray;
```

2022-07-06 21:01 UTC, PaulHigin commented on src/code/Utils.cs
> +                    currentModuleSpec = new ModuleSpecification(moduleSpecName);
Is there a reason why we are not using `ModuleSpecification.TryParse()`?

2022-07-06 21:01 UTC, PaulHigin commented on test/PSGetTestUtils.psm1
>          if(Test-Path -Path $path)
Why are we not using Pester `$TestDrive`?

2022-07-06 21:01 UTC, PaulHigin commented on test/NewPSScriptFileInfo.Tests.ps1
> +        $tmpDir1Path = Join-Path -Path $TestDrive -ChildPath "tmpDir1"
All test directories created under Pester `$TestDrive` get cleaned up automatically.  You should not have to manually remove them.

2022-07-06 21:01 UTC, PaulHigin commented on test/UpdatePSScriptFileInfo.Tests.ps1
> +    It "Update .ps1 file with relative path" {
Do we have a test that verifies the actual script remains unchanged after update?

2022-07-08 14:25 UTC, anamnavi commented on src/code/NewPSScriptFileInfo.cs
> +                uriResult: out projectUri,
I can't declare this inline because later on L231, when we create a PSScriptFileInfo instance, we need to pass `projectUri` to the constructor, and if I declare it inline here then it gives an error that we're using an unassigned local variable. So I need to declare it and set it to null by default.

2022-07-08 14:45 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            if (ast == null)
they checked for this in V2, so I think we should keep this early out check.

2022-07-08 14:52 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +        internal static bool TryParseScriptIntoPSScriptInfo(
you recommended this name for the method TryParseScript() -> TryParseScriptFile() in an above comment. That method parses the .ps1 file contents into a hashtable.

This method here calls that first method + also validates that all the necessary properties were found in the hashtable and finally creates the PSScriptFileInfo instance. If that helps think of another name for this method..:)

2022-07-08 15:00 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +                        verboseMsgsList.Add("LicenseUri property could not be created as a Uri");
good point! when this method returns we write a warning (in addition to verbose message) with the messages returned regarding Uri creation failing.

2022-07-11 15:42 UTC, anamnavi commented on src/code/Utils.cs
> +                    currentModuleSpec = new ModuleSpecification(moduleSpecName);
The [documentation ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.modulespecification.tryparse?view=powershellsdk-7.0.0#microsoft-powershell-commands-modulespecification-tryparse(system-string-microsoft-powershell-commands-modulespecification@))for ModuleSpecification.TryParse() isn't clear on what the value would need to look like for the `input` string parameter. So TryParse() is returing false and resulting in a null value if I swapped it in the code here. I've tried the following for what `$input` should be:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/30238344/178303196-3a06753e-e35c-4b1d-a07e-72703e168159.png">

2022-07-11 16:40 UTC, PaulHigin commented on src/code/Utils.cs
> +                    currentModuleSpec = new ModuleSpecification(moduleSpecName);
Yeah, this is a good example of a poorly designed API.  It looks like the parse will fail if the requires keyword is absent, with no error message, so we cannot use it.  Not sure why it was made public as it does not seem very useful.  Thanks for looking.

2022-07-11 16:50 UTC, anamnavi commented on test/UpdatePSScriptFileInfo.Tests.ps1
> +    It "Update .ps1 file with relative path" {
added a test to Update for this.

2022-07-11 17:52 UTC, PaulHigin requested changes

2022-07-11 17:52 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            keyName = "";
It looks like both `keyName` and `value` are only used within the for loop below.  So they can be defined there (in that scope) instead of here.

2022-07-11 17:52 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // TODO: Anam does this really need to return bool?
Please resolve the TODO.

2022-07-11 17:58 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            // TODO: Anam does this really need to return bool?
this is resolved in the latest commit.

2022-07-11 18:01 UTC, PaulHigin requested changes

2022-07-11 18:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // keyName = "";
Please don't check in commented out code.

2022-07-11 18:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            endOfFileContents = String.Join("\n", contentAfterAndIncludingDescription.SkipWhile(x => !x.Contains("#>")).Skip(1).ToArray());
I am not sure about this.  It is not clear what this is doing and whether script content, that can also include comments, is always included in endOfFileContents.  Instead of using LINQ I would prefer to see a utility method that is a bit more explicit about what it is doing.

2022-07-11 18:01 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            string keyName = "";
keyName and value variables can be defined within the for loop scope.

2022-07-11 18:03 UTC, anamnavi commented on src/code/PSScriptFileInfo.cs
> +            keyName = "";
FYI, in the latest commit this is in a helper method GetMetadataFromCommentLines().

We need the `keyName` and `value` variables defined outside the for loop, as we're iterating through lines of the metadata string. When grabbing the key name and value, the value can continue onto the next line. So for certain metadata properties we may not get all the value on that line/within the current iteration of the for loop.

2022-07-11 18:04 UTC, PaulHigin requested changes

2022-07-11 18:04 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                // if (EndOfFileContents.Contains(signatureStartString))
Please remove commented out code.

2022-07-11 21:29 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            string keyName = "";
This needs to be defined in this scope because previous iteration values can be used.

2022-07-14 23:14 UTC, anamnavi commented
this PR willl be closed in favor of #708

2022-07-20 15:15 UTC, closed without merging