Allow .psd1 to be passed into -RequiredResourceFile
PowerShell/PSResourceGet pull request #610
Opened 2022-02-12 04:03 UTC by alerickson

# PR Summary

Adding functionality to allow .psd1 files to be passed into -RequiredResourceFile in Install-PSResource. 

## PR Context

Addresses issue: https://github.com/PowerShell/PowerShellGet/issues/594
## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-02-16 19:19 UTC, PaulHigin requested changes

2022-02-16 19:19 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                if (!Utils.TryParsePsd1(
Maybe `TryParsePSDataFile` ?

2022-02-16 19:19 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (!resolvedPath.EndsWith(".json") && !resolvedPath.EndsWith(".psd1"))
You could set a private enum here that determines what kind of file:
```csharp
private enum
{
    UnknownFile = 0,
    JsonFile,
    PSDataFile
};
```
And then use that value instead of checking for file extension each time.

2022-02-16 19:19 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (!resolvedPath.EndsWith(".json") && !resolvedPath.EndsWith(".psd1"))
String compare should be case insensitive:
```csharp
resolvedPath.EndsWith(".json", StringComparison.InvariantCultureIgnoreCase);
```

2022-02-22 16:43 UTC, anamnavi requested changes
Some minor suggestions, and I also agree with Paul's idea of a private enum for type of file though

2022-02-22 16:43 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                if (!Utils.TryParsePsd1(
I like this idea as well

2022-02-22 16:43 UTC, anamnavi commented on test/InstallPSResource.Tests.ps1
> +        $rrFilePSD1 = ".\$RequiredResourcePSD1FileName"
this way it doesn't matter where you run tests from, it should be able to find this required resource psd1 file unlike with the relative path.
```suggestion
        $rrFilePSD1 = Join-Path -Path $psscriptroot -ChildPath "test" -AdditionalChildPath ".\$RequiredResourcePSD1FileName"

```

2022-02-22 16:43 UTC, anamnavi commented on test/TestRequiredResourceFile.psd1
> +}
nitpick, but add newline

2022-02-22 18:27 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                if (!resolvedPath.EndsWith(".json") && !resolvedPath.EndsWith(".psd1"))
How exactly would the private enum work?  Right now I have variables in the class instead of the hardcoded extension names, but I'm a little confused as to how the enum type works to categorize ".json" and ".psd1"

2022-02-22 18:36 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (!resolvedPath.EndsWith(".json") && !resolvedPath.EndsWith(".psd1"))
I was thinking of something like:

```csharp
ResourceFileType fileType;
if (resolvedPath.EndsWith(".json", StringComparison.InvariantCultureIgnoreCase)
{
    fileType = ResourceFileType.JsonFile;
}
else if (resolvePath.EndsWith(".psd1", StringComparison.InvariantCultureIgnoreCase)
{
    fileType = ResourceFileType.PSDataFile;
}
else
{
    // Or maybe just throw here, if no further processing can be done.
    fileType = ResourceFileType.UnknownFile;
}

// No need to check path anymore, if further processing needs to check file type.

```

2022-02-22 22:17 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                if (!resolvedPath.EndsWith(".json") && !resolvedPath.EndsWith(".psd1"))
Ah, yes.  This makes sense, I can add this

2022-02-22 23:30 UTC, PaulHigin approved these changes
Looks good after some minor changes.

2022-02-22 23:30 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +        #region Enums
Please add white space after 'Enums'

2022-02-22 23:30 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +        public enum ResourceFileType
Enum should be `private` since it is not useful for a user and is needed internally only.

2022-02-22 23:48 UTC, anamnavi approved these changes
LGTM, just one minor feedback

2022-02-22 23:48 UTC, anamnavi commented on test/TestRequiredResourceFile.psd1
> +}
still needs to be added if you can, thanks!

2022-02-23 01:13 UTC, merged