Add publisher validation to Install-PSResource
PowerShell/PSResourceGet pull request #632
Opened 2022-04-22 02:17 UTC by alerickson

# PR Summary
Adding -SkipPublisherCheck parameter to `Install-PSResource` to validate signed files sand catalog files at install time.

Still needed:
- [ ] Tests 
- [ ] Comments
- [ ] Proper error messaging on failure
- [ ] Discussion as to whether the default behavior should be to validate signatures (ie -SkipPublisherCheck flag) or to not validate signatures (ie opt in via -PublisherCheck)
- [ ]  Discussion as to whether Update-PSResource and/or Save-PSResource should also have publisher validations

## PR Context
See issue #519 

## PR Checklist
- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-05-23 14:09 UTC, anamnavi approved these changes
LGTM, just some questions/suggestions

2022-05-23 14:09 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +        /// Skips the check for package validation.
Should this message be updated, since we're performing authentication check not really package validation as a whole?
```suggestion
        /// Check validation for signed and catalog files
```

2022-05-23 14:09 UTC, anamnavi commented on src/code/SavePSResource.cs
> +        /// Skips the check for package validation.
```suggestion
        /// Check validation for signed and catalog files

```

2022-05-23 14:09 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +        /// Skips the check for package validation.
```suggestion
        /// Check validation for signed and catalog files

```

2022-05-23 14:09 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                var isLocalRepo = repo.Uri.AbsoluteUri.StartsWith(Uri.UriSchemeFile + Uri.SchemeDelimiter, StringComparison.OrdinalIgnoreCase);
Could we just do this instead? Or does it end up including cases (local server based paths) that we don't want?
```suggestion
                var isLocalRepo = repo.Uri.Scheme == Uri.UriSchemeFile;
```

2022-05-23 14:09 UTC, anamnavi commented on src/code/InstallHelper.cs
> +            // TODO: validate all files (need to figure out what all files are (ie what files shouldn't be validated) : list of extensions
we can remove this TODO comment now I think

2022-05-23 22:41 UTC, PaulHigin requested changes
A good start, but some logic seems broken and all of the signature check function should be separated from this file, and added as static utility methods either in Utils.cs (in separate code region) or in a new AuthenticodeUtils.cs source file.  Also we need to make use of cache to prevent repeatedly searching the same paths and validating the same signature certificate.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private readonly string[] certStoreLocations = { "cert:\\LocalMachine\\Root", "cert:\\LocalMachine\\AuthRoot", "cert:\\CurrentUser\\Root", "cert:\\CurrentUser\\AuthRoot" };
```suggestion
        private readonly string[] CertStoreLocations = { "cert:\\LocalMachine\\Root", "cert:\\LocalMachine\\AuthRoot", "cert:\\CurrentUser\\Root", "cert:\\CurrentUser\\AuthRoot" };

```

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                                            param ([string] $certStoreLocation )
`element` parameter is not being passed in as a parameter argument, so $element is always null.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private bool CheckAuthenticodeSignature(string pkgName, string tempDirNameVersion, VersionRange versionRange, List<string> pathsToSearch, string installPath, out ErrorRecord errorRecord)
All of the signature check logic should not be in 'InstallHelper.cs', but should be static methods in 'Utils.cs', in its own 'Authenticode Signauture' code region.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    TestFileCatalogResult = _cmdletPassedIn.InvokeCommand.InvokeScript(
All script invocations should be wrapped in a static method in the 'Utils.cs'.  If very large we could have a 'AuthenticodeUtils.cs' file.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                string[] listOfExtensions = { "*.ps1", "*.psd1", "*.psm1", "*.mof", "*.cat", "*.ps1xml" };
We can't gather all file signatures in a single collection, because we need to ensure each signable file is actually signed with a valid signature.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        X509Certificate2 rootCertificateAuthority = results.Any() ? (X509Certificate2)results.FirstOrDefault() : null;
Don't use LINQ, and instead use actual properties on objects.

Also, this should be wrapped in a utility method that returns expected object/type.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                            ThrowTerminatingError(
Cmdlet exception should be thrown at higher layer.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private Hashtable GetAuthenticodePublisher(Signature authenticodeSignature, string pkgName)
This should be a static method.  Also, this performs an exhaustive search and is expensive.  Most files will have the same signature certificate, so it should be possible to cache results for a SignerCertificate based on its thumbprint.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                                            Microsoft.PowerShell.Management\Get-ChildItem -Path $certStoreLocation |
This is an expensive search and results should be cached.  Also include comments to make clear what the search does and what the results mean.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        public static bool IsMicrosoftCertificateHelper(SafeX509ChainHandle pChainContext)
Don't use the word 'helper' in utility methods.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            if (authenticodeSignature.SignerCertificate != null)
Maybe this is the place to add the cache.  Once a signature certificate has been validated it can be added to a cache based on its thumbprint.

2022-05-23 22:41 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +
Remove unneeded white space.

2022-05-25 20:02 UTC, alerickson commented on src/code/InstallHelper.cs
> +                        X509Certificate2 rootCertificateAuthority = results.Any() ? (X509Certificate2)results.FirstOrDefault() : null;
I addressed the first comment, but not sure if I fully addressed the second comment.

2022-05-25 20:02 UTC, alerickson commented on src/code/InstallHelper.cs
> +                string[] listOfExtensions = { "*.ps1", "*.psd1", "*.psm1", "*.mof", "*.cat", "*.ps1xml" };
Lines 721-732 will handle this.  Basically, if any file that ends with the one of the extensions in the array does not have a valid signature, it will still return a Signature object, but the 'SignatureStatus' will not be valid (ie 'NotSigned' or 'UnknownError')

2022-05-25 20:02 UTC, alerickson commented on src/code/InstallHelper.cs
> +        private Hashtable GetAuthenticodePublisher(Signature authenticodeSignature, string pkgName)
Added a cache for both validating if a cert is a Microsoft cert and to find the publisher details

2022-05-25 20:03 UTC, alerickson commented on src/code/InstallHelper.cs
> +                                            Microsoft.PowerShell.Management\Get-ChildItem -Path $certStoreLocation |
I haven't added comments yet, but will do that

2022-05-25 20:23 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                string[] listOfExtensions = { "*.ps1", "*.psd1", "*.psm1", "*.mof", "*.cat", "*.ps1xml" };
We should also include in the error which file failed the Authenticode signature check and how it failed (no signed or invalid).

2022-05-25 20:24 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        X509Certificate2 rootCertificateAuthority = results.Any() ? (X509Certificate2)results.FirstOrDefault() : null;
This is not needed anymore since we are not validating certs, but just performing Authenticode signature checks.

2022-05-25 20:24 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private Hashtable GetAuthenticodePublisher(Signature authenticodeSignature, string pkgName)
I don't think this is needed anymore as we are not doing cert checks.

2022-06-01 21:51 UTC, merged

2022-06-01 23:09 UTC, PaulHigin reviewed
LGTM