Publish fix
PowerShell/PSResourceGet pull request #640
Opened 2022-05-04 05:28 UTC by alerickson

# PR Summary
Add fix for publishing with `RequiredResources` specified in module manifest

## PR Context

Addresses issue #486 

## PR Checklist

- [] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-05-05 18:06 UTC, PaulHigin requested changes

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +        private CancellationToken _cancellationToken;
Please include in the PR description, a short summary of the issue and how these changes address the problem.

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
>                  var repository = new[] { repositoryUri };
The caller now passes in `repository.Name` to this method, so the parameter name should reflect that.

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +
pwsh.Invoke() above will throw if the command it is running throws.  So it should be wrapped in a try/catch to be safe.

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                    if (string.IsNullOrEmpty(message))
```suggestion
                    if (string.IsNullOrEmpty(message) && pwsh.Streams.Error.Count > 0)

```

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        message = error[0].ToString() + "Run 'Test-ModuleManifest' to validate the module manifest.";
```suggestion
                        message = pwsh.Streams.Error[0].ToString() + "Run 'Test-ModuleManifest' to validate the module manifest.";

```

2022-05-05 18:06 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                bool depPrerelease = depVersion.Contains("-") ? true : false;
This local variable does not appear to be used anywhere.

2022-05-05 18:06 UTC, PaulHigin commented on test/PublishPSResource.Tests.ps1
> +        Publish-PSResource -Path $script:PublishModuleBase -Verbose -ErrorAction SilentlyContinue
If this throws, then you should use the Pester `-Should throw` here.

2022-05-05 18:06 UTC, PaulHigin commented on test/PublishPSResource.Tests.ps1
>          $Error[0].FullyQualifiedErrorId | Should -be "DependencyNotFound,Microsoft.PowerShell.PowerShellGet.Cmdlets.PublishPSResource"
Please add tests for 'invalid manifest' and for 'invalid version format'.

2022-05-13 20:44 UTC, anamnavi reviewed
LGTM, minor suggestion for variable assignment.

This will probably resolve in merge conflicts with the Publish scripts PR

2022-05-13 20:44 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                bool depPrerelease = depVersion.Contains("-") ? true : false;
```suggestion
                bool depPrerelease = depVersion.Contains("-");

```

2022-05-13 20:44 UTC, anamnavi approved these changes

2022-05-18 17:18 UTC, merged