Publish-PSResource Script publishing support
PowerShell/PSResourceGet pull request #642
Opened 2022-05-05 14:40 UTC by anamnavi

# PR Summary

Please ignore the branch name. 

This PR will ensure we can publish script resources (locally and remotely) and add tests for local publishing. For publishing to a local path, if it's not a server based path but rather a Drive based path, we also check that the directory path exists.

For testing scripts that have errors, I created a `testFiles` folder under `test` and have added invalid scripts there. Otherwise the script would have been created with New-ScriptFileInfo cmdlet and that cmdlet would have caught the errors instead of letting Publish-PSResource error handle it.

It also adds error handling and bool return for PackNupkg() and PushNupkg() methods.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-05-05 20:01 UTC, PaulHigin requested changes
Still reviewing...

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                else if (File.Exists(resolvedPath) && resolvedPath.EndsWith(PSScriptFileExt, StringComparison.OrdinalIgnoreCase))
What if an unsupported filepath is provided?  Is an error thrown?  It seems like the code to determine whether the path is directory or supported file path, along with all validation, should be done in the BeginProcess() block.

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                if (!parsedMetadataHash.ContainsKey("author") || String.IsNullOrWhiteSpace(parsedMetadataHash["author"].ToString()))
A blank line should always be included after a closing bracket.

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                    if (!PackNupkg(outputDir, outputNupkgDir, nuspec))
What does 'false' returned here mean?  Should some kind of error or verbose message be emitted?

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +        private Hashtable ParseScriptMetadataIntoHash(string filePath)
```suggestion
        private Hashtable ParseScriptMetadata(string filePath)

```

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                foreach (ParseError err in parserErrors)
If we want to skip workflow parse errors, then that can be added within the foreach loop.  Also we should return after all parse errors are emitted.

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +            else if (ast != null)
ast == null should be an early out.

2022-05-05 20:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                string commentPattern = "<#PSScriptInfo";
This can be const string.

2022-05-11 16:54 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                else if (File.Exists(resolvedPath) && resolvedPath.EndsWith(PSScriptFileExt, StringComparison.OrdinalIgnoreCase))
added an `else` block to ThrowTerminatingError() if not a valid path for script or module resources in the path format we currently expect

2022-05-11 16:57 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                    if (!PackNupkg(outputDir, outputNupkgDir, nuspec))
need to ask Amber

2022-05-11 16:58 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +        private Hashtable ParseScriptMetadataIntoHash(string filePath)
renamed to TryParseScriptMetadata()

2022-05-12 14:26 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                // alternatively could use resourceFilePath = _path
is it faster/more efficient to use the variable (pkgFileOrDir) to set resourceFilePath, or use the private field (_path) to set the resourceFilePath variable?

2022-05-12 15:07 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                    if (!PackNupkg(outputDir, outputNupkgDir, nuspec))
I changed the method to return a Error if it fails to pack the package into a .nupkg and to write that error and return when execution returns to EndProcessing().

2022-05-18 00:42 UTC, alerickson approved these changes
Looks good, just left some suggestions for removing comments and whitespace, please take them at your discretion!

2022-05-18 00:42 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                // alternatively could use resourceFilePath = _path
Hmm, I don't really have any opinions on this one.  I don't see one as being more advantageous than the other.

2022-05-18 00:42 UTC, alerickson commented on src/code/PublishPSResource.cs
> -            // parse .ps1 - example .ps1 metadata:
I think we should leave this example metadata in the comment just to have an idea of what a proper script should look like.

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +    # $version = "1.0.0"
This looks like it might not be needed anymore

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +    # $publishScriptBase = Join-Path $script:testIndividualResourceFolder $scriptName
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +    # $null = New-Item -Path $publishScriptBase -ItemType Directory -Force
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +    # $version = "1.0.0"
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
>  .PRIVATEDATA$(if ($PrivateData) {" $PrivateData"})
```suggestion

.PRIVATEDATA$(if ($PrivateData) {" $PrivateData"})
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/PSGetTestUtils.psm1
> +
```suggestion
```

2022-05-18 00:42 UTC, alerickson commented on test/UninstallPSResource.Tests.ps1
> +}
```suggestion
}
```

2022-05-18 21:31 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +
this is weird .ps1 file script syntax...for the `ast.GetHelpContent()` method to pick up `.DESCRIPTION` that comment block (i.e `<#`) has to be preceeded by a space, and has to be followed by a space before the `.DESCRIPTION` key, and then again before the closing comment block (i.e `#>`) it needs another space. We should have a blogpost or documentation somewhere about these weird format peculiarities .ps1 files have

2022-05-18 21:32 UTC, anamnavi commented on test/PSGetTestUtils.psm1
> +
this is weird .ps1 file script syntax...for the ast.GetHelpContent() method to pick up .DESCRIPTION that comment block (i.e <#) has to be preceeded by a space, and has to be followed by a space before the .DESCRIPTION key, and then again before the closing comment block (i.e #>) it needs another space. We should have a blogpost or documentation somewhere about these weird format peculiarities .ps1 files have

2022-05-18 21:54 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                // alternatively could use resourceFilePath = _path
I'll keep this as is

2022-05-19 14:57 UTC, merged