WIP:  'Update-ModuleManifest' cmdlet implementation
PowerShell/PSResourceGet pull request #677
Opened 2022-06-16 17:29 UTC by alerickson

# PR Summary

Adding implementation for the cmdlet `Update-ModuleManifest` 

## PR Context
Resolves issue #586 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-07 16:16 UTC, anamnavi requested changes
The tests will need to use Pester's $TestDrive

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +In this example, the user already has the TestModule package installed and they update the package. Update-PSResource will install the latest version of the package without deleting the older version
remove this example from an older doc I assume

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Specifies script modules (.psm1) and binary modules (.dll) that are imported into the module's session state. The files in the NestedModules key run in the order in which they're listed in the value.
is this a description for -Path or another parameter?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Enter each module name as a string or as a hash table with ModuleName and ModuleVersion keys. The hash table can also have an optional GUID key. You can combine strings and hash tables in the paramet
is this a description for -Path or another parameter?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
L437 says wildcards are permitted, does this need to be set to True then?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
L454 says wildcards are permitted, does this need to be set to True then?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
L471 says wildcards are permitted, does this need to be set to True then?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
L488 says wildcards are permitted, does this need to be set to True then?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
L505 says wildcards are permitted, does this need to be set to True then?

2022-07-07 16:16 UTC, anamnavi commented on help/Update-ModuleManifest.md
> +### System.String[]
should this also include `System.Reflection.ProcessorArchitecture` as the ProcessorArchitecture parameter has `ValueFromPipeline` attribute?

2022-07-07 16:16 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +        /// Indicates the module is prerelease.
```suggestion
        /// Indicates the prerelease label of the module.

```

2022-07-07 16:16 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +        string ResolvedManifestPath;
is this a private member?

2022-07-07 16:16 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            ResolvedManifestPath = SessionState.Path.GetResolvedPSPathFromPSPath(Path).First().Path;
if we're not processing records/pipeline input wouldn't this all go in EndProcessing()? I may be wrong, @PaulHigin would know probably

2022-07-07 16:16 UTC, anamnavi commented on src/code/UpdateModuleManifest.cs
> +            // After getting the original module manifest contentes, migrate all the fields to the new module manifest,
nitpick
```suggestion
            // After getting the original module manifest contents, migrate all the fields to the new module manifest, 

```

2022-07-07 16:16 UTC, anamnavi commented on test/UpdateModuleManifest.Tests.ps1
> +        $script:TempPath = Get-TempPath
we should ideally be using Pester's $TestDrive, which automatically is cleaned up after each test

2022-07-07 17:49 UTC, alerickson commented on src/code/UpdateModuleManifest.cs
> +            ResolvedManifestPath = SessionState.Path.GetResolvedPSPathFromPSPath(Path).First().Path;
I was wondering about that too.  I'll move it over to EndProcessing() for now

2022-07-07 18:04 UTC, alerickson commented on help/Update-ModuleManifest.md
> +Specifies script modules (.psm1) and binary modules (.dll) that are imported into the module's session state. The files in the NestedModules key run in the order in which they're listed in the value.
Yup, that was the wrong description, updated now :)

2022-07-07 18:06 UTC, alerickson commented on help/Update-ModuleManifest.md
> +Enter each module name as a string or as a hash table with ModuleName and ModuleVersion keys. The hash table can also have an optional GUID key. You can combine strings and hash tables in the paramet
That was for -NestedModules (same info in the NestedModules description, that I must have copied over when creating a new parameter description)

2022-07-07 18:08 UTC, alerickson commented on help/Update-ModuleManifest.md
> +Accept wildcard characters: False
Yup, just changed that

2022-07-07 18:12 UTC, alerickson commented on help/Update-ModuleManifest.md
> +### System.String[]
Ah great catch, that actually shouldn't have the `ValueFromPipeline` attribute, so I'll remove that.

2022-07-07 20:22 UTC, PaulHigin requested changes
Sorry, I forgot to submit this review comment.  I will continue reviewing as well.

2022-07-07 20:22 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                if (!Utils.IsValidModuleManifest(resourceFilePath, this))
I think it would be cleaner if you did not pass in `this` and have `IsValidModuleManifest` throw if invalid and not return a boolean.  This would then be wrapped in try/catch here and throw the terminating error record here.

2022-07-07 21:21 UTC, PaulHigin requested changes

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +        /// Specifies a string array that contains release notes or comments that you want available for this version of the script.
```suggestion
        /// Specifies a string that contains release notes or comments that you want available for this version of the script.

```

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +
Please remove white space.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +        private string ResolvedManifestPath;
This does not need to be a class field.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +             ResolvedManifestPath = SessionState.Path.GetResolvedPSPathFromPSPath(Path).First().Path;
```suggestion
             string resolvedManifestPath = SessionState.Path.GetResolvedPSPathFromPSPath(Path).First().Path;

```

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +                var message = $"No file with a .psd1 extension was found in '{ResolvedManifestPath}'.  Please specify a path to a valid modulemanifest.";
```suggestion
                var message = $"The provided file path was not found: '{ResolvedManifestPath}'.  Please specify a valid module manifest (.psd1) file path.";

```

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +            if (!File.Exists(ResolvedManifestPath))
I am thinking that we should also test for .psd1 file extension.  We should not accept any file extension.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +                return;
Don't need a return here, since we are throwing.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +                    return;
We don't need this return.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +            if (!Directory.Exists(tmpParentPath))
This test shouldn't be necessary since GUIDs are guaranteed to be unique.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/UpdateModuleManifest.cs
> +            Utils.MoveFiles(tmpModuleManifestPath, ResolvedManifestPath, overwrite:true);
Please add a removal of the temporary directory in a finally block to ensure it is always done.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/Utils.cs
> +                        if (string.IsNullOrWhiteSpace((results[0].BaseObject as PSModuleInfo).Author))
We should cast the result base object to PSModuleInfo just once and save it to a local variable for use in the if statements.

2022-07-07 21:21 UTC, PaulHigin commented on src/code/Utils.cs
> +        public static bool IsValidModuleManifest(string moduleManifestPath, PSCmdlet cmdletPassedIn)
The returned bool seems unneeded since we always throw if the manifest is invalid.  Also it would be cleaner to not pass in PSCmdlet and just throw a PSInvalidOperation exception and let the calling cmdlet deal with handling the error.

2022-07-12 21:52 UTC, anamnavi approved these changes
LGTM, just had a nitpick comment

2022-07-12 21:52 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                    Utils.ValidateModuleManifest(resourceFilePath, out errorMsgs);
Declare inline if we can
```suggestion
                    Utils.ValidateModuleManifest(resourceFilePath, out string[] errorMsgs);

```

2022-07-12 22:56 UTC, PaulHigin approved these changes

2022-07-12 23:33 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                    Utils.ValidateModuleManifest(resourceFilePath, out errorMsgs);
I accepted these changes but reverted it because the finally block is using the errorMsgs variable so it needs to be declared before the try block.

2022-07-13 00:42 UTC, merged