Add benchmark tests for v3 (and v2) performance
PowerShell/PSResourceGet pull request #690
Opened 2022-07-06 21:57 UTC by alerickson

# PR Summary

Add benchmark tests to check performance of:

- Finding Az module 
- Finding Az module and its dependencies
- Installing Az module
- Installing Az module and its dependencies 

For both remote repositories (testing against the PSGallery) and local repositories (testing against the current directory), and for both PowerShellGet v2 (2.2.5) and PowerShellGet v3 (3.0.14-beta14).

## PR Context
Adding benchmark tests to help guide us as we continue to make changes to improve performance of PSGet v3.  Hopefully this can help us evaluate trade-offs and measure how much we're improving performance with each new change.  
Related issue: #653 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-06 22:26 UTC, PaulHigin requested changes
Looks good but remember to clear pwsh object commands before adding new script to run.

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +            pwsh.AddScript("Find-Module -Name Az -Repository LocalRepo");
You should clear the previous commands, otherwise they will be run again.
```powershell
pwsh.Commands.Clear();
```

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +            pwsh.AddScript("Find-Module -Name Az -IncludeDependencies -Repository LocalRepo");
```powershell
pwsh.Commands.Clear();
```

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +            pwsh.AddScript("Install-Module -Name Az -Repository LocalRepo -Force");
```powershell
pwsh.Commands.Clear();
```

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/BenchmarksV2RemoteRepo.cs
> +            pwsh.AddScript("Find-Module -Name Az -Repository PSGallery");
Don't forget to clear previous commands.

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/Program.cs
> +}
Github says there is no newline here at the end of the file.  Please add.

2022-07-06 22:26 UTC, PaulHigin commented on test/perf/benchmarks/benchmarks.csproj
> +</Project>
Github says there is no newline here at the end of the file.  Please add.

2022-07-06 23:23 UTC, PaulHigin approved these changes
LGTM

2022-07-07 16:56 UTC, anamnavi approved these changes
LGTM, just suggested renaming some of the methods to reflect V2, not V3 (I think it was probably just a typo copying it over :)

2022-07-07 16:56 UTC, anamnavi commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +        public void FindAzModuleV3()
```suggestion
        public void FindAzModuleV2()

```

2022-07-07 16:56 UTC, anamnavi commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +        public void FindAzModuleAndDependenciesV3()
```suggestion
        public void FindAzModuleAndDependenciesV2()

```

2022-07-07 16:56 UTC, anamnavi commented on test/perf/benchmarks/BenchmarksV2LocalRepo.cs
> +        public void InstallAzModuleAndDependenciesV3()
```suggestion
        public void InstallAzModuleAndDependenciesV2()

```

2022-07-07 19:32 UTC, merged