Convert IEnumerables to Lists for perf improvements
PowerShell/PSResourceGet pull request #691
Opened 2022-07-07 18:41 UTC by alerickson

# PR Summary
Pervasive use of IEnumerables in primarily FindHelper and InstallHelper were causing some unexpected performances degradations.   Occasionally the same call was (unexpectedly) occurring multiple times due to the fact that IEnumerable does not return a collection.  This was particularly painful because it meant multiple, unnecessary server calls, which can hit the server hard, but also decreases performance of PowerShellGet.

## PR Context
Breaking up issue #654 by tackling the first half:

- LINQ is generics and can cause multiple compiled methods calling search APIs.
- Find code always returned IEnumerable interface, causing LINQ calls to call search APIs multiple times to manipulate IEnumerable as collections. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-07 22:42 UTC, PaulHigin requested changes

2022-07-07 22:42 UTC, PaulHigin commented on src/code/FindHelper.cs
> +                                cancellationToken: _cancellationToken).GetAwaiter().GetResult().ToList());
It is not necessary to convert to List here, since the IEnumerable iterator is used only once with `wildcardPkgs.AddRange()`, which actually takes an IEnumerable type as argument.

2022-07-07 22:42 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    includeDependencies: !skipDependencyCheck).ToList();
If we never need IEnumerable from FindByResourceName(), maybe we should just change it to return List<> instead of IEnumerable<>.

2022-07-07 22:42 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                    pkgsFromRepoToInstall = FilterByInstalledPkgs(pkgsFromRepoToInstall).ToList();
I see `FilterByInstalledPkgs` was changed to return List<>.  So `ToList()` is no longer needed here.

2022-07-07 22:42 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            return filteredPackages.Values.ToList();
This seems pretty inefficient.  I think it would be better to create a HashSet and then add to a final List<> only those packages that are not already installed.

2022-07-07 22:42 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            List<PSResourceInfo> pkgsAlreadyInstalled = getHelper.GetPackagesFromPath(
Since `pkgsAlreadyInstalled` is iterated over only once, converting to List<> is not needed here.

2022-07-19 22:50 UTC, alerickson commented on src/code/InstallHelper.cs
> +            return filteredPackages.Values.ToList();
Updated this to reference a HashSet.

2022-07-28 20:24 UTC, alerickson commented
Closing this PR in favor of #728

2022-07-28 20:24 UTC, closed without merging