Bug fix in Publish-PSResource when creating nuspec
PowerShell/PSResourceGet pull request #693
Opened 2022-07-07 22:39 UTC by alerickson

# PR Summary
In module manifests, properties are labeled "LicenseUri", "ProjectUri", and "IconUri", however in a nuspec the same properties are "LicenseUrl", "ProjectUrl", and "IconUrl", respectively.  This PR updates references to "url" and changes them to "uri" where appropriate.   

All of these properties, as well as "ReleaseNotes"  are found under the "PSData" section of a module manifest, so the code is moved under that section to reflect this and so we can properly extract the respective values.

Only those nuspec properties which exist in the module manifest get added to the nuspec.  See below for all properties that are allowed in a nuspec:
https://docs.microsoft.com/en-us/nuget/reference/nuspec

## PR Context

Resolves #603 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-13 02:34 UTC, alerickson commented
This PR is ready to be reviewed.

2022-08-02 22:15 UTC, PaulHigin requested changes

2022-08-02 22:15 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        if (psData.ContainsKey("releasenotes") && psData["releasenotes"] is string releaseNotes)
Can `releaseNotes` ever be anything other than string type?

2022-08-02 22:15 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        string requireLicenseAcceptance = psData.ContainsKey("requirelicenseacceptance") ? psData["ReleaseNotes"] as string  : "false";
```suggestion
                        string requireLicenseAcceptance = psData.ContainsKey("requirelicenseacceptance") ? psData["requirelicenseacceptance"] : "false";

```

2022-08-02 23:57 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        if (psData.ContainsKey("releasenotes") && psData["releasenotes"] is string releaseNotes)
That's a good question, I just looked up how `releaseNotes` is referenced in v2 and it can be a string[] as well, so I'll update this to accommodate for that as well

2022-08-04 21:45 UTC, anamnavi reviewed
Have some questions about whether license, icon and project are named consistently in the nuspec or license will follow different naming (without "Url" appended at end) and why?

2022-08-04 21:45 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                        if (psData.ContainsKey("licenseUri") && psData["licenseuri"] is string licenseUri)
typo in key name check
```suggestion
                        if (psData.ContainsKey("licenseuri") && psData["licenseuri"] is string licenseUri)

```

2022-08-04 21:45 UTC, anamnavi commented on src/code/PublishPSResource.cs
> +                            metadataElementsDictionary.Add("license", licenseUri.Trim());
I'm a little confused, why do we add license as `license` but project as `projectUrl` and icon as `iconUrl`? Do the 3 of them follow different naming guidelines for the nuspec now?

2022-08-04 21:45 UTC, anamnavi commented on src/code/PublishPSResource.cs
>                  <projectUrl>https://github.com/PowerShell/PowerShell</projectUrl>
Per the comment about naming guideline for the 3 (license, icon, project) would `projectUrl` change to the below? Or would icon be `iconUrl` and only license is named `license`?
```suggestion
                <project>https://github.com/PowerShell/PowerShell</project>

```

2022-08-11 21:26 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                            metadataElementsDictionary.Add("license", licenseUri.Trim());
The nuspec schema is specified here, so this is what I used to validate correct property names: https://docs.microsoft.com/en-us/nuget/reference/nuspec

`License` used to be `licenseUrl` but the latter is deprecated now: https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl

2022-08-11 21:28 UTC, alerickson commented on src/code/PublishPSResource.cs
>                  <projectUrl>https://github.com/PowerShell/PowerShell</projectUrl>
Nope, `projectUrl` would not change to `project`, see: https://docs.microsoft.com/en-us/nuget/reference/nuspec#projecturl

2022-08-15 18:29 UTC, PaulHigin approved these changes
LGTM

2022-08-15 18:39 UTC, merged