Publish folder
PowerShell/PSResourceGet pull request #704
Opened 2022-07-13 21:22 UTC by alerickson

# PR Summary
This PR expands what `Publish-PSResource` will accept as a path for a resource to be published.  
Acceptable paths:
- Modules with a file path pointing to the root directory eg:
    `C:\user\ModuleToBePublished`
- Modules with a file path pointing to the module manifest, eg:
   `C:\users\ModuleToBePublished\ModuleToBePublished.psd1`
   `C:\users\ADifferentDirectoryName\ModuleToBePublished.psd1`
- Scripts with a file path pointing to that script, eg:
   `C:\users\ScriptToBePublished.psd1`

## PR Context

Resolves #305 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-13 21:23 UTC, alerickson commented
This PR is ready for review

2022-08-02 21:28 UTC, PaulHigin requested changes

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                var exMessage = string.Format("Either the path to the resource to publish does not exist or is not in the correct format, point to a the path or file of the module or script to publis
The above `GetResolvedPSPathFRomPSPath` will throw a `MethodInvocationException` if the path cannot be resolved (does not exist).  So we can remove the `does not exist` part of the message here, or alternatively catch the exception above and let this check notify the user if it does not exist.

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                _pkgName = pkgFileOrDir.Name.Remove(pkgFileOrDir.Name.Length - PSScriptFileExt.Length);
```suggestion
                _pkgName = Path.GetFileNameWithoutExtension(pkgFileOrDir.Name);

```

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                if (pkgFileOrDir.Name.EndsWith(PSDataFileExt))
```suggestion
                if (pkgFileOrDir.Name.EndsWith(PSDataFileExt, StringComparison.OrdinalIgnoreCase))

```

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                    foreach (FileInfo file in childFiles)
No need to create a list object.
```suggestion
                    foreach (FileInfo childFile in pkgFileOrDir.EnumerateFiles())

```

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                            _pkgName = file.Name.Remove(file.Name.Length - PSDataFileExt.Length);
```suggestion
                            _pkgName = Path.GetFileNameWithoutExtension(file.Name);

```

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        if (file.Name.EndsWith(PSDataFileExt))
```suggestion
                        if (file.Name.EndsWith(PSDataFileExt, StingComparer.OrdinalIgnoreCase))

```

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        && (resolvedPath.EndsWith(PSDataFileExt, StringComparison.OrdinalIgnoreCase)
It looks like we check path file extension multiple times.  Ideally, this would only be done once and we set local variables describing the state:
 - what to publish: enum -> script or module
 - path to script file to publish
 - path to module manifest file to publish
 - path to module directory to publish

Instead of if/else statements, it would be better to have two classes that encapsulate publishing a script or module, and that derive from a base class that provides common functions (temporary directory) and a `publish` virtual method.

2022-08-02 21:28 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        string rootModuleDir = _path.EndsWith(PSDataFileExt) ? new FileInfo(_path).Directory.FullName : _path;
We have checked the `_path` file extension previously.
```suggestion
                        string rootModuleDir = _path.EndsWith(PSDataFileExt, StringComparer.OriginalIgnoreCase) ? new FileInfo(_path).Directory.FullName : _path;

```

2022-08-11 23:19 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                var exMessage = string.Format("Either the path to the resource to publish does not exist or is not in the correct format, point to a the path or file of the module or script to publis
I changed this a little bit so that it catches the `MethodInvocationException` and throws immediately if applicable.  I removed the check to see if the directory or file exists since that was unnecessary anyway.

2022-08-11 23:26 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        && (resolvedPath.EndsWith(PSDataFileExt, StringComparison.OrdinalIgnoreCase)
That's a good idea.  I'll clean up the path variables here, but address splitting up the class in a different PR so we can review the design of it.

2022-08-15 22:01 UTC, PaulHigin requested changes
Overall looks good.  Just a few comments and suggestions.

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +            else if (string.IsNullOrEmpty(resolvedPath))
We should do this check first.  There is no point in finding out what kind of path if the string is null or empty.

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +            _path = resolvedPath;
Not sure why this assignment is necessary.  You already have fully resolved paths for each case...

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                    var message = String.Format("No file with a .psd1 extension was found in {0}.  Please specify a path to a valid modulemanifest.", _path);
```suggestion
                    var message = String.Format("No file with a .psd1 extension was found in {0}.  Please specify a path to a valid modulemanifest.", pathToModuleManifestToPublish);

```

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
>                      File.Copy(_path, System.IO.Path.Combine(outputDir, _pkgName + PSScriptFileExt), true);
```suggestion
                    File.Copy(pathToScriptFileToPublish, System.IO.Path.Combine(outputDir, _pkgName + PSScriptFileExt), true);

```

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        string rootModuleDir = !string.IsNullOrEmpty(pathToModuleManifestToPublish) ? new FileInfo(_path).Directory.FullName : _path;
```suggestion
                        string rootModuleDir = !string.IsNullOrEmpty(pathToModuleManifestToPublish) ? 
                            Path.GetDirectoryName(pathToModuleManifestToPublish) :
                            pathToModuleDirToPublish;

```

2022-08-15 22:01 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        foreach (string dir in System.IO.Directory.GetDirectories(rootModuleDir, "*", System.IO.SearchOption.AllDirectories))
I wonder if we should make this CopyDir Utility method public and use it here?  It would be nice to not duplicate code if we can help it.

https://github.com/PowerShell/PowerShellGet/blob/115343118fb9eb794b927bb78aa20c031768d900/src/code/Utils.cs#L1135

2022-08-15 22:12 UTC, alerickson commented on src/code/PublishPSResource.cs
> +            _path = resolvedPath;
I just got rid `_path` and am just using `resolvedPath` where `_path` was previously used

2022-08-15 22:33 UTC, alerickson commented on src/code/PublishPSResource.cs
> +                        foreach (string dir in System.IO.Directory.GetDirectories(rootModuleDir, "*", System.IO.SearchOption.AllDirectories))
There's a small issue with the Utility method, which is that it doesn't ignore the `.nuspec` file if it sees it.  The way the publish 'copy' function currently works is that it prioritizes any .nuspec file that it sees in the publish folder, so that if the user specifically wants to use their own nuspec file they can.  We can get rid of this and only use the PSGet generated .nuspec file and if there's feedback that the community wants that functionality, add it back in at that point.

2022-08-15 22:36 UTC, PaulHigin commented on src/code/PublishPSResource.cs
> +                        foreach (string dir in System.IO.Directory.GetDirectories(rootModuleDir, "*", System.IO.SearchOption.AllDirectories))
If the utility method is not suitable then it is fine to have your own custom code.

2022-08-18 22:01 UTC, PaulHigin approved these changes
LGTM

2022-08-18 22:43 UTC, merged