Script info cmdlets new design
PowerShell/PSResourceGet pull request #708
Opened 2022-07-14 01:53 UTC by anamnavi

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-15 20:33 UTC, anamnavi commented on src/code/Utils.cs
> +                public static bool TryCreateModuleSpecification(
fix indentation

2022-07-18 18:27 UTC, PaulHigin requested changes

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptContents.cs
> +        public PSScriptContents(string endOfFileContents)
Please add ///<summary> comment.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptContents.cs
> +                EndOfFileContents = String.Join("", commentLines);
Does this preserve line endings?

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptContents.cs
> +        /// This function would be called by PSScriptFileInfo.TryCreateScriptFileInfoString(),
```suggestion
        /// This function is called by PSScriptFileInfo.TryCreateScriptFileInfoString(),
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptContents.cs
> +        /// The Update cmdlet checks for -RemoveSignature before control reaches this method).
/// Any file signature is always removed because it is invalidated when the content is updated.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            this.ScriptMetadataComment = scriptMetadataComment;
We generally omit `this.` in PowerShell code.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            bool reachedPSSCriptInfoCommentEnd = false;
```suggestion
            bool reachedPSScriptInfoCommentEnd = false;
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                    int j = i + 1; // start at the next line
Minor comment.  We don't really need the new `j` index and can just keep incrementing the `i` index as it always moves forward.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                    // we assume the next comment block should be the help comment block (containing description)
// The next comment block *must be* the description block.  We know this because we write these blocks and expect them not to be modified by the user.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            string[] remainingFileContent = new string[]{};
Don't need `{}` initializer brackets.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // parse .ps1 contents out of file into list objects
```suggestion
            // Parse .ps1 contents out of file into list objects
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // populate PSScriptFileInfo object by first creating instances for the property objects
```suggestion
            // Populate PSScriptFileInfo object by first creating instances for the property objects
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // create PSScriptFileInfo instance with script metadata class instances (PSScriptMetadata, PSScriptHelp, PSScriptRequires, PSScriptContents)
```suggestion
            // Create PSScriptFileInfo instance with script metadata class instances (PSScriptMetadata, PSScriptHelp, PSScriptRequires, PSScriptContents)
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +        /// as this method will remove original signature, as updating would have invalidated it
```suggestion
        /// as this method will remove original signature, as updating would have invalidated it.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +                var message = String.Format("Could not update .ps1 file as PSScriptFileInfo object created for it was null");
Would this message make sense to a user?  Since this is an internal implementation detail, we can just through an argument null exception, and ensure that we never call this with a null value.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            errors = new ErrorRecord[]{};
Don't need `{}` initializer brackets.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // step 1: validate object properties for required script properties
```suggestion
            // Step 1: validate object properties for required script properties.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            // step 2: create string that will be used to write later
```suggestion
            // Step 2: create string that will be used to write later.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptFileInfo.cs
> +            if (!String.IsNullOrEmpty(psRequiresCommentBlock))
We should try to preserve all line endings so that the file contents look similar after updating.  I think we will need `\r\n` for Windows and `\n` for non-Windows platforms.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptMetadata.cs
> +using System.Net.Http.Headers;
I think this can be removed.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/PSScriptMetadata.cs
> +        public PSScriptMetadata(
All public APIs should have ///<summary> comment blocks (and most internal APIs).

2022-07-18 18:27 UTC, PaulHigin commented on src/code/UpdatePSScriptFileInfo.cs
> +                    // also write a warning as the existing ProjectUri, LicenseUri, IconUri may be overwrriten if they were determined to not be valid when parsed.
```suggestion
                    // Also write a warning as the existing ProjectUri, LicenseUri, IconUri may be overwrriten if they were determined to not be valid when parsed.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/UpdatePSScriptFileInfo.cs
> +                WriteWarning("The .ps1 script file passed in was not valid due to the following error(s) listed below");
Should be Error?

2022-07-18 18:27 UTC, PaulHigin commented on src/code/UpdatePSScriptFileInfo.cs
> +                WriteWarning("This script contains a signature and cannot be updated without invalidating the current script signature");
I feel this warning isn't necessary.  It is unneeded if `RemoveSignature` is used and the error below handles the other case.

It might be worthwhile to emit a warning when the signature is removed, reminding the user that the updated file needs to be re-signed.

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +            // this will be a string where entries are separated by space
```suggestion
            // This will be a string where entries are separated by space.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +                // ModuleSpecification(string) constructor for creating a ModuleSpecification when only ModuleName is provided
```suggestion
                // ModuleSpecification(string) constructor for creating a ModuleSpecification when only ModuleName is provided.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +                // at this point it must contain ModuleName key.
```suggestion
                // At this point it must contain ModuleName key.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +                    // pass to ModuleSpecification(string) constructor
```suggestion
                    // Pass to ModuleSpecification(string) constructor.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +                    // this constructor method would only throw for a null/empty string, which we've already validated against above
```suggestion
                    // This constructor method would only throw for a null/empty string, which we've already validated against above.
```

2022-07-18 18:27 UTC, PaulHigin commented on src/code/Utils.cs
> +                    // ModuleSpecification(Hashtable) constructor for when ModuleName + {Required,Maximum,Module}Version value is also provided
```suggestion
                    // ModuleSpecification(Hashtable) constructor for when ModuleName + {Required,Maximum,Module}Version value is also provided.
```

2022-07-19 21:35 UTC, PaulHigin requested changes

2022-07-19 21:35 UTC, PaulHigin commented on src/code/PSScriptHelp.cs
> +            psHelpInfoLines.Add($"{Description}{Environment.NewLine}");
Is `Environment.NewLine` needed here?  I though `System.IO.File.WriteAllLines()` would add line ending characters so you should not have to.

2022-07-19 22:04 UTC, PaulHigin approved these changes
LGTM

2022-07-20 13:27 UTC, merged