[WIP]: Add -Force param to Register-PSResourceRepository and Set-PSResourceRepository
PowerShell/PSResourceGet pull request #717
Opened 2022-07-18 22:40 UTC by alerickson

# PR Summary
This PR adds a `-Force` parameter to `Register-PSResourceRepository`, which allows a user to update (or set) a resource repository if the repository already exists.

The PR also adds a `-Force` parameter to `Set-PSResourceRepository`, which allows a user to create a new resource repository if the user attempts to set a resource repository that does not already exist. 

## PR Context

Resolves #612 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-07-19 20:34 UTC, ThomasNieto commented on src/code/SetPSResourceRepository.cs
> +        public SwitchParameter Force { get; set; }
A `Force` parameter isn't needed for `Set-PSResourceRepository`. If the repository exists then it will update the repo config if the repo doesn't exist then it should create the repo if all the required values (Uri) are passed.

For example take a look at `New-Variable` and `Set-Variable`:

```powershell
PS C:\> Get-Variable -Name Test
Get-Variable: Cannot find a variable with the name 'Test'.
PS C:\> New-Variable -Name Test -Value $true
PS C:\> New-Variable -Name Test -Value $false
New-Variable: A variable with name 'Test' already exists.
PS C:\> New-Variable -Name Test -Value $false -Force
PS C:\> Get-Variable -Name Test

Name                           Value
----                           -----
Test                           False

PS C:\> Set-Variable -Name Test -Value $true
PS C:\> Get-Variable -Name Test

Name                           Value
----                           -----
Test                           True

PS C:\> Remove-Variable -Name Test
PS C:\> Set-Variable -Name Test -Value $false
PS C:\> Get-Variable -Name Test

Name                           Value
----                           -----
Test                           False
```

`New-Variable` will create the variable but fail if it already exists unless the `Force` flag is passed. `Set-Variable` will either set the variable value or create the variable if it doesn't exist.

`Register-PSRespositoy` and `Set-PSRepository` should match `New-Variable` and `Set-Variable` behavior.

2022-07-20 02:28 UTC, alerickson commented on src/code/SetPSResourceRepository.cs
> +        public SwitchParameter Force { get; set; }
That makes sense!  Just removed the -Force parameter for Set-PSResourceRepository but kept the implementation so that set will still create a new repository by default if it doesn't already exist.

2022-07-20 17:01 UTC, anamnavi requested changes
Some design questions about:
1) `Set` creating a repo (if it doesn't already exist) *without* -Force
2)  Set being run with Name, Force and no other parameter ..is this a valid case (because at that point you are setting no properties, just registering the repository). I feel it would not be a valid case..but would love to discuss

2022-07-20 17:01 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                        if (errorMsgs.Length > 0)
Can we only have 1 error message returned from this? If so then I think we should have the `errorMsg` variable be of type `string` instead of `string[]`. If instead we could have more than 1 error message, then should we write those other errors out too?

2022-07-20 17:01 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +            if (errorMsgs.Length > 0)
same comment as above about plurality of error(s) and whether we need to report all if them back?

2022-07-20 17:01 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                if (errorMsgs.Length > 0)
same comment as above about plurality of error(s) and whether we need to report all if them back?

2022-07-20 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            errorMsgs = new string[] { };
instead of initializer brackets:
```suggestion
            errorMsgs = Utils.EmptyStrArray;
```

2022-07-20 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            errorMsgs = new string[] { };
```suggestion
            errorMsgs = Utils.EmptyStrArray;
```

2022-07-20 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            if (repoUri == null && repoPriority == defaultPriority && _trustedNullable == null && repoCredentialInfo == null)
could a user do:
`Set-PSResourceRepository -Name "MyRepo" -Force`

to attempt to create the repo? i.e  do we allow users to solely create the repo with Set? If so remove this condition, otherwise this condition will ensure they are trying to set atleast one property for the repo aside from Name (whether the repo exists or not, using Force)

2022-07-20 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            errorMsgs = new string[] { };
```suggestion
            errorMsgs = Utils.EmptyStrArray;
```

2022-07-20 17:01 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    bool repoIsTrusted = repoTrusted == null || repoTrusted == false ? false : true;
I think this could simplify, but not sure if this is less readable?
```suggestion
                    bool repoIsTrusted = !(repoTrusted == null || repoTrusted == false);
```

2022-07-20 17:01 UTC, anamnavi commented on test/RegisterPSResourceRepository.Tests.ps1
> +    It "not register incorrectly formatted Name type repo among correct ones when incorrect type is -Name is not specified" {
may sound clearer:
```suggestion
    It "not register incorrectly formatted -Name type repo among correct ones, where incorrect one is missing -Name" {
```

2022-07-20 17:01 UTC, anamnavi commented on test/RegisterPSResourceRepository.Tests.ps1
> +    It "not register incorrectly formatted Name type repo among correct ones when incorrect type is -Name is PSGallery" {
```suggestion
    It "not register incorrectly formatted -Name type repo among correct ones, where incorrect type has -Name of PSGallery" {
```

2022-07-20 17:01 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
> +        Set-PSResourceRepository -Name $testRepoName -Uri $tmpDir1Path -PassThru
Would we not need to use `-Force` with this? How is this creating this right now without `-Force` and passing the test?

2022-07-20 17:01 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
> +        Set-PSResourceRepository -Name $testRepoName -Uri $tmpDir1Path -PassThru
Or do we create create with `Set` even if repo doesn't exist, *without* Force? Because that seems like it would be problematic..

2022-07-20 18:04 UTC, ThomasNieto commented on src/code/RepositorySettings.cs
> +            if (repoUri == null && repoPriority == defaultPriority && _trustedNullable == null && repoCredentialInfo == null)
Set wouldn't have a force parameter, see this [discussion](https://github.com/PowerShell/PowerShellGet/pull/717#discussion_r924933746). If the user runs `Set-PSResourceRepository -Name MyRepo` and the repo doesn't exist it should throw an error saying `Uri` is required to register the repository.

2022-07-21 00:42 UTC, alerickson commented on test/SetPSResourceRepository.Tests.ps1
> +        Set-PSResourceRepository -Name $testRepoName -Uri $tmpDir1Path -PassThru
Read @ThomasNieto's comment above as for the reasoning to not include -Force for set. I initially included a -Force parameter for set, but was convinced by his explanation as to why it should be the default behavior and not functionality only added with the -Force param

2022-07-21 00:46 UTC, alerickson commented on src/code/RepositorySettings.cs
> +            if (repoUri == null && repoPriority == defaultPriority && _trustedNullable == null && repoCredentialInfo == null)
Yup, Set is just calling 'Add' repository, so anything that fails for adding a new repository would fail for setting a repository that does not exist.

2022-07-21 00:54 UTC, alerickson commented on src/code/RegisterPSResourceRepository.cs
> +                        if (errorMsgs.Length > 0)
Only 1 error message.  I can change it to string, I left it as string[] to be consistent with the other out error message variables, but can update this to just string

2022-08-03 17:27 UTC, SydneyhSmith commented on src/code/SetPSResourceRepository.cs
> +        public SwitchParameter Force { get; set; }
Thanks @ThomasNieto we like this design, what are your thoughts on if there should be a warning that a new PSResourceRepository has been registered?

2022-08-04 02:12 UTC, ThomasNieto commented on src/code/SetPSResourceRepository.cs
> +        public SwitchParameter Force { get; set; }
No warning should be written.

2022-08-04 21:13 UTC, anamnavi approved these changes
LGTM, minor nitpicks

2022-08-04 21:13 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +            var tempErrors = new List<string>() { };
I believe you don't need bracket initializer
```suggestion
            var tempErrors = new List<string>();
```

2022-08-04 21:13 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    return AddToRepositoryStore(repoName, repoUri, repoPriority, repoIsTrusted, repoCredentialInfo, force:true, cmdletPassedIn, out errorMsgs);
do you mind removing L317 below? Not sure how the `bool urlAttributeExists = node.Attribute("Url") != null;` got added twice (probably a typo), thanks!

2022-08-04 21:13 UTC, anamnavi commented on src/code/RegisterPSResourceRepository.cs
> +                        if (errorMsgs.Length > 0)
I think error string would be better

2022-08-11 15:21 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    return AddToRepositoryStore(repoName, repoUri, repoPriority, repoIsTrusted, repoCredentialInfo, force:true, cmdletPassedIn, out errorMsgs);
Ignore my comment here, I just re-read this and one line is to check for uri and the other for url existing

2022-08-14 20:07 UTC, merged