Fix -PassThru to return all properties
PowerShell/PSResourceGet pull request #748
Opened 2022-08-10 17:30 UTC by alyssa1303

# PR Summary

This PR fixes `-PassThru` parameter for `Set-PSResourceRepository` to return all properties, specifically the missing `Uri`.

## PR Context

Resolve #715 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-08-10 23:46 UTC, alerickson commented on src/code/RepositorySettings.cs
> +
You can get rid of all these new lines (lines 190-194), we should have 1 new line at the end of the file, but we can delete everything else.

2022-08-10 23:51 UTC, alerickson commented on test/SetPSResourceRepository.Tests.ps1
>          $res.Trusted | Should -Be False
Just a comment, unrelated to this PR-- it's kind of strange that we were actually testing to see if -PassThru returned the correct Uri path, but we still somehow still managed to have a bug with that scenario.  Do either of you know why that's the case? @alyssa1303 @anamnavi?

2022-08-10 23:52 UTC, alerickson approved these changes
Looks good!  Just have the one request to remove whitespace before merging

2022-08-11 15:14 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
>          $res.Trusted | Should -Be False
Unfortunately I was testing `-PassThru` with setting the Uri. The issue is reproduced only when setting anything but the Uri, as that's when it detects Uri is not being set and incorrectly sets it to null.

2022-08-11 15:53 UTC, anamnavi requested changes
I think we should account for the case where the user provides a Uri to be set for the repository, it's an invalid Uri, so we revert to the original value Uri before throwing. Just a thought on the flow, happy to discuss more :)

2022-08-11 15:53 UTC, anamnavi commented on src/code/RepositorySettings.cs
>                  // determine if existing repository node (which we wish to update) had Url to Uri attribute
nitpick, I think I left this typo in last time
```suggestion
                // determine if existing repository node (which we wish to update) had Url or Uri attribute
```

2022-08-11 15:53 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
Your code sets the node's Uri (or Url) attribute to the Uri passed in by the user, then we try to validate the node's new Uri. If it fails we throw but we've changed the node.Attribute(Uri) (or Url) already and don't revert it back. On the plus side though, we *always* validate that the value present for Uri (or Url) is valid, which the original code didn't do.

Looping @alerickson @PaulHigin into this for what they also think the flow should be, but I think if we detect the new Uri value provided by the user isn't a valid Uri we should throw an error and keep the original. If the user isn't trying to set the Uri, in my opinion, we should still validate the existing Uri (or Url) and throw if needed, but keep the original value.

2022-08-11 15:53 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
One way to do what I suggested could be that in the original code, we had a condition for `if (repoUri != null)`...I think we need an `else` to that condition which would try to validate the current Uri- throw if invalid and if valid then set `thisUri` to the current Uri value. This way when we create `updatedRepo` and use `thisUri` it's not possible for `thisUri` to be null.

2022-08-11 15:53 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +
Agreed, sorry this must've been a typo in the original code to have so many newlines.

2022-08-11 15:53 UTC, anamnavi commented on test/SetPSResourceRepository.Tests.ps1
> +    It "set repository given Priority and see updated repository with -PassThru" {
test looks great!!

2022-08-11 19:52 UTC, alerickson commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
I mentioned this a little earlier, but I don't think we need to validate what the current contents of uri/url is.  I think you can just put lines 175-178 before lines 172-174 so that the error gets thrown before the property gets set. Same with 184-187 getting placed before 181-183.  That should fix the  original problem right?  Good catch on this bug though

2022-08-11 21:47 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
I feel the creation of the Uri from user input should be done before checking whether an existing Uri exists in the store (Can we ever have a repository store entry without a Uri?  If not then this check should not be needed).  I see that the `Uri.TryCreate()` is called twice, but this can be done just once and throw if needed, before anything else is done (since that is a terminating error condition).

2022-08-11 21:55 UTC, alerickson commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
> Can we ever have a repository store entry without a Uri? 
Nope, only if a user manually modifies their file

2022-08-11 22:03 UTC, alyssa1303 commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
The reason why `Uri.TryCreate()` is called twice in my previous code is because there are 2 different conditions, one for Uri and the other for Url. I updated the code and now `Uri.TryCreate()` is called 4 times because for each condition, I need to check if the user input Uri/Url is a valid one before I update the value. I call `Uri.TryCreate()` before `if (repo != null)` because if user doesn't input a Uri, `thisUri` will be `null`, which causes the current bug.

2022-08-11 22:33 UTC, PaulHigin requested changes

2022-08-11 22:33 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    if (repoUri != null)
We can move this `if()` statement outside the `if (urlAttributeExists)` if, since it is duplicated in both if/else blocks.
Also, we are only updating an existing Uri, if the user provided one.  If not we don't need to do anything and leave the previous Uri (Url) ... we have already validated that there is an existing Uri or Url.

```csharp
if (repoUri != null)
{
    // Update the existing Uri or Url with the new one provided by the user.
    if (!Uri.TryCreate(repoUri.AbsoluteUri, UriKind.Absolute, out userUri))
    {
        throw ...
    }

    if (urlAttributeExists)
    {
        node.Attribute("Url").Value = userUri;
    }
    else
    {
        node.Attribute("Uri").Value = userUri;
    }
}
```

2022-08-11 22:36 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    if (!Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl))
I feel need to only call `Uri.TryCreate()` one time for the Uri provided by the user.  Also I think we only need to update the existing Uri or Url if the user provided one (see my comment below), and do nothing otherwise.

2022-08-12 00:12 UTC, alyssa1303 commented on src/code/RepositorySettings.cs
> +                    if (repoUri != null)
Yes, I can refactor it like you recommended. However, I think I still need to keep the `else` part for when `repo` is `null` because even though the existing Uri (Url) is not affected, when the `updatedRepo` is created and returned in line 245 - 259, `thisUrl` will be `null` when user uses `-PassThru`. The `updatedRepo` takes a `Uri` argument, not `string`, so I'm not sure if there's a better way than just assign the existing Uri (Url) to `thisUri`.

2022-08-12 14:47 UTC, anamnavi approved these changes
LGTM

2022-08-15 14:59 UTC, alerickson approved these changes

2022-08-15 17:29 UTC, PaulHigin requested changes

2022-08-15 17:29 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                    else{
Please be consistent with bracket placement (on following line).

2022-08-15 17:29 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                        Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl);
I think we should test for failure on Uri creation.  Seems unlikely it would fail, but if it does that means the repository entry is corrupted and useless.  At minimum we should throw an error informing the user.  We might consider just removing the entry, but that may be too drastic.

2022-08-15 19:13 UTC, anamnavi commented on src/code/RepositorySettings.cs
> +                        Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl);
Agreed on not removing the entry, just throwing an error

2022-08-15 22:42 UTC, alyssa1303 commented on src/code/RepositorySettings.cs
> +                    else{
Will fix that!

2022-08-15 22:50 UTC, alyssa1303 commented on src/code/RepositorySettings.cs
> +                        Uri.TryCreate(node.Attribute("Url").Value, UriKind.Absolute, out thisUrl);
I made the change you requested. I'm not sure if I throw the right kind of error with the right message so I'd really appreciate your input on that.

2022-08-15 23:02 UTC, PaulHigin requested changes

2022-08-15 23:02 UTC, PaulHigin commented on src/code/RepositorySettings.cs
> +                            throw new PSInvalidOperationException(String.Format("Current 'Url' for repo {0} is an invalid Uri. Fix this so the file is not corrupted.", repoName));
Maybe:

"The 'Url' for repository {0} is invalid and the repository cannot be used. Please update the Url field or remove the repository entry."

2022-08-15 23:13 UTC, alyssa1303 commented on src/code/RepositorySettings.cs
> +                            throw new PSInvalidOperationException(String.Format("Current 'Url' for repo {0} is an invalid Uri. Fix this so the file is not corrupted.", repoName));
Sounds good! I'll change to that

2022-08-16 00:33 UTC, PaulHigin approved these changes
LGTM

2022-08-16 13:56 UTC, merged