WIP: Install-PSResource not adding Scripts install path to $env:PATH and allowing to invoke installed script
PowerShell/PSResourceGet pull request #750
Opened 2022-08-15 14:43 UTC by anamnavi

# PR Summary

Installing a script with Install-PSResource happens successfully except that the script installation path (`%USERPROFILE%\Documents\PowerShell\Scripts`) isn't added to the environment PATH variable, so the script can't be invoked without prepending install folder path.

Need to add tests and determine scope, currently just adding this environment variable for current user.

## PR Context

Resolves #709 and was working in V2.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-08-15 20:56 UTC, alerickson commented
V2 prompts for user to accept/confirm the action before setting the environment variable.  I'm not a fan of prompts but since it's changing the env var, I think it might be important to include (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/PSGet.Resource.psd1#L222 for the v2 prompt)

2022-08-15 21:05 UTC, alerickson requested changes

2022-08-15 21:05 UTC, alerickson commented on src/code/InstallHelper.cs
> +                            string currentPathEnvVarValue = Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User);
I think we should also check the scope and accommodate for AllUsers scope as well, similar to what v2 does here: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L34

2022-08-15 21:05 UTC, alerickson commented on src/code/InstallHelper.cs
> +                        if (!Environment.GetEnvironmentVariable("PATH").Contains(installPath))
Also looks like v2 checks that that both `installPath` and `installPath\` are not in `PATH` before adding `installPath` to `PATH` (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L71)

2022-08-15 21:05 UTC, alerickson commented on src/code/InstallHelper.cs
> +                            string currentPathEnvVarValue = Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User);
It also looks like on top of adding the scope specific target, it is also adding the path to the env var for the current process (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L110)

2022-08-17 18:27 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                            string currentPathEnvVarValue = Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User);
I added a check to accommodate for AllUsers scope, and to add the path to current process target.

2022-08-17 18:28 UTC, anamnavi commented on src/code/InstallHelper.cs
> +                        if (!Environment.GetEnvironmentVariable("PATH").Contains(installPath))
added this check, good catch thank you!

2022-08-22 23:32 UTC, alerickson commented
This looks good to me!  Should be good once the tests are resolved.

2022-08-24 16:52 UTC, PaulHigin requested changes

2022-08-24 16:52 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +        private const string ScriptPATHPromptQuery = "Your system has not been configured with a default script installation path yet, which means you can only run a script by specifying the full pat
```suggestion
        private const string ScriptPATHPromptQuery = "The installation path for the script does not appear in the {scope} path environment variable. Do you want the script installation path, {path}, added to the {scope} PATH environment variable?";

```

2022-08-24 16:52 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
```suggestion
                        // Add Scripts install path to Path environment variable so that it can be discovered.

```

2022-08-24 16:52 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        string envPathValue = Environment.GetEnvironmentVariable("PATH"); // todo anam- does this get all targets?
This retrieves environment variable in the current process. We want to check that both process and scope PATH variables contain the path, and if not then update those paths.  We only need to prompt the user for non-process (scope) PATH variable changes.

2022-08-24 16:52 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        if (!envPathValue.Contains(installPath) && !envPathValue.Contains(installPathwithBackSlash))
This code is complex enough to be in its own private static method.  We also need error handling if the environment variable cannot be retrieved or set (access denied).  For example a non-Admin user will not be able to get/set machine scope variables.  Access error would probably happen during installation, but we still need to handle access errors here.

2022-08-24 16:52 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                        if (!envPathValue.Contains(installPath) && !envPathValue.Contains(installPathwithBackSlash))
The private method should also be able to override the user prompt via a `force` parameter.

2022-08-24 16:52 UTC, PaulHigin commented on test/InstallPSResource.Tests.ps1
> +    # Windows only
We should also have tests that verify environment PATH variables exist (for non-interactive case, force case).

2022-08-30 17:13 UTC, anamnavi commented on test/InstallPSResource.Tests.ps1
> +    # Windows only
No longer applicable with warning based approach, so resolving.

2022-08-30 18:23 UTC, PaulHigin approved these changes
LGTM

2022-08-30 19:27 UTC, alyssa1303 approved these changes
LGTM too

2022-08-31 00:54 UTC, alerickson approved these changes

2022-08-31 17:38 UTC, merged