Add -TemporaryPath parameter to Install-PSResource, Save-PSResource, and Update-PSResource
PowerShell/PSResourceGet pull request #763
Opened 2022-08-16 17:57 UTC by alyssa1303

# PR Summary

This PR adds a parameter called `-TemporaryPath` for `Install-PSResource`, `Save-PSResource`, and `Update-PSResource` cmdlets, which allows users to set the directory for temporary installation.  

## PR Context

Resolves #650 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-08-16 20:11 UTC, alerickson reviewed
Everything looks good-- just have 1 comment on providing user messaging.  @anamnavi and @PaulHigin may have some opinions on that as well.

2022-08-16 20:11 UTC, alerickson commented on src/code/InstallPSResource.cs
> +                    }
We might want to emit a warning, verbose message or non-terminating error if the directory does not exist.  I do think the default behavior should be to use the default temp directory if the one provided by the user does not exist.  I'm just not sure if we should provide some kind of messaging to the user to that we are doing that or just specify what the expected behavior is in our docs.

2022-08-17 15:12 UTC, anamnavi reviewed
Not sure about whether we warn/throw/write error if the temp path directory does not exist, but aside from that looks great to me.

2022-08-17 15:12 UTC, anamnavi commented on src/code/InstallPSResource.cs
> +                    }
This is a good question. On one hand, I think it's reasonable to try and use the default temp path if the user provided one does not exist. On the other hand, for a team like Azure functions or whoever is using this to provide a directory with more space, if we use the default temp path it's pointless for them...but the argument can be made that they should've ensured their desired directory was created. Is there a scenario where we would want to try to create the user provided temp path directory if it doesn't exist and throw/warn if that creation failed?

Essentially not sure what best practice is here, perhaps @PaulHigin may have more idea.

2022-08-17 15:12 UTC, anamnavi commented on src/code/SavePSResource.cs
> +        /// The destination where the resource is to be temporarily installed
```suggestion
        /// The destination where the resource is to be temporarily saved to.

```

2022-08-17 15:12 UTC, anamnavi commented on src/code/UpdatePSResource.cs
> +        /// The destination where the resource is to be temporarily installed
```suggestion
        /// The destination where the resource is to be temporarily installed to while updating.

```

2022-08-17 16:45 UTC, PaulHigin requested changes
I also noticed that the `InstallHelper` class is derived from `PSCmdlet`, and this is incorrect because it is not being processed as a PowerShell cmdlet.  I think this was done so that the PSCmdlet `ThrowTerminatingError()` and `WriteError()` methods could be called.  But this is incorrect (and I am not sure what the behavior is).  `InstallHelper` should throw a normal C# exceptions and the top level cmdlets should catch and rethrow.  Also `InstallHelper` should return a `string[]` for any errors to be reported by the top level cmdlet.

@alyssa1303 Can you make these changes, or create a new `Issue` to make these changes later (since this is not really in scope of this PR)?

2022-08-17 16:45 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +                tmpPath != null ? tmpPath.ToString() : string.Empty));
`ToString()` is not needed since `tmpPath` is a string type.
```suggestion
                tmpPath ?? string.Empty));

```

2022-08-17 16:45 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            _tmpPath = tmpPath ?? Path.GetTempPath();
I don't think we need the `_tmpPath` class field since it appears that tmpPath is only used here locally.

2022-08-17 16:45 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                if (!string.IsNullOrEmpty(value))
This check is not needed because the above `[ValidateNotNullOrEmpty]` attribute will ensure the argument is not null or empty.

2022-08-17 16:45 UTC, PaulHigin commented on src/code/InstallPSResource.cs
> +                    }
I agree with @anamnavi that if a temporary path is provided and that path does not exist (or some other error like access) then this is a terminating error at parameter binding time.  The user specified an invalid path and so the cmdlet operation cannot continue.

Also, the `GetResolvedPSPathFromPSPath` API will throw for a number of errors, including if it cannot resolve the path, so the `DirectoryExists()` is not needed.  But only if the path does not contain wildcard characters, which we don't want to support so we should throw if there are any.  I think something like:

```csharp
if (WildcardPattern.ContainsWildcardCharacters(value))
{
    throw PSArgumentException("Wildcard characters are not allowed in the temporary path.");
}

// This will throw if path cannot be resolved.
_tmpPath = SessionState.Path.GetResolvedPSPathFromPSPath(value).First().Path;
```

2022-08-17 17:59 UTC, anamnavi commented
> I also noticed that the `InstallHelper` class is derived from `PSCmdlet`, and this is incorrect because it is not being processed as a PowerShell cmdlet. I think this was done so that the PSCmdlet `ThrowTerminatingError()` and `WriteError()` methods could be called. But this is incorrect (and I am not sure what the behavior is). `InstallHelper` should throw a normal C# exceptions and the top level cmdlets should catch and rethrow. Also `InstallHelper` should return a `string[]` for any errors to be reported by the top level cmdlet.
> 
> @alyssa1303 Can you make these changes, or create a new `Issue` to make these changes later (since this is not really in scope of this PR)?

I think creating an issue for that (and a separate PR) would be better.

2022-08-17 18:59 UTC, alyssa1303 commented on src/code/InstallHelper.cs
> +            _tmpPath = tmpPath ?? Path.GetTempPath();
I created `_tmpPath` class field because the tmpPath needs to be passed from InstallPackages() to InstallPackage(). If you think it's better to add a parameter to ProcessRepositories() to pass `tmpPath` from InstallPackages() to ProcessRepositories() and then from ProcessRepositories() to InstallPackage(), I can change it that way.

2022-08-17 19:36 UTC, alyssa1303 commented
I created an issue #767

2022-08-17 20:03 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            _tmpPath = tmpPath ?? Path.GetTempPath();
Oh, I see that now.  I am fine leaving it as is.

2022-08-19 16:37 UTC, anamnavi approved these changes
LGTM

2022-08-22 16:39 UTC, PaulHigin approved these changes
LGTM

2022-08-22 21:17 UTC, merged