[WIP] Add String and SecureString to acceptable credential types in PSCredentialInfo
PowerShell/PSResourceGet pull request #764
Opened 2022-08-16 18:04 UTC by alerickson

# PR Summary
Currently `Register-PSResourceRepository` and `Set-PSResourceRepository` both have a `-CredentialInfo` parameter, which takes a type of `PSCredentialInfo`.  This type includes the vault name, secret name, and `PSCredential` object, all used to configure credential persistence with SecretManagement.  

This PR adds two new constructors to the `PSCredentialInfo` class:
1)  Includes vault name, secret name, and string. 
2)  Includes vault name, secret name, and secure string.

## PR Context

Resolves #652 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-08-17 19:01 UTC, anamnavi approved these changes
LGTM

2022-08-17 23:08 UTC, PaulHigin requested changes

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +            if (credentialAttr is String)
```suggestion
            if (credentialAttr is string credStr)
```

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +                Credential = new PSCredential("PSGetUser", new NetworkCredential("", (String) credentialAttr).SecurePassword);
```suggestion
                Credential = new PSCredential("PSGetUser", new NetworkCredential("", credStr).SecurePassword);
```

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +            else if ((credentialAttr as PSObject)?.BaseObject is SecureString)
```suggestion
            else if ((credentialAttr as PSObject)?.BaseObject is SecureString credSS)
```

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +                Credential = new PSCredential("PSGetUser", (credentialAttr as PSObject).BaseObject as SecureString);
```suggestion
                Credential = new PSCredential("PSGetUser", credSS);
```

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +            else if (credentialAttr is PSCredential)
```suggestion
            else if (credentialAttr is PSCredential psCred)
```

2022-08-17 23:08 UTC, PaulHigin commented on src/code/PSCredentialInfo.cs
> +                Credential = (PSCredential)credentialAttr;
```suggestion
                Credential = psCred;
```

2022-08-18 14:28 UTC, alyssa1303 reviewed
LGTM as well

2022-08-18 14:29 UTC, alyssa1303 approved these changes

2022-08-18 15:42 UTC, PaulHigin approved these changes
LGTM

2022-08-18 22:34 UTC, merged