Add SupportsWildcards() attribute to parameters accepting wildcards
PowerShell/PSResourceGet pull request #833
Opened 2022-10-18 22:03 UTC by alyssa1303

# PR Summary

This PR adds `[SupportsWildcards()]` attribute to parameters that accept wildcards but aren't currently having it.

## PR Context

Resolves #751 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-10-19 16:22 UTC, anamnavi requested changes
Looking great so far! I left some questions we should consider. Also, Get-PSResource -Version parameter also supports wildcards so if we can add that would be great, thanks!

2022-10-19 16:22 UTC, anamnavi commented on src/code/SavePSResource.cs
>          public string Version { get; set; }
The `Version` parameter also supports wildcards. Running the cmdlet with `-Version "2.2.*"` saves the latest version that satisfies the wildcard. Do we want this to be the expected behavior? If so we should add `[SupportsWildcards]` attribute here. If instead, we want only specific versions to be allowed we should fix this in the code.

2022-10-19 16:22 UTC, anamnavi commented on src/code/UpdatePSResource.cs
>          /// Specifies one or more repository names to update packages from.
The `-Version` parameter also *takes* wildcards, but do we want this as expected behavior? I tried running `Update-PSResource "folder_test" -Version "4.5.*" -Repository PSGallery` but it updates to version 6.5.0.0 which is the latest version. So it doesn't make sense. If we want wildcard support for Version we should correct this. If we don't want that as expected behavior we should ensure wildcards are not passed in for the Version parameter.

2022-10-20 15:19 UTC, alyssa1303 commented on src/code/UpdatePSResource.cs
>          /// Specifies one or more repository names to update packages from.
I agree that the current behavior doesn't make sense, so we should discuss this in our next meeting.

2022-12-28 20:41 UTC, alerickson approved these changes

2022-12-28 20:41 UTC, merged