Add Get-PSScriptFileInfo cmdlet
PowerShell/PSResourceGet pull request #839
Opened 2022-10-26 18:38 UTC by alyssa1303

# PR Summary

This PR adds `Get-PSScriptFileInfo` cmdlet which takes a `-Path` parameter and returns a `PSScriptFileInfo` object. 

## PR Context

Resolves #762 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2022-10-27 18:28 UTC, PaulHigin requested changes

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +                var exMessage = "Path needs to end with a .ps1 file. Example: C:/Users/john/x/MyScript.ps1";
```suggestion
                var exMessage = "The script file pathname must end with a .ps1 file extension. Example: C:/Users/john/x/MyScript.ps1";
```

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +        public string Path { get; set; }
We're not very consistent about it, but when expecting a file pathname, we generally use 'FilePath'

```suggestion
        public string FilePath { get; set; }
```

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +    public sealed class GetPSScriptFileInfo : PSCmdlet
If we return a known type, we generally include this:
```powershell
[OutputType(typeof(PSScriptFileInfo))]
```

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +                var exMessage = "Error: Could not resolve provided Path argument into a single path.";
```suggestion
                var exMessage = "Error: Could not resolve provided FilePath argument into a single file.";
```

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +                    WriteVerbose("The .ps1 script file passed in was not valid due to: " + error.Exception.Message);
We generally use dotNet string formatting for error messages:
```suggestion
                    WriteVerbose($"The '{fileName}' script file passed in was not valid due to: {error.Exception.Message}");
```

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +                    WriteVerbose("The .ps1 script file passed in was not valid due to: " + error.Exception.Message);
Actually, since these are errors, they should be written as errors (WriteError()).  I would write them after the initial 'invalid file' error message below.  I see that you write 'verbose' messages later below.  I would just write them here to make the code a bit clearer.

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +            else
'else' is not needed here since conditional block above returns early with a terminating error exception.

2022-10-27 18:28 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +                var exMessage = "Error: Invalid .ps1 script file. Verify that the script file has Version, Guid, Description and Author properties.";
```suggestion
                var exMessage = $"Error: '{fileName}' script file is invalid. The script file must include Version, Guid, Description and Author properties.";
```

2022-10-27 20:29 UTC, alyssa1303 commented on src/code/GetPSScriptFileInfo.cs
> +        public string Path { get; set; }
In that case, should I change the parameter name for `Test-PSScriptFileInfo`, `New-PSScriptFileInfo`, and `Update-PSScriptFileInfo` since they all use `Path`? Otherwise, `Get-PSScriptFileInfo` will be inconsistent with them.

2022-10-27 22:16 UTC, PaulHigin commented on src/code/GetPSScriptFileInfo.cs
> +        public string Path { get; set; }
Oh, no.  If the other PSGet use 'Path', let's be consistent with that.

2022-10-28 14:38 UTC, alyssa1303 commented on src/code/GetPSScriptFileInfo.cs
> +                    WriteVerbose("The .ps1 script file passed in was not valid due to: " + error.Exception.Message);
Thanks for the suggestion! I'll write them after the `invalid file` error message then. As for the verbose message at the end, they were written later because they should be written whether the script is a valid one or not. Those verbose message are for errors like an invalid projectUri. This type of error doesn't make the script invalid but will return a null projectUri object, which is why it's written as verbose message instead of error.

2022-10-31 17:40 UTC, PaulHigin approved these changes
LGTM

2022-11-02 14:47 UTC, anamnavi commented on src/code/GetPSScriptFileInfo.cs
> +            foreach (string msg in verboseMsgs)
I think the verbose messages (potentially about Uris being invalid) should be written before the `WriteObject()` call that writes the script file object. That way all errors + verbose messages can be displayed and out of the way before the object is shown,

2022-11-02 14:53 UTC, anamnavi approved these changes
LGTM, just one request for change

2022-11-03 21:14 UTC, merged