Fix -NoClobber bug in Install-PSResource
PowerShell/PSResourceGet pull request #908
Opened 2023-01-23 22:19 UTC by alerickson

# PR Summary
`-NoClobber` parameter for `Install-PSResource` was not working properly.  I made a small bug fix there and added an early out if the package to be installed does not have any cmdlets (ie there's no potential for clobbering).

## PR Context

Resolves #676 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-01-23 23:34 UTC, PaulHigin requested changes

2023-01-23 23:34 UTC, PaulHigin commented on src/code/InstallHelper.cs
>                      duplicateCmdlets = listOfCmdlets.Where(cmdlet => pkg.Includes.Cmdlet.Contains(cmdlet)).ToList();
Please remove unneeded white space here and below.

2023-01-23 23:34 UTC, PaulHigin commented on src/code/InstallHelper.cs
> +            if (listOfCmdlets.Count == 0)
`listOfCmdlets` should be a HashSet (with case insensitive compare) instead of a List, for more efficient searches.
Also, I think this method can do an early return on first command name collision found.  The user just needs to know there is at least one name collision with an existing installed module, and then decide if they are going to allow the install or not.  This would make the detection process much faster.

2023-01-24 00:07 UTC, alerickson commented on src/code/InstallHelper.cs
> +            if (listOfCmdlets.Count == 0)
In v2 we display every cmdlet that causes a clobber (so the user knows what exactly they're potentially going to be clobbering).  We don't clobber by default anymore, so if a user opts-in to check clobbering it might be beneficial to have the list of cmdlets that will be clobbered.

2023-01-24 19:16 UTC, alerickson commented on src/code/InstallHelper.cs
> +            if (listOfCmdlets.Count == 0)
I've added the early out in the latest commit.

2023-01-24 19:22 UTC, PaulHigin approved these changes

2023-01-24 19:22 UTC, merged