Update help documentation for the module
PowerShell/PSResourceGet pull request #912
Opened 2023-01-24 23:15 UTC by adityapatwardhan

# PR Summary

Update help content for beta 19 version.

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-01-24 23:22 UTC, PaulHigin requested changes

2023-01-24 23:22 UTC, PaulHigin commented on help/Get-PSScriptFileInfo.md
> +{{ Fill in the Synopsis }}
It looks like there are a few places like this, where new parameters information is missing (also with -SkipModuleManifestValidate).

2023-01-24 23:31 UTC, alerickson requested changes
Just leaving notes of areas to fix

2023-01-24 23:31 UTC, alerickson commented on help/Find-PSResource.md
> + [-Repository <String[]>] [-Credential <PSCredential>] [-IncludeDependencies] [<CommonParameters>]
remove new line

2023-01-24 23:31 UTC, alerickson commented on help/Update-PSResource.md
> + [-AcceptLicense] [-Force] [-PassThru] [-SkipDependencyCheck] [-AuthenticodeCheck] [-WhatIf] [-Confirm]
Remove new line here

2023-01-24 23:31 UTC, alerickson commented on help/en-US/PowerShellGet.dll-Help.xml
> +      <command:name>Get-PSResourceRepository</command:name>
This needs to be reverted

2023-01-24 23:31 UTC, alerickson commented on help/Update-ModuleManifest.md
> + [-LicenseUri <Uri>] [-IconUri <Uri>] [-ReleaseNotes <String>] [-Prerelease <String>] [-HelpInfoUri <Uri>]
remove new line here

2023-01-24 23:31 UTC, alerickson commented on help/Update-ModuleManifest.md
> + [-CmdletsToExport <String[]>] [-DscResourcesToExport <String[]>] [-Tags <String[]>] [-ProjectUri <Uri>]
remove new line

2023-01-24 23:31 UTC, alerickson commented on help/Update-ModuleManifest.md
> + [-Description <String>] [-ProcessorArchitecture <ProcessorArchitecture>] [-CompatiblePSEditions <String[]>]
remove new line

2023-01-24 23:31 UTC, alerickson commented on help/Uninstall-PSResource.md
> +Uninstall-PSResource [-Prerelease] -InputObject <PSResourceInfo> [-SkipDependencyCheck] [-Scope <ScopeType>]
remove new line

2023-01-24 23:31 UTC, alerickson commented on help/Register-PSResourceRepository.md
> +{{ Fill Force Description }}
Fill out description

2023-01-24 23:31 UTC, alerickson commented on help/Publish-PSResource.md
> +### -SkipModuleManifestValidate
fill out description

2023-01-24 23:31 UTC, alerickson commented on help/PowerShellGet.md
> +### [Get-PSResourceRepository](Get-PSResourceRepository.md)
this needs to be reverted

2023-01-24 23:31 UTC, alerickson commented on help/New-PSScriptFileInfo.md
> + [-ExternalScriptDependencies <String[]>] [-Tags <String[]>] [-ProjectUri <String>] [-LicenseUri <String>]
remove new line

2023-01-24 23:31 UTC, alerickson commented on help/Install-PSResource.md
> +# Get-PSResourceRepository
file needs to be reverted

2023-01-24 23:31 UTC, alerickson commented on help/Get-PSScriptFileInfo.md
> +{{ Fill in the Synopsis }}
fill out contents

2023-01-24 23:31 UTC, alerickson commented on help/Find-PSResource.md
> +Find-PSResource [-Version <String>] [-Prerelease] [-ModuleName <String[]>] -DscResourceName <String[]>
remove new line

2023-01-25 00:17 UTC, alerickson commented
Everything should be good to go now, except that 'help/en-US/PowerShellGet.dll-Help.xml' needs to be updated to reflect the new changes (I didn't want to make that change manually).

2023-01-25 01:22 UTC, adityapatwardhan commented on help/Get-PSScriptFileInfo.md
> +{{ Fill in the Synopsis }}
@alerickson fixed those. @PaulHigin Please re-review.

2023-01-25 05:41 UTC, alerickson approved these changes

2023-01-25 18:15 UTC, PaulHigin approved these changes

2023-01-25 18:19 UTC, merged