#969: Inject credentials to ISettings to pass them into PushRunner
PowerShell/PSResourceGet pull request #993
Opened 2023-03-01 20:36 UTC by hemisphera

# PR Summary
Inject credentials passed to `Publish-PSResource` into `ISettings` object in order to pass them along to the `PushRunner` that pushes the .nupkg to the feed.

## PR Context
This allows publishing PS resources to an authenticated feed.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

2023-05-03 17:50 UTC, adityapatwardhan requested changes

2023-05-03 17:50 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +          if (Credential == null) return;
```suggestion
          if (Credential == null)
          {
               return;
          }

```

2023-05-03 17:50 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +
```suggestion
          if (packageSource != null)
          {
                if (!packageSource.IsEnabled)
                {
                    packageSource.IsEnabled = true;
                }
           }


```

2023-05-03 17:50 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +          if (packageSource == null)
```suggestion
          
          if (packageSource == null)

```

2023-05-03 17:50 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +            key = packageSource.Name;
```suggestion
          else
          {
              key = packageSource.Name;
          }

```

2023-05-05 16:47 UTC, alerickson approved these changes

2023-05-05 17:48 UTC, adityapatwardhan requested changes

2023-05-05 17:48 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +              InjectCredentialsToSettings(settings, sourceProvider, publishLocation);
```suggestion
            if (Credential != null)
            {
                 InjectCredentialsToSettings(settings, sourceProvider, publishLocation);
            }

```

2023-05-05 17:48 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +
```suggestion

```

2023-05-05 17:48 UTC, adityapatwardhan commented on src/code/PublishPSResource.cs
> +              true, ""));
use named parameter for `true` and string.Empty for the last parameter

2023-05-05 18:09 UTC, anamnavi approved these changes

2023-05-05 18:51 UTC, adityapatwardhan approved these changes

2023-05-05 18:53 UTC, merged

2023-05-09 12:54 UTC, dbrennand commented
Hi all,

I'd like to test this change but based on the CHANGELOG this didn't make it into `3.0.21-beta21`? #1091

2023-05-09 14:46 UTC, anamnavi commented
I forgot to include this in the changelog, but it should be included in the beta21 code changes. We're aiming to release later today so the changes would be included when it releases.